### ISSUE TITLE
[bug] Can't import `RainbowKitProviderProps` with Webpack 5

### ISSUE THREAD

**Issue by avele** [rainbow-me/rainbowkit#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.6

### Current Behavior

In the latest Webpack version it restricts imports of package files outside of paths specified in `exports` field in `package.json`

```
ModuleNotFoundError: Module not found: Error: Package path ./dist/components/RainbowKitProvider/RainbowKitProvider is not exported from package .../node_modules/@rainbow-me/rainbowkit (see exports field in .../node_modules/@rainbow-me/rainbowkit/package.json)
```

### Expected Behavior

`RainbowKitProviderProps` type should be available to import from one of files specified in `exports` field of `package.json`.

**Comment by DanielSinclair** [comment]
Hi @avele! Can you provide a reproducible sample?

**Comment by DanielSinclair** [comment]
Are you having an issue importing like so? 
```ts
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';
```

**Comment by DanielSinclair** [comment]
Closing for now, but will re-open if this issue persists

**Comment by avele** [comment]
@DanielSinclair 

I have no issue importing the Provider, but it's props. Importing it like this will result in error above.

```js
import { RainbowKitProviderProps } from '@rainbow-me/rainbowkit';
```

**Comment by DanielSinclair** [comment]
Hey @avele. Could you link us to a reproducible example?
