### ISSUE TITLE
[bug] WalletConnect, Argent, Rainbow, Trust, Omni, imToken, Ledger Live options missing handler on mobile view 

### ISSUE THREAD

**Issue by nikoscb** [rainbow-me/rainbowkit#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.6

### Current Behavior

When on mobile view (e.g. emulating samsung Galaxy S8+ or real android device) clicking on any of the aforementioned choices results to the below error 

(Failed to launch 'wc:bd8ac295-6839-4836-8b16-46e99098df93@1?bridge=https%3A%2F%2F1.bridge.walletconnect.org&key=aa3b4e7fa259d028a757796cf51734eeca6d1ade0f536b649b058ad149f30aa4' because the scheme does not have a registered handler.)

### Expected Behavior

A connection should be attempted to be established as in desktop

### Steps To Reproduce

1. Access https://www.rainbowkit.com/
2. Switch to mobile view 
3. Attempt to click e.g. WalletConnect

### Anything else?

Console log

(Failed to launch 'wc:bd8ac295-6839-4836-8b16-46e99098df93@1?bridge=https%3A%2F%2F1.bridge.walletconnect.org&key=aa3b4e7fa259d028a757796cf51734eeca6d1ade0f536b649b058ad149f30aa4' because the scheme does not have a registered handler.)

**Comment by DanielSinclair** [comment]
Hi @nikoscb. In this test environment, do you have the wallets installed? This error is referencing a failed deep link attempt, meaning Android can't find an app registered to `wc://`
