### ISSUE TITLE
[bug] fixed too many items in chains breaking UI on mobile (overflow)

### ISSUE THREAD

**Issue by brieyla1** [rainbow-me/rainbowkit#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

latest

### wagmi Version

latest

### Current Behavior

Hey rainbow kit team,

when you have too many chains on mobile, they don't all show up, and block the "close" button from view. here is the fix. (see pictures)

The fix simply adds overflow scroll and a max width of 90vh, it should not interact with any logic whatsoever.

Current behavior
![image](https://user-images.githubusercontent.com/19621413/217116597-00a72852-f9da-45c8-93ec-48b86bc9fbfb.png)

### Expected Behavior

Fixed behaviour 
![image](https://user-images.githubusercontent.com/19621413/217116567-be5362a2-09e9-4626-b44e-f2672714aca3.png)
Thanks

### Steps To Reproduce

same chains for reproduction ([...chains, ...chains, ...chains, ...chains] in ChainModal.tsx

### Anything else?

Fixed contribution pull request:

https://github.com/rainbow-me/rainbowkit/pull/998

**Comment by DanielSinclair** [comment]
Thanks for spotting this @brieyla1. More chains, more problems 😅

**Comment by 0xDmitry** [comment]
Hey! Was it fixed in some other PR? Any updates?

**Comment by CJskii** [comment]
Hey, I am running into the same issue
![image](https://github.com/rainbow-me/rainbowkit/assets/106323731/736b3e79-5a7e-4ea9-b8f2-d8bf6280c012)

Is there a way to set max-height to viewport height and enable scrolling if it overflows?
