### ISSUE TITLE
[bug] connect modal opens automatically when disconnected, cannot be closed

### ISSUE THREAD

**Issue by robitaille1** [rainbow-me/rainbowkit#1010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.0

### Current Behavior

On disconnect, the connect modal is opening automatically and isn't closeable. It also adds a greyish overlay, which I have not seen before

https://user-images.githubusercontent.com/50972198/217676581-a2e0fa0c-1f04-4d63-ad3c-7d8a122a2950.mov

### Expected Behavior

On disconnect, the connect modal should not automatically open. 

### Steps To Reproduce

Hard to say, but usually, it is after the first instance of disconnecting

**Comment by robitaille1** [comment]
> @robitaille1 also getting this with different versions. solution?

Looks like there's an open issue to resolve this: https://github.com/rainbow-me/rainbowkit/issues/836

**Comment by robitaille1** [comment]
@b-bot worked for me, thanks. Although I still don't want the modal to open automatically, but at least it's closeable 😄

**Comment by callmejm** [comment]
I also facing modal issue, after connected or disconnected, connect modal / account modal popup automatically
