### ISSUE TITLE
WalletConnect 2 support

### ISSUE THREAD

**Issue by Ashoat** [rainbow-me/rainbowkit#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.11.5

### Current Behavior

* WalletConnect says they're [deprecating WalletConnect 1.0](https://docs.walletconnect.com/2.0/advanced/migrating-from-v1.0) at the end of this month (February 2023)
* WalletConnect 2.0 requires Wagmi 0.11
* Latest version of RainbowKit (0.8) only works with Wagmi 0.8

### Expected Behavior

RainbowKit works with WalletConnect 2 and hits wss://relay.walletconnect.com instead of `wss://bridge.walletconnect.org`

### Steps To Reproduce

1. Install latest RBK and latest Wagmi. See that it doesn't work (when you select a wallet nothing happens)
2. Install 0.8 Wagmi and check network and see that it's still using WalletConnect 1

**Comment by DanielSinclair** [comment]
Hey @Ashoat! We have a Draft PR open at #1003 for WalletConnect v2. This migration is still very much in flight but we will support it alongside the migration timeline. We're actively coordinating with the WalletConnect team on this.

**Comment by Ashoat** [comment]
Great news!! Thanks @DanielSinclair
