### ISSUE TITLE
[bug] MetaMask "Scan with Metamask" screen displayed even with MetaMask extension in Firefox

### ISSUE THREAD

**Issue by mwelche** [rainbow-me/rainbowkit#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.10.14

### Current Behavior

On firefox with the metamask extension installed, the 'scan with metamask' screen shows when metamask is selected in the connection modal.

### Expected Behavior

When the user has metamask extension installed and select metamask from the options in the connect modal, the metamask connection should open to connect the wallet, or the option should be presented to either connect with the wallet extension or via the mobile app (scan qr code). if no metamask exension is detected in the browser, show the 'scan with metamask' qr code.

### Steps To Reproduce

- With the metamask extension installed on firefox, click the 'connect button'
- select metamask from the list of available options.
- the 'scan with metamask' qr code shows and the metamask extension is not detected.

### Anything else?

FireFox 109.0.1 (64-bit)
Mac 12.5.1

<img width="737" alt="mmff" src="https://user-images.githubusercontent.com/620121/218620951-853d2425-3755-40ee-9cad-5d8a799753aa.png">

**Comment by DanielSinclair** [comment]
Hi @mwelche! Do you happen to have any other extensions installed, including wallets or transaction security extensions (like Stelo)?

**Comment by adbario** [comment]
Hi @mwelche, I couldn't replicate this scenario with RainbowKit 0.8.1, Firefox 109.0.1 and MacOS 13.2.1. As @DanielSinclair mentioned, the issue might be related to other browser extensions.

Also tested the latest Firefox Developer Edition without any issues.

**Comment by DanielSinclair** [comment]
@mwelche I see that you're also using a Custom Wallet List. If you don't mind, please upload an example to CodeSandbox or deploy via Vercel. Would not expect the custom wallet list to cause this issue, but would like to test and confirm on my end.

**Comment by mwelche** [comment]
I've confirmed the metamask extension was being blocked in Firefox on the application level due to the CSP. thanks for your help!
