### ISSUE TITLE
Can't login metamask when I have tokenpocket plugin in my chrome browser.

### ISSUE THREAD

**Issue by Santiago0412** [rainbow-me/rainbowkit#1038]
when I have token pocket plugin in my chrome, the pop up looks like this：
<img width="472" alt="image" src="https://user-images.githubusercontent.com/10152008/219256318-12a159a0-82d3-4ef1-85ea-7593b557641c.png">
but I do have metamask plugin;

when I remove the token pocket plugin, it works fine:
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/10152008/219256454-1ee6f90e-be61-4b80-9834-11c85fa752d7.png">

How can I connect metamask with tokenpocket exist?

https://www.rainbowkit.com/
this link have same issue.

**Comment by DanielSinclair** [comment]
Hey @Santiago0412! This looks to be an issue with TokenPocket specifically. Each browser extension will have their own behavior, and some play alongside others better. To connect with MetaMask, you'll want to disable TokenPocket temporarily and refresh the page. This will reset the "injected provider" and allow you to communicate with MetaMask again. We're actively working on improvements and discussing with the top wallet extensions to mitigate this multi-wallet issue in RainbowKit. Stay tuned!

**Comment by Santiago0412** [comment]
https://github.com/wagmi-dev/wagmi/issues/1869
