### ISSUE TITLE
[bug] Trustwallet <> BrowserConnect failure using Alchemy: Unsupported method: test

### ISSUE THREAD

**Issue by actuallymentor** [rainbow-me/rainbowkit#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.9.0

### wagmi Version

0.9.6

### Current Behavior

1. Click connect wallet
2. Select wallet connect
3. Use iOS based Trust Wallet to connect
4. Visually: no error
5. Console: `400` error from alchemy with the message `Unsupported method: test. See available methods at https://docs.alchemy.com/alchemy/documentation/apis`
6. Wallet connection does NOT work

### Expected Behavior

Same as above, but from 5 onward no errors.

### Steps To Reproduce

1. Go to [this example](https://checkout.poap.xyz/#/sale/3bea7986-cf33-44df-b489-311e1f3ced31?debug=true)
2. Connect with WalletConnect using trust wallet
3. Inspect the `400` error in the network tab

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

See above

### Anything else?

Full request:

```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "test",
    "params": []
}
```

Full response

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32600,
    "message": "Unsupported method: test. See available methods at https://docs.alchemy.com/alchemy/documentation/apis"
  }
}
```

**Comment by actuallymentor** [comment]
Can confirm issue persists on `"@rainbow-me/rainbowkit": "^0.11.0"` with `"wagmi": "^0.11.6"`

**Comment by DanielSinclair** [comment]
@actuallymentor It looks like all of the plumbing is working as expected here. `test` isn't a valid RPC call for those nodes: https://ethereum.github.io/execution-apis/api-documentation/
Using something like Wagmi's `useBlockNumber` hook as a test RPC call would be more suitable. Let me know if you're still seeing any issues.

**Comment by actuallymentor** [comment]
Thanks for your response @DanielSinclair :)

That's what I'm trying to point out: I'm not calling any endpoints. I'm seeing this error when connecting a trust wallet on ios through rainbow.

The test call seems to come from a rainbow subfile called ponyfill (not a typo).

**Comment by DanielSinclair** [comment]
@actuallymentor Can you put together a CodeSandbox example that reproduces this? I don't believe a `test` RPC method is triggered anywhere on our end, but can pull down and examine.
