### ISSUE TITLE
[bug] Core Wallet Overrides MetaMask Detection

### ISSUE THREAD

**Issue by kinkoph** [rainbow-me/rainbowkit#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.11.0

### wagmi Version

0.11.6

### Current Behavior

Rainbow Kit does not detect MM as installed unless Core Wallet Extension is disabled.

### Expected Behavior

Expect MM to be detected without having to disable Core Wallet Extension.

### Steps To Reproduce

Install Core Wallet and try to login with MM.

### Anything else?

Chrome Version 110.0.5481.177 (Official Build) (arm64)

MetaMask Version 10.25

**Comment by DanielSinclair** [comment]
@kinkoph This unfortunately appears to be an issue with Core's injector. It is overriding `window.ethereum` and appears to perform slow asynchronous work before making `isMetaMask` available to the window. MetaMask and other extensions are optimized to reduce these issues. Core also doesn't support `window.ethereum.providers` to allow an alternative path for using multiple wallets simultaneously. The only path currently available will be to disable Core when interacting with MetaMask; Chrome Profiles with different extensions installed/activated can be the easiest way to accomplish this. We're hoping to work with wallets to be good stewards of standards to reduce the ugliness of this particular issue, so if any of the Core team happens to read this, please reach out!
