### ISSUE TITLE
[bug] Even after using useDisconnect hook from wagmi, it is not possible to signout and rainbow kit signs back in on page refresh

### ISSUE THREAD

**Issue by eriktoor** [rainbow-me/rainbowkit#1054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.11.0

### wagmi Version

0.9.6

### Current Behavior

![Screenshot from 2023-02-26 23-48-03](https://user-images.githubusercontent.com/30181835/221476788-738afb50-82db-45b8-966a-69eba383d903.png)
![Screenshot from 2023-02-26 23-47-52](https://user-images.githubusercontent.com/30181835/221476792-149abf71-7d61-4fb3-a33d-92eab6a9c4ca.png)
![Screenshot from 2023-02-26 23-47-45](https://user-images.githubusercontent.com/30181835/221476793-c50bfa6d-d80d-4bec-a88b-e0925389e9f5.png)

Step 1: sign into wallet with rainbow kit
Step 2: sign out of wallet using disconnect button (removes sign in status and it seems like you are disconnected)
Step 3: [BUG] after refreshing you auto-sign back in

### Expected Behavior

After disconnecting you should stay disconnected. 

### Steps To Reproduce

Step 1: sign into wallet with rainbow kit
Step 2: sign out of wallet using disconnect button (removes sign in status and it seems like you are disconnected)
Step 3: [BUG] after refreshing you auto-sign back in

**Comment by eriktoor** [comment]
Unfortunately I am using wagmi ^0.11.6. Is there a best practice for signing out then other than calling disconnect / does rainbow kit provide a hook to disconnect or is using the wagmi hook best practice? @DanielSinclair

**Comment by eriktoor** [comment]
Additionally, I tried removing local storage after disconnecting and it seems to be added back after refreshing the page. Is there any workaround to ensure that this information doesn't get populated until I click signin?

**Comment by lililemon** [comment]
@DanielSinclair @eriktoor The wagmi.connected in local storage can determine if you clicked disconnect

**Comment by sonipranjal** [comment]
Same issue!

**Comment by axejintao** [comment]
experiencing the same issue, any logic due to connection or modal triggering when using a custom connect button should be managed by the implementer. this behavior does not make sense given a call to disconnect triggering an unwanted modal - which btw can also not be exited from

**Comment by TateB** [comment]
i created a pr to fix this issue, but as a temp fix, if you are using the `getDefaultWallets` function you can replace with this:

```ts
const wallets = connectorsForWallets([
    {
        groupName: 'Popular',
        wallets: [
            injectedWallet({ chains, shimDisconnect: true }),
            rainbowWallet({ chains, shimDisconnect: true }),
            coinbaseWallet({ appName, chains }),
            metaMaskWallet({ chains, shimDisconnect: true }),
            walletConnectWallet({ chains }),
            braveWallet({ chains, shimDisconnect: true }),
        ],
    },
]);
```

or if you're using any other wallet that has an injected connector, just make sure to pass through `shimDisconnect: true`
