### ISSUE TITLE
[BUG] Custom style theme breaks the ConnectButton styling

### ISSUE THREAD

**Issue by xenoliss** [rainbow-me/rainbowkit#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.11.0

### wagmi Version

0.11.7

### Current Behavior

Copy pasting the [doc](https://www.rainbowkit.com/docs/custom-theme#creating-custom-theme-selectors) example breaks the `ConnectButton` styling. 

### Expected Behavior

 I'd expect the ConnectButton to be properly styled as I am passing the exact same `theme` object I'd pass as param to the `RainbowKitProvider` component.

### Steps To Reproduce

My code is as follow:
```jsx
<WagmiConfig client={wagmiClient}>
  <RainbowKitProvider chains={chains} theme={null}>
    <style
      dangerouslySetInnerHTML={{
        __html: `
          :root {
            ${cssStringFromTheme(lightTheme)}
          }

          html[data-dark] {
            ${cssStringFromTheme(darkTheme, {
              extends: lightTheme,
            })}
          }
        `,
      }}
    />
    <div className="w-full h-full">{children}</div>
  </RainbowKitProvider>
</WagmiConfig>
```

And outputs the following UI:
![image](https://user-images.githubusercontent.com/33523487/222933037-20079386-7a95-4f58-ab90-d3aa814ea5d2.png)

### Anything else?

More generally, I'm trying to modify the `height` css property to set the `RainbowKitProvider`  [root div](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/RainbowKitProvider/RainbowKitProvider.tsx#L119) to a height of 100% so that my children elements are not limited in height. I'm curious to know if there is a better way to achieve this ?

**Comment by outdoteth** [comment]
did you find a workaround?

**Comment by KosmosKey** [comment]
@xenoliss Seems to be an issue with next.js server side and `@vanilla-extract/css` styles not being populated properly. At least it should work with react.

If you're using next.js are you able to add `@vanilla-extract/next-plugin` plugin to your `next.config.js` like such:

```
const { createVanillaExtractPlugin } = require('@vanilla-extract/next-plugin')

const withVanillaExtract = createVanillaExtractPlugin()

/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = withVanillaExtract(nextConfig)
```

**Comment by KosmosKey** [comment]
@xenoliss Any updates from this ?

**Comment by KosmosKey** [comment]
Closing this issue for now. Feel free to open another issue if this approach doesn't work.

**Comment by joelpierre** [comment]
Hey, this is still a bug. I have added the plugin to the next config and I have no styles loading
