### ISSUE TITLE
[bug] Error: WebSocket connection failed for URL: wss://relay.walletconnect.com?

### ISSUE THREAD

**Issue by sonipranjal** [rainbow-me/rainbowkit#1061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.11.1

### wagmi Version

^0.12.1

### Current Behavior

Getting this error while running the nextjs app with trpc.

**Comment by fredrare** [comment]
Same here, I just had the error a few minutes ago for the first time after updating to RainbowKit `0.11.1`. Now the error persists every time I run my project.

**Comment by sonipranjal** [comment]
I think this issue is related to this https://github.com/WalletConnect/walletconnect-monorepo/issues/1686, but don't know how to fix it, so I just uninstalled this package and used wagmi for now.

**Comment by sonipranjal** [comment]
Thanks a lot! It worked.

**Comment by nfts2me** [comment]
Thank you! Waiting for it!

**Comment by DanielSinclair** [comment]
`0.12.0` is now available to resolve this problem. You may now use the latest Wagmi version. Here are the [release notes](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.12.0).
