### ISSUE TITLE
How to change the "Connect a Wallet" text on the connect modal?

### ISSUE THREAD

**Issue by junhuang-ho** [rainbow-me/rainbowkit#1067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.0

### wagmi Version

0.12.1

**Comment by junhuang-ho** [comment]
![Screenshot from 2023-03-09 20-05-42](https://user-images.githubusercontent.com/96459097/224018195-1d885341-040f-4d4f-9637-7a116402902b.png)

**Comment by DanielSinclair** [comment]
Currently not supported. You can use the Custom ConnectButton API to accomplish this, but that would require additional UI work. What are you hoping to accomplish? We are hoping to work towards out-of-the-box internationalization soon.

**Comment by junhuang-ho** [comment]
The custom connect button api does not allow for text change. 

Recent developments in [EIP-4337](https://eips.ethereum.org/EIPS/eip-4337) expands the scope in "login" methods to not only just a typical wallet. For example, a user might consider using biometrics to access a contract account wallet. Hence, it would be more useful to have the ability to customize the connect modal text to something like "login" instead of a more specific "connect a wallet".

**Comment by junhuang-ho** [comment]
I think in general, it would be nice if rainbowkit exposes all of the modal (account/connect/network) logic and we can using them in our own UI.

**Comment by DanielSinclair** [comment]
- There are quite a few pieces RainbowKit would need to get in place for a decent dev UX for AA dApps. We're evaluating this. In the meantime, I would recommend using a third-party Wagmi connector like this from ZeroDev that happens to play well with RainbowKit: https://docs.zerodev.app/create-wallets/social/wagmi/rainbowkit
- We'll start to evaluate what it would take for us to expose more text customization, but it's currently only useful for a minority of dApp devs.

**Comment by junhuang-ho** [comment]
zerodev helps with AA logic with wagmi but does not help with UI.

**Comment by inclinedmind** [comment]
> We are hoping to work towards out-of-the-box internationalization soon.

Hey, just wondering if there's any update on this?

**Comment by DanielSinclair** [comment]
@inclinedmind Currently in progress. Follow #1091 for updates
