### ISSUE TITLE
[bug] TypeError: 'get' on proxy (Brave)

### ISSUE THREAD

**Issue by akp111** [rainbow-me/rainbowkit#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.1

### wagmi Version

0.12.1

### Current Behavior

While trying to connect metamask to the dapp, I am getting this error
```
TypeError: 'get' on proxy: property 'request' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function requestProxy(...args) {
    return proxyTarget.request(...args);
  }' but got 'function requestProxy(...args) {
    return proxyTarget.request(...args);
  }')
    at x (chrome-extension://gacgndbocaddlemdiaadajmlggabdeod/injectedScript.bundle.js:7:73972)
    at I (chrome-extension://gacgndbocaddlemdiaadajmlggabdeod/injectedScript.bundle.js:7:74403)
```

Here is a ss of the log
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/38760485/225678218-3aec79b7-0216-4d87-a09c-f805703b0ad5.png">

### Expected Behavior

Previously, it used to connect successfully but now it is throwing error.

**Comment by akp111** [comment]
Strange thing is, I am getting this error only in brave browser and not in chrome.

**Comment by DanielSinclair** [comment]
@akp111 Can you share a CodeSandbox example? Unable to replicate with our test dApp. Which wallet are you using? It does seem like there is an issue with Brave's built-in wallet right now.

**Comment by DanielSinclair** [comment]
@japes12345 What wallet are you using in Brave? The built-in or MetaMask?

**Comment by DanielSinclair** [comment]
Closing in favor of #1122. I believe these are the same issue related to Brave's changes to the "Default Ethereum wallet" setting that favors Brave Wallet and will now prevent other injectors like MetaMask or Pocket Universe from overriding `window.ethereum`. Try toggling this setting to "Extensions" and restarting the browser. Will continue to track.
