### ISSUE TITLE
[bug] <title> walletconnect page index overflow on mobile

### ISSUE THREAD

**Issue by IhsotasTon** [rainbow-me/rainbowkit#1096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.12.2

### wagmi Version

0.12.0

### Current Behavior

![491679387796_ pic](https://user-images.githubusercontent.com/93902066/226554093-e13c54d3-18c2-4b01-8c1c-187ebdf5beb9.jpg)

**Comment by DanielSinclair** [comment]
Thanks for spotting! This is actually a Web3Modal v1 issue; we just wrap that modal for this particular WalletConnect flow. We will soon be migrating away from this legacy flow/modal.
