### ISSUE TITLE
[bug] rainbowkit v0.12.2 walletconnect / injected wallet doesn't detect kucoin in kucoin's in-app browser

### ISSUE THREAD

**Issue by fionnachan** [rainbow-me/rainbowkit#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.2

### wagmi Version

0.12.3

### Current Behavior

rainbowkit v0.12.2 walletconnect / injected wallet doesn't detect kucoin in kucoin's in-app browser

users visiting a site with rainbowkit v0.12.2 on kucoin's in-app browser cannot connect their wallet to the site

### Expected Behavior

expect kucoin to be an option in the walletconnect modal

### Steps To Reproduce

open kucoin wallet mobile app

use their in-app browser

navigate to https://www.rainbowkit.com/docs/

click "Connect Wallet" button

click "WalletConnect"

search "KuCoin"

**Comment by DanielSinclair** [comment]
@fionnachan Does KuCoin Wallet offer an in-app browser? Can't find anything to test against for injected provider detection. As far as WalletConnect, it looks like KuCoin hasn't yet registered with the WalletConnect Cloud Registry. The QR Code scanner in the KuCoin Wallet does allow Desktop users to connect, though.

**Comment by fionnachan** [comment]
@DanielSinclair ![image](https://user-images.githubusercontent.com/13184582/226831058-d623fff3-3bd9-495d-9379-cf7d92cf3eaf.png)
Their app is not very obvious but the search bar is the url input field.

Indeed the workaround for now is to let users know they can use desktop.

Kucoin shows up on web3modal v2 though so I suspect support for walletconnect v2 would solve the problem.

**Comment by DanielSinclair** [comment]
@fionnachan Was able to replicate this. It looks like we were detecting the KuCoin provider as MetaMask, and this was preventing our fallback "Injected Wallet" option from appearing. 
- I went ahead and opened #1102 for this. Give it a test on our test dApp and let me know if this is more preferred behavior: https://rainbowkit-example-git-daniel-metamask-detection-rainbowdotme.vercel.app
- We'll need KuCoin to submit a PR to add their metadata for a prettier experience, but this should be functional for you now

**Comment by fionnachan** [comment]
thank you @DanielSinclair for the speedy response!

tested on Kucoin wallet's iOS in-app browser and it's showing as injected wallet

another issue for their mobile support is that if users visit the dApp site on a native mobile browser, they won't be able to choose Kucoin from the walletconnect list
