### ISSUE TITLE
[bug] Metamask not opening automatically on triggering Wagmi write function on Mobile

### ISSUE THREAD

**Issue by Mohamed-kassim** [rainbow-me/rainbowkit#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.2

### wagmi Version

0.12.4

### Current Behavior

on triggering write action from Wagmi for any available contract methods, Meta mask not opening, need to open it manually and then accept the transaction there.
this is only happening on Mobile android and IOS, the web is working perfectly.

### Expected Behavior

write action should open or switch to meta mask as the wallet is already connected.

### Steps To Reproduce

- connect wallet through meta mask
- Run any write action in your contract

**Comment by DanielSinclair** [comment]
@Mohamed-kassim Are you using the MetaMask in-app browser, or Safari/Chrome and connecting via WalletConnect?

**Comment by FranRom** [comment]
I'm having a similar problem trying to sing a message in mobile, although the connection is working well when I try to launch signMessage is not doing anything

**Comment by chungit201** [comment]
when i switch network is not navigating to metamask

**Comment by DanielSinclair** [comment]
I believe we fixed this with #1145. Just released as `0.12.7`. Let me know if you're still experiencing the issue.
