### ISSUE TITLE
[bug] WC v2 no `projectId` passed

### ISSUE THREAD

**Issue by h0tw4t3r** [rainbow-me/rainbowkit#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.0

### wagmi Version

0.12.0

### Current Behavior

Any app using the new rainbowkit version will have `projectId is required to work with explorer api` error.

In fact there is no possibility now to set one:
https://github.com/rainbow-me/rainbowkit/blob/26e59998e4f59746b33ca015798377b4c590c4f6/packages/rainbowkit/src/wallets/getWalletConnectConnector.ts#L19-L37

![Screenshot 2023-03-21 at 20 50 19](https://user-images.githubusercontent.com/35642018/226711606-d9964c5a-01aa-4fe5-8ba0-b84719e83630.png)
https://wagmi.sh/react/connectors/walletConnect

### Expected Behavior

WalletConnect to work

**Comment by DanielSinclair** [comment]
@h0tw4t3r 
- There is no need to use `WalletConnectConnector` directly with RainbowKit; follow our [Installation Guide](https://www.rainbowkit.com/docs/installation). This is abstracted by our Wallets. 
- If you were to use the Custom Wallet API, you can reference the docs or our other wallet connectors to see how `WalletConnectConnector` is implemented under the hood with `getWalletConnectConnector`.
- We currently use `WalletConnectLegacyConnector` as the new `WalletConnectConnector` has chain switching bugs for WalletConnect v2 that are being ironed out. We'll introduce this and the `projectId` option in a release soon without breaking changes.

**Comment by DanielSinclair** [comment]
For further context, most/all wallets that support WalletConnect v2 are backwards compatible with v1, so this will be a smooth transition as we release support and roll-over our wallet connectors to v2 when both sides of the equation are ready.
