### ISSUE TITLE
[bug] RainbowKitProvider ruins app layout

### ISSUE THREAD

**Issue by artgadliba** [rainbow-me/rainbowkit#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.2

### wagmi Version

0.12.4

### Current Behavior

After wrapping App with RainbowKitProvider it somehow impacts on the front end layout. I tried lots of different ways, as well as taken from original guide. Here is the link to the app's code, so you can reproduce the issue. Once, the RainbowKitProvider is removed everything backs to normal. 

Any help would be appreciated.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/artgadliba/CryptoRaffles

**Comment by DanielSinclair** [comment]
@artgadliba Looks like `display: flex;` in your global style is causing this issue. Ensure that `styles.css` is imported at top wrapper level before other global styles are applied. I'd also recommend that you rearchitect to ensure that `WagmiProvider` is wrapping the entire application to maintain provider state across routes. Checkout the codebase of our docs site in `site/` to see a more realistic RainbowKit implementation for a large project.

**Comment by artgadliba** [comment]
DanielSinclair, thank you for comments. You gave us right direction. It might be useful for someone else. That adjustment for global styles solved our problem:

  #root > div {
    display: flex;
    width: 100%;
    min-height: 100vh;
  }
