### ISSUE TITLE
[bug] clicking coinbase wallet does nothing

### ISSUE THREAD

**Issue by chuckstock** [rainbow-me/rainbowkit#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.4

### wagmi Version

0.12.0

### Current Behavior

Everything works as normal, but when I click on the button to connect a Coinbase wallet nothing happens.

### Expected Behavior

I would expect to see a QR code popup for the coinbase wallet so I can connect my wallet.

### Steps To Reproduce

1. Click "connect button"
2. click "coinbase wallet"
3. See there that nothing happens and no logs in the console.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://stackblitz.com/edit/github-rgoxpc?file=remix.config.js

### Anything else?

The stackblitz link will show a black screen for a few seconds that says "upgrade required," but if you wait a few seconds the app will start up correctly.

**Comment by alecananian** [comment]
+1

It's functioning for me on a dev build (also using Remix), but the production build behavior follows your StackBlitz example

**Comment by fullpipe** [comment]
As I understand, same problem with `vite`
https://stackblitz.com/edit/vitejs-vite-ceijxz?file=src/App.tsx

**Comment by DanielSinclair** [comment]
I was able to reproduce this behavior in the Vite and Remix examples, but oddly cannot in CRA/Next. If you roll back to previous RainbowKit/Wagmi versions, does this issue resolve?

**Comment by chuckstock** [comment]
> I was able to reproduce this behavior in the Vite and Remix examples, but oddly cannot in CRA/Next. If you roll back to previous RainbowKit/Wagmi versions, does this issue resolve?

Tried reverting RainbowKit & Wagmi every version from current to 0.8.0 with no changes.  All default wallets continued to work while clicking on coinbase wallet did nothing and resulted in no errors.

**Comment by nftchance** [comment]
Also encountering this issue.

**Comment by bangtoven** [comment]
👋 
a new version of @coinbase/wallet-sdk `v3.6.6` has been just released to fix the issue.
PR is out on wagmi https://github.com/wagmi-dev/references/pull/246
in the mean time, please point to `v3.6.6` of coinbase wallet sdk.

**Comment by bangtoven** [comment]
and it's applied on the latest wagmi, `0.12.12` https://github.com/wagmi-dev/wagmi/releases/tag/wagmi%400.12.12

**Comment by DanielSinclair** [comment]
@bangtoven Awesome, thank you!

**Comment by einaralex** [comment]
Our dapp hasn't been updated to React 18 yet, therefore we havent been able to update to Rainbowkit v2 and we are experiencing this problem. I tried to set the coinbase wallet sdk to v3.6.6 and it does not work :/

**Comment by DanielSinclair** [comment]
@einaralex Which version are you using currently? I believe the latest RainbowKit v1 and Wagmi v1 versions should not bump into this issue. If possible, please send over a reproducible example (CodeSandbox) and I can have a look. It's possible there is also a bundler or dependency issue in your setup.
