### ISSUE TITLE
[bug] <Disconnect wallet Error Code 5, any version>

### ISSUE THREAD

**Issue by HFXFL** [rainbow-me/rainbowkit#1123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.4

### wagmi Version

0.12.0

### Current Behavior

Hit 'Disconnect Wallet' 

A) Does not disconnect from Metamask. 
B) When disconnecting, `Aww Snap Error code 5`
-> tested in multiple browsers. 
C) When switching chain on Metamask, throws error code 5.

This happens with any version of Rainbowkit and Wagmi. 

We are using transaction signers in _app.tsx

### Expected Behavior

It disconnects from the Dapp and Metamask. 

### Steps To Reproduce

Package.json

`  "dependencies": {
    "@chakra-ui/icons": "^2.0.17",
    "@chakra-ui/react": "^2.5.2",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@rainbow-me/rainbowkit": "0.12.4",
    "@thirdweb-dev/react": "3.6.7",	
    "@thirdweb-dev/sdk": "3.6.7",
    "@types/node": "18.13.3",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "dotenv": "^16.0.3",
    "eslint": "8.36.0",
    "eslint-config-next": "13.2.4",
    "ethers": "^5.7.2",
    "framer-motion": "^10.6.1",
    "next": "13.2.4",
    "next-auth": "^4.20.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.8.0",
    "react-reveal": "^1.2.2",
    "react-spinners": "^0.13.8",
    "react-spring": "^9.7.1",
    "thirdweb": "^0.10.3",
    "typescript": "5.0.2",
    "wagmi": "^0.12.0"
  }
}`

_app.tsx

```
import React from "react";
import "@/styles/globals.css";
import {
  darkTheme,
  getDefaultWallets,
  RainbowKitProvider,
} from "@rainbow-me/rainbowkit";
import "@rainbow-me/rainbowkit/styles.css";
import { ChainId, ThirdwebSDKProvider } from "@thirdweb-dev/react";
import { SessionProvider } from "next-auth/react";
import type { AppProps } from "next/app";
import {
  configureChains,
  createClient,
  WagmiConfig,
  useSigner,
} from "wagmi";
import { polygonMumbai } from "wagmi/chains"; //mainnet
import { jsonRpcProvider } from "wagmi/providers/jsonRpc";

const { provider, webSocketProvider, chains } = configureChains(
  [polygonMumbai],
  [
    jsonRpcProvider({
      rpc: (chain) =>
        chain.id === ChainId.Mumbai
          ? {
              http: `https://mumbai.rpc.thirdweb.com`,
            }
          : null,
    }),
  ]
);

const { connectors } = getDefaultWallets({
  appName: "My RainbowKit App",
  chains,
});

const wagmiClient = createClient({
  provider,
  webSocketProvider,
  autoConnect: false,
  // added connectors from rainbowkit
  connectors,
});

function ThirdwebProvider({
  wagmiClient,
  children,
}: {
  wagmiClient: any;
  children: React.ReactNode;
}) {
  const { data: signer } = useSigner();

  return (
    <ThirdwebSDKProvider
    desiredChainId={ChainId.Mumbai}
    signer={signer as any}
    queryClient={wagmiClient.queryClient as any}
    provider={wagmiClient.provider}
    >
      {children}
    </ThirdwebSDKProvider>
  );
}

export default function App({ Component, pageProps }: AppProps) {
  return (
    <WagmiConfig client={wagmiClient}>
      <SessionProvider session={pageProps.session} refetchInterval={0}>
        <ThirdwebProvider wagmiClient={wagmiClient}>
          <RainbowKitProvider coolMode={true}
            theme={darkTheme({
              accentColor: "#7b3fe4",
              accentColorForeground: "white",
              borderRadius: "small",
              fontStack: "system",
              overlayBlur: "small",
            })}
            chains={chains}
            
          >
            <Component {...pageProps} />
          </RainbowKitProvider>
        </ThirdwebProvider>
      </SessionProvider>
    </WagmiConfig>
  );
}
```

Then just import the ConnectButton to app. 

### Anything else?

Any suggestions?

**Comment by DanielSinclair** [comment]
@HFXFL Can you send a CodeSandbox/Stackblitz? Can't seem to replicate this with our test dApp. How do you initiate a disconnect? From the RainbowKit UI or in MetaMask? Do you have any additional extensions installed, like Stello?

**Comment by DanielSinclair** [comment]
Will close this out for now. I do see that you're using Next 13, so ensure that you're tagging the layout and page with `'use client';` at the top of the file to prevent Next from attempting to server-side render the `RainbowKitProvider`. I have a Next 13 example here that you can reference: https://github.com/rainbow-me/rainbowkit/tree/25ef559d880aefd1a1e16edf0992cfd68752337b/examples/with-next-13/app
