### ISSUE TITLE
[bug] Safe Wallet and Injected Wallet not working/displaying on Modal, even after adding to wallets list. 

### ISSUE THREAD

**Issue by codingfarhan** [rainbow-me/rainbowkit#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.4

### wagmi Version

0.12.8

### Current Behavior

Even after importing and adding `safeWallet` to the `wallets` list in `connectorsForWallets`, it is not displaying the safeWallet on the Modal that lists various options for wallets. Facing the same issue with `injectedWallet`.

### Expected Behavior

It should display the safeWallet and injectedWallet option on the Modal for selecting a wallet.

### Steps To Reproduce

import { WagmiConfig, configureChains, createClient } from 'wagmi';
import { goerli } from 'wagmi';
import { publicProvider } from 'wagmi/providers/public';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { RainbowKitProvider, connectorsForWallets } from '@rainbow-me/rainbowkit';
import {
  metaMaskWallet,
  safeWallet,
  rainbowWallet,
  walletConnectWallet,
  ledgerWallet,
  trustWallet,
  injectedWallet
  coinbaseWallet,
} from '@rainbow-me/rainbowkit/wallets';
import { trezor } from '../customRainbowWallets/customWallets';
import '@rainbow-me/rainbowkit/styles.css';
import { ErrorBoundary } from './layout/ErrorBoundary';
import Router from './routes/Router';

const { chains, provider } = configureChains(
  [goerli],
  [alchemyProvider({ apiKey: config.alchemyAPIKey }), publicProvider()],
);

const connectors = connectorsForWallets([
  {
    groupName: 'Recommended',
    wallets: [
      metaMaskWallet({chains}),
      coinbaseWallet({appName: config.appName, chains}),
      injectedWallet({chains}),
      safeWallet({chains}),
      rainbowWallet({chains}),
      walletConnectWallet({chains}),
      ledgerWallet({chains}),
      trustWallet({chains}),
      trezor({chains}),
    ],
  },
]);

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});

function App(props: Prop)
  return (
    <WagmiConfig client={wagmiClient}>
    <RainbowKitProvider theme={myWalletTheme} chains={chains}>
    <ErrorBoundary>
      <Router />
    </ErrorBoundary>
    </RainbowKitProvider>
    </WagmiConfig>
  );
}

**Comment by DanielSinclair** [comment]
@codingfarhan `injectedWallet` is displayed as "Browser Wallet" in the UI and will only appear as a fallback in the case that the user's injected wallet does not match a wallet supported by the dApp. `safeWallet` likewise will only appear from within the context of the Safe Browser. Safe will automatically connect, but the Safe icon is available in the case that the user initiates a disconnect and then attempts to connect another wallet. Will close this issue out for more, but let me know if there is a deeper issue or unexpected behavior, and I'll reopen.

**Comment by codingfarhan** [comment]
I'm sorry, I'm unable to understand how to connect Gnosis safe wallet to my app using Rainbowkit connect wallet modal. As much as I understand, there is no web extension for Gnosis Safe to connect with web app. Would be helpful if you can explain what you mean by "Safe Browser". Thanks a ton.

**Comment by DanielSinclair** [comment]
@codingfarhan "Safe Browser" is the first-party browser that acts similarly to mobile wallet embedded dApp browser or an extension. It's available on [Web](https://app.safe.global/welcome) and in the desktop and mobile Safe apps: https://safe.global/wallet. Additional docs on Safe Apps distribution: https://docs.safe.global/build/sdks/safe-apps/launch
