### ISSUE TITLE
[bug] hook useSendTransaction doesnt work into mobile wallets (trust wallet, metamask)

### ISSUE THREAD

**Issue by deantek** [rainbow-me/rainbowkit#1137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.2

### wagmi Version

0.12.3

### Current Behavior

i want to transfer eth from one wallet to another

### Expected Behavior

on success, a modal window should open in the trust wallet confirming the transaction

### Steps To Reproduce

i use the standard rainbowkit + wagmi + ethers example, in mobile wallets confirmation does not work anywhere, only the metamask extension works

````
const { config } = usePrepareSendTransaction({
    request: {
      to: toAddress,
      value: incomeVal ? utils.parseEther(incomeVal).toString() : undefined,
    }
  })

  const { data, sendTransaction } = useSendTransaction(config)
````
![trusterror](https://user-images.githubusercontent.com/37242034/229509993-c9f96401-e3fd-47ad-b154-5e04bd7213ea.png)

### Anything else?

I've been trying to solve this problem for a week now, does no one notice this? Please tell me how to make transactions work in mobile wallets

**Comment by DanielSinclair** [comment]
I believe we fixed this with https://github.com/rainbow-me/rainbowkit/pull/1145. Just released as `0.12.7`. Let me know if you're still experiencing the issue.
