### ISSUE TITLE
[bug] Connecting to Metamask doesn't work on deployed project

### ISSUE THREAD

**Issue by kecerud** [rainbow-me/rainbowkit#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.11.4

### Current Behavior

When I click on rainbow connect button popup shows up with a Metamask as an only option correctly since that's the only one I specified in rainbowkit initialization for wallets. But afterwards when I click on the metamask option - nothing happens.

### Expected Behavior

What's weird is that this only happens in production - deployed app, but it works correctly (after clicking on metamask option, the metamask window popup appears and I can log in) on dev environment. The app is deployed on render.com and this has worked before but suddenly it seems broken.

Also when trying to click on the option in incognito mode (without metamask extension), after clicking it shows up a QR code so it seemingly somewhat works still(?)

### Steps To Reproduce

1. Click on connect button imported directly from rainbowkit library
2. A modal appears with Metamask as the connecting option
3. When trying to click on the option - nothing happens.

### Anything else?
Rainbow kit initialization: 

<img width="590" alt="Screenshot 2023-04-03 at 16 05 44" src="https://user-images.githubusercontent.com/75565018/229533707-234f474b-a30d-40f0-abc8-93de302f3720.png">

Created a basic page just for showcasing in the current project:

Dev environment - 

https://user-images.githubusercontent.com/75565018/229512880-d7009163-8e37-4537-858b-353304941567.mov

Deployed app - 

https://user-images.githubusercontent.com/75565018/229512912-9435dc03-5918-4b78-9651-ef1bb1324fcf.mov

Nothing in console / network tab that would help me shows up. Any tips on what could be the culprit and how to make it work on deployed version? There are no missing ENVs - i'm sure of that and I have tried upgrading to latest versions of both packages (wagmi & rainbowkit)

**Comment by DanielSinclair** [comment]
@kecerud 
- You'll want to bump up to RainbowKit 0.11 or beyond. The versions are designed to parity Wagmi, so RainbowKit 0.12 will only be compatible with Wagmi 0.12.
- Which framework are you using? SSR might be a culprit.
- What browser?

**Comment by kecerud** [comment]
@DanielSinclair Hi Daniel, thanks for the reply!

- As mentioned in the last section of my initial issue, I have tried bumping up to the max versions of both packages specifically to RainbowKit 0.12.6 and Wagmi 0.12.8 and this didn't change anything.
- I'm using RedwoodJS - no SSR here.
- Google Chrome ver. 111.0.5563.146

**Comment by DanielSinclair** [comment]
@kecerud Just deployed a CRA example here with a similar wallet setup. I was unable to replicate the issue, so I assume this may be specific to RedwoodJS and that bundler setup. Are you able to replicate the MetaMask issue from your end on this deployment? https://with-create-react-app-danielsinclair.vercel.app/

**Comment by kecerud** [comment]
@DanielSinclair Your deployment works just fine. Any guesses / tips where to try looking into it if it's purely RedwoodJS problem by any chance? What I'm confused about the most is that this setup worked initially but I had a few weeks of not touching anything related to the connect button and I didn't needed to be connected until now since I started to connect the UI - if that makes sense.

**Comment by DanielSinclair** [comment]
@kecerud Deployed a fresh RedwoodJS example here, but am not able to replicate the issue. Let me know if you are seeing the same issue. If you're able to share a CodeSandbox/repo, I can try to hunt down the issue https://redwoodjs-rainbowkit.vercel.app/

**Comment by kecerud** [comment]
@DanielSinclair Hi Daniel! I'm closing this issue. It seems that the culprit was using this package - [pagecrypt](https://www.npmjs.com/package/pagecrypt) on production to hash the page so that it requires a password before accessing. I assume this blocked some kind of initial rainbowkit calls or whatnot and that's why the connect button didn't behave properly. After removing this package and implementation, everything works as expected. 

As to if pagecrypt + rainbowkit can work somehow together I'm not sure as of now but I'll investigate and reply for other people to see if they stumble upon this problem in the future.

Thanks a lot for the help and conversation!
