### ISSUE TITLE
OpenConnectModal returning undefined

### ISSUE THREAD

**Issue by emmajane1313** [rainbow-me/rainbowkit#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.12.6

### wagmi Version

^0.12.8

### Current Behavior

When invoking the openConnectModal() function from the useConnect hook the openConnectModal returns undefined and the modal to connect wallet does not appear. I'm building a NextJs app and have used Rainbow many times before with no issues, not sure if this is because it's a later / unstable version? I've uninstalled / reinstalled multiple times and the issue persists. 

### Expected Behavior

The connect modal should appear on the screen. 

### Steps To Reproduce

1. Follow manual installation of the rainbow wallet
2. Create custom styled div with onClick to openconnectmodal

  const handleConnect = (): void => {
    openConnectModal && openConnectModal();
  };

 <div
        className="relative w-full h-12 font-geom text-white border-white border rounded-tl-lg rounded-br-lg flex flex-row items-center px-2 cursor-pointer"
        onClick={() => handleConnect()}
      >
        <div className="relative w-full h-full flex items-center justify-center">
          CONNECT
        </div>
</div>

**Comment by DanielSinclair** [comment]
To confirm, you're using the `useConnectModal` hook, correct? `useConnect` would be a separate Wagmi hook.

**Comment by DanielSinclair** [comment]
Will close out for now. Can reopen if the issue persists.
