### ISSUE TITLE
[bug] switch network does not redirect to metamask

### ISSUE THREAD

**Issue by chungit201** [rainbow-me/rainbowkit#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.5

### wagmi Version

0.12.2

### Current Behavior

network switch does not redirect to metamask

### Expected Behavior

network switch redirect to metamask

**Comment by DanielSinclair** [comment]
I believe we fixed this with https://github.com/rainbow-me/rainbowkit/pull/1145. Just released as `0.12.7`. Let me know if you're still experiencing the issue.
