### ISSUE TITLE
[bug] UserRejectedRequestError: User rejected request error when user cancels

### ISSUE THREAD

**Issue by basememara** [rainbow-me/rainbowkit#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.6

### wagmi Version

0.12.9

### Current Behavior

When a user cancels or rejects the connect, the error occurs: `UserRejectedRequestError: User rejected request`

### Expected Behavior

No error should occur.

### Steps To Reproduce

Connect > WallectConnect > Open > X-close; occurs with MM as well.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next

### Anything else?

I tried this with the example app in the main repo. This does not occur on your home page so I'm wondering what you're doing differently there. Am I supposed to catch the error, but could not find an API for it.

https://user-images.githubusercontent.com/892152/229895268-613c6ab5-8a93-409b-8909-d5df35002767.mp4

**Comment by basememara** [comment]
Answered by wagmi team: https://github.com/wagmi-dev/wagmi/issues/2129#event-8931111905

**Comment by saitejas-cypherd** [comment]
This is not working. I'm not able to catch the error by the useSwitchNetwork hook
