### ISSUE TITLE
[bug] Wagmi throws coinbaseWallet error

### ISSUE THREAD

**Issue by lotinasa** [rainbow-me/rainbowkit#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.7

### wagmi Version

0.12.9

### Current Behavior

I have installed the latest Rainbowkit and Wagmi in React application.

When I import @rainbow-me/rainbowkit, it throws the following error.

./node_modules/wagmi/node_modules/@wagmi/core/node_modules/@wagmi/connectors/dist/coinbaseWallet.js 167:54
Module parse failed: Unexpected token (167:54)
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         }]
|       });
>       return this.chains.find(x => x.id === chainId) ?? {
|         id: chainId,
|         name: `Chain ${id}`,

**Comment by DanielSinclair** [comment]
@lotinasa Can you share a CodeSandbox/StackBlitz? This is mostly likely a bundler issue.

**Comment by lotinasa** [comment]
@DanielSinclair This worked for me:
I modified browserslist in package.json

Not working:
  "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    }

Working:
  "browserslist": [
        ">0.2%",
        "not dead",
        "not op_mini all"
    ]
