### ISSUE TITLE
[bug] <Custom.ConnectButton will only work with metamask>

### ISSUE THREAD

**Issue by 0xDegenDeveloper** [rainbow-me/rainbowkit#1153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.4

### wagmi Version

0.12.7

### Current Behavior

When using the normal ConnectButton component, everything works as normals. But when I set up a Custom.ConnectButton component, it shows the wallet list, but nothing happens when you click on them. Clicking on Rainbow, WalletConnect, or Argent does nothing, but clicking metamask does open metamask. I am fairly certain I have implemented from the docs correctly. 

### Expected Behavior

All connectors to open up the corresponding wallet when clicked within a Custom.ConnectButton

**Comment by DanielSinclair** [comment]
Have you wrapped the App in `RainbowKitProvider`? Please send over a reproducible example, and can help debug. Unable to replicate in our test dApp https://rainbowkit-example.vercel.app/ with the Custom Connect Button implementation there. You can reference this dApp in the `packages/example/` directory.

**Comment by DanielSinclair** [comment]
@0xDegenDeveloper Can you provide more information about the browser you're using and the wallets you are having an issue with?

**Comment by DanielSinclair** [comment]
Will close out for now. Can reopen if the issue persists.

**Comment by 0xDegenDeveloper** [comment]
I fixed my issue, the issue stems from using Vite for the react project instead of create-react-app. Here is the code I used to fix this if anyone runs into the issue in the future: (the commented out lines are my old `fite.config.js` file)

```
// // https://vitejs.dev/config/
// export default defineConfig({
//   plugins: [react()],
// })
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import inject from "@rollup/plugin-inject";
import nodePolyfills from "rollup-plugin-polyfill-node";

export default defineConfig({
  base: "./",
  // Node.js global to browser globalThis
  define: {
    global: "globalThis",
  },
  plugins: [
    svelte(),
    inject({
      util: "util/",
      modules: {
        Buffer: ["buffer", "Buffer"],
        process: ["process"],
      },
    }),
    react(),
  ],
  build: {
    rollupOptions: {
      input: ["src/main.js", "src/polyfill.js"],
      plugins: [nodePolyfills()],
    },
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
});
```

**Comment by mortezashojaei** [comment]
> I fixed my issue, it stems from using Vite for the react project instead of create-react-app. Here is the code I used to fix it if anyone runs into the issue in the future: (the commented out lines are my old `vite.config.js` file)
> 
> ```
> // // https://vitejs.dev/config/
> // export default defineConfig({
> //   plugins: [react()],
> // })
> import react from "@vitejs/plugin-react";
> import { defineConfig } from "vite";
> import { svelte } from "@sveltejs/vite-plugin-svelte";
> import inject from "@rollup/plugin-inject";
> import nodePolyfills from "rollup-plugin-polyfill-node";
> 
> export default defineConfig({
>   base: "./",
>   // Node.js global to browser globalThis
>   define: {
>     global: "globalThis",
>   },
>   plugins: [
>     svelte(),
>     inject({
>       util: "util/",
>       modules: {
>         Buffer: ["buffer", "Buffer"],
>         process: ["process"],
>       },
>     }),
>     react(),
>   ],
>   build: {
>     rollupOptions: {
>       input: ["src/main.js", "src/polyfill.js"],
>       plugins: [nodePolyfills()],
>     },
>     commonjsOptions: {
>       transformMixedEsModules: true,
>     },
>   },
> });
> ```

Saved my day man!
Thank you!!!
