### ISSUE TITLE
Rainbow kit doesn't work in Next js 13 with app directory

### ISSUE THREAD

**Issue by Ricky2206** [rainbow-me/rainbowkit#1157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

latest

### wagmi Version

latest

### Current Behavior

I am currently working with Next js and the new App directory. When I wrap my components into the Wagmi and Rainbow provider the app stops working. First it tells me that the layout should be marked as a client component because of the fact that rainbow uses react hooks. However if I mark the layout as a client component it throws the error "fs is not defined" which is quite obvious since the layout has become a client component. Either way I am not able to get rainbow kit to work with the new app directory.

### Steps To Reproduce

1. create a new project with the latest next js version and enable the app directory
2. implement the rainbow kit connection as described in the official docs
3. start the app and view the error

**Comment by DanielSinclair** [comment]
We're waiting on the App Router beta to settle before updating the docs, but I have a Next 13 example prepared here. The important piece is to disable SSR for the `RainbowKitProvider` and UI by tagging the top of your files with `'use client';` as RainbowKit and Wagmi require client-side state.  https://github.com/rainbow-me/rainbowkit/tree/%40daniel/next13/examples/with-next-13

**Comment by Ricky2206** [comment]
As I said when I posted the issue, marking the layout as a client component doesn't solve it. In fact, the error simply changes to 'Can't resolve fs' as shown in the image below.

<img width="990" alt="Screenshot 2023-04-11 at 23 21 21" src="https://user-images.githubusercontent.com/29000662/231291010-45f3c5e9-9ccb-4de6-898c-6b98d2b3f9f4.png">

**Comment by DanielSinclair** [comment]
@Ricky2206 You have to mark both the page and layout as client components. Let me know if that resolves the issue.

**Comment by Ricky2206** [comment]
In the end the problem was with the webpack configuration in the next.config file. Changing the configuration to include fs fixed the issue for me.

**Comment by tomiiide** [comment]
@rforzani  what config did you change?
