### ISSUE TITLE
[bug] Reliance on window.Buffer polyfill

### ISSUE THREAD

**Issue by KholdStare** [rainbow-me/rainbowkit#1172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.6

### wagmi Version

0.12.8

### Current Behavior

It is currently not obvious that a polyfill for `window.Buffer` is required to properly use rainbowkit. If the polyfill is missing, there is no error message, and the failures are extremely subtle and non obvious. For example TrustWallet just generates a bogus QR code. This has wasted 2 days of developer time.

https://github.com/rainbow-me/rainbowkit/blob/4bbaac1b21e24ebfd71a661814cb194215508b7e/examples/with-create-react-app/src/polyfills.ts#L4

There are several issues with the "fix" being the polyfill. See:

https://github.com/rainbow-me/rainbowkit/issues/1122
https://github.com/rainbow-me/rainbowkit/issues/341

### Expected Behavior

The polyfill should not be required, or at the very least _make it obvious through console error or some other means_ that the polyfill is missing. If it's an external module that relies on `window.Buffer` which one is it? If it is rainbowkit itself, can it use `import Buffer from "buffer";` directly instead of the polyfill?

Thank you.

### Steps To Reproduce

Clone any example and remove the Buffer polyfill.

**Comment by DanielSinclair** [comment]
@KholdStare These issues mostly appeared with Webpack 5 adoption, which no longer includes Node polyfills by default. [These docs](https://web3auth.io/docs/troubleshooting/webpack-issues) from Web3Auth explain the problem and solution quite well. Ethers is the main dependency culprit, which is relied on by the WalletConnect and Wagmi libraries. We should probably update this docs section to be more verbose given Webpack 5, but let me know if you have other ideas: https://www.rainbowkit.com/docs/installation#additional-build-tooling-setup

**Comment by DanielSinclair** [comment]
I've opened a PR to amend our docs to simplify this for devs. This problem has unfortunately worsened with Wagmi v1 as additional modules required by WalletConnect packages upstream of Wagmi are no longer automatically bundled (as they were with ethers). https://www.rainbowkit.com/docs/installation#additional-build-tooling-setup
