### ISSUE TITLE
[bug] Rainbow kit connect wallet not working Properly

### ISSUE THREAD

**Issue by Yamini-yadav-pro** [rainbow-me/rainbowkit#1176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.7

### wagmi Version

0.12.10

### Current Behavior

The first time when we try to connect wallet button provided by rainbow kit , it is working fine. But once  the wallet disconnected  and try to connect second time, the connect wallet button is not clickable. We have used openConnectModal as a state, which shows undefined on console. 

We have implemented a custom "Connect Wallet" button that triggers the "openConnectModal()" function from the "useConnectModal()" hook in the "rainbowkit" package when clicked. Upon clicking the button, we use "wagmi" to set a state that displays the wallet address instead of the button when the wallet is connected. When the user clicks the wallet address, a popup is triggered using the "useDisconnect()" hook from "wagmi" that allows the user to disconnect. After disconnecting and resetting the state to display the "Connect Wallet" button, we click on the button again. However, upon clicking, the "openConnectModal()" function becomes undefined, which prevents the "rainbowkit" modal from opening again. We need assistance in resolving this issue so that the "rainbowkit" modal opens again when we click on the "Connect Wallet" button after disconnecting.

"@rainbow-me/rainbowkit": "^0.12.7","wagmi": "^0.12.10",

### Expected Behavior

Clicking the connect wallet should connect the wallet , irrespective of the number of times it is clicked. 

### Steps To Reproduce

**Steps to replicate:** 
Here are the steps to reproduce the issue:

1.Click on the "Connect Wallet" button.
2.Connect the wallet.
3.Click on the wallet address displayed on the screen.
4.Disconnect the wallet.
5.Click on the "Connect Wallet" button again.
Expected result: The "rainbowkit" modal should open again.
Actual result: The "openConnectModal()" function becomes undefined, preventing the "rainbowkit" modal from opening.

### Anything else?

![issue](https://user-images.githubusercontent.com/131171266/233072938-b91db54a-101e-43d7-a632-93eae4484be6.png)

We are using this function to connect modal:

`import { useConnectModal} from "@rainbow-me/rainbowkit";
const { openConnectModal } = useConnectModal();
const handleOpenConnectWallet = (e) => {
    openConnectModal();
  };
`
For disconnecting, we are doing like this:

`import { useDisconnect } from "wagmi";
const { disconnect } = useDisconnect({
    onSettled(data, error) {
      console.log('Settled DISCONNECT', { data, error })
    },
    onSuccess(data) {
      console.log('Success DISCONNECT', data)
    },
    onError(error) {
      console.log('Error DISCONNECT', error)
    }});

const disconnectWallet = () => {
  disconnect();
}`

Every time we disconnect, we get undefined on all the callback functions.
We would appreciate any help in resolving this issue, as we need to ensure that the "rainbowkit" modal opens again when we click on the "Connect Wallet" button after disconnecting.

**Comment by DanielSinclair** [comment]
@Yamini-yadav-pro Can you share a CodeSandbox or GitHub repo example? It is a bit difficult to parse where this issue originates. Do you encounter the same issue on our test dApp's "Modal hooks" section? https://rainbowkit-example.vercel.app/

**Comment by luneShaoGM** [comment]
Hi, I have the same problem, here is my code.
https://codesandbox.io/s/rainbowkit-openconnectmodal-0lqe3n

> @Yamini-yadav-pro Can you share a CodeSandbox or GitHub repo example? It is a bit difficult to parse where this issue originates. Do you encounter the same issue on our test dApp's "Modal hooks" section? https://rainbowkit-example.vercel.app/

**Comment by luneShaoGM** [comment]
If the value of autoConnect is false, it will work.

> Hi, I have the same problem, here is my code. https://codesandbox.io/s/rainbowkit-openconnectmodal-0lqe3n The button in https://rainbowkit-example.vercel.app/ opens the connect modal in my browser.
> 
> > @Yamini-yadav-pro Can you share a CodeSandbox or GitHub repo example? It is a bit difficult to parse where this issue originates. Do you encounter the same issue on our test dApp's "Modal hooks" section? https://rainbowkit-example.vercel.app/

**Comment by srivastavadevesh124** [comment]
> @Yamini-yadav-pro Can you share a CodeSandbox or GitHub repo example? It is a bit difficult to parse where this issue originates. Do you encounter the same issue on our test dApp's "Modal hooks" section? https://rainbowkit-example.vercel.app/

Yes its working on this dApp , can you provide the versions of rainbowkit and wagmi that this dApp is working on ? and also can you provide the github repo for this test dApp if possible ? .

**Comment by DanielSinclair** [comment]
@srivastavadevesh124 The test dApp is in the monorepo here: https://github.com/rainbow-me/rainbowkit/tree/main/packages/example

**Comment by DanielSinclair** [comment]
I tested against the latest RainbowKit and Wagmi again, and I wasn't able to replicate the issues with the `openConnectModal` even when `autoConnect` was enabled. Let me know if you're still experiencing the issue and can investigate further.
