### ISSUE TITLE
[bug] closeButton

### ISSUE THREAD

**Issue by fableleslie** [rainbow-me/rainbowkit#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.0

### wagmi Version

0.6.4

### Current Behavior

I am trying to click the close button of connectModal and then do something, such as redirecting to another page, or forcing the user to not close the modal as soon as connectModal appears, and only closing the modal after connecting to the wallet.

### Anything else?

![截屏2023-04-20 11 11 01](https://user-images.githubusercontent.com/51555478/233250297-32a2a21f-9c1b-4ee1-9732-220482740e14.png)

**Comment by DanielSinclair** [comment]
Have opened #1251 to offer an new API that should meet your needs:
```tsx
const { connectModalOpen } = useConnectModal();
const { accountModalOpen } = useAccountModal();
const { chainModalOpen } = useChainModal();
```
I also updated the docs for guidance on your usecase. Typically, it is recommended that you keep RainbowKit non-interruptive so that users can connect to your dApp at their leisure. 
> RainbowKit is designed to be non-interruptive and responsive, so dApps should always render an interface for users whether or not they have connected their wallet. A user could connect or disconnect their wallet directly from MetaMask, so the dApp must be responsive to the underlying connection status directly.
 
> dApps that rely on mechanisms like Sign-in with Ethereum for user verification should instead rely on the [Authentication](https://rainbowkit-site-git-daniel-modal-state-rainbowdotme.vercel.app/docs/authentication) feature.
