### ISSUE TITLE
[bug] MetaMask not installed when Rabby enabled

### ISSUE THREAD

**Issue by vvvvvv1vvvvvv** [rainbow-me/rainbowkit#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.9

### wagmi Version

0.12.12

### Current Behavior

When click MetaMask button, it shows MetaMask not installed(actually both Rabby and MetaMask installed)

<img width="511" alt="image" src="https://user-images.githubusercontent.com/86296331/233430247-ec212275-3ce4-40fe-bd5b-3cabe8c6f65d.png">

### Expected Behavior

Open Rabby or MetaMask when I click MetaMask button

### Steps To Reproduce

1. Enable Rabby and MetaMask
2. Open https://lenstube.xyz/
3.  Click Connect

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://lenstube.xyz/

`npm init @rainbow-me/rainbowkit@latest` also can reproduce

### Anything else?

it works before, looks like can't works after https://github.com/rainbow-me/rainbowkit/pull/1037 merged, I tried to debug but can't find the reason

**Comment by DanielSinclair** [comment]
Rabby is overriding `window.ethereum` and thus blocking dApps from using MetaMask. We have reached out to their team to adopt a `window.ethereum.providers` standard that can mitigate this. You'll either want to use Rabby's "default wallet" toggle (and refresh the page) to force Rabby to let dApps connect to MetaMask, or you'll want to disable one of the extensions at a time. An unfortunate industry standards issue. We're working with the community on adopting [EIP-5749](https://eips.ethereum.org/EIPS/eip-5749) or a similar standard.

**Comment by vvvvvv1vvvvvv** [comment]
any doc for how `window.ethereum.providers` work?

**Comment by fionnachan** [comment]
I'm on `"@rainbow-me/rainbowkit": "^0.12.9"` and `"wagmi": "^0.12.12"` with only Rabby enabled, Metamask disabled
plus this mode on Rabby 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/13184582/234238041-9031d297-6fc1-4568-97dc-3ecca8d8334a.png">

but choosing Metamask would not work with Rabby
<img width="714" alt="image" src="https://user-images.githubusercontent.com/13184582/234238135-b7986346-0db0-42a5-b47c-94265db2d2ce.png">
Please feel free to try on https://bridge.arbitrum.io/

but it worked with https://www.rainbowkit.com/docs/introduction

**Comment by vvvvvv1vvvvvv** [comment]
Yes, thats why I create https://github.com/rainbow-me/rainbowkit/pull/1187 for temporarily fix before Rabby adapt with eip-5749

**Comment by DanielSinclair** [comment]
@vvvvvv1vvvvvv That is unfortunately not a viable solution.

**Comment by vvvvvv1vvvvvv** [comment]
I guess it caused by Rabby set `isMetaMask` and `isRabby` same time, like:
- if no `isMetaMask` found, Rainbowkit will use Browser Wallet
- if `isMetaMask` found, Rainbowkit will use MetaMask
- if `isMetaMask` and `isRabby` found, Rainbowkit will not use Browser Wallet and MetaMask is not installed since Rabby is installed

That's why I think we should make `isMetaMask()` return false when `isRabby` found like other wallets

**Comment by vvvvvv1vvvvvv** [comment]
again, please merge https://github.com/rainbow-me/rainbowkit/pull/1187 to fix this issue, we have received many connection issues from users

**Comment by nico-limo** [comment]
Hello, here we are also having the issue @DanielSinclair  testing locally is working but on production is not detecting the wallet

**Comment by nico-limo** [comment]
@vvvvvv1vvvvvv @DanielSinclair we make it work Rabby downgrading the next packages
-   "wagmi": "0.12.1"
-   "@rainbow-me/rainbowkit": "0.12.7",

Still the issues with the persist on walletconenct and not connecting with coinbase

**Comment by DanielSinclair** [comment]
@nico-limo You can downgrade to Wagmi `0.12.11` for now

**Comment by vvvvvv1vvvvvv** [comment]
The reason is:

1. Rinbowkit check ready state of connector, and not ready means not installed in https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/wallets/useWalletConnectors.ts#L88
2. wagmi will always return false on ready check when `window.ethereum.isRabby` found in https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/metaMask.ts#L61

So it means Rainbowkit should always use the same wallet list as wagmi for those have `isMetaMask` but not MetaMask wallets.

I will create a PR for sync the wallet list from wagmi then you can merge it for a quick fix

**Comment by ConnorSB13** [comment]
Any update for a fix on this @DanielSinclair ?

**Comment by DanielSinclair** [comment]
@ConnorSB13 This fix is available as [0.12.13](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.12.13)
