### ISSUE TITLE
[bug] <WalletConnect, Trust Wallet & OKX  not possible to persist connection>

### ISSUE THREAD

**Issue by nico-limo** [rainbow-me/rainbowkit#1183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.7

### wagmi Version

0.12.1

### Current Behavior

When I try to connect the differents wallets

- Metamask: Working and handle the connection when I refresh the page(have the connector persisted)
- WalletConnect, Trust Wallet & OKX : Connected but when I refresh the page I need to connect a wallet again (the connector is undefined)

### Expected Behavior

Connect and persist the connection when I refresh the page.

### Steps To Reproduce

1. Go to the App
2. Try to connect your wallet with WalletConnect, Trust Wallet or OKX
3. When is connected, refresh the page

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

 https://app.tender.fi/

### Anything else?

Here is the way we are handling the logic

```ts
import { connectorsForWallets } from "@rainbow-me/rainbowkit";
import { multicallProvider } from "multicall-provider/wagmi";

import { createClient, configureChains } from "wagmi";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";
import { infuraProvider } from 'wagmi/providers/infura'
import { jsonRpcProvider } from 'wagmi/providers/jsonRpc'
import { arbitrum } from "wagmi/chains";

import {
  injectedWallet,
  walletConnectWallet,
  metaMaskWallet,
  ledgerWallet,
  coinbaseWallet,
  safeWallet,
  trustWallet,
  okxWallet,
} from "@rainbow-me/rainbowkit/wallets";

import getEnv from "~/utils/getEnv";
import type { MulticallProviderOptions } from "multicall-provider/.";

export const multicallProviderOptions: MulticallProviderOptions = {
  // max amount of transactions per multicall call
  batchSize: 30,
  // time in ms to wait for new transactions before sending a batch
  timeWindow: 10,
  // turns on logging to see when it batches requests
  logs: false,
  // The multicall3 contract address is the sam across the main EVM chains
  multicall3: "0xcA11bde05977b3631167028862bE2a173976CA11",
};

const env = getEnv();

const config = configureChains(
  [arbitrum],
  [
    alchemyProvider({ apiKey: env.ALCHEMY_API_KEY, priority: 0, stallTimeout: 500, }),
    infuraProvider({
      apiKey: env.INFURA_API_KEY,
      priority: 1,
      stallTimeout: 500,
    }),
    jsonRpcProvider({
      rpc: () => ({
        http: env.BLAST_RPC,
        webSocket: env.BLAST_WSS,
      }),
      priority: 2,
      stallTimeout: 500,
    }),
    jsonRpcProvider({
      rpc: () => ({
        http: env.ANKR_RPC,
        webSocket: env.ANKR_WSS,
      }),
      priority: 3,
      stallTimeout: 500,
    }),
    publicProvider({ priority: 4, stallTimeout: 500, }),
  ]
);

export const chains = config.chains;
export const provider = multicallProvider(
  config.provider,
  multicallProviderOptions
);
export const webSocketProvider = multicallProvider(
  config.webSocketProvider,
  multicallProviderOptions
);

const connectors = connectorsForWallets([
  {
    groupName: "Recommended",
    wallets: [
      injectedWallet({ chains }),
      metaMaskWallet({ chains }),
      okxWallet({ chains }),
    ],
  },
  {
    groupName: "Others",
    wallets: [
      walletConnectWallet({ chains }),
      ledgerWallet({ chains }),
      // coinbaseWallet({ appName: "Tender.fi", chains }),
      safeWallet({ chains }),
      trustWallet({ chains }),
      // rainbowWallet({ chains }),
      // zerionWallet({ chains }),
    ],
  },
]);

export const wagmiClient = createClient({
  autoConnect: true,
  provider,
  webSocketProvider,
  connectors,
});
```

Here is an error that happened when trying to connect with one of the wallets with the error
![image](https://user-images.githubusercontent.com/74354611/233468962-d9117301-9149-40ea-9053-961fca020845.png)

With Metamask I don't have that error

**Comment by nico-limo** [comment]
I just tested the example with remix and is the same error on the walletConnect there
![image](https://user-images.githubusercontent.com/74354611/233480408-cfaf8fbd-b932-4414-af48-7422afbd0b18.png)

Then If I click on disconnect show the next errors
![image](https://user-images.githubusercontent.com/74354611/233480484-88465508-5b5f-4e0e-a4a8-f56bf124d7c8.png)

**Comment by DanielSinclair** [comment]
@nico-limo If you bump up to the latest version of Wagmi, do you still encounter the issue? Th

**Comment by dcmrockwell** [comment]
Same issue with me, it works with wagmi 0.9.0 but not the latest version

**Comment by DanielSinclair** [comment]
@nico-limo @dcmrockwell Tested against RainbowKit v1 and Wagmi v1, and it appears that this issue has since been resolved. Also tested the current deployment of Tender.fi and was not able to replicate the issue. Will close as completed, but can reopen if this remains an ongoing issue.
