### ISSUE TITLE
[bug] Approve pop-up not autofilling value field anymore

### ISSUE THREAD

**Issue by daburuu** [rainbow-me/rainbowkit#1185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.2

### Current Behavior

When i call the approve function with a given value, the metamask pop-up appears but the "Amount" field is blank. I then have to click on either "Max." or "Use default." for the field to be filled. It only happened since the new metamask approval window UX/UI.

### Expected Behavior

When i call the approve function, the value is correctly set as soon as the pop-up opens.

### Steps To Reproduce

Call the approve config like this:

`const { config: approveConfig }: { config: any } = usePrepareContractWrite({
        address: contractAddress,
        functionName: "approve",
        abi: [
            {
                "name": "approve",
                "inputs": [
                    {
                        "internalType": "address",
                        "name": "spender",
                        "type": "address"
                    },
                    {
                        "internalType": "uint256",
                        "name": "amount",
                        "type": "uint256"
                    }
                ],
                "outputs": [
                    {
                        "internalType": "bool",
                        "name": "",
                        "type": "bool"
                    }
                ],
                "stateMutability": "nonpayable",
                "type": "function"
            }
        ],
        args: [spender, BigNumber.from(MAX_UINT256_VALUE)],
    });`

**Comment by DanielSinclair** [comment]
@daburuu This looks to be an issue with MetaMask itself. You can confirm that by trying an `approve` with their test dApp: https://metamask.github.io/test-dapp/
I'd submit an issue on their project: https://github.com/MetaMask/metamask-extension
