### ISSUE TITLE
Issues with Nextjs 13 App Directory: "`useClient` must be used within `WagmiConfig`"

### ISSUE THREAD

**Issue by hexcowboy** [rainbow-me/rainbowkit#1195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.12.10

### wagmi Version

^0.12.12

### Current Behavior

In a new Nextjs 13 App, `RainbowkitProvider` is somehow calling `useClient()` outside `WagmiConfig`, even though it is nested in `<WagmiConfig>`

![image](https://user-images.githubusercontent.com/8162609/234663327-573c0fd2-e7c2-41c1-a554-479abbe0c012.png)

<details>
  <summary>Trace</summary>

  ```
  Uncaught Error: `useClient` must be used within `WagmiConfig`.
  Read more: https://wagmi.sh/react/WagmiConfig
      useClient index.js:73
      useConnect index.js:659
      useWalletConnectors chunk-B7PGO5ZC.js:985
      usePreloadImages chunk-B7PGO5ZC.js:1402
      RainbowKitProvider chunk-B7PGO5ZC.js:1461
      renderWithHooks react-dom.development.js:10187
      mountIndeterminateComponent react-dom.development.js:15256
      beginWork$1 react-dom.development.js:16831
      beginWork react-dom.development.js:25568
      performUnitOfWork react-dom.development.js:24430
      workLoopSync react-dom.development.js:24146
      renderRootSync react-dom.development.js:24111
      recoverFromConcurrentError react-dom.development.js:23355
      performConcurrentWorkOnRoot react-dom.development.js:23261
      workLoop index.js:10
      flushWork index.js:10
      performWorkUntilDeadline index.js:10
  ```

</details>

### Expected Behavior

The app should render without errors.

### Steps To Reproduce

1. Clone https://github.com/hexcowboy/rainbowkit-bug-repro
2. Run `pnpm dev`
3. Visit localhost:3000 to see the error

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

(bug is not present on codesandbox for some reason)

**Comment by hexcowboy** [comment]
Closing this because I magically can no longer reproduce this..

**Comment by Jbern16** [comment]
Deeing this as well on latest @hexcowboy. Did it ever crop back up for you?

**Comment by hexcowboy** [comment]
If anyone runs into this issue and is confused, I think I fixed it by removing `.next` directory completely and restarting the dev server
