### ISSUE TITLE
[bug] Confirmation Dialog not showing up in DeFi Wallet

### ISSUE THREAD

**Issue by 0xartcro** [rainbow-me/rainbowkit#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.11

### wagmi Version

0.12.12

### Current Behavior

Confirmation dialog in DeFi App is not popping up. It used to work few versions earlier.

### Expected Behavior

Transaction confirmation showing up

### Steps To Reproduce

1. Install DeFi Wallet app (https://crypto.com/us/defi-wallet)
2. Connect to DeFi Wallet (Crypto(dot)com) through Wallet Connect
3. Call any contract to pop up confirmation (transaction, message signing etc)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

1. https://doonft.com/verify/000000
2. Connect
3. Tap on *Verify*

```typescript
onst {
        data: signingData,
        signMessage,
    } = useSignMessage({
        message: `Message to sign`
    });
```

### Anything else?

It does work properly here:
https://wagmi.sh/examples/sign-message

**Comment by DanielSinclair** [comment]
@0xartcro `0.12.11` introduced a regression with WalletConnect, so you'll want to bump up to `0.12.12`. I did test the dApp with Rainbow Wallet, and everything worked as expected. It seems like DeFi Wallet now has an issue with handling messages on WalletConnect v1. The example in Wagmi's docs is using WalletConnect v2. This should explain the difference you're seeing. Hopefully that wallet team resolves the issue. RainbowKit will be migrating to WalletConnect v2 in the next few weeks anyway.
