### ISSUE TITLE
[bug] TypeError: Illegal invocation: Function must be called on an object of type JSEthereumProvider

### ISSUE THREAD

**Issue by Shiyasmohd** [rainbow-me/rainbowkit#1210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.12.12

### wagmi Version

^0.12.0

### Current Behavior

<img width="954" alt="Screenshot 2023-05-05 at 6 29 31 AM" src="https://user-images.githubusercontent.com/83513144/236359063-3c4627b6-88db-4a8e-ad5e-64c0f509487f.png">

This issue is showing console of rainbowkit website as well as family connect kit website too.

**Comment by DanielSinclair** [comment]
@Shiyasmohd Can you share a CodeSandbox example?

**Comment by DanielSinclair** [comment]
Are you using Brave Browser, by chance? This might be related to their ongoing injection issues.

**Comment by Shiyasmohd** [comment]
> Are you using Brave Browser, by chance? This might be related to their ongoing injection issues.

Yes. I found out that this issue is only on brave browser. I tested with arc,chrome and safari. they are working fine.

**Comment by DanielSinclair** [comment]
Unfortunately, this is only something Brave can address. The current recommendation is that you select `Extensions (no fallback)` in the `Web3 > Default Ethereum wallet` Brave setting. This settings' behavior has changed multiple times in the last few weeks, so you'll also want to make sure that you're using the latest version of Brave.
