### ISSUE TITLE
[bug]  The requested module 'wagmi' does not provide an export named 'UserRejectedRequestError'

### ISSUE THREAD

**Issue by paOol** [rainbow-me/rainbowkit#1223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.14

### wagmi Version

1.0.1

### Current Behavior

When cloning the "with-next" example repo, 
installing with 'yarn'
and running with 'yarn dev'
and going to localhost:3000

the app crashes with the error

```
Server Error
SyntaxError: The requested module 'wagmi' does not provide an export named 'UserRejectedRequestError'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

### Expected Behavior

the app should not crash with no changes made to the example repo.

### Steps To Reproduce

clone `https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next`
and run `yarn`
then `yarn dev`
and browse to localhost:3000

### Anything else?

![image](https://github.com/rainbow-me/rainbowkit/assets/5941389/ae1fcd10-446f-4d7c-b4f6-4d465ca8ed8e)

**Comment by DanielSinclair** [comment]
It looks like you caught the monorepo in the midst of the v1 release. RainbowKit 0.12.x is only compatible with Wagmi 0.12.x. RainbowKit 1.0.0 will be compatible with Wagmi v1, and will be released shortly. In the meantime, you can downgrade Wagmi.

**Comment by DanielSinclair** [comment]
`1.0.0` is now available. Let me know if you continue to bump into an issue, and can have another look.

**Comment by paOol** [comment]
working now, thanks.
