### ISSUE TITLE
[bug] Brave Wallet connector option not showing up

### ISSUE THREAD

**Issue by v1v3krk** [rainbow-me/rainbowkit#1226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.11.1

### wagmi Version

0.11.6

### Current Behavior

The Brave Wallet option is not showing up on the list of available wallets to connect. However, if Brave is replaced with either Ledger, Omni, or some other additional wallets, these additional wallets show up.

### Expected Behavior

Brave should show up as an option to select on the list of connectable wallets.

### Steps To Reproduce

```
import { configureChains, createClient, WagmiConfig } from 'wagmi';
import { getDefaultWallets, connectorsForWallets } from '@rainbow-me/rainbowkit';
import { braveWallet, rainbowWallet, coinbaseWallet, metaMaskWallet, walletConnectWallet, omniWallet } from '@rainbow-me/rainbowkit/wallets';

const connectors = connectorsForWallets([
  {
    groupName: 'Popular',
    wallets:  [
      rainbowWallet({chains}),
      coinbaseWallet({chains}),
      metaMaskWallet({chains}),
      walletConnectWallet({chains}),
      omniWallet({chains}),
      braveWallet({chains})
    ]
  }
])

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});
```

### Anything else?

<img width="705" alt="Screen Shot 2023-05-10 at 10 16 07 AM" src="https://github.com/rainbow-me/rainbowkit/assets/29716939/448e997e-7db8-4399-95a0-36cdfcb2cb57">

**Comment by DanielSinclair** [comment]
@v1v3krk Did you test in Brave browser? Currently this connector will only appear in that browser when the `Web3 > Default Ethereum Wallet` setting is set to `Brave Wallet` or `Extensions (Brave Wallet fallback)`.
<img width="709" alt="Screenshot 2023-05-10 at 12 01 07 PM" src="https://github.com/rainbow-me/rainbowkit/assets/4412473/b24704d0-01b7-4296-87a6-4b77f75dde37">

**Comment by kylengn** [comment]
Is there any way to show Brave Wallet by default on Brave Browser without the wallet configuration on v.0.12? @DanielSinclair

**Comment by DanielSinclair** [comment]
@kylengn Yes. Just add the `braveWallet` wallet connector to your Wallet List, and it will always appear on Brave

**Comment by kylengn** [comment]
@DanielSinclair Thanks for the answer. However, I have added the braveWallet to my app. It's only showing after the configuration to set `Default Ethereum Wallet` to Brave Wallet. As I have noticed, on the RainbowKit official website, it will automatically show the Brave Wallet without the prior configuration. I would love to achieve the same thing in our app using rainbowkit and wagmi version 0.12.x.

`const connectors = connectorsForWallets([
  {
    groupName: 'Gnosis Supported Wallets',
    wallets: [
      metaMaskWallet({ projectId, chains }),
      walletConnectWallet({ projectId, chains }),
      coinbaseWallet({ appName, chains }),
      rabbyWallet({ chains }),
      braveWallet({ chains }),
      safeWallet({ chains }),
    ],
  },
])`

![Screenshot 2024-03-16 at 12 35 07 PM](https://github.com/rainbow-me/rainbowkit/assets/89263955/3303750c-7bc0-493d-8bdd-0b1c54299456)
![Screenshot 2024-03-16 at 12 35 29 PM](https://github.com/rainbow-me/rainbowkit/assets/89263955/a8e69968-7314-454b-aebc-28214c89a237)

**Comment by DanielSinclair** [comment]
@kylengn This is a side effect of Brave's default wallet behavior and how it treats `window.ethereum`. If you upgrade to RainbowKit and Wagmi v2, you'll adopt the new EIP-6963 standard that circumvents that behavior (which is what you see on RainbowKit.com).
