### ISSUE TITLE
[bug] walletconnect, rainbow, etc. silently fail with relative rpc urls

### ISSUE THREAD

**Issue by fubhy** [rainbow-me/rainbowkit#1228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.2

### Current Behavior

We are putting alchemy behind a cloudflare reverse proxy / vercel edge function (respectively) so we do not end up with the alchemy keys in the browser bundle and can also do some caching (and more fine grained access control and rate limiting) in the proxy.

In our app, we then simply use `/rpc/ethereum`, `/rpc/polygon`, etc. (in the client) as our rpc urls. On the server (e.g. with RSC), we continue to directly query alchemy.

However, when specifying the rpc urls for the public client as e.g. `/rpc/ethereum` with a custom `jsonRpcProvider` (which is perfectly fine otherwise), both walletconnect & rainbow wallet stop working and silently fail (no errors in console, etc.): It simply doesn't render the QR code.

It seems that these require a full uri (`http://foo.com/rpc/ethereum`). That seems unnecessary unless I'm missing something? If it's required for some reason however, then it would at least be good to not swallow this error and instead fail brutally ;-)

./cc @jxom the rpc proxy was your idea :-P

### Expected Behavior

Either fail brutally if the rpc uri doesn't fulfill the requirements of the wallet or actually allow relative uris (which should be fine unless I'm missing sth.).

**Comment by DanielSinclair** [comment]
@fubhy RainbowKit relies on the `WalletConnectLegacyConnector` and `WalletConnectConnector`, so the issue is more likely upstream in these Wagmi implementations of the WalletConnect libraries, or further yet in those libraries. Will bump this issue to Wagmi

**Comment by DanielSinclair** [comment]
Oops, looks like I can't transfer it myself. Feel free to copy this report over to that repo: https://github.com/wagmi-dev/wagmi
