### ISSUE TITLE
[bug] Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by angryhayder** [rainbow-me/rainbowkit#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.1

### Current Behavior

i was working on an older nextJs project and i had to restart because it became too old , so i tried the **npm init @rainbow-me/rainbowkit@latest** , right out of the box just with npm run dev , i was faced with this :
error - ./node_modules/node-gyp-build/node-gyp-build.js:1:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/node-gyp-build/index.js
./node_modules/bufferutil/index.js
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/sender.js
./node_modules/ws/index.js
./node_modules/@walletconnect/legacy-client/dist/esm/socket.js
./node_modules/@walletconnect/legacy-client/dist/esm/core.js
./node_modules/@walletconnect/legacy-client/dist/esm/index.js
./node_modules/@walletconnect/legacy-provider/dist/esm/signer.js
./node_modules/@walletconnect/legacy-provider/dist/esm/index.js
./node_modules/@wagmi/connectors/dist/walletConnectLegacy.js
./node_modules/@wagmi/core/dist/connectors/walletConnectLegacy.js
./node_modules/wagmi/dist/connectors/walletConnectLegacy.js
./node_modules/@rainbow-me/rainbowkit/dist/index.js
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
i upgraded my node on mac m1 from node18 to node20 and retried , same error, so i tried to create-next-app and tried to manually do everything on a fresh next project , and i got the same error

**Comment by DanielSinclair** [comment]
Apologies; we have fixed this issue with our templates but haven't released the updated version of `@rainbow-me/create-rainbowkit` yet. Wagmi v1 now requires that you polyfill a few dependencies. You can reference the [migration guide](https://www.rainbowkit.com/docs/migration-guide#:~:text=3.%20Ensure%20bundler%20and%20polyfill%20compatibility) for further details, and the [Next.js example](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next) or sample `next.config.js` below:
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack: config => {
    config.resolve.fallback = { fs: false, net: false, tls: false };
    return config;
  },
};

module.exports = nextConfig;
```
