### ISSUE TITLE
[bug] Firefox button/link takes to chrome extension store

### ISSUE THREAD

**Issue by o-az** [rainbow-me/rainbowkit#1253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0

### wagmi Version

0

### Current Behavior

<img width="1101" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/23618431/30f8cdd7-5a7a-458e-b25a-9ee41b6830e1">

### Expected Behavior

go to firefox add-ons site

### Steps To Reproduce

go to https://app.ens.domains/

press connect button

select metamask

press get on bottom right

[`Add to Firefox`](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://app.ens.domains/

**Comment by DanielSinclair** [comment]
@o-az This was corrected in a recent release, and the change should propagate to dApps soon.
