### ISSUE TITLE
[bug] Error disconnecting Trust Wallet

### ISSUE THREAD

**Issue by andrewaggb** [rainbow-me/rainbowkit#1259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.1

### Current Behavior

Disconnecting a Trust wallet gives an error.

### Expected Behavior

No errors disconnecting

### Steps To Reproduce

connect a trust wallet.
disconnect a trust wallet.

Can be done directly from your website.

### Anything else?

![image](https://github.com/rainbow-me/rainbowkit/assets/1630971/4992b5dc-96aa-42dc-bc50-96d8fa5ce029)

I have multiple providers installed, eg Trust Wallet, MetaMask, and Coinbase wallet.  I disabled their extensions and the error still occurs so I don't believe it's related.

main-eb61dab5f7771ce3.js:1 TypeError: o.removeListener is not a function
    at _app-62475ccf5efec63d.js:1:1176200
    at ei (framework-ca98db3857d7b0ec.js:1:93368)
    at ti (framework-ca98db3857d7b0ec.js:1:93564)
    at Ss (framework-ca98db3857d7b0ec.js:1:113664)
    at framework-ca98db3857d7b0ec.js:1:112695
    at ws (framework-ca98db3857d7b0ec.js:1:112761)
    at is (framework-ca98db3857d7b0ec.js:1:106480)
    at jl (framework-ca98db3857d7b0ec.js:1:46916)
    at framework-ca98db3857d7b0ec.js:1:103875

**Comment by DanielSinclair** [comment]
@andrewaggb Thanks for reporting this; I was able to replicate. Investigating.

**Comment by DanielSinclair** [comment]
@george-gkas This issue appears to be isolated to Trust Wallet. Has there been any changes to the Trust provider lately, or are there any known issues?

**Comment by ybgbob** [comment]
I may found possible reasons. 

`wagmi` removed `InjectedConnector` `shimChainChangedDisconnect` in [0.10.3](https://github.com/wagmi-dev/wagmi/blob/c02fd1caab61c93c41c8f2be78066d04e5fd9e56/packages/core/CHANGELOG.md#patch-changes-26), but rainbowkit used https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/wallets/walletConnectors/trustWallet/trustWallet.ts#L127

**Comment by ybgbob** [comment]
BTW, when call `disconnect()` method, actually call `window.trustwallet` ([getTrustWalletInjectedProvider](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/wallets/walletConnectors/trustWallet/trustWallet.ts#L33) return `window.trustwallet`)

But, `trustwallet` don't supply `removeListener` function:
<img width="453" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/106944652/57b5de5d-eeed-4dbc-94be-f3d5cdfb4c9f">

**Comment by glitch-txs** [comment]
I reported this issue to Trust months ago but no luck yet, the custom injector only supports on and off methods which are not called inside wagmi, seems like it needs a special connector or a fix on Trust Wallet end

**Comment by DanielSinclair** [comment]
A fix for this is included in #1156

**Comment by DanielSinclair** [comment]
[1.0.5](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.0.5) is now available with a fix for this issue.
