### ISSUE TITLE
[bug] Cant resolve 'fs' when using rainbow kit and next js

### ISSUE THREAD

**Issue by gtsui** [rainbow-me/rainbowkit#1260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.5

### Current Behavior

A number of us are running into this same issue (described here under discussions: https://github.com/rainbow-me/rainbowkit/discussions/1239) when trying to use rainbowkit with any brand new nextjs project. Any fixes or workarounds would be greatly appreciated!

./node_modules/node-gyp-build/node-gyp-build.js:1:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/node-gyp-build/index.js
./node_modules/bufferutil/index.js
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/websocket.js
./node_modules/ws/index.js
./node_modules/@walletconnect/legacy-client/dist/esm/socket.js
./node_modules/@walletconnect/legacy-client/dist/esm/core.js
./node_modules/@walletconnect/legacy-client/dist/esm/index.js
./node_modules/@walletconnect/legacy-provider/dist/esm/signer.js
./node_modules/@walletconnect/legacy-provider/dist/esm/index.js
./node_modules/@wagmi/core/node_modules/@wagmi/connectors/dist/walletConnectLegacy.js
./node_modules/@wagmi/core/dist/connectors/walletConnectLegacy.js
./node_modules/wagmi/dist/connectors/walletConnectLegacy.js
./node_modules/@rainbow-me/rainbowkit/dist/index.js

### Steps To Reproduce

The "Getting Started" code from the docs (https://www.rainbowkit.com/docs/installation) is enough to generate the errors.

const { chains, publicClient } = configureChains(
  [mainnet, polygon, optimism, arbitrum],
  [
    alchemyProvider({ apiKey: process.env.ALCHEMY_ID }),
    publicProvider()
  ]
);

const { connectors } = getDefaultWallets({
  appName: 'My RainbowKit App',
  projectId: 'YOUR_PROJECT_ID',
  chains
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient
})

**Comment by DanielSinclair** [comment]
@gtsui Wagmi v1 migrated to viem over ethers, which has meant some of the pollyfills utilized by WalletConnect v1 are no longer included by default. Here is an example `next.config.js` implementation that will solve your issue: https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next/next.config.js
This issue will luckily quielty disappear in the next few weeks as the WalletConnect v2 transition is wrapped up, as those libraries no longer depend on these Node polyfills.
