### ISSUE TITLE
[bug] metamask does not open when running from chrome extension

### ISSUE THREAD

**Issue by j-5-s** [rainbow-me/rainbowkit#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.5

### Current Behavior

Maybe this isnt possible cause of security reasons, idk, however when trying to open the metamask wallet from within a custom page or new tab of a chrome extension it doesnt work. nothing loads, just the QR code sits there.

Maybe because its not a normal url its hosted on?  I'm happy to put together a chrome extension dummy app to reproduce if needed. Thinking it may be a simple answer though like its just not possible.

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.05.19-21_02_23.webm](https://github.com/rainbow-me/rainbowkit/assets/666455/e22c92fc-f08b-4c29-9978-7a2d2eaed0ed)

### Expected Behavior

the popup should open

### Steps To Reproduce

run rainbowkit from within chrome extension

**Comment by DanielSinclair** [comment]
This is unfortunately a Chrome limitation. An extension content script or inpage script (which hosts the MetaMask window injector) cannot run in the context of another extension. You can test this by looking for a successful injection of `window.ethereum`; it will be unset in these contexts. You'll want to instead kick the user to a web URL where `window.ethereum` will be properly set by the wallet.
