### ISSUE TITLE
[bug] Connecting wallet on mobile not working

### ISSUE THREAD

**Issue by sniper365** [rainbow-me/rainbowkit#1262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.5

### Current Behavior

I tried to follow the example https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app
With latest versions...
Web browser is working. but on mobile...

So I tried with on this example https://codesandbox.io/s/rainbowkit-create-typescript-app-xuxnqy?ref=morioh.com&utm_source=morioh.com&file=/src/App.tsx:822-840 ( wagmi-v0.5.9 rainbow-v0.4.2) . 
It's working on this itself. So copied on my dApp.. But it's not working as well.

```
import * as React from "react"
import { Provider } from 'react-redux';
import { I18nextProvider } from 'react-i18next'
import { ChakraProvider } from '@chakra-ui/react'
import merge from 'lodash.merge';
import {
  darkTheme,
  getDefaultWallets,
  RainbowKitProvider,
  Theme
} from '@rainbow-me/rainbowkit'
import '@rainbow-me/rainbowkit/styles.css'
import { chain, configureChains, createClient, WagmiConfig } from 'wagmi'
import { mainnet, goerli } from 'wagmi/chains'
import { alchemyProvider } from 'wagmi/providers/alchemy'
import { publicProvider } from 'wagmi/providers/public'
import { store } from './state/store';
import { Router } from './Router'
import theme from './theme'
import i18n from './i18n'
import useLanguage from "./hooks/useLanguage";

const ALCHEMY_API_KEY = process.env.REACT_APP_ALCHEMY_API_KEY || ''

const myTheme = merge(darkTheme({
  borderRadius: 'small'
}), {
  colors: {
    accentColor: '#00204c',
    connectButtonBackground: '#00204c',
    modalBackground: '#002b66',
    connectButtonInnerBackground: '#00204c',
    modalText: 'white'
  },
  radii: {
    connectButton: 'none'
  },
  fonts: {
    body: '10px'
  }
} as Theme);

const { chains, provider } = configureChains(
  [
    chain.mainnet
  ],
  [
    alchemyProvider({
      alchemyId: ALCHEMY_API_KEY,
    }),
    publicProvider()
  ]
)

const { connectors } = getDefaultWallets({
  appName: "my dApp",
  chains
});

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider
});

export const App = () => {
  const { language } = useLanguage()

  i18n.changeLanguage(language)

  return (
    <I18nextProvider i18n={i18n}>
      <WagmiConfig client={wagmiClient}>
        <RainbowKitProvider
          chains={chains}
          theme={myTheme}
        >
          <ChakraProvider theme={theme}>
            <Provider store={store}>
              <Router />
            </Provider>
          </ChakraProvider>
        </RainbowKitProvider>
      </WagmiConfig>
    </I18nextProvider>
  )
}

```
What am I wrong?

**Comment by DanielSinclair** [comment]
@sniper365 Which wallet did you try to connect to on mobile? Can you share a video or screenshot of the behavior you're seeing?

**Comment by sniper365** [comment]
@DanielSinclair 

It's Metamask. After unlock the wallet, connect confirm modal not pop-up.

By the way, when I am trying to 'npm install', I can see these comments
![image](https://github.com/rainbow-me/rainbowkit/assets/30114178/a6fbfc4f-1577-4838-82a7-b8ef109f3f35)

**Comment by DanielSinclair** [comment]
Shouldn't be a WalletConnect issue. Are you referring to MetaMask Mobile or the MetaMask Desktop Extension? Was unable to replicate the issue on mobile after opening MetaMask, scanning a WalletConnect QR Code, and confirming the connection. I was also able to successfully use the in-app MetaMask browser to navigate to a RainbowKit dApp and connect the injected provider.

**Comment by DanielSinclair** [comment]
If you use this hosted version of the Create React App example, do you run into the same issue? https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app
https://qqp2xl-3030.csb.app/

**Comment by DanielSinclair** [comment]
I see. It looks like you slightly misconfigured Wagmi; the syntax changed with Wagmi v1. 

The new `createConfig` method:
```ts
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
  webSocketPublicClient,
});
```
The provider implementation:
```tsx
<WagmiConfig config={wagmiConfig}>
  <RainbowKitProvider chains={chains}>
    <App />
  </RainbowKitProvider>
</WagmiConfig>
```

**Comment by sniper365** [comment]
Hey @DanielSinclair 
Quick question

You sure this example is working? 
https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app

**Comment by DanielSinclair** [comment]
Yes, the example is working for me on mobile. Can you share a video of what you're experiencing, or describe what is missing?

**Comment by sniper365** [comment]
Ok.. I will try again and will let you now asap... thanks in advance

**Comment by sniper365** [comment]
Connect confirm modal Still not pop up. so I can't connect.

[2.zip](https://github.com/rainbow-me/rainbowkit/files/11548313/2.zip)

Here are my updated configuration

```
import * as React from "react"
import { Provider } from 'react-redux';
import { I18nextProvider } from 'react-i18next'
import { ChakraProvider } from '@chakra-ui/react'
import merge from 'lodash.merge';
import { getDefaultWallets, RainbowKitProvider, darkTheme, Theme } from '@rainbow-me/rainbowkit';
import { configureChains, createConfig, WagmiConfig } from 'wagmi';
import { mainnet, polygon, optimism, arbitrum, goerli } from 'wagmi/chains';
import { publicProvider } from 'wagmi/providers/public';
import { store } from './state/store';
import { Router } from './Router'
import theme from './theme'
import i18n from './i18n'
import useLanguage from "./hooks/useLanguage";
import '@rainbow-me/rainbowkit/styles.css'

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [
    mainnet
  ],
  [publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: 'bitoro',
  projectId: '2023-5',
  chains,
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
  webSocketPublicClient,
});


const myTheme = merge(darkTheme({
  borderRadius: 'small'
}), {
  colors: {
    accentColor: '#003680',
    connectButtonBackground: '#003680',
    modalBackground: '#003680',
    connectButtonInnerBackground: '#003680',
    modalText: 'white'
  },
  // radii: {
  //   connectButton: 'none'
  // },
  fonts: {
    body: '20px'
  }
} as Theme);

export const App = () => {
  const { language } = useLanguage()

  i18n.changeLanguage(language)

  return (
    <I18nextProvider i18n={i18n}>
      <WagmiConfig config={wagmiConfig}>
        <RainbowKitProvider
          chains={chains}
          theme={myTheme}
        >
          <ChakraProvider theme={theme}>
            <Provider store={store}>
              <Router />
            </Provider>
          </ChakraProvider>
        </RainbowKitProvider>
      </WagmiConfig>
    </I18nextProvider>
  )
}
```

What am I wrong?

**Comment by DanielSinclair** [comment]
The Custom Wallet List isn't required, correct. Can you share a reproducible example of your implementation? I wasn't able to replicate on the with-create-react-app example on MetaMask Mobile on Android. This is possibly an issue with your network. If you have a firewall or VPN active, I'd suggest disabling and testing again.

**Comment by sniper365** [comment]
By the way this example working on my side... 
https://codesandbox.io/s/rainbowkit-create-typescript-app-xuxnqy?ref=morioh.com&utm_source=morioh.com&file=/src/App.tsx:822-840 

But your example - https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app and my dApp not working.. how to explain?

**Comment by sniper365** [comment]
[video1.zip](https://github.com/rainbow-me/rainbowkit/files/11551077/video1.zip)

I compared dydx.exchange and my dApp.
As you can see dydx pop up walletconnect modal when click connect wallet button. And then go to metamask by choosing activity.
Anyway all are same until that. but we can see the 'Connect to this site?' connect modal in dydx. but not in my case...
You can guess what is wrong?

**Comment by sniper365** [comment]
Hi @DanielSinclair 
Can you help me further?

**Comment by DanielSinclair** [comment]
@sniper365 Can you share a CodeSandbox example? Unable to reproduce an issue.

**Comment by sniper365** [comment]
Here it is..

https://codesandbox.io/p/github/sniper365/bitoro-codesandbox-test/draft/zealous-stitch?file=/src/views/Home.tsx:24,41&workspaceId=db2815ed-51c7-4310-949f-75c1d42b0e6b

**Comment by sniper365** [comment]
@DanielSinclair  Have you had a chance to check my sandbox?

**Comment by foooooouny** [comment]
> Author

This example doesn't apply to me either. My MetaMask app version is v6.3.0, and it was working fine before I updated the app.

**Comment by DanielSinclair** [comment]
@foooooouny What device are you using? What does your test path look like? It sounds like MetaMask introduced an issue on their end. The wallets are currently undergoing an upgrade to WalletConnect v2, so it is very likely issues are appearing.

**Comment by foooooouny** [comment]
> @foooooouny What device are you using? What does your test path look like? It sounds like MetaMask introduced an issue on their end. The wallets are currently undergoing an upgrade to WalletConnect v2, so it is very likely issues are appearing.

@DanielSinclair iPhone 11 pro，iOS version 16.4.1

**Comment by foooooouny** [comment]
@DanielSinclair Another question: How can I enable redirection to the wallet app's dapp deeplink when connecting from a browser outside of the wallet, rather than using WalletConnect to establish the connection?

**Comment by DanielSinclair** [comment]
@foooooouny I'm not sure I understand the question. RainbowKit supports injected providers (like a wallet's in-app browser or a browser extension) and WalletConnect.

**Comment by sniper365** [comment]
@DanielSinclair @foooooouny  Did you find the solution for this issue?

**Comment by adrianotadao** [comment]
The problem seems to be bigger than I thought because even their site is not working well https://www.rainbowkit.com

**Comment by sniper365** [comment]
Hey @adrianotadao 
Please read [this](https://github.com/rainbow-me/rainbowkit/discussions/1294#discussioncomment-6173811). It will help you for sure. Good luck

**Comment by DanielSinclair** [comment]
@adrianotadao What issue are you seeing on rainbowkit.com?

**Comment by adrianotadao** [comment]
> @adrianotadao What issue are you seeing on rainbowkit.com?

@DanielSinclair Metamask doesn't do anything when you try to connect to rainbowkit.com using an iPhone. Is it working for you?

**Comment by FranRom** [comment]
Experiencing the same Issue...

**Comment by DanielSinclair** [comment]
@adrianotadao There is currently a known issue with MetaMask's WalletConnect support. We are told an update is coming imminently to resolve this on their end.

**Comment by adrianotadao** [comment]
> @adrianotadao There is currently a known issue with MetaMask's WalletConnect support. We are told an update is coming imminently to resolve this on their end. [MetaMask/metamask-mobile#6457](https://github.com/MetaMask/metamask-mobile/issues/6457)

nice!

Thank you @DanielSinclair!

**Comment by adrianotadao** [comment]
@DanielSinclair did they say something about this bug? any good news?! ❤️
