### ISSUE TITLE
[bug] Recent Transactions replaced - Speed up or cancelled

### ISSUE THREAD

**Issue by agsola** [rainbow-me/rainbowkit#1266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.22

### wagmi Version

0.12.13

### Current Behavior

When adding a recent transaction, if it is replaced or cancelled, it isn't reflected.

NOTE: Using wagmi to be alerted of this is not valid, since the user can close the window, speed up or cancel the TX on Metamask (for instance) and then reload the website. And the TX is showing still as pending but it is already cancelled.

### Expected Behavior

Replace with the replaced TX when it is replaced (either cancelled or speed up).

### Steps To Reproduce

Create a TX, add to recent TXs, and the cancel or speed up from Metamask before it is included.

**Comment by nfts2me** [comment]
It'd also add that there should be a "timeout" configurable period after which the transaction is considered stale.
We're having TXs pending for days that are replaced, but users still see them.

**Comment by KosmosKey** [comment]
@agsola Just to double check this once again. You're saying whenever you're submitting a transaction with a wallet and add "recent transactions" to rainbowkit it shows as pending when it's cancelled or speed up right ? 

I'm not sure if we support the "speed up" part, but if you have cancelled your transaction it should come up as "failed" in rainbowkit account modal. Can you give a reproducible example ?
