### ISSUE TITLE
[bug] Metamask shows connected although the wallet is not

### ISSUE THREAD

**Issue by dani69654** [rainbow-me/rainbowkit#1267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.14

### wagmi Version

0.12.13

### Current Behavior

This behaviour can be replicated here: https://www.rainbowkit.com/ <br />
Connect Metamask, the wallet will appear as connected on metamask. <br />
Disconnect Metamask, the wallet still appears as connected on metamask. <br />
Shouldn't the wallet appear as disconnected? <br />

![Screen Recording 2023-05-29 at 12 17 28](https://github.com/rainbow-me/rainbowkit/assets/60792849/c9d7504b-1ab4-461d-af96-4cb6350e4afa)

### Expected Behavior

The wallet should appear as disconnected

### Steps To Reproduce

video

**Comment by DanielSinclair** [comment]
@dani69654 MetaMask unfortunately does not offer an RPC call for programmatic disconnects, so Wagmi creates this behavior with a synthetic [shimDisconnect](https://wagmi.sh/react/connectors/metaMask#shimdisconnect) and RainbowKit has adopted this API. While MetaMask will continue to inject into the page, Wagmi remembers whether a user has previously disconnected and will not automatically 'connect' (updating the dApp state). There aren't too many tradeoffs to this approach, but we'll certainly revisit if the MetaMask RPC support changes.
