### ISSUE TITLE
[bug] Unhandled Runtime Error Error: No matching key. keychain:

### ISSUE THREAD

**Issue by 0xartcro** [rainbow-me/rainbowkit#1273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.2-canary.0

### wagmi Version

1.1.0

### Current Behavior

Unhandled Runtime Error Error: No matching key. keychain: <keychain number here>

### Expected Behavior

No error showing up

### Steps To Reproduce

Preconditions:
- Chrome Desktop Browser
- Already had connected wallet using previous version of RainbowKit

1. Tap on button Connect Wallet
2. Use Wallet Connect option
3. Click on "Open" (next to _Need the official WalletConnect modal?_)

Notes:
- After disconnecting wallet from MetaMask - could not reproduce anymore
- Could not reproduce on another browser with same preconditions

**Comment by 0xartcro** [comment]
Related to https://github.com/WalletConnect/walletconnect-monorepo/issues/1772 most likely

**Comment by DanielSinclair** [comment]
@0xartcro Thanks for spotting this. Have confirmed that it is a known issue with WalletConnect and that their team is working on a fix. Once those upstream changes are pulled into Wagmi, I'll provide an update here.

> This happens when you receive request from wallet for a session topic that is no longer in localStorage of a dApp. That can happen due to various reasons like our expirer removing it or a user disconnecting manually, but the wallet not respecting that.

**Comment by DanielSinclair** [comment]
@0xartcro A new version of Wagmi was released. If you upgrade to wagmi `1.2.0` and rainbowkit `1.0.2-canary.2` do you still see this issue?
