### ISSUE TITLE
[bug] openConnectModal is undefined

### ISSUE THREAD

**Issue by pavelivanov** [rainbow-me/rainbowkit#1277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.1

### wagmi Version

1.0.9

### Current Behavior

`useConnectModal()` always returns `openConnectModal: undefined`.

### Expected Behavior

`useConnectModal()` returns `openConnectModal` a function which opens a connect modal.

### Steps To Reproduce

There is no way to create codesandbox example because it doesn't allow to install the latest 1.0.1 version.

Step to reproduce: follow the guide from the docs https://www.rainbowkit.com/docs/installation.
1. Create NextJS application
2. Install the packages
3. Setup providers
4. Create button component and use `useConnectModal` hook.

### Anything else?

it's sad that you face a problem at the very beginning. There is not enough usage example, it will be cool if the team itself provides links to API usage examples.

**Comment by DanielSinclair** [comment]
@pavelivanov Hey Pavel. This seems to be an issue with your configuration. Can help debug if you share a CodeSandbox example! We use the `openConnectModal` function in our example dApp [here](https://rainbowkit-example.vercel.app), without issue. Please also reference our [with-next-custom-button](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-custom-button) example that uses `useConnectModal()`.

**Comment by pavelivanov** [comment]
@DanielSinclair thank you for so fast response. You are right, looks like it was somehow conflicted with previously setup ethers libs.
