### ISSUE TITLE
Code Sandbox for Next.js App Router is broken

### ISSUE THREAD

**Issue by 0xRowdy** [rainbow-me/rainbowkit#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

workspace:*

### wagmi Version

~1.0.5

### Current Behavior

Code Sandbox example gets stuck on Running Setup Tasks. Asks to select a version but there is no way to select version. App Never launches.

![image](https://github.com/rainbow-me/rainbowkit/assets/22626267/efab26cb-c81a-420d-88aa-87eed04015ac)

### Expected Behavior

The application should launch and should be able to see the project.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-next-app?file=%2Fpackage.json%3A12%2C32-12%2C43

**Comment by DanielSinclair** [comment]
@0xRowdy Ah, sorry about that. Created #1284 to fix that. Here's a temporary link in the meantime: https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/%40daniel/next-app-sandbox-fix/examples/with-next-app
