### ISSUE TITLE
[bug] need to handle refresh the balance when any transaction is completed

### ISSUE THREAD

**Issue by Sachidanand-shah** [rainbow-me/rainbowkit#1290]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

0.8.0

### wagmi Version

0.11.4

### Current Behavior

i have added ConnectButton in Navbar using react app, navbar render only once when app is started,
what happen whenever  i'm doing any transaction using MetaMask balance is not updating inside ConnectButton component  

### Expected Behavior

you have to re-render that component whenever any changes happen in MetaMask wallet

**Comment by 0xartcro** [comment]
I could work on that, any tips where to start?

**Comment by Sachidanand-shah** [comment]
You need re-render the connect button whenever any transaction happen;
in may case ConnectButton is Child component

**Comment by DanielSinclair** [comment]
Opened #1415 to implement this behavior with Wagmi's balance polling behavior
