### ISSUE TITLE
[bug] next-auth compatibility of 4.20.1

### ISSUE THREAD

**Issue by cctdaniel** [rainbow-me/rainbowkit#1292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.1

### wagmi Version

1.0.9

### Current Behavior

ran a copy of the with-next-siwe-next-auth example locally and getting `Error verifying signature, please retry!` when trying to sign message

### Expected Behavior

should be able to successfully sign message

### Anything else?

seems like `await getCsrfToken({ req })` is returning undefined even though the csrf token exists in `req`

**Comment by DanielSinclair** [comment]
@cctdaniel I typically see this when the `.env` or `.env.local` is missing. Did you supply the required env keys?

**Comment by prometx11** [comment]
Might be related to a breaking change in Next-Auth. 
You could try the fix to get the csrf token like that
```
const nonce = await getCsrfToken({ req: { headers: req.headers } });
 ``` 
instead of 
```
const nonce = await getCsrfToken({ req });
```

You can get more infos here https://github.com/nextauthjs/next-auth/issues/7166

**Comment by DanielSinclair** [comment]
@prometx11 I see. It is indeed relatated to that breaking change; the `next-auth` docs still haven't been updated. The current supported `next-auth` peers are `>=4.10.2 <=4.20.1`. Please revert while that settles. Will keep this open and see if we can mitigate with your recommendation.

**Comment by antho1404** [comment]
I am not sure how related it is, but I was able to make it work even with the `getCsrfToken({ req })` when forced to install the latest version but I had to force the install `npm i --force next-auth@4.22.1`
It would be great if the `<=4.20.1` could be removed it is not needed to force the install

**Comment by antho1404** [comment]
Any update related to the removal of `<=4.20.1`?

**Comment by DanielSinclair** [comment]
Support for `next-auth@4.21.0` and above is now available with [https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit-siwe-next-auth%400.3.0](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit-siwe-next-auth%400.3.0). Make sure to reference the [Migration Guide](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit-siwe-next-auth%400.3.0). Let me know if you bump into any issues.
