### ISSUE TITLE
[bug] error Error: `useConfig` must be used within `WagmiConfig`

### ISSUE THREAD

**Issue by mpaler** [rainbow-me/rainbowkit#1304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

main branch

### wagmi Version

1.2.0

### Current Behavior

Trying to run the examples from a fresh clone of rainbowkit and `pnpm run dev` in any of the examples throws the following error when navigating to the local instance (http://localhost:3000):

```
error Error: `useConfig` must be used within `WagmiConfig`.
```

### Expected Behavior

Examples should load up and be accessible via browser locally.

### Steps To Reproduce

```
git clone https://github.com/rainbow-me/rainbowkit.git rainbowkit
cd rainbowkit
pnpm install
cd examples/with-next-mint-nft
pnpm run dev
```
visit http://localhost:3000 in browser

**Comment by DanielSinclair** [comment]
@mpaler This is a package manager issue described [here](https://github.com/wagmi-dev/wagmi/issues/1491). Ensure that you're on a recent build of `pnpm` and try running `pnpm store prune` and `pnpm install --shamefully-hoist`. This should be fixed in an upcoming version of Wagmi.

**Comment by mpaler** [comment]
@DanielSinclair thank you

**Comment by DanielSinclair** [comment]
@mpaler Odd. I have found that build artifacts can also cause this. Try using our `pnpm run clean:untracked` to remove build artifacts and then run another install. Alternatively, we use Synced Templates on CodeSandbox, so you always use the latest demos with this syntax: https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-next-mint-nft

**Comment by vladislavKlimov** [comment]
@mpaler,  I experienced the same issues. Please check the version of your pnpm package. I encountered a problem with version 7.., and it was resolved after updating to the latest version, 8.7.4.

@DanielSinclair, perhaps it's worth considering adding some version check or a warning for the package manager version? The error stack trace is not very intuitive, and one can spend a significant amount of time trying to locate the issue. I could take care of that if you think it's necessary.

**Comment by DanielSinclair** [comment]
@vladislavKlimov Ah, that'll do it. Unfortunately we don't have much control over the behavior in this situation. We can add ```"packageManager": "pnpm@8.7.4",``` to our monorepo, but that won't help anyone consuming Wagmi or the RainbowKit package.

**Comment by vladislavKlimov** [comment]
@DanielSinclair  I'am agree, but it could help people who wants run dev mode of RainbowKit package.

**Comment by DanielSinclair** [comment]
@vladislavKlimov Agreed; opened #1507 to add that

**Comment by vladislavKlimov** [comment]
@DanielSinclair Thank you!
