### ISSUE TITLE
[bug] Inconsistent Sign-In Behaviour With Rainbow Wallet on Mobile Devices

### ISSUE THREAD

**Issue by vjohnston** [rainbow-me/rainbowkit#1305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.1

### wagmi Version

1.0.5

### Current Behavior

During the sign-in process via Rainbow Wallet, instead of directly opening the Rainbow Wallet app, occasionally a browser page opens, prompting users to "Go to Rainbow". This inconsistency occurs at various steps: sometimes after the "Connect Wallet" action and sometimes after the "Sign Message" action. Moreover, after users complete the required action within the Rainbow app, the application does not automatically navigate back to our app. When users manually navigate back, the application state is reset and does not acknowledge the signed message or the established connection.

Interestingly, we have noticed that opening dev tools or causing the web app to slow down makes this behaviour less frequent, suggesting possible race conditions.

### Expected Behavior

We expect the Rainbow Wallet application to open directly every time a user triggers an action (like "Connect Wallet" or "Sign Message"), and for the state of our application to consistently recognize these actions upon navigating back to our app.

### Steps To Reproduce

- Initiate the sign-in process in our app via Rainbow Wallet.
- Observe whether a browser page opens, prompting users to "Go to Rainbow" or if the Rainbow app opens directly.
- Complete the required Rainbow app action (connect or sign message).
- Manually navigate back to our app and note whether the application state acknowledges the action taken in the Rainbow app.

### Anything else?

We have already seen this issue in the [WalletConnect documentation](https://docs.walletconnect.com/1.0/mobile-linking#ios-app-link-constraints) and ensured that wallet interactions happen early in the event handler.

Additionally, we observed that the Rainbow app routes back to the "go to rainbow" webpage automatically after the "Connect" action but does not do so after the "Sign Message" action. We are curious as to why there's a difference in the behaviour between these two actions.

We hope you shed some light on why this is happening and whether there are any upcoming fixes or any possible workaround that could ensure a seamless user experience.

Thank you!

**Comment by vjohnston** [comment]
I can reproduce the issue on Rainbow Wallet + Safari and Rainbow Wallet + Chrome.
I tried the same flow with Metamask and Trust Wallet - both work so far

**Comment by DanielSinclair** [comment]
@vjohnston Thanks for reporting! Having a look at our go-back behavior. One explanation for the other failed redirects you're seeing when going to the wallet from the dApp is that you're forgetting to use [Prepare Hooks](https://wagmi.sh/react/prepare-hooks). These are specific hooks in Wagmi that prepare async work (like generating a transaction or signature request) before redirecting the user to the wallet because Mobile Safari will attempt to block non-user initiated redirects (like firing a redirect in a async fn after a 1 second network loop).
