### ISSUE TITLE
mac os chrome,Error: WebSocket connection closed abnormally

### ISSUE THREAD

**Issue by gwz-365461760** [rainbow-me/rainbowkit#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^1

### wagmi Version

1

### Current Behavior

Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: Unauthorized: invalid key)

App.tsx
`
import { ConnectButton } from "@rainbow-me/rainbowkit";

function App() {
  return (
    <>
      <ConnectButton />
    </>
  );
}
`

package.json
`  "dependencies": {
    "@rainbow-me/rainbowkit": "^1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "viem": "^1.1.6",
    "wagmi": "^1.2.1"
  }`

There is no link to any WebSocket, and this error is reported when the test project is started. I am sure it is RainbowKit version v1.x

**Comment by Jaypov** [comment]
Have you create a WalletConnect ID and passed it to your config?

```
const { wallets } = getDefaultWallets({
  appName: 'My App',
  projectId: '3q2....',
  chains,
});
```

this should fix that error for you

**Comment by linghuccc** [comment]
> 

I have the same error. But I am using customized wallet list, so I do not use getDefaultWallets, instead I used connectorsForWallets. Below is my code, please advise how I should revise them.

import { connectorsForWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit';
import {
  metaMaskWallet,
  walletConnectWallet,
  coinbaseWallet,
  okxWallet,
  trustWallet,
  imTokenWallet,
  rainbowWallet,
  injectedWallet,
} from '@rainbow-me/rainbowkit/wallets';
import { configureChains, createConfig, WagmiConfig } from 'wagmi';
import { mainnet } from 'wagmi/chains';
import { jsonRpcProvider } from 'wagmi/providers/jsonRpc';

const { chains, publicClient } = configureChains(
  [
    mainnet,
  ],
  [
    jsonRpcProvider({
        rpc: (chain) => ({ http: chain.rpcUrls.default.http[0] }),
    }),]
);

const appName = 'My App';
const projectId = 'My Project';

const connectors = connectorsForWallets([
    {
        groupName: 'Recommended',
        wallets: [
            metaMaskWallet({ projectId, chains }),
            walletConnectWallet({ projectId, chains }),
            injectedWallet({ chains }),
        ],
    },
    {
        groupName: 'Popular',
        wallets: [
            coinbaseWallet({ appName, chains }),
            trustWallet({ projectId, chains }),
            okxWallet({ projectId, chains }),
            imTokenWallet({ projectId, chains }),
            rainbowWallet({ projectId, chains }),
        ],
    },
]);

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
});

Thank you.

**Comment by linghuccc** [comment]
> Have you created a WalletConnect ID and passed it to your config?
> 
> ```
> const { wallets } = getDefaultWallets({
>   appName: 'My App',
>   projectId: '3q2....',
>   chains,
> });
> ```
> 
> this should fix that error for you

This is definitely not the cause of the issue. I just find out, even I just download rainbowkit without doing any change, there is this error. This error must be introduced by Wagmi update and nobody can use current version Rainbowkit  to do development at the moment.


    "@rainbow-me/rainbowkit": "^1.0.3",
    "next": "^13.4.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "viem": "~1.0.6",
    "wagmi": "~1.2.0"

**Comment by DanielSinclair** [comment]
@gwz-365461760 This appears to be because you've supplied an incorrect `projectId` for WalletConnect. Reference the docs [here](https://www.rainbowkit.com/guides/walletconnect-v2#:~:text=2.%20Supplying%20a%20projectId). It is also possible that your domain is not authorized for your Project within the WalletConnect Cloud dashboard. Please provider additional details as we will try to improve the error messages here.

**Comment by linghuccc** [comment]
> 

Thanks! This seems to be the cause. I tried to apply a project ID and the error disappeared. Will try more and hopefully the error won't come back.
