### ISSUE TITLE
[bug] wallet connect not working with gnosis wallet 

### ISSUE THREAD

**Issue by edgardo-mkr** [rainbow-me/rainbowkit#1323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.12.4

### wagmi Version

^0.12.6

### Current Behavior

since the implementation of walletConnect v2 and the requirement of the projectId, the connection of gnosis with my dapp through walletConnect fails with the following message: "Connection refused: Incompatible chain detected. Make sure the Dapp uses Goerli to interact with this Safe." the safe is in the goerli network that's why is asking for it but the i have goerli setup in the wallet and was working previously before adding the projectId

### Expected Behavior

Gnosis detecting the goerli network in my dapp and connecting without any issue

### Steps To Reproduce

-create a gnosis safe (https://app.safe.global/welcome)
-inside the safe select the option to connect using walletConnect
-In the dapp copy the link of the walletConnect modal and paste it in the gnosis page
-fails to connect 

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/sandbox/rainbowkit-walletconnect-m2jgz3

**Comment by glitch-txs** [comment]
This is currently being [discussed by WalletConnect team](https://github.com/orgs/WalletConnect/discussions/2733)
What happen is that wagmi will add the first chain of the array (when you set the config) as a required chain and the rest as optionals, if you set Goerli first in the array it will work for this particular case, ideally there should be q way to add multiple chains as optional and none as required but this is not possible ATM on ethereum-provider lib (the one wagmi uses on their connector)

**Comment by edgardo-mkr** [comment]
ok thanks, will do that as a temporary fix at least to be able to test for now. when they solved that issue could you notify it over here?

**Comment by DanielSinclair** [comment]
This appears to now work as expected on the latest versions of Wagmi, RainbowKit, and the Safe Dashboard.
