### ISSUE TITLE
Access to fetch at 'https://data-seed-prebsc-2-s3.binance.org:8545/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.[bug] <title>

### ISSUE THREAD

**Issue by linghuccc** [rainbow-me/rainbowkit#1326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.1

### wagmi Version

1.0.5

### Current Behavior

Whenever I load the page, below error will appear.
![binanceError](https://github.com/rainbow-me/rainbowkit/assets/59200993/ab49bd8a-21f8-4319-9828-0546054d9628)

### Expected Behavior

No error is expected

### Steps To Reproduce

The code is pretty standard. I was just following the Youtube video on RainbowKit Official channel: RainbowKit 🌈 🧰 Learn How to Build an NFT Minting Site with wagmi. (https://www.youtube.com/watch?v=YnxyVpE6PIE&t=57s)

And I was not even connecting to BNB testnet/mainnet. I do not understand why this error occurs.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/github/linghuccc/rainbowkit_example_error/master?workspaceId=54d5c3e7-96fe-41fc-b2e2-ab46b92fb8d9

### Anything else?

Strangely, running the project in codesandbox does not seem to have this error.

**Comment by DanielSinclair** [comment]
This appears to be an issue with Math Wallet as their content script is throwing the error.

**Comment by linghuccc** [comment]
> This appears to be an issue with Math Wallet as their content script is throwing the error.

But my code does not have Math Wallet at all....

**Comment by DanielSinclair** [comment]
@linghuccc This means the Math Wallet extension is installed in your browser; that is the origin of the error.

**Comment by linghuccc** [comment]
> @linghuccc This means the Math Wallet extension is installed in your browser; that is the origin of the error.

Thanks, this should be the cause.
