### ISSUE TITLE
[bug] Trust Wallet: Unable to sign typed data on Polygon after WalletConnect v2 upgrade

### ISSUE THREAD

**Issue by hzhu** [rainbow-me/rainbowkit#1334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.16

### wagmi Version

0.12.18

### Current Behavior

We're upgrading versions to support WalletConnect v2. However, we noticed that signing typed data on Polygon through WallletConnect results in an error:

<img width="1281" alt="error" src="https://github.com/rainbow-me/rainbowkit/assets/1811365/d29c1b3d-3b98-41b6-8ab8-74dc6225a424">

### Expected Behavior

I expect to sign typed data on Polygon without an error.

### Steps To Reproduce

You can reproduce locally following the steps below, or follow the steps with the[ live demo app](https://walletconnect-hzhu.vercel.app/). Also, a minimal code example can be found in [this repo](https://github.com/hzhu/walletconnect).

1. Ensure you have TrustWallet installed on your phone.
1. Install the dependencies with `npm install`.
1. Run the app with `npm run dev`.
1. Click on the "Connect Wallet" button.
1. Click "WalletConnect" and scan the QR code with the TrustWallet app.
1. Switch to the Polygon network.
1. Click on the "Sign typed data" button.
1. Observe the error in the JavaScript console.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

 https://github.com/hzhu/walletconnect

### Anything else?

❌ Signing typed data results in an error on Polygon

https://github.com/rainbow-me/rainbowkit/assets/1811365/1a926875-7aed-4907-b7ed-8e608572569b

✅ Signing typed data works on Ethereum

https://github.com/rainbow-me/rainbowkit/assets/1811365/34d41568-b32b-4367-9fd7-cd8966b44918

**Comment by glitch-txs** [comment]
Could you try updating wagmi to 0.12.8?

**Comment by hzhu** [comment]
> Could you try updating wagmi to 0.12.8?

Thanks for taking a look @glitch-txs 🙇🏽 . I tried downgrading wagmi to `0.12.8` and unfortunately the error is still present.

**Comment by 0xAsimetriq** [comment]
Unable to recreate via https://lab.web3modal.com/with-wagmi/react

1. Connect
2. Switch to polygon
3. Sign typed data

Need to check with RainbowKit team if sign typed data request is sent via polygin (not ethereum) after switching chain. Also, is your rpc set up for polygon correctly?

**Comment by DanielSinclair** [comment]
@hzhu I was able to replicate with Trust Wallet; it is a problem specific to Trust and they're throwing back this error `'The operation couldn’t be completed. (TrustWalletConnect.WCError error 1.)'`. Working fine via Rainbow and some other wallets right now. Will relay to their team.

**Comment by hzhu** [comment]
@DanielSinclair thank you for looking into this!

**Comment by hzhu** [comment]
Amazing, thank you @gastonm5. I'm looking forward to the fix 🙇🏽 .

**Comment by DanielSinclair** [comment]
Tested today and still ran into the same issue, so we'll need to wait for the Trust Wallet fix, but am going to close this out on RainbowKit's end

**Comment by kvngrldy** [comment]
@gastonm5 we encounter this exact issue on our app using trust wallet, do we have a fix released for this?
