### ISSUE TITLE
[bug] Unable to connect to Metamask on mobile

### ISSUE THREAD

**Issue by brian-lb** [rainbow-me/rainbowkit#1338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.1

### wagmi Version

1.0.9

### Current Behavior

Only applicable on mobile when attempting to connect wallet with metamask, rainbow kits opens up metamask, but doesn't prompt you to connect your account, and fails to connect do your dapp.

### Expected Behavior

RainbowKit should connect your wallet for your dapp.

### Steps To Reproduce

This is also reproducible on https://rainbowkit.com/

1. On mobile device, go to https://rainbowkit.com/
2. Click "Connect Wallet"
3. Click "MetaMask"
4. Notice it takes you to the MetaMask app and does nothing.

**Comment by brian-lb** [comment]
This may be related. Scanning QR Code.

![rainbowkit-err](https://github.com/rainbow-me/rainbowkit/assets/102826803/f37a27ce-350f-4f10-a116-669d60002d59)

**Comment by DanielSinclair** [comment]
@brian-lb You'll to upgrade to RainbowKit `1.0.2` or above. `1.0.1` still relies on WalletConnect v1, and the WalletConnect team unfortunately was aggressive in winding down those bridge servers. It is recommended that you use the latest versions of both Wagmi and RainbowKit, as WalletConnect v2 improvements are still propagating through the supply chain.

For your other point, there is a known issue https://github.com/MetaMask/metamask-mobile/issues/6457 with MetaMask Mobile deep links currently that the MetaMask team introduced in a recent release. We are waiting on that team to resolve the issue on their side. Tracking progress for that in #1303

**Comment by gonzaotc** [comment]
After reading this I have to ask, was compatibility added with v.0.12.x? my dapp is still facing issues with this version

"RainbowKit enabled WalletConnect v2 by default with 0.12.15 and 1.0.2. We are continuing support for 0.12.x in case your dApp has not yet upgraded to wagmi v1 and RainbowKit v1"
Source: https://www.rainbowkit.com/guides/walletconnect-v2

Thanks in advance

**Comment by DanielSinclair** [comment]
[0.12.17](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.12.17) and [1.0.5](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.0.5) are now available with a fix for the MetaMask Mobile connection issue.
