### ISSUE TITLE
[bug] Rainbow kit not working on the latest react version.

### ISSUE THREAD

**Issue by KosmosKey** [rainbow-me/rainbowkit#1339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.2

### Current Behavior

This is super disappointing. People i know even have spent hours figuring this out and we can't find the right solution.

Our goal is to build an web3 app with react.

Do these steps: 
1. `npx create-react-app my-app`
2. `cd my-app`
3. `npm install @rainbow-me/rainbowkit wagmi viem` (on rainbowkit's documentation)

You will get peer dependencies errors. In case i got this: 
```
npm ERR! Found: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">= 2.7" from fork-ts-checker-webpack-plugin@6.5.3
npm ERR!   node_modules/fork-ts-checker-webpack-plugin
npm ERR!     fork-ts-checker-webpack-plugin@"^6.5.0" from react-dev-utils@12.0.1
npm ERR!     node_modules/react-dev-utils
npm ERR!       react-dev-utils@"^12.0.1" from react-scripts@5.0.1
npm ERR!       node_modules/react-scripts
npm ERR!         react-scripts@"5.0.1" from the root project
npm ERR!   peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"5.0.1" from the root project
npm ERR!   1 more (tsutils) 
```

### Expected Behavior

Everything should work in the latest react version

**Comment by KosmosKey** [comment]
@DanielSinclair

**Comment by KosmosKey** [comment]
There are way more peer dependencies errors...

**Comment by DanielSinclair** [comment]
@KosmosKey Can you share a CodeSandbox example? Looks like a dev environment issue, but can try to diagnose. Feel free to checkout our latest [create-react-app example](https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app). Some common issues are described [here](https://www.rainbowkit.com/docs/installation#react-nextjs-and-webpack).

**Comment by KosmosKey** [comment]
@DanielSinclair It will only work if you do `npm i --force` or `npm i --legacy-peer-deps` which is not good. Regarding code sandbox i can't reproduce it there...

`
1. npx create-react-app my-app
2. cd my-app
3. npm install @rainbow-me/rainbowkit wagmi viem (on rainbowkit's documentation)
`

You will see it once you do these steps

**Comment by DanielSinclair** [comment]
@KosmosKey I see. This one is a bit out of our scope and control. `react-scripts` and `create-react-app` are essentially dead projects, and no longer maintained. Newer versions of Wagmi and RainbowKit have bumped up to TypeScript `^5.0.4`, and `react-scripts` is frozen in time. `npm i --force` is acceptable here. `yarn` will handle this TypeScript peer mismatch scenario a bit better as well. If you see any major issues outside of these installation errors, please do let me know. Some teams are having luck with `craco` and `react-app-rewired` to fork the outdated `create-react-app` setups. We'll need to evaluate that as well. Open to ideas!
