### ISSUE TITLE
The mobile connect wallet to metamask ,wallet connecter ,trust wallet not work .

### ISSUE THREAD

**Issue by chungit201** [rainbow-me/rainbowkit#1340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.10

### wagmi Version

0.12.9

### Current Behavior

when using mobile browser i can't connect with meatamask , trust wallet
​

### Expected Behavior

when using mobile browser i can connect with meatamask , trust wallet
​

### Steps To Reproduce

when using mobile browser i can connect with meatamask , trust wallet

### Anything else?

No

**Comment by neb-b** [comment]
We are also seeing this for our @linksdao site. Desktop is working fine, but seeing reports of users who can't login on mobile. Started happening yesterday

**Comment by leo-2408** [comment]
We are having a similar issue. After migrating for WalletConnect v2, the top level Metamask Button is no longer working. When tapping Metamask, it correctly sends users into the Metamask App, but with no tx signature pop up so they are unable to sign and get into our dApp. 

We did notice that if users first click WalletConnect and then Metamask from WalletConnect, everything works as expected, but the top level Metamask button is broken (see attached screenshot). Please help RainbowKit team! 

![Screenshot 2023-06-29 at 11 11 23 AM](https://github.com/rainbow-me/rainbowkit/assets/93679109/8924d55c-0615-4c6d-bafa-08cb68a505f0)

**Comment by neb-b** [comment]
@leo-2408 thanks for the suggestion. I am experiencing the same behavior. Metamask button opens the app with no prompt to sign a message, but using WalletConnect, then metamask works

**Comment by gonzaotc** [comment]
Facing the same issue here, Metamask button appears, redirects to the Metamask app but nothing happens

**Comment by marcolivierbouch** [comment]
![image](https://github.com/rainbow-me/rainbowkit/assets/29548847/ec906913-77a3-4eba-be3f-d35b307067fc)
I get this error when using wallet connect

**Comment by DanielSinclair** [comment]
This is unfortunately an issue with MetaMask Mobile specifically. We are awaiting their response to the open issues https://github.com/MetaMask/metamask-mobile/issues/6457. The introduction in recent weeks was unfortunately timed poorly with the WalletConnect v2 transition. Please relay to the MetaMask team and support channels. Tracking in #1303 and will close this as a duplicate.

**Comment by DanielSinclair** [comment]
You can assist users in mitigating the issue in the meantime by recommending that they use the in-app MetaMask Browser, as it does not rely on the the same WalletConnect deep link flow.

**Comment by Holybasil** [comment]
I found the reason, there's an extra / in the metamask deeplink.
In addition, [pr](https://github.com/rainbow-me/rainbowkit/pull/1372) has been submitted.

**Comment by DanielSinclair** [comment]
[0.12.17](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.12.17) and [1.0.5](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.0.5) are now available with a fix for this MetaMask issue.
