### ISSUE TITLE
[bug] Running test with walletConnect breaks since upgrade to 1.0.2

### ISSUE THREAD

**Issue by goosecoid** [rainbow-me/rainbowkit#1343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.2

### wagmi Version

1.1.1

### Current Behavior

When upgrading I got the following errors when running my unit tests:

```shell
To use WalletConnect server side, you'll need to install the "lokijs" dependency. If you are seeing this error during a build / in an SSR environment, you can add "lokijs" as a devDependency to make this error go away.
```

So next I installed lokijs

```shell
$ npm i lokijs
```

Afterwards I get the following error:

```shell
 To use QR modal, please install @web3modal/standalone package
```

Installing this package as well as its successor (@walletconnect/modal) doesn't fix the test.

When I comment the following line in my test:

```ts
const connectors = connectorsForWallets([
  {
    groupName: 'Recommended',
    wallets: [safeWallet({ chains }), metaMaskWallet({ projectId, chains }), rainbowWallet({ projectId, chains })],
  },
  {
    groupName: 'Others',
    wallets: [
      braveWallet({ chains }),
      coinbaseWallet({ appName: 'SettleMint', chains }),
      // walletConnectWallet({ projectId, chains }),
      injectedWallet({ chains }),
    ],
  },
]);

```

The test passes. Any ideas? I have checked all relevant walletConnect repos, but similar errors were only discovered when explicitly using the Web3Modal. Maybe rainbowkit uses it behind the scenes and something isn't right there?

**Comment by DanielSinclair** [comment]
@goosecoid Can you share a CodeSandbox example with your unit test and framework environment? You shouldn't need to install `@web3modal/standalone` as it is include upstream in Wagmi.

**Comment by DanielSinclair** [comment]
Discussed solutions in #1368
