### ISSUE TITLE
[bug] <Trustwallet disconnect Issue>

### ISSUE THREAD

**Issue by smartworlddev** [rainbow-me/rainbowkit#1354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.3

### Current Behavior

Hi, Great Team.
Hope you are doing well.
I got an error when I was trying to disconnect Trust Wallet from RainbowKit.
I am developing a project using Next.js and I am using RainbowKit to connect wallet.

Connection behavior was done successfully, but when I was trying to disconnect Trust Wallet, I got this error.

**Unhandled Runtime Error
TypeError: provider.removeListener is not a function**

I have attached the screenshot of detailed error.

I tried to test on several websites such as rainbowkit demos but got same error.

Please take a look and and fix this issue asap.
Any helpful feedback is appreciated.

Thank you.
![2023-07-01_23-19-45](https://github.com/rainbow-me/rainbowkit/assets/99595213/575f7339-5f63-4303-ab1d-c5ffd3dc19f7)

### Expected Behavior

Let's say I want to change wallet in the platform from Trust wallet to Metamask.
Because of this error, I can't connect another wallet such as Meta Mask as the previous session is still alive.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://walletconnect-hzhu.vercel.app/

**Comment by meri-maki** [comment]
Having the same issue with 
"@rainbow-me/rainbowkit": "^1.0.4",
		"@wagmi/core": "^1.3.3",
		"react": "^18.2.0",
		"viem": "^1.2.9",
		"wagmi": "^1.3.4",

**Comment by DanielSinclair** [comment]
Hi @meri-maki and @smartworlddev. This is a known issue that we have reported to the Trust Wallet team. Their ethereum providers seems to be doing something different than the standard implementation, causing this downstream issue. We are still awaiting a response from them. Closing in favor of #1259

**Comment by DanielSinclair** [comment]
[0.12.17](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.12.17) and [1.0.5](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.0.5) are now available with a fix for this issue.
