### ISSUE TITLE
Server Error: Attempted to call publicProvider() from the server but publicProvider is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.

### ISSUE THREAD

**Issue by linghuccc** [rainbow-me/rainbowkit#1363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.5

### Current Behavior

Please refer to image below:

![publicProvider](https://github.com/rainbow-me/rainbowkit/assets/59200993/5e34a0af-3634-4afa-af35-f4b0b273db0e)

### Expected Behavior

No error is expected.

### Steps To Reproduce

First run below command to create a new NextJs application:
npx create-next-app@latest

Then install RainbowKit as instructed in RainbowKit official page (https://www.rainbowkit.com/docs/installation);

Step 3: import, configure, and wrap providers as instructed in RainbowKit official page (https://www.rainbowkit.com/docs/installation);

Step 4: update parameter projectId from 'YOUR_PROJECT_ID' to my own; 

Step 5: edit next.config.js file as instructed in post (https://github.com/rainbow-me/rainbowkit/issues/1244)

Step 6: run below command:
npm run dev

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/github/linghuccc/rainbowkit_error/main?workspaceId=54d5c3e7-96fe-41fc-b2e2-ab46b92fb8d9

**Comment by DanielSinclair** [comment]
For the Next 13 App Router, you'll need to tag your RainbowKit and Wagmi implementation with `'use client';` at the top of the file and ensure that your bundler keeps this tag. This is a Next 13 requirement when using client-side libraries. Here is [an example](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-app) with best practices, including using a separate `Providers` component for RainbowKit and Wagmi that limits the client-side needs.
