### ISSUE TITLE
[bug] Got "Missing or invalid. request() method: wallet_swithEthereumChain" when switch chain with WalletConnect

### ISSUE THREAD

**Issue by jingxuan98** [rainbow-me/rainbowkit#1389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.4

### Current Behavior

Got this `Missing or invalid. request() method: wallet_swithEthereumChain` error when trying to switch chain using wallet connect + Gnosis Safe wallet

![Screenshot 2023-07-09 at 10 40 24 PM](https://github.com/rainbow-me/rainbowkit/assets/43902263/bfeea4ce-9579-4457-b2c3-c4ab75981ee7)

Any idea how can i solve this?

### Expected Behavior

Should be able to switch the chain for wallet connect + gnosis

### Steps To Reproduce

1. Connect WalletConnect + Gnosis Safe Wallet
2. call the wagmi hook `switchNetwork(chainId)` to switch chain
3. error should appear at console

**Comment by DanielSinclair** [comment]
@jingxuan98 This appears to be a Safe Wallet issue as the console error you're seeing is relayed by the wallet. We won't be able to address this on the RainbowKit side, but I'll relay the issue to the Safe team and see if we can get the issue resolved on their end.

**Comment by DanielSinclair** [comment]
Closing this out on the RainbowKit side, and am awaiting fixes/guidance from Safe

**Comment by DanielSinclair** [comment]
@jingxuan98 Do you have a particular use case in mind? The Safe team does not currently plan to fix this as most Safe usecases are single-chain.
