### ISSUE TITLE
[bug] Unexpected token E in JSON at position 0 from Csrf Token After Upgrading Next 13

### ISSUE THREAD

**Issue by 0xAskar** [rainbow-me/rainbowkit#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.5

### wagmi Version

1.3.8

### Current Behavior

After upgrading Nextjs to 13.x, I get an error on signature A) specifically on the await getCsrfToken because it gets an unexpected token at JSON... error when sending in the Req. It seems like the req state is a readable stream that isn't able to get parsed because its a circular object, I don't understand why the incompatibility that occurs after upgrading nextjs.
Specifically, there's an error when I try to get the CSRF token: `await getCsrfToken({ req }))`. The req looks something like this in C)

Here's the code for the authentication:

A)
```
https://next-auth.js.org/errors#client_fetch_error Unexpected token E in JSON at position 0 {
  error: {
    message: 'Unexpected token E in JSON at position 0',
    stack: 'SyntaxError: Unexpected token E in JSON at position 0\n' +
      '    at JSON.parse (<anonymous>)\n' +
      '    at parseJSONFromBytes (
      .... (shortened)
    name: 'SyntaxError'
  },
  url: 'http://localhost:3000/api/auth/csrf',
  message: 'Unexpected token E in JSON at position 0'
}
```
B)
```
import { Console } from "console"
import NextAuth from "next-auth"
import CredentialsProvider from "next-auth/providers/credentials"
import { getCsrfToken } from "next-auth/react"
// import {getToken} from "next-auth/jwt"
import { SiweMessage } from "siwe"

// For more information on each option (and a full list of options) go to
// https://next-auth.js.org/configuration/options
export default async function auth(req, res) {
  const providers = [
    CredentialsProvider({
      name: "Ethereum",
      credentials: {
        message: {
          label: "Message",
          type: "text",
          placeholder: "0x0",
        },
        signature: {
          label: "Signature",
          type: "text",
          placeholder: "0x0",
        },
      },
      async authorize(credentials) {
        try {
          const siwe = new SiweMessage(JSON.parse(credentials?.message || "{}"))
          const nextAuthUrl =
          process.env.NEXTAUTH_URL ||
            (process.env.VERCEL_URL
              ? `https://${process.env.VERCEL_URL}`
              : null)
          if (!nextAuthUrl) {
            return null
          }

          const nextAuthHost = new URL(nextAuthUrl).host
          if (siwe.domain !== nextAuthHost) {
            return null
          }
          // let token = await getToken({req})
          if (siwe.nonce !== (await getCsrfToken({ req }))) {
            return null
          }
          await siwe.validate(credentials?.signature || "")
          return {
            id: siwe.address,
          }
        } catch (e) {
          // console.log("failing something else", e)
          console.log(e)
          return null
        }
      },
    }),
  ]

  const isDefaultSigninPage =
    req.method === "GET" && req.query.nextauth.includes("signin")

  // Hide Sign-In with Ethereum from default sign page
  if (isDefaultSigninPage) {
    providers.pop()
  }

  return await NextAuth(req, res, {
    // https://next-auth.js.org/configuration/providers/oauth
    providers,
    session: {
      strategy: "jwt",
    },
    secret: process.env.NEXT_PUBLIC_NEXTAUTH_SECRET,
    callbacks: {
      async session({ session, token }) {
        session.address = token.sub
        session.user.name = token.sub
        session.user.image = 'https://www.fillmurray.com/128/128'
        return session
        
      },
    },
  })
}
```

C)
```
<ref *2> IncomingMessage
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: true,
    ended: true,
    endEmitted: true,
    reading: false,
    constructed: true,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: true,
    errored: null,
    closed: true,
    closeEmitted: true,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: true,
    dataEmitted: true,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: false
  },
  _events: [Object: null prototype] {
    end: [ [Function: clearRequestTimeout], [Function (anonymous)] ],
    error: [Function (anonymous)]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
..... 

```

### Expected Behavior

This should pull the CSRF token in the request (which does exist but wasn't included) but for some reason the new state doesn't work.

**Comment by DanielSinclair** [comment]
@0xAskar Did you happen to also upgrade `next-auth`? A breaking change was introduced after `4.20.1` that we're waiting on some documentation around, so if that's the case, please downgrade to `4.20.1` or below for the time being.

**Comment by DanielSinclair** [comment]
If that doesn't resolve the issue, are you using the Next.js App Router or Routes after upgrading to Next 13?

**Comment by 0xAskar** [comment]
@DanielSinclair hey thanks for the response:

- my `next-auth` is    ` "next-auth": "^4.15.0",`
- After upgrading to Next 13, I haven't changed what I had previously with respect to routes. I've been using `next/router`

Why do you think it may problematic because of that? Its weird that the response that hits the /api/auth/[next-auth] response is a stream which makes it not accessible for the csrf token.

**Comment by DanielSinclair** [comment]
Not sure if this would resolve the issue, but you should be using `NEXTAUTH_SECRET` instead of `NEXT_PUBLIC_NEXTAUTH_SECRET` as Next.js will bundle public envs on the client-side

**Comment by 0xAskar** [comment]
@DanielSinclair thanks for the reply, but that didn't seem to fix it either, changing the env variable and ensuring that the versions of next-auth are good. I'm still confused as to why the "res" that is passed into the nextAuth route is a circular object, a stream. Because I think that is what's preventing the getCsrfToken function from doing its thing correctly. Does that make sense or no? I'm confused as to why its a circular object that isn't parseable by the getCsrfToken function anymore?

**Comment by DanielSinclair** [comment]
With [@rainbow-me/rainbowkit-siwe-next-auth@0.3.0](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit-siwe-next-auth%400.3.0) (reference the Migration Guide) and the latest version of `next-auth`, are you still experiencing this issue? It is possible that we need to add more consideration for the App Router. Lmk

**Comment by 0xAskar** [comment]
@DanielSinclair i can try this and see if its still a problem

**Comment by Markkos89** [comment]
This worked for me!

```
// let token = await getToken({req})
if (siwe.nonce !== (await getCsrfToken({ req: { headers: req?.headers } }))) {
    return null
}
```

**Comment by 0xAskar** [comment]
hey @Markkos89 this worked for me too. this is great, thank you so much!
