### ISSUE TITLE
[bug] Got "Oops! An error occurred" when using TrustWallet chrome extension for approve() function of ERC20

### ISSUE THREAD

**Issue by jingxuan98** [rainbow-me/rainbowkit#1422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.7

### wagmi Version

1.3.9

### Current Behavior

Got "Oops! An error occurred" when using TrustWallet chrome extension for approve() function of ERC20
![Screenshot 2023-07-21 at 10 19 36 AM](https://github.com/rainbow-me/rainbowkit/assets/43902263/6eb6a32d-1ce3-4397-9829-7c38a20a6e5f)

When its other contract interaction, it works fine
![Screenshot 2023-07-21 at 10 18 24 AM](https://github.com/rainbow-me/rainbowkit/assets/43902263/418e1555-a499-47e3-9213-b98582027d75)

### Expected Behavior

Able to sign the approval txn successfully

### Steps To Reproduce

1. Try to sign a ERC20 approve() function

**Comment by DanielSinclair** [comment]
@jingxuan98 This is out of the RainbowKit scope and there won't be much we can do here, but I have forwarded the issue to the Trust team. If you don't receive a response, feel free to also open an issue on Wagmi as the issue could be in how you're preparing the signature request.
