### ISSUE TITLE
Change Polygon Mumbai RPC

### ISSUE THREAD

**Issue by redditoooor** [rainbow-me/rainbowkit#1424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.6

### wagmi Version

1.2

### Current Behavior

When rainbow wallet prompts a user to switch to polygon mumbai, it fetches an rpc that is not working anymore.

### Expected Behavior

When user who doesnt have mumbai and is prompted to approve the new mumbai chain to his list of networks, it should fetch a working one.

### Steps To Reproduce

Can you replace old RPC with this working one i got from chainlist.
https://rpc-mumbai.maticvigil.com

**Comment by DanielSinclair** [comment]
This is actually behavior controlled by Wagmi. Open an issue/PR over here: https://github.com/wagmi-dev/references Unfortunately I don't know which RPC the Wagmi team selects when an official testnet public RPC is unavailable.

The `infuraProvider` and `alchemyProvider` RPCs should still be working if you create an API key for either of those node providers. You can also always override their public RPC defaults manually in your `chains` list like this:
```tsx
import { configureChains, polygonMumbai as _polygonMumbai } from 'wagmi'
import { publicProvider } from 'wagmi/providers/public'
 
const polygonMumbai = { ..._polygonMumbai, rpcUrls: {
    public: { http: ['https://rpc-mumbai.maticvigil.com/'] },
    default: { http: ['https://rpc-mumbai.maticvigil.com/'] },
  },
};

const { chains } = configureChains(
  [polygonMumbai],
  [publicProvider()],
)
```
