### ISSUE TITLE
[bug] Error: WebSocket connection closed abnormally with code: 3000

### ISSUE THREAD

**Issue by Camillebzd** [rainbow-me/rainbowkit#1433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.3

### wagmi Version

1.2.2

### Current Behavior

A lot of errors appears every seconds in the console "Error: WebSocket connection closed abnormally with code: 3000". It seems to come from the walletauth:
![Capture](https://github.com/rainbow-me/rainbowkit/assets/48495021/b08eb8ca-3a6f-4da0-b1e0-6c2b001a111f)

How can we fix this ?

### Expected Behavior

I expect no errors at all...

### Steps To Reproduce

I implemented the rainbowkit in a Next.js app v13 by following the doc but you can even go directly on the sandbox here: https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-next-app.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-next-app

**Comment by DanielSinclair** [comment]
@Camillebzd Hey! Did you supply a valid `projectId` in the example?

**Comment by Camillebzd** [comment]
@DanielSinclair Hey, I fill really dump because this is written in big on the documentation that I needed a projectId from WalletConnect... Thank you very much for your time that was indeed the problem!
