### ISSUE TITLE
[bug] Metamask doesn't connect on Metamask browser on Android

### ISSUE THREAD

**Issue by saguirre** [rainbow-me/rainbowkit#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

v1.0.7

### wagmi Version

v1.3.9

### Current Behavior

Inside the Metamask browser on an Android phone, if the Metamask option is clicked, nothing happens. Other options, like Coinbase, Rainbow and WalletConnect work.

Metamask app version: v7.3.0.

### Expected Behavior

A connection popup shows that allows me to connect and subsequently sign a message.

### Steps To Reproduce

1. Open Metamask app on an Android phone.
2. Open the Metamask browser inside the Metamask app.
3. Go to app.playswoops.com/login
4. Tap on Sign in with your Wallet.
5. Tap on the Metamask icon.

### Anything else?

The app is a Next.js app (v12). I can provide code if this works for you to checkout the configurations I have in place:

```
// Inside _app.tsx
const { chains, publicClient, webSocketPublicClient } = configureChains(
    [mainnet, polygon],
    [infuraProvider({ apiKey: process.env.NEXT_PUBLIC_INFURA_API_KEY }), publicProvider()]
);

const { wallets } = getDefaultWallets({
    appName: 'App',
    projectId: `${process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}`,
    chains,
});

const connectors = connectorsForWallets([...wallets]);

const wagmiConfig = createConfig({
    connectors,
    publicClient,
    webSocketPublicClient,
    autoConnect: true,
});

const App = ({ Component, pageProps }: AppProps) => {
    return (
            <WagmiConfig config={wagmiConfig}>
                <RainbowKitProvider appInfo={{ appName: 'App, learnMoreUrl: 'https://blog.com' }}
                    modalSize="compact"
                    chains={chains}
                >
                    <Component {...pageProps} />
                </RainbowKitProvider>
            </WagmiConfig>
        );
    };
}

export default App;
```

**Comment by IhorLeonov** [comment]
Hi! How did you solve this problem?

**Comment by KosmosKey** [comment]
@saguirre Are you still seeing this issue ? If not we can close this issue. 

Feel free to open any issues if you find other bugs 👍
