### ISSUE TITLE
[bug] can't get modal state in version 0.12.18

### ISSUE THREAD

**Issue by sansx** [rainbow-me/rainbowkit#1439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.18

### wagmi Version

0.12.19

### Current Behavior

for now, there is no way can check current modal state in 0.12.18, there do have a hook `useModalState` but didn't export it

### Expected Behavior

export `useModalState` hook, or add modal state check like we did in v1

**Comment by DanielSinclair** [comment]
@sansx Unfortunately it will be difficult to continue bringing new APIs to 0.12.x. Is there a reason you are unable to upgrade to Wagmi and RainbowKit v1?

**Comment by DanielSinclair** [comment]
Will close for now, but will continue the conversation here!

**Comment by sansx** [comment]
> @sansx Unfortunately it will be difficult to continue bringing new APIs to 0.12.x. Is there a reason you are unable to upgrade to Wagmi and RainbowKit v1?

yeah, for some reason we need to use 0.12.x for now, I checked our codes, there is a hook called `useConnectionStatus` exported in https://github.com/rainbow-me/rainbowkit/blob/d5d1de8150857ab22d25e207214b357cbac6e09d/packages/rainbowkit/src/components/RainbowKitProvider/ModalContext.tsx#L127, but didn't export here https://github.com/rainbow-me/rainbowkit/blob/d5d1de8150857ab22d25e207214b357cbac6e09d/packages/rainbowkit/src/index.ts#L9, we just fix that part is enough, it won't be a big change but that hook is very useful

**Comment by DanielSinclair** [comment]
@sansx You can use Wagmi's `useAccount()` hook to replace `useConnectionStatus()`
```ts
const { isConnected } = useAccount()
```
