### ISSUE TITLE
[bug] RainbowKit Provider re-renders too many times when window is being resized

### ISSUE THREAD

**Issue by atanasbozhkov** [rainbow-me/rainbowkit#1440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.7

### wagmi Version

1.3.9

### Current Behavior

If you wrap your entire App in a RainbowKit Provider it seems that the provider uses a custom `useWindowSize` hook. [Hook Code](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/hooks/useWindowSize.ts#L13) 

The hook attaches a `onResize` listener on the window object - I'm assuming in order to render the correct modals for phones/tablets. 
While this behaviour is expected - the listener is not throttled and will re-render multiple times when resizing the browser window on a desktop. 
If the RainbowKit Provider is at the top level of the app - this means that the entire app will re-render multiple times when resizing. 

### Expected Behavior

As a user of RainbowKit I'd expect one of the following:

1. The onResize event handler is throttled (250-300ms) and by trailing event - so that it only re-renders the child elements of the provider when the user has finished resizing the browser. 
2. Less intuitive - but the provider might want to expose a prop/config option that allows dev to directly pass in the current windows size and update it as they fit. 

### Steps To Reproduce

1. Create a new Rainbowkit App - or better yet clone the [CRA example](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app)
2. In the main child of the RainbowKit provider - add a console.log to monitor re-renders. 
3. Start resizing the browser window and notice how many times the app re-renders.

**Comment by regexyl** [comment]
Just wondering, are there any updates to this? @DanielSinclair

**Comment by JoeyKhd** [comment]
Noticing this too!

**Comment by atanasbozhkov** [comment]
I am more than happy to implement this and raise a PR. 
I just need to know - seems like rainbowkit doesn't have any utilities that provide throttling - happy to write a func to do that - but a bit of expectation setting would be great to kick start this
