### ISSUE TITLE
[bug] Walletconnect V2 doesn't work in production

### ISSUE THREAD

**Issue by MB2M** [rainbow-me/rainbowkit#1445]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

0.12.18

### wagmi Version

0.12.19

### Current Behavior

In local development: Everything works perfectly

in production: I can't connect using a metamask or ledger live for example. When the app open, it doesn't ask for confirmation to connect to the site.

### Expected Behavior

When the app open, it should ask for a confirmation.

### Steps To Reproduce

you can try it here: [https://neofin-nft.com](https://neofin-nft.com)

**Comment by DanielSinclair** [comment]
@MB2M When creating and supply a `projectId`, did you whitelist your domain name in the WalletConnect Cloud dashboard? `localhost` is automatically whitelisted, but production domains are not.

**Comment by DanielSinclair** [comment]
Will close for now, but can continue investigating this issue for you

**Comment by MB2M** [comment]
Thank for you answer @DanielSinclair.

I was using nextjs 13.0.4. Just updated to the last version and everything is working fine!

**Comment by danaugrs** [comment]
We're experiencing this same issue. Everything works fine locally and on Vercel development branches. But on production branches the generated QR code is not read successfully by mobile apps.

**Comment by DanielSinclair** [comment]
@danaugrs Have you provided your `projectId? If so, there is likely a missing dependency or bundler issue. Can you open a new issue with a minimal reproducible example for us to debug your setup? Thanks!

**Comment by danaugrs** [comment]
@DanielSinclair I figured this out partially. The problem is fixed when the Wagmi `localhost` chain is included in the chain configuration, so that's why we're only seeing this in Production branches. Setting `isProd` to `true` below makes it fail.
```ts
export const { chains, publicClient, webSocketPublicClient } = configureChains(
  [
    mainnet,
    (isProd ? [] : [{ ...localhost, id: 31337 }]),
  ],
  [publicProvider()]
);
```
This is mind boggling to me and probably indicates some bug in some dependency -- either rainbowkit or another. Do you have any ideas?

**Comment by danaugrs** [comment]
It works with `mainnet` and `mantle` as well as `mainnet` and `localhost` but not with just `mainnet`. So it has something to do with multichain. It's likely a bug in RainbowKit. I created a ticket: https://github.com/rainbow-me/rainbowkit/issues/1521
