### ISSUE TITLE
[bug] No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect v2 https://www.rainbowkit.com/docs/installation

### ISSUE THREAD

**Issue by heymanishjain** [rainbow-me/rainbowkit#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.5

### wagmi Version

1.3.8

### Current Behavior

This is a very strange bug where it breaks the whole project and shows the below error 
**unexpected server error
No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect v2 https://www.rainbowkit.com/docs/installation**
but the actual error is something else. To replicate this integrate rainbowkit and then just give any undefined variable name or navigate to a 404 route it will throw you this error saying No ProjectId found but the actual reason is the route user tried to navigate is not present and instead of showing the 404 page it shows the unexpected server error so something is not set right here because when I try to comment out the rainbowkit provider wagmi config and wallet connect code part then 404 error page is shown properly for unknown routes.

Please help me fix this issue

### Expected Behavior

It should show the actual error messages and not say as unexpected server error or break the whole project.

### Steps To Reproduce

create a remix js project
integrate rainbow kit wallet
configure and handle 404 page for unknown routes
now hit any unknown route you will see this error

### Anything else?

<img width="1438" alt="Screenshot 2023-08-03 at 11 04 01 AM" src="https://github.com/rainbow-me/rainbowkit/assets/87717868/6fbfe389-840f-4528-a34d-1ec1b733e23c">

**Comment by DanielSinclair** [comment]
@heymanishjain Can you share a CodeSandbox example? When you see this error, is it accurate that your `projectId` is not specified? If so, that does need to fixed. This generally sounds like an issue with your configuration or a side-effect of Remix's Error/Catch Boundary tree, where this thrown error executes before Remix's standard 404 routing error is thrown.

**Comment by DanielSinclair** [comment]
Will close for now as this is more likely a Remix specific side effect
