### ISSUE TITLE
[bug] Webpack 5 build issues

### ISSUE THREAD

**Issue by dmytrotkk** [rainbow-me/rainbowkit#1458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.8

### wagmi Version

1.3.9

### Current Behavior

I'm currently integrating RainbowKit into a library that will be used by external React apps and ran into issues with webpack build.

Local in-project Storybook v7 (with default webpack 5 config) works just fine, but production build results in the following issues when imported into default `create-react-app`:

1. All inline SVGs are missing in Rainbow's popup window (see attached pic)
2. Strange `Uncaught SyntaxError: Unexpected token '<'` error appeared 

Current webpack config:

```
const path = require('path');
const webpack = require("webpack");

module.exports = {
  entry: path.join(__dirname, '/src/index.ts'),
  mode: 'production',
  output: {
    filename: 'index.js',
    publicPath: '',
    path: path.join(__dirname, 'build'),
    libraryTarget: 'commonjs',
    //chunkFilename: '[id].[chunkhash].js'
  },
  module: {
    rules: [
      { test: /\.m?js$/, type: 'javascript/auto' },
      { test: /\.m?js$/, resolve: { fullySpecified: false } },
      {
        test: /\.(ts|tsx)$/,
        loader: require.resolve("babel-loader"),
        options: {
          presets: [["react-app", {
            flow: false,
            typescript: true
          }]]
        }
      },
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        // include: path.resolve(__dirname, 'src'),
        exclude: /node_modules/
      },
      {
        test: /\.svg$/,
        use: [
          {
            loader: 'svg-url-loader',
            options: {
              limit: 200000,
            },
          },
        ],
      },
      {
        test: /\.css$/,
        sideEffects: true,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1
            }
          }
        ]
      },
      {
        test: /\.s[ac]ss$/i,
        use: [
          {
            loader: 'style-loader',
            options: {
              esModule: false,
            },
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true
            }
          },
          "sass-loader",
        ],
      }
    ]
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js", ".css", ".scss"],
    fallback: {
      // make sure you `npm install path-browserify` to use this
      path: require.resolve('path-browserify'),
      os: "os-browserify/browser",
      "fs": false,
      "https": require.resolve("https-browserify"),
      "http": require.resolve("stream-http"),
      "crypto": require.resolve("crypto-browserify"),
      "stream": require.resolve("stream-browserify"),
      "buffer": require.resolve("buffer")
    }
  },
  plugins: [
    new webpack.ProvidePlugin({
      Buffer: ['buffer', 'Buffer'],
    }),
    new webpack.ProvidePlugin({
      process: 'process/browser',
    }),
  ]
};
```

Maybe you have any reference webpack config that will load all required assets?

### Anything else?

<img width="1512" alt="Screenshot 2023-08-08 at 18 38 41" src="https://github.com/rainbow-me/rainbowkit/assets/15244591/f5c515a7-cc95-4d20-ba4a-5207ced36814">

Also, Storybook preview where is works fine: https://metaport-git-new-metaport-architecture-skale-network.vercel.app/?path=%2Fstory%2Ffunctional-widget--widget-demo

**Comment by RutenisN** [comment]
Getting same issue, have you found the solution?

**Comment by RutenisN** [comment]
For me the issue was that I used this in an iframe. I needed to fix my bash script which would transfer built files from one project to the one using those files.

**Comment by KosmosKey** [comment]
@dmytrotkk Are you able to provide us the `package.json` file ? We can have a look into the dependencies and test it ourselves on our end. 

You also mentioned you're using `create-react-app` right ? If you do it's recommended that you're using some other packages like `react-app-rewired`, but feel free to send us `package.json` first and then we can have a look 👍

**Comment by KosmosKey** [comment]
@dmytrotkk Going to close this issue. If this still doesn't work feel free to raise another issue.

You can also have a look at our example app with create-react-app [here](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app)
