### ISSUE TITLE
[bug] walletconnect on mobile is not working

### ISSUE THREAD

**Issue by slotZero01** [rainbow-me/rainbowkit#1466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.2

### Current Behavior

cannot connect walletconnect on mobile. However, it's working on desktop

got this error on mobile
```
Failed to launch 'wc:db9366530bf923fdd7f17db93d2425b85c4592241d660411aceb65b34e65d6ae@2?relay-protocol=irn&symKey=32b862f1cb07129234dfb5aecb62977e2534abdcb3fdd0e7381eb288e5d07252' because the scheme does not have a registered handler.
```

### Expected Behavior

can connect to walletConnect on both mobile and desktop

**Comment by DanielSinclair** [comment]
@slotZero01 Which wallet are you trying to connect to in this example? This is an iOS error if a wallet has not registered a deep link for WalletConnect. Is the wallet actively installed (and not i.e. offloaded by the system because of low memory)? Typically wallets will register both `wc://` and i.e. `rainbow://`

**Comment by slotZero01** [comment]
I was trying to connect to metamask mobile. The expected result I think is opening the QR modal or the official walletconnect modal that enables user to choose what wallet to connect to

**Comment by DanielSinclair** [comment]
@slotZero01 Can you provide more clarity on reproduction steps? Which platform are you using, and what is the exact test path?

**Comment by slotZero01** [comment]
can you try on this demo https://swap-telegram-git-master-slotzero01.vercel.app/ ?

**Comment by DanielSinclair** [comment]
@slotZero01 I was able to replicate the issue on your dApp, but am seeing strange failures. It is likely there is a lower-level dependency issue (likely in the WalletConnect libraries). Can you share a CodeSandbox example? Please also reference the build tooling setup guide to ensure all of these issues are already considered in your framework setup: https://www.rainbowkit.com/docs/installation#additional-build-tooling-setup
