### ISSUE TITLE
[bug]  Socket stalled when trying to connect to wss://relay.walletconnect.com

### ISSUE THREAD

**Issue by alexayan** [rainbow-me/rainbowkit#1467]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

1.0.8

### wagmi Version

1.3.10

### Current Behavior

Unable to log in with wallet connect.

console has the following error:

`Error: Socket stalled when trying to connect to wss://relay.walletconnect.org`

websocket url:

`wss://relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtpdnhpM2twQUtoTUhMTWR6MWRUdXZSUTNxVGU5Yllna3B5bkZ4VHFYRUs3RyIsInN1YiI6ImZlZDViYTQ3MWU5NDlmZjYxZTBiZGVlOGI4ODYwNGUzZGJiYTI2ZTg4NDMwNDBhYzNmZTk4OGNhYjQ5NzA0YzAiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY5MjA5OTg3MiwiZXhwIjoxNjkyMTg2MjcyfQ.HQHV-lP5ZqV5EAGv0s_yX3rWXv69eR5wCDCmQkwQEKEwtwX80HFnqtAOWx_iAtQnaPepgBZCuvlW8jFMFCWODw&projectId=626b0ac32f11c6d7ea40774c1e47ae88&ua=wc-2%2Fjs-2.9.2%2Fmacos-chrome-115.0.0%2Fbrowser%3Alocalhost%3A3000&useOnCloseEvent=true`

https://www.rainbowkit.com/ has the same problem connecting to the wallet via wallet connect

**Comment by DanielSinclair** [comment]
@alexayan This is a WalletConnect network level error upstream from RainbowKit. Do you happen to be using a VPN or have any other unique network characteristics? Have you specified your `projectId` created with WalletConnect Cloud?

**Comment by n1c01a5** [comment]
Same issue

**Comment by Hanggi** [comment]
It still happens on Chrome with next.js + rainbowkit

**Comment by ZeroTimeDrift** [comment]
Still trying to resolve this issue as well

**Comment by minnzee** [comment]
Same issue

**Comment by zkSoju** [comment]
Any resolutions?

**Comment by mmiw3** [comment]
any solutions?
