### ISSUE TITLE
`eth_getBalance` is requested when showBalance is disabled

### ISSUE THREAD

**Issue by DanielSinclair** [rainbow-me/rainbowkit#1488]
### Discussed in https://github.com/rainbow-me/rainbowkit/discussions/1479

<div type='discussions-op-text'>

<sup>Originally posted by **einaralex** August 23, 2023</sup>
My dapp does not need the balance of the native currency and I've made sure that `showBalance` on the ConnectButton is off, but RainbowKitProvider still calls `eth_getBalance` every time it's rendered, is there a way to stop this?</div>

**Comment by KosmosKey** [comment]
We will fix this in this PR: https://github.com/rainbow-me/rainbowkit/pull/1608

I'll mark it as solved for now and should be ready in the next release

**Comment by DanielSinclair** [comment]
This was fixed in #1681 with RainbowKit [1.3.3](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.3.3)
