### ISSUE TITLE
switch network doesn't working on mobile

### ISSUE THREAD

**Issue by minhhoang2404** [rainbow-me/rainbowkit#1490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.0

### Current Behavior

yesterday, I test switch network done. But today, it not show modal and redirect to metaMask switch network. Please check help me ˆˆ

### Expected Behavior

yesterday, I test switch network done. But today, it not show modal and redirect to metaMask switch network. Please check help me ˆˆ

### Steps To Reproduce

yesterday, I test switch network done. But today, it not show modal and redirect to metaMask switch network. Please check help me ˆˆ

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/

### Anything else?

https://www.rainbowkit.com/

**Comment by DanielSinclair** [comment]
This sounds like the expected MetaMask behavior. When requesting to switch networks, a MetaMask window will appear requesting an approval. This will occur each time. If you're seeing additional unexpected behavior, please feel free to reply and I can investigate further.
