### ISSUE TITLE
WebSocket connection failed: Invalid frame header

### ISSUE THREAD

**Issue by nextidearly** [rainbow-me/rainbowkit#1520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.11

### wagmi Version

1.4.1

### Current Behavior

ws.ts:121 WebSocket connection to 'wss://relay.walletconnect.com/?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtzZE15UEpYZktld0E1b25FYlcyQ0tlTFNKSmdMdlh4bVF4TjVwNlNXQ1pkUCIsInN1YiI6IjNiZGVjZDAwZmZkZGQzMGQzMjdlZTI5NjNhODkzOWMzNTQ1ZDhjNGZkN2E5ZjNhZjJkMmM2ZDcxZWYxZDIzMmYiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY5NTA4OTE5MCwiZXhwIjoxNjk1MTc1NTkwfQ.uEjWCMEIZZdg3xMie5_72cXIM3WRt6Jadi5iQNdd7u1HEmm6T2q68EObZAY44_S6769eRxTphMjNo0nTErc0Cg&projectId=85ea32d265dfc865d0672c8b6b5c53d2&ua=wc-2%2Fjs-2.10.0%2Fwindows10-chrome-116.0.0%2Fbrowser%3Alocalhost%3A3000&useOnCloseEvent=true' failed: Invalid frame header

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wildbase-swap-8mtsn24kb-nextidearly.vercel.app/

### Anything else?

![image](https://github.com/rainbow-me/rainbowkit/assets/130300960/af0aec34-246c-44da-bc06-ac7be6bb15e8)

**Comment by glitch-txs** [comment]
Hey, on your MRE I'm only seen this error which should be fixed in Wagmi v1.4.2 or higher
![image](https://github.com/rainbow-me/rainbowkit/assets/66949816/dc7db346-7713-427f-8cdb-956b2fbbf576)
