### ISSUE TITLE
[bug] Using only `mainnet` as the sole chain makes QR code scanning fail silently

### ISSUE THREAD

**Issue by danaugrs** [rainbow-me/rainbowkit#1521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.11

### wagmi Version

1.4.2

### Current Behavior

When providing only `mainnet` as the sole chain to `configureChains` the QR codes generated fail silently when scanned via a mobile wallet.

### Expected Behavior

I'd expect the generated QR codes to work for any number of chains.

### Steps To Reproduce

The below makes the QR codes fail silently when scanned
```ts
export const { chains, publicClient, webSocketPublicClient } = configureChains([mainnet], [publicProvider()])
```

The below makes QR codes work when scanned
```ts
export const { chains, publicClient, webSocketPublicClient } = configureChains([mainnet, mantle /* or `localhost` (or probably any other chain)*/], [publicProvider()])
```

**Comment by danaugrs** [comment]
I worked around this by modifying the `chains` object returned by `configureChains` to include a bogus chain (`localhost`).
```ts
const { chains, publicClient, webSocketPublicClient } = configureChains([mainnet], [publicProvider()])

// Adding `localhost` directly below is a workaround for this issue:
// https://github.com/rainbow-me/rainbowkit/issues/1521
// When we are actually supporting a second network we can remove `localhost` below and just use `chains`
// Localhost will show up as Unsupported Network since it's not being passed to `configureChains`, but including it here will fix the QR code issue
const modifiedChains = [chains[0], localhost];
```
And then passing `modifiedChains` instead of `chains` to the RainbowKit wallet functions e.g.:

```ts
const connectors = connectorsForWallets([
  {
    groupName: "Popular",
    wallets: [
      metaMaskWallet({ projectId, chains: modifiedChains }),
      walletConnectWallet({ projectId, chains: modifiedChains }),
      rainbowWallet({ projectId, chains: modifiedChains }),
    ],
  },
  {
    groupName: "Other",
    wallets: [
      argentWallet({ projectId, chains: modifiedChains }),
      trustWallet({ projectId, chains: modifiedChains }),
      ledgerWallet({ projectId, chains: modifiedChains }),
    ],
  },
]);
```

**Comment by KosmosKey** [comment]
Hey @danaugrs. Seems like everything works for me here with the same code your provided:

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/9965e455-eeed-4c70-ae96-30c4197b56fe)
![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/4bcb65bb-e4f9-4908-a42f-6ffbe9f8b3d7)

```
export const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet],
  [publicProvider()]
);

const connectors = connectorsForWallets([
  {
    groupName: "Popular",
    wallets: [
      metaMaskWallet({ projectId, chains }),
      walletConnectWallet({ projectId, chains }),
      rainbowWallet({ projectId, chains }),
    ],
  },
  {
    groupName: "Other",
    wallets: [
      argentWallet({ projectId, chains }),
      trustWallet({ projectId, chains }),
      ledgerWallet({ projectId, chains }),
    ],
  },
]);
```

Where exactly are you seeing this issue ? Is it with wallet connect ? 

Also if you could give me a reproducible example that would be great.

**Comment by DanielSinclair** [comment]
Ran through this again with Wagmi v1.4.12 and an example dApp with only 1 chain supplied, and couldn't replicate the issue. It is possible that there was a temporary error with the WalletConnect session relayer, or an issue with the wallet. If you're still seeing this issue with a particular wallet, let me know and I'll investigate further.
