### ISSUE TITLE
[bug] Invalid address on mobile safari

### ISSUE THREAD

**Issue by Linch1** [rainbow-me/rainbowkit#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.11

### wagmi Version

1.0.1

### Current Behavior

The first time that i click metamask icon, appears a popup that says "Would you like to open this page on 'Metamask' ?", 

but if you click 'cancel' on the pupop, and try to click the metamask icon again the popup now says that the link is now invalid.

Metamask is installed. On mobile chrome is working fine. I'm using Iphone 11.
You can reproduce it also on rainbowkit website.

**Comment by DanielSinclair** [comment]
@Linch1 This is unfortunately a limitation of iOS Mobile Safari, which blocks consecutive deep link attempts after a user has rejected the first one. We do plan to offer Universal Link connection options to users again, but that also comes with it's own set of limitations described [here](https://docs.walletconnect.com/web3wallet/mobileLinking#ios-app-link-constraints).

**Comment by DanielSinclair** [comment]
Marking as a duplicate of #1336
