### ISSUE TITLE
[bug] <RainbowKit breaks react rendering on build>

### ISSUE THREAD

**Issue by wulforr** [rainbow-me/rainbowkit#1543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.12

### wagmi Version

1.4.3

### Current Behavior

On adding rainbowkit to a react typescript project it stops working after build.

It works fine in local but once you build the project it stops working. 

### Expected Behavior

Should work even after building the app

### Steps To Reproduce

1. Create a react project using create-react-app with typescript template - `yarn create react-app rainbow-test --template typescript`
2. Add rainbowkit wagmi and viem from rainbowkit docs
3. Copy paste setup code from docs and wrap the WagmiConfig and RainbowKitProvider
4. Build app and use serve to test it locally it shows blank page

### Anything else?

**Some of the findings**

1. This might be related to new release as it works on older version of rainbowkit@0.12.10 which I have in a different project and when i downgraded the rainbowkit version to 0.12.10 it works. Not sure in which version in between it stopped working.
2. Not an issue with wagmi as I tried only wrapping wagmiConfig and it worked perfectly

**Comment by DanielSinclair** [comment]
@wulforr Can you share a CodeSandbox example or repo? There are fairly minimal updates with `1.0.11` and `1.0.12` so I would initially suspect a package manager or bundler issue in your project. Can help diagnose with an example.

**Comment by wulforr** [comment]
https://codesandbox.io/s/bold-meninsky-fll287?file=/src/App.js

In this sandbox I have added the basic structure but I am not sure on how to build in codesandbox

**Comment by DanielSinclair** [comment]
It looks like you have a few issues:
You should wrap your `<App/>` component with the providers like this:
```
<React.StrictMode>
    <WagmiConfig config={wagmiConfig}>
      <RainbowKitProvider chains={chains}>
        <App />
      </RainbowKitProvider>
    </WagmiConfig>
</React.StrictMode>
```
You need to use the `<ConnectButton/>` component to show a button for users. Checkout out Create React App example here: https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-create-react-app/

Let me know if you still see any issues

**Comment by wulforr** [comment]
I have wrapped it in the same way but its not working. 

https://github.com/wulforr/Rainbow-test/blob/main/src/index.tsx
