### ISSUE TITLE
any way to get rid of the wrapper data-rk div while theming?

### ISSUE THREAD

**Issue by shrugs** [rainbow-me/rainbowkit#1546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.12

### wagmi Version

1.4.3

### Current Behavior

using the `RainbowKitProvider` with the `theme` prop wraps my app tree in a `<div data-rk />` that is pretty damn annoying, layout-wise, to deal with, and usually requires setting some global css to make it not break my app layout while integrating rainbowkit.

```postcss
body > [data-rk] {
  @apply flex flex-col h-full;
}
```

which only works because luckily the rest of the data-rk divs are portalled into a naked div, which isn't tagged with data-rk.

### Expected Behavior

idk, it should be easy to set css variables without relying on this wrapper div across the whole project. for context, `connectkit` has their `ResetContainer` applied within any components that they render, meaning that abstraction doesn't leak into my app. no idea if it's a bad thing that they define those css variables all the time, but it makes it much less difficult to integrate.

### Steps To Reproduce

use any theme

**Comment by 0xernesto** [comment]
> i ended up just console-logging the generated css variables and adding those to my root component,
> 
> ```ts
>   console.log(
>     cssStringFromTheme(lightTheme(THEME_OPTIONS)),
>     cssStringFromTheme(darkTheme(THEME_OPTIONS)),
>   );
> ```
> 
> ```postcss
> :root {
>   // ...lightTheme
> }
> 
> .dark {
>   // ...darkTheme
> }
> ```
> 
> and setting `theme={null}` on the provider. seems like everything works just fine like this

Thank you. This was super annoying. It's ridiculous that this is not documented. I spent over an hour trying to figure out why my app's layout gets ruined by `RanbowKitProvider`.

**Comment by codeaid** [comment]
Just discovered this too after I realised my layout was broken due to RK wrapping the whole application in some completely unstyled `div` that you can't even style. Also, is there really a need to inject a whole `style` element into the DOM instead of adding it to `head`?

It's a bit ridiculous that a library that should be unobtrusive decides to just take over the whole application.
