### ISSUE TITLE
[bug] modal doesn't play well with radix's popper (and therefore shadcn/ui)

### ISSUE THREAD

**Issue by shrugs** [rainbow-me/rainbowkit#1547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.12

### wagmi Version

1.4.3

### Current Behavior

opening the connect modal from a radix dialog produces an invalid stacking experience where the RK modal is visibly in front of the radix content but click/hover passes through the rainbow modal and registers on the radix component.

this is because the radix popper adds `pointer-events: none` to the body element, and the RK modals don't explicity set `pointer-events: auto`

### Expected Behavior

clicks should work

### Steps To Reproduce

```tsx
<Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>title</DialogTitle>
            <DialogDescription>desc</DialogDescription>
          </DialogHeader>
          
          <DialogFooter>
            <DialogClose asChild>
              <Button variant="ghost" size="lg">
                nvm
              </Button>
            </DialogClose>
            <Button size="lg" onClick={connectAndSave} disabled={connectModalOpen}>
              sign in & save
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/sandbox/suspicious-jasper-g5lxl4

(page.tsx)

### Anything else?

the rainbowkit modal should perhaps capture any clicks on its background and stop propagation, otherwise the `onPointerDownOutside` override must be used on the top-most radix dialog

**Comment by shrugs** [comment]
with `pointer-events: auto` set on the RK parent div, clicks work but aren't captured and are still bubbling up the tree, cause the radix dialog to dismiss itself while the user clicks on "browser wallet" for example, since presumably it's triggering radix's "did click outside" logic. preventing bubbling of any clicks at the RK modal level should be the solution

**Comment by shrugs** [comment]
i suspect calling `e.stopPropagation()` as part of [this fn](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/Dialog/Dialog.tsx#L44C9-L44C28) will solve the bubbling issues, and including an explicit `pointer-events: auto` on https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/Dialog/Dialog.tsx#L54 will allow the modal to receive clicks in this situation

curiously, the `stopPropagation` on the [FocusTrap](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/Dialog/Dialog.tsx#L66C30-L66C45) doesn't seem to actually stop the propagation when a click occurs inside the RK modal

**Comment by DanielSinclair** [comment]
@shrugs Can you share a CodeSandbox sample so that I can have a look at your Radix components and UI?

**Comment by shrugs** [comment]
got around to making a repro! here it is (also updated above) https://codesandbox.io/p/sandbox/suspicious-jasper-g5lxl4

start in page.tsx

**Comment by hieuhlc** [comment]
I resolved this by using `modal` prop on Dialog

**Comment by shrugs** [comment]
@hieuhlc can you expand? i wasn't able to change the behavior whether i set `<Dialog modal />` to true or false

**Comment by hieuhlc** [comment]
When `modal` set to true, interaction with outside elements will be disabled (body has `pointer-events: none`)
So I set `modal={!connectModalOpen}` to enable pointer events

**Comment by shrugs** [comment]
ah, makes sense! i think this does solve the point events issue (though i'm not sure how this affects accessibility ¯\_(ツ)_/¯) but unless i'm mistaken you probably still need to prevent clicks using the onPointerDownOutside prop, or clicks will cause the radix dialog to dismiss itself
