### ISSUE TITLE
[bug] Breaks styling of entire app

### ISSUE THREAD

**Issue by emmajane1313** [rainbow-me/rainbowkit#1551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^1.1.1

### wagmi Version

^1.4.3

### Current Behavior

Adding the <RainbowKitProvider chains={chains}></RainbowKitProvider> to the App component breaks the entire styling of the app so that all content (outside of rainbowkit wallet) is forceably pushed to the left side of the screen. 

### Expected Behavior

Rainbow styling should only effect the rainbow wallet component.

### Steps To Reproduce

Adding <RainbowKitProvider chains={chains}> </RainbowKitProvider> to the NextJs app v13.3 (next). When removing the wrapper the issue is fixed. 

<WagmiConfig config={wagmiConfig}>
      <RainbowKitProvider chains={chains}>
        <Index />
      </RainbowKitProvider>
    </WagmiConfig>

### Anything else?

Two screenshots showing the state of the app with and without Rainbow error.
<img width="1512" alt="Captura de pantalla 2023-10-09 a las 8 30 14 a m" src="https://github.com/rainbow-me/rainbowkit/assets/72898465/5a12a9de-98ce-4dd9-b8db-fc79ad23dba2">
<img width="1510" alt="Captura de pantalla 2023-10-09 a las 8 30 04 a m" src="https://github.com/rainbow-me/rainbowkit/assets/72898465/02707310-cf9d-468a-868e-3decf29c8929">

**Comment by DanielSinclair** [comment]
@emmajane1313 Can you share a reproducible example? This typically shouldn't be the case.

**Comment by emmajane1313** [comment]
I think this was ultimately a nextjs error, i switched from using the App
router and there was no issues
