### ISSUE TITLE
[bug] <Issue connecting with metamask>

### ISSUE THREAD

**Issue by Jrosado16** [rainbow-me/rainbowkit#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.8

### wagmi Version

1.3.10

### Current Behavior

I am trying to connect with MM but I never get the MM option to connect and when I click on the icon it takes a while to go to the wallet

https://github.com/rainbow-me/rainbowkit/assets/32801851/e54a7ccb-4a70-43e7-9c3f-14a65e26250c

**Comment by DanielSinclair** [comment]
@Jrosado16 This unfortunately appears to be a WalletConnect v2 and/or MetaMask issue, outside of RainbowKit's control. If you are using a VPN, WalletConnect requests can often fail or create unstable behavior like this. The WalletConnect team is currently working on improvements, so please open an issue on their repo: https://github.com/WalletConnect/walletconnect-monorepo/issues
