### ISSUE TITLE
[bug] Firefox showing scan QR for all wallet options.

### ISSUE THREAD

**Issue by MeanBoyCousin** [rainbow-me/rainbowkit#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.16

### wagmi Version

0.12.18

### Current Behavior

Many of our users have raised support tickets with us recently about not being able to sign in to our dapp via Firefox. Despite having the necessary extensions installed and being on desktop devices, they are always presented with the QR code for sign-in.

### Expected Behavior

Users should be shown the standard sign-in flow via installed extensions.

### Steps To Reproduce

1. In a Firefox browser, visit [the dapp](https://app.rysk.finance/).
2. Click "Connect" in the top right corner.
3. Selecting one of the available wallet options will display QR codes.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://app.rysk.finance/

### Anything else?

The dapp front-end source code can be found [here](https://github.com/rysk-finance/dynamic-hedging/tree/production/packages/front-end).

**Comment by KosmosKey** [comment]
Hey @MeanBoyCousin. I've just taken a look at your repo and for me it seems to be working fine locally: 
![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/754285bc-d9a6-4134-bbd3-11661144d5eb)

Few things i can point out here is that on production (https://app.rysk.finance) the `window.ethereum` is disabled which means the wallets will be marked as "not ready" which leads to this issue. You can click on inspect -> console -> type in `window.ethereum`.

Production: 
![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/dacb6c2c-6cac-42d3-aabe-2af00912dc6c)

Local:
![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/1b69807f-3ba5-44f0-86c4-8da14a512d99)

When you deploy on production does something disable the `window.ethereum` ? If not then can you try updating your `wagmi` and `@rainbow-me/rainbowkit` to the latest one and tell me if that works ?

**Comment by MeanBoyCousin** [comment]
@KosmosKey Sorry for the late reply, totally forgot about this.

From what I can tell, this seems to be related to our CSP. I found this [very old thread](https://github.com/MetaMask/metamask-extension/issues/3133) that seems to have little traction and sadly, it seems that without downgrading our CSP to allow inline scripts there isn't much we can do.

**Comment by KosmosKey** [comment]
Hey @MeanBoyCousin. All good!

Yeah that's a bit rough. Honestly there isn't much we can do on our side since we use `window.ethereum` to get the injected providers. If the `window.ethereum` is not available we generate a QR code for the user to connect via wallet connect.

Hopefully there will be some solutions to CSP in the future, but if you're facing with any other issues feel free to create another issue. I'll close this one for now 🙏
