### ISSUE TITLE
[bug] WalletConnect option works on localhost but not in production

### ISSUE THREAD

**Issue by ZeroTimeDrift** [rainbow-me/rainbowkit#1598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.2.0

### wagmi Version

1.4.5

### Current Behavior

This QRcode works and scans fine on localhost but when deploying to prod the code doesn't scan using mobile wallets, deeplinked wallets also don't work on prod - checked the allowed origins, no issue there.

### Expected Behavior

Wallet QR code should scan

### Steps To Reproduce

go to https://staging.moongate.one/ and attempt to scan the qr code option on there.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://staging.moongate.one/

**Comment by DanielSinclair** [comment]
@ZeroTimeDrift Have you obtained a valid `projectId`? Also, are you using a VPN? WalletConnect is not supported and/or blocked via firewalls in some regions.

**Comment by ZeroTimeDrift** [comment]
Hey @DanielSinclair, I have a valid projectId, I can confirm I am also not using any VPNs. I've also tested this in multiple environments - you can check the staging URL at https://staging.moongate.one/

**Comment by DanielSinclair** [comment]
@ZeroTimeDrift I was able to replicate the issue on your deployment. The URI appears correct, so this could be a bundler or Next.js config issue. I also suspect there could be a CORS issue that blocks WalletConnect calls. Can you share a code sample or CodeSandbox? Please also double check that you've verified and whitelisted the domain via WalletConnect Cloud.

**Comment by ZeroTimeDrift** [comment]
You are totally right, wc2 works on npm run dev but fails to work on builds - any reason that might be from building?

**Comment by glitch-txs** [comment]
Are you using nextjs? Could you share your next.config.js if so?

**Comment by ZeroTimeDrift** [comment]
Resolved the issue, @DanielSinclair made a v. good point about the nextjs config, it's related to `swcMinify`

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  swcMinify: false,
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
        {
            protocol: 'https',
            hostname: '**',
            port: '',
            pathname: '**',
        },
    ],
},
}

module.exports = nextConfig

When `swcMinify` was set to true WC2 was throwing up a tonne of errors. Fixed now, thank you.
