### ISSUE TITLE
[bug] Custom injected wallet EIP1193

### ISSUE THREAD

**Issue by Heisenburgirs** [rainbow-me/rainbowkit#1600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.2.0

### wagmi Version

1.4.5

### Current Behavior

Custom connector displays QR code, but I doesn't trigger connection with the "window.lukso" injected provider.

### Expected Behavior

I'd like to have my custom injectedWallet look for "window.lukso" instead of "window.ethereum" and prompt connect that way.

I can't modify existing injectedWallet import from package, so I've to create custom one, but there's nothing on what I'm looking for within the documentation. Is it even possible to create custom injected wallet connector using custom logic?

**Comment by DanielSinclair** [comment]
You can add/distribute additional wallet connectors with the [Custom Wallet](https://www.rainbowkit.com/docs/custom-wallets) API. RainbowKit will be supporting EIP-6963 going forward to automatically detect installed wallets, so an additional connector won't be necessary in an upcoming release.
