### ISSUE TITLE
[bug] Cannot destructure property 'status' of '(0 , i.useSession)(...)' as it is undefined. on deploy

### ISSUE THREAD

**Issue by Mergemat** [rainbow-me/rainbowkit#1610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.2.0

### wagmi Version

1.4.6

### Current Behavior

I use rainbowkit-siwe-next-auth in my Nextjs App router project. I get my session in layout and passing it to my provider.
On development it works fine, i get my session (or null). But when i deploy on vercel it gives a error

```
TypeError: Cannot destructure property 'status' of '(0 , i.useSession)(...)' as it is undefined.
    at a (2699-ba09cec10158accd.js:355:189135)
    at rb (1dd3208c-4ac3c89ac4c1c5a4.js:1:40330)
    ...
```
So problem with this line.
https://github.com/rainbow-me/rainbowkit/blob/bd694e8457260cd3dd1c28a2076866d2a61f1d11/packages/rainbowkit-siwe-next-auth/src/RainbowKitSiweNextAuthProvider.tsx#L34C35-L34C35

For context i use it in a monorepo.
"next-auth": "5.0.0-beta.3",
"@auth/core": "^0.18.0",

### Expected Behavior

It doesn't give an error 🥺. 
Idk if it Next-Auth error or what. can it return undefined or null from useSession? idk.

### Steps To Reproduce

provider.tsx
```tsx
export function Web3Provider({
  session,
  children,
}: PropsWithChildren<{ session: Session | null }>) {
  return (
    <WagmiConfig config={wagmiConfig}>
      <SessionProvider session={session}>
        <RainbowKitSiweNextAuthProvider>
          <RainbowKitProvider
            chains={chains}
            theme={darkTheme({
              accentColor: "#212121",
              accentColorForeground: "#c0e000",
            })}
          >
            {children}
          </RainbowKitProvider>
        </RainbowKitSiweNextAuthProvider>
      </SessionProvider>
    </WagmiConfig>
  );
}
```

layout.tsx
```tsx
export default async function Layout(props: { children: React.ReactNode }) {
  const session = await auth();
  return (
    <html lang="en">
      <body
      >
          <Web3Provider session={session}>
            <Navbar />
            {props.children}
          </Web3Provider>
      </body>
    </html>
  );
}
```

### Anything else?

my repo is private, i cant make it public, but i can add you to the collabs so you can get more context of my problem

**Comment by Mergemat** [comment]
i copied `RainbowKitSiweNextAuthProvider` code and added 'use client' on top and it works!

**Comment by DanielSinclair** [comment]
> i copied `RainbowKitSiweNextAuthProvider` code and added 'use client' on top and it works!

@Mergemat Thanks for spotting this; we've amended the package to support the `use client` directive going forward

**Comment by DanielSinclair** [comment]
@Mergemat This looks like an incompatibility with the `next-auth@5` API. There are a few breaking changes with v5 that we will need to address; please downgrade to v4. I've also updated the adapter package to strictly warn about this compatibility for the time being. Will close this for now, and we'll update to v5 when the API settles in the next few days/weeks.
