### ISSUE TITLE
[bug] WalletConnect QR code not appearing

### ISSUE THREAD

**Issue by asoong** [rainbow-me/rainbowkit#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.7

### wagmi Version

1.4.3

### Current Behavior

Clicking WalletConnect does not surface a QR code despite configurations

I see a seemingly related error in the console whose stacktrace includes `walletconnect.js` but not sure how to make sense of it:
```
index.mjs:152 Uncaught (in promise) TypeError: n is not a function
    at index.mjs:152:20
    at async a.getItem (9.b5a06b3b.chunk.js:2:219759)
    at async 9.b5a06b3b.chunk.js:2:221374
```

Anyone seen anything like this before?

### Expected Behavior

Clicking WalletConnect should surface QR code

### Steps To Reproduce

You can try the application in production here: https://zkp2p.xyz/

Go to `Connect Wallet` > `WalletConnect`

See config file here: https://github.com/zkp2p/zk-p2p/blob/develop/client/src/index.js.

**Comment by KosmosKey** [comment]
Hey @asoong. Are you able to update `@rainbow-me/rainbowkit` and `wagmi` package to the latest version ? 

Also can you look at your [project id](https://github.com/zkp2p/zk-p2p/blob/develop/client/src/index.js#L48) and make sure it's configured correctly on the wallet connect dashboard ? Usually when a qr code is not appearing it has to do with the project id most of the times.

We also have an example repo [here](https://github.com/rainbow-me/rainbowkit/tree/main/packages/example) to look at. Here is the [preview link](https://rainbowkit-example.vercel.app/) as well.

**Comment by asoong** [comment]
Thanks for getting back to me.

I tried updating the packages to the latest [here](https://github.com/zkp2p/zk-p2p/pull/225) and also double checked my project id config. Neither seems to have done the trick.

**Comment by DanielSinclair** [comment]
@asoong It is possible that you're seeing a dependency bundling/resolution issue bubble up as this behavior. The WalletConnect libraries under the hood of Wagmi can sometimes be temperamental. Here is our example [Next.js app config](https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next/next.config.js) to compare against. Additional  docs discussing this are [here](https://www.rainbowkit.com/docs/installation#additional-build-tooling-setup). Let me know if this doesn't resolve the issue!

**Comment by DanielSinclair** [comment]
Closing for now, but let me know if your issue persists after the above!
