### ISSUE TITLE
[bug] <title>Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by gonghaibo** [rainbow-me/rainbowkit#1633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.0

### wagmi Version

1.4.7

### Current Behavior

I followed the documentation process to set up rainbowkit, but I don’t know why this warning was reported.

I thought it was a nextjs version problem, but the problem still exists after downgrading.
I also thought it might be a rainbowkit version issue, so I also downgraded, but the problem still exists.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/github/gonghaibo/mykit/master

### Anything else?

![image](https://github.com/rainbow-me/rainbowkit/assets/36252719/fac18aca-b837-4178-b178-4ae3bdb3fda1)

**Comment by DanielSinclair** [comment]
@gonghaibo Did you see any particular issue in functionality? This appears to just be a warning from the underlying WalletConnect libraries. This will be corrected with support for Wagmi v2.
