### ISSUE TITLE
[bug] Localization is always included without tree-shaking and is bloating the bundle size

### ISSUE THREAD

**Issue by akshatmittal** [rainbow-me/rainbowkit#1634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^1.1.0

### wagmi Version

1.4.7

### Current Behavior

Localization files are always included in every component and not being tree-shaked out when either a specific localization is selected or when it is disabled.

The package size is _significantly_ larger starting with v1.1.0 which is drastically increasing bundle sizes. See: https://bundlephobia.com/package/@rainbow-me/rainbowkit

### Expected Behavior

The localization files should be tree-shakable, be disabled when a specific localization is selected and not be enabled when there's no localization support.

### Steps To Reproduce

Install RainbowKit

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/sandbox/github/rainbow-me/rainbowkit/tree/main/examples/with-next-app

**Comment by KosmosKey** [comment]
Hey @akshatmittal

We'll reduce the localization bundle size pretty soon. I've linked a PR to this issue as well. Once it's merged i'll go ahead and close this ticket.

**Comment by qodeboy** [comment]
@magiziz is is merged, what's next? How to actually tree-shake unused locales? 

![shot_20240912_085452_NGa2RXod000346@2x](https://github.com/user-attachments/assets/7cad9490-dd6d-475a-a8fb-7a4d62f6f203)
