### ISSUE TITLE
[bug] Fix for signMessage via DeepLink to MetaMask mobile app

### ISSUE THREAD

**Issue by rnakashiro** [rainbow-me/rainbowkit#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.0

### wagmi Version

1.4.7

### Current Behavior

Sign Message button doesn't respond to MetaMask mobile app on iOS, it looks issue of DeepLink.

### Expected Behavior

Expected to move MetaMask mobile app, and user can sign.

### Anything else?

I found that RainbowKit@1.3.0 doesn't work, but wagmi examples page below works with MetaMask mobile app.
https://wagmi.sh/examples/sign-message

And I confirmed that wagmi@1.4.9 with RainbowKit@1.3.0 works.
This is diff of wagmi between 1.4.7 and 1.4.9.
https://github.com/wevm/wagmi/compare/wagmi@1.4.7...wagmi@1.4.9

Could you please add minor release to just upgrade wagmi@~1.4.9 ?

**Comment by KosmosKey** [comment]
@rnakashiro We've updated the latest wagmi and viem version in this PR: https://github.com/rainbow-me/rainbowkit/pull/1653

Can you let me know if it works now ?

**Comment by rnakashiro** [comment]
Hi, thank you for the updating, I confirmed the expected behavior 😄

**Comment by KosmosKey** [comment]
@rnakashiro Ok let me know if there is any other questions you have. If not i'll close this ticket.
