### ISSUE TITLE
[bug] "ChainId not found" when connecting to Ledger wallet via Ledger Live

### ISSUE THREAD

**Issue by deHB6** [rainbow-me/rainbowkit#1673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.1

### wagmi Version

1.4.12

### Current Behavior

I try to connect to a ledger wallet via the Ledger connector in rainbowkit dropdown
<img width="1212" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/129817868/653153bb-2590-4240-aeec-c87015b3ede9">

I then get this popup where the rainbowkit site is trying to open Ledger Live
<img width="643" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/129817868/8a659c74-b941-4ab4-a49d-b40c6cdc73d2">

I am presented with this screen in ledger live
<img width="788" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/129817868/ed696dfe-e78b-4797-a4aa-797e00552c01">

I scroll to the bottom and hit connect
<img width="788" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/129817868/efd4c307-5033-49ab-a266-6ffe8c7f01f4">

Ledger Live says I am connected
<img width="784" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/129817868/ac4b9015-9c69-45be-b9d2-ec9035b16f1a">

but nothing happens on the rainbowkit example site except an error appears in console "ChainId not found".
<img width="1562" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/129817868/1d1c66d8-66a4-4869-a6bc-6e8cfdd987a3">

fyi I am logged into ethereum mainnet app on my ledger and it is unlocked

Same behavior on my application I am building

### Expected Behavior

I can connect with ledger live and my application detects the connection

### Steps To Reproduce

See description above which uses rainbowkit example site

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://rainbowkit-example.vercel.app/

**Comment by DanielSinclair** [comment]
@deHB6 Thanks for reporting this. This appears to be an issue somewhere between Wagmi/WalletConnect and Ledger Live itself, outside of RainbowKit's control. I'll pass this on to the Ledger team. Can you share more information about your Wagmi configuration and chain list when encountering this error?

**Comment by KosmosKey** [comment]
@deHB6 Any updates on this ? Can you share your wagmi code setup so we can reproduce this on our end ?

**Comment by DanielSinclair** [comment]
This has been relayed to the Ledger Live team
