### ISSUE TITLE
[bug] RainbowKit Connect modal does not function properly within a Radix Dialog

### ISSUE THREAD

**Issue by antai0926** [rainbow-me/rainbowkit#1675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.2

### wagmi Version

1.4.12

### Current Behavior

When opening a Radix Dialog that contains a RainbowKit connect button, clicking the connect button to open the RainbowKit connect modal results in the inability to click any buttons.

### Expected Behavior

When a Radix Dialog is opened, which contains a RainbowKit connect button, clicking the connect button opens the RainbowKit connect modal, and the buttons on the modal can be clicked normally to connect the wallet.

### Steps To Reproduce

1. click open radix modal button
2. click rainbowkit connect wallet button
3. click the button on the rainbowkit connect modal.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/devbox/jolly-kirch-5d325l

### Anything else?

![截圖 2023-12-29 晚上10 10 21](https://github.com/rainbow-me/rainbowkit/assets/7610273/f176d75c-fb78-4e64-9773-d847304973ad)

**Comment by DanielSinclair** [comment]
@antai0926 Does this workaround resolve your issue? https://github.com/rainbow-me/rainbowkit/issues/1547#issuecomment-1756701266
