### ISSUE TITLE
[bug] siwe signature verify prompt on disconnect

### ISSUE THREAD

**Issue by edxeth** [rainbow-me/rainbowkit#1685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.2

### wagmi Version

1.4.12

### Current Behavior

Everytime I disconnect, call `signOut({ redirect: false })`, a new signature dialog appears. Very annoying and counter intuitive.
`signOut()` (without `redirect: false`) actually works but I don't want the app to perform a hard reload, that's the goal.
How do I fix it?

https://github.com/rainbow-me/rainbowkit/assets/105494645/a5d07b34-46ae-4b63-ae74-9beff6d97d7c

**@/app/connect/page.tsx**:

```ts
"use client";

import type { NextPage } from "next";
import { useSession, signOut } from "next-auth/react";
import { useAccount } from "wagmi";
import { useConnectModal } from "@rainbow-me/rainbowkit";

const ConnectModal: NextPage = () => {
  const { data: session, status } = useSession();
  const { isConnected } = useAccount();
  const { openConnectModal } = useConnectModal();
  return (
    <>
      <button
        onClick={
          session && isConnected
            ? () => signOut({ redirect: false })
            : () => openConnectModal?.()
        }
      >
        {status === "authenticated" && isConnected ? "Disconnect" : "Connect"}
      </button>
    </>
  );
};

export default ConnectModal;
```

**Dependencies**:

```json
"@rainbow-me/rainbowkit": "1.3.2",
"@rainbow-me/rainbowkit-siwe-next-auth": "0.3.4",
"next": "14.0.5-canary.37",
"siwe": "2.1.4",
"viem": "1.21.3",
"wagmi": "1.4.12"
```

**EDIT:** I was in a hurry so I forgot to add a title, I'm so sorry!
### Expected Behavior

No signature dialog is supposed to appear upon sign-out.

**Comment by c0rdeiro** [comment]
can you provide a codesandbox or stackblitz with this? It would be easier to help you

**Comment by c0rdeiro** [comment]
@edxeth so I took a look at this, and I'm not sure if you need to use the `signOut()` from next-auth because I think this is the root of this problem

You should just use `useDisconnect` from wagmi which fixes both the hard reload and the new signature dialog after disconnecting

**Comment by edxeth** [comment]
Yep, that worked like a charm!
Thank you very much @c0rdeiro

**Comment by KosmosKey** [comment]
@c0rdeiro Yeah that's correct. `useDisconnect` would be the option here. Thanks for looking at this 🙏
