### ISSUE TITLE
[bug] Migration doc for wagmi v2

### ISSUE THREAD

**Issue by evmbuddha** [rainbow-me/rainbowkit#1691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.3

### wagmi Version

2.0.3

**Comment by DanielSinclair** [comment]
@evmbuddha RainbowKit does not currently support Wagmi v2, but we'll have a beta release out in the next few days. Stay tuned to the releases.

**Comment by jd1900** [comment]
Can we use the "rainbowkit-wagmi-v2" branch now? or not yet available as beta release?

**Comment by DanielSinclair** [comment]
@jd1900 The beta release is not currently available. Check back early next week

**Comment by DanielSinclair** [comment]
The beta release for RainbowKit v2 with Wagmi v2 support is now available. Here is a [beta migration guide.](https://beta.rainbowkit.com/guides/rainbowkit-wagmi-v2) Please let us know if you see any type issues, bugs, or have feedback! We'll be in beta for the next week or so.
