### ISSUE TITLE
[bug] rename BSC chain name on switch networks modal error

### ISSUE THREAD

**Issue by rks118** [rainbow-me/rainbowkit#1699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.3

### wagmi Version

1.4.13

### Current Behavior

I want to rename chain's name on switch networks modal, but errors:

<img width="1137" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/146054454/529fbd65-d15c-41a0-8b4b-1c2ba8c67b08">

### Expected Behavior

Show correct name

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/devbox/amazing-goldberg-pr3v6p?file=%2Fsrc%2Findex.tsx

**Comment by KosmosKey** [comment]
@rks118 We currently don't support custom names for some chains. If the chain name is not configured on our end then it might work. 

You can probably try using a different chain like `holesky`, but with binance smart chain we always override the name to our own custom metadata provided [here](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/RainbowKitProvider/provideRainbowKitChains.ts#L121)
