### ISSUE TITLE
[bug] <Bifrost Wallet website doc omits wallet connect projectId >

### ISSUE THREAD

**Issue by james-carr-siftware** [rainbow-me/rainbowkit#1700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.0

### wagmi Version

1.4.13

### Current Behavior

Documentation [https://www.rainbowkit.com/docs/custom-wallet-list#bifrost-wallet](https://www.rainbowkit.com/docs/custom-wallet-list#bifrost-wallet)

## [Bifrost Wallet](https://www.rainbowkit.com/docs/custom-wallet-list#bifrost-wallet)

```
import { bifrostWallet } from '@rainbow-me/rainbowkit/wallets';
bifrostWallet(options: {
  chains: Chain[];
});
```
Gives an error:
`Error: No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect v2`

## [Bifrost Wallet](https://www.rainbowkit.com/docs/custom-wallet-list#bifrost-wallet)

```
import { bifrostWallet } from '@rainbow-me/rainbowkit/wallets';
bifrostWallet(options: {
  **projectId: string;**
  chains: Chain[];
});
```

### Steps To Reproduce

Follow the documentation in [(https://www.rainbowkit.com/docs/custom-wallet-list#bifrost-wallet]((https://www.rainbowkit.com/docs/custom-wallet-list#bifrost-wallet) and don't provide a wallet connect project id.

**Comment by KosmosKey** [comment]
@james-carr-siftware Thanks for pointing it out. We'll make sure to update `bifrostWallet` to include `projectId` in the doc.
