### ISSUE TITLE
[bug] Module not found: Package path ./connectors/walletConnect is not exported from package 

### ISSUE THREAD

**Issue by 0xPetra** [rainbow-me/rainbowkit#1723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.3

### wagmi Version

2.5.1

### Current Behavior

RainbowKit expects exports that are no longer supported by WAGMI. 

### Expected Behavior

Follow the installation guide and get things working out of the box.

It would be great to upgrade or update the docs to install the best-suited version from WAGMI. 

### Steps To Reproduce

Follow the manual installation guide.

**Comment by nakedfool** [comment]
+1

I'm curios if PR https://github.com/rainbow-me/rainbowkit/pull/1697 will solve rainbowkit migration to wagmi v2?

**Comment by KosmosKey** [comment]
> +1
> 
> I'm curious if PR #1697 will solve rainbowkit migration to wagmi v2?

Yep that's correct. We'll be merging a full migration guide to wagmi v2 and update our docs fully once we're going live with wagmi v2

**Comment by 0xPetra** [comment]
Amazing! 

I already downgraded, and got it working. But it would make sense to add the versions in the installation guide would be helpful to avoid this conflict. At least until wagmi v2 is integrated.

**Comment by nakedfool** [comment]
Btw, @KosmosKey, it appears that the rainbowkit package no longer exports the `Chain` type. I recently installed the beta version. Will `iconUrl` be removed or will it be added back in v2?

This is an example of code from before the v2 beta was released.
```
import { Chain } from "@rainbow-me/rainbowkit";

export const linea: Chain = {
  id: 59144,
  name: "linea",
  network: "linea",
  iconUrl: "/linea.svg",
  nativeCurrency: {
    decimals: 18,
    name: "Ether",
    symbol: "ETH",
  },
  rpcUrls: {
    public: {
      http: ["https://linea-mainnet.infura.io/v3"],
    },
    default: {
      http: ["https://linea-mainnet.infura.io/v3"],
    },
  },
  blockExplorers: {
    etherscan: { name: "Lineascan", url: "https://lineascan.build/" },
    default: { name: "Lineascan", url: "https://lineascan.build/" },
  },
};

```

**Comment by KosmosKey** [comment]
> Btw, @KosmosKey, it appears that the rainbowkit package no longer exports the `Chain` type. I recently installed the beta version. Will `iconUrl` be removed or will it be added back in v2?
> 
> This is an example of code from before the v2 beta was released.
> 
> ```
> import { Chain } from "@rainbow-me/rainbowkit";
> 
> export const linea: Chain = {
>   id: 59144,
>   name: "linea",
>   network: "linea",
>   iconUrl: "/linea.svg",
>   nativeCurrency: {
>     decimals: 18,
>     name: "Ether",
>     symbol: "ETH",
>   },
>   rpcUrls: {
>     public: {
>       http: ["https://linea-mainnet.infura.io/v3"],
>     },
>     default: {
>       http: ["https://linea-mainnet.infura.io/v3"],
>     },
>   },
>   blockExplorers: {
>     etherscan: { name: "Lineascan", url: "https://lineascan.build/" },
>     default: { name: "Lineascan", url: "https://lineascan.build/" },
>   },
> };
> ```

@nakedfool That's right we disabled that for now. We will expose a new function in the package that will allow you to add `iconUrl` and `iconBackground`. Here is the [PR](https://github.com/rainbow-me/rainbowkit/pull/1710) for more context, but we will make sure to release this in the next beta version.

**Comment by GMGNAI** [comment]
@rainbow-me/rainbowkit@2.0.0 is still having problems, while version 2.0.0-beta.6 works fine.

**Comment by KosmosKey** [comment]
> @rainbow-me/rainbowkit@2.0.0 is still having problems, while version 2.0.0-beta.6 works fine.

What version of RainbowKit, wagmi and viem are you using ? Have you followed the [migration guide](https://www.rainbowkit.com/docs/migration-guide) ?

**Comment by DanielSinclair** [comment]
@GMGNAI If you are able to share a reproducible example, that would be great as well. It is possible another factor is at play, like your bundler.
