### ISSUE TITLE
[bug] Using Rainbow Chrome Extension and rainbow-kit in dev environment causes  Error in invocation of runtime.sendMessage

### ISSUE THREAD

**Issue by softwarecurator** [rainbow-me/rainbowkit#1727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.1.3

### wagmi Version

1.4.5

### Current Behavior

```bash
TypeError: Error in invocation of runtime.sendMessage(optional string extensionId, any message, optional object options, optional function callback): chrome.runtime.sendMessage() called from a webpage must specify an Extension ID (string) for its first argument.
```

### Expected Behavior

No error lol

### Steps To Reproduce

```
  "dependencies": {
    "@headlessui/react": "^1.7.17",
    "@heroicons/react": "^2.0.18",
    "@rainbow-me/rainbowkit": "^1.1.3",
    "@rainbow-me/rainbowkit-siwe-next-auth": "^0.3.2",
    "alchemy-sdk": "^2.10.1",
    "ethers": "^5.7.2",
    "mongoose": "^8.0.0",
    "next": "^14.0.1",
    "react": "^18",
    "react-dom": "^18",
    "react-hot-toast": "^2.4.1",
    "siwe": "^2.1.4",
    "swr": "^2.2.4",
    "viem": "^1.18.0",
    "wagmi": "^1.4.5"
  },
  ```
  
  clicking connect just throws error

**Comment by KosmosKey** [comment]
@softwarecurator Do you have a small reproducible example ? It'll be easier for us to reproduce this issue on our end. Otherwise we'll just install the packages you've provided, but not get the same error.

**Comment by DanielSinclair** [comment]
@softwarecurator Another follow-up question! Which browser are you using? Do you have any other extensions installed?

**Comment by KosmosKey** [comment]
@softwarecurator Any updates ?

**Comment by KosmosKey** [comment]
Closing this issue for now due to inactivity. Please raise another issue if the problem still persists.

**Comment by billsbooth** [comment]
Hitting this same issue; on Chrome, Version 122.0.6261.69 (Official Build) (arm64), have latest Rainbow Wallet, Metamask, and Phantom wallets installed.
