### ISSUE TITLE
[bug] It looks like the new wagmi version doesn't support configureChains

### ISSUE THREAD

**Issue by rafaelfaria** [rainbow-me/rainbowkit#1729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.3

### wagmi Version

2.5.2

### Current Behavior

I am trying to follow the getting start guide and looking into most of the code snippets and everyone is using  "configureChains" however [The Wagmi v2](https://wagmi.sh/react/guides/migrate-from-v1-to-v2#removed-configurechains) Config now has native multichain support using the [chains](https://wagmi.sh/react/api/createConfig) parameter so the configureChains function is no longer required.

### Expected Behavior

Trying to get this working without the configChains has been a bit tricky, so expecting the docs to reflect the new version.

### Steps To Reproduce

Install the latst versions of wagmi and rainbowkit and follow the installation steps.

**Comment by KosmosKey** [comment]
@rafaelfaria That's right the `configureChains` is no longer supported in wagmi version `2.0.1` and higher. We'll be supporting the newest wagmi version pretty soon. For now feel free to use wagmi's version `1.4.13` if you want support for `configureChains`.

Also if you would like to use the latest wagmi version with rainbowkit feel free to follow our `beta` migration guide [here](https://beta.rainbowkit.com/guides/rainbowkit-wagmi-v2).
