### ISSUE TITLE
[BUG] Rainbowkit does not detect unsupported network correctly

### ISSUE THREAD

**Issue by allenjlee** [rainbow-me/rainbowkit#1744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0-beta.2

### wagmi Version

2.0.0

### Current Behavior

When switching network to a network that is not configured by Rainbowkit, the chain modal fails to detect that the network is not supported and still leaves the previous network connected even though it is not.

![bug](https://github.com/rainbow-me/rainbowkit/assets/24996586/da639bd5-81f6-4b3f-96c1-75b345ef832e)

### Expected Behavior

Expects that no network is selected in the modal.

### Steps To Reproduce

Go to: https://beta.rainbowkit.com/guides/rainbowkit-wagmi-v2. 
Connect wallet using Ethereum Mainnet.
Switch network to Ethereum Sepolia, or any network not on the configured list.
Unable to reconnect to Ethereum using the Modal UI.

**Comment by KosmosKey** [comment]
@allenjlee This will be fixed with RainbowKit v2. Wagmi automatically fallbacks to the first configured chain if your wallet switches to an unsupported chain.

Here is the PR if you're interested in seeing how it'll look like: https://github.com/rainbow-me/rainbowkit/pull/1709
