### ISSUE TITLE
[bug] Wallet balance not working

### ISSUE THREAD

**Issue by Markcode1992** [rainbow-me/rainbowkit#1750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.4

### wagmi Version

1.4.13

### Current Behavior

account.displayBalance is not working anymore and doesn't show anything

### Expected Behavior

account.displayBalance is supposed to show wallet balance

### Steps To Reproduce

Connect wallet and check for balance

### Anything else?

Works fine to 1.3.2

**Comment by KosmosKey** [comment]
@Markcode1992 Are you able to link us a small reproducible example ? 

There are cases where you might not see your balance:
1. You have set `showBalance` to `false` on one of the responsive values for `largeScreen` and `smallScreen`.
2. The rpc provider you use in `wagmi` configuration hasn't made a successful call to fetch your balance.
3. Your wallet isn't connected or isn't giving you back `address` from wagmi's `useAccount` hook.

**Comment by KosmosKey** [comment]
@Markcode1992 Are you able to give us a small reproducible example ? Also if you could show me the code you've written that'd be super helpful!
