### ISSUE TITLE
[bug] Build fails in monorepo

### ISSUE THREAD

**Issue by neel-ds** [rainbow-me/rainbowkit#1776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0

### wagmi Version

2.5.7

### Current Behavior

It works well in an isolated new app. I tried implementing it in Monorepo, and it works well but the build fails due to a type error from the package. I think it's maybe due to `wagmi/core`. I have followed the docs exactly with the Next App Router Sandbox example. 
![Screenshot 2024-02-17 at 3 13 53 PM](https://github.com/rainbow-me/rainbowkit/assets/79443588/8f6b083c-e0fd-4b28-9a75-811122b3d041)

**Comment by neel-ds** [comment]
> @neel-ds Just to confirm is this the RainbowKit's monorepo or is this your one ? Also what pnpm version are you using ?

In my monorepo. pnpm version: 8.3.1

**Comment by KosmosKey** [comment]
@neel-ds Since you're using next.js app router can i have a look at your provider code at least ? Since many people need to define `'use-client'` at the root of their provider like [this](https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-app/app/providers.tsx). 

The reason for this is because next.js app router uses server components and client components. Wagmi and RainbowKit configuration needs to be using client components.

If this doesn't work please can i get a small reproducible example ?

**Comment by neel-ds** [comment]
@KosmosKey Yes! I defined 'use-client'. Please check the attached screenshot of `provider.tsx` which is imported in layout.

For your reference:
```
dependencies: {     
        "@rainbow-me/rainbowkit": "^2.0.0",
        "@tanstack/react-query": "^5.20.5",
        "viem": "~2.7.10",
        "wagmi": "^2.5.7"
}
versions: {
        "node": v20.11.1
        "pnpm": 8.3.1
}
```

`apps/web/src/app/provider.tsx`
![Screenshot 2024-02-20 at 12 07 39 AM](https://github.com/rainbow-me/rainbowkit/assets/79443588/ecf15d45-00bc-4efb-8775-7e879ccb1d59)

**Comment by KosmosKey** [comment]
@neel-ds Can you put the config and queryClient above the Provider component ? Like [this](https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-app/app/providers.tsx#L28-L50)

**Comment by KosmosKey** [comment]
@neel-ds It would be super helpful to get a small reproducible example since i have no idea what exactly is wrong with the code you have. Would a small reproducible example be possible ?

**Comment by neel-ds** [comment]
@KosmosKey Thank you so much for the help! I have updated it according to the reference but it still fails in vercel.

> @neel-ds Can you put the config and queryClient above the Provider component ? Like [this](https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-app/app/providers.tsx#L28-L50)

Updated codebase:
![Screenshot 2024-02-21 at 4 50 52 PM](https://github.com/rainbow-me/rainbowkit/assets/79443588/418e6d5a-9190-49e1-a212-133e2e093612)


Please check the build log:
![Screenshot 2024-02-21 at 4 48 39 PM](https://github.com/rainbow-me/rainbowkit/assets/79443588/2b690f10-1a23-41d1-b8d2-2ef1f92cd8bd)

**Comment by KosmosKey** [comment]
@neel-ds Are you able to share a small reproducible example ? Just a github code or codesandbox would be great. 

Since i only know your `package.json` and `providers.tsx`. I can't really reproduce this issue on my end.

**Comment by neel-ds** [comment]
Here, you can find a reproducible [example](https://stackblitz.com/edit/stackblitz-starters-hfufcd). 

### Steps to reproduce
Please try to build the project by following command
```sh
npm run build
```

Current behaviour in build:
![Screenshot 2024-02-22 at 5 27 34 PM](https://github.com/rainbow-me/rainbowkit/assets/79443588/81a6ab13-c162-48d0-bb9a-8b5ebaa1f2fc)

**Comment by neel-ds** [comment]
Thank you very much. It solves the issue.
