### ISSUE TITLE
[bug] <title>.3eth swap get only 20 usdt worth of token

### ISSUE THREAD

**Issue by coolmanya1234** [rainbow-me/rainbowkit#1779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.0

### Current Behavior

guys pls help me, i use rainbow wallet many times, but unfortunately today i make transaction worth of .3 th, but i get only 20 usdt worth of token, pls help me, txid 0x427df857a009a4b45d663083b6a44d3540f4f62a62e7cf45cf4389fa2a5bed35

### Expected Behavior

guys pls help me, i use rainbow wallet many times, but unfortunately today i make transaction worth of .3 th, but i get only 20 usdt worth of token, pls help me, txid 0x427df857a009a4b45d663083b6a44d3540f4f62a62e7cf45cf4389fa2a5bed35

### Steps To Reproduce

guys pls help me, i use rainbow wallet many times, but unfortunately today i make transaction worth of .3 th, but i get only 20 usdt worth of token, pls help me, txid 0x427df857a009a4b45d663083b6a44d3540f4f62a62e7cf45cf4389fa2a5bed35

### Anything else?

guys pls help me, i use rainbow wallet many times, but unfortunately today i make transaction worth of .3 th, but i get only 20 usdt worth of token, pls help me, txid 0x427df857a009a4b45d663083b6a44d3540f4f62a62e7cf45cf4389fa2a5bed35

**Comment by KosmosKey** [comment]
@coolmanya1234 Can you send me link to the tx ? I can't find it on etherscan or polygon

Also what's your wallet address ?

**Comment by KosmosKey** [comment]
@coolmanya1234 Any updates ?

**Comment by KosmosKey** [comment]
@coolmanya1234 Closing this issue for now. If you're still facing this issue please feel free to reach out to the support team [here](https://rainbow.me/support)

**Comment by DanielSinclair** [comment]
@coolmanya1234 Hello! Can you please relay your issue to support@rainbow.me for us to further investigate? Thank yoU!
