### ISSUE TITLE
[bug] Error: To use QR modal, please install @walletconnect/modal package

### ISSUE THREAD

**Issue by nakedfool** [rainbow-me/rainbowkit#1781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2

### wagmi Version

2.5.7

### Current Behavior

When configuring connectors in a wagmi setup to include various wallets, including `walletConnectWallet`, the build process fails with an error message indicating the absence of the `@walletconnect/modal` package. This issue arises during the build phase, specifically when `walletConnectWallet` is listed among the connectors. Removing `walletConnectWallet` from the configuration removes the error, pinpointing the cause to the WalletConnect integration.

This is the exact error message `Error: To use QR modal, please install @walletconnect/modal package`

This is how i define connectors in wagmi config file
```
const connectors = connectorsForWallets(
  [
    {
      groupName: "Wallets",
      wallets: [
        metaMaskWallet,
        walletConnectWallet,
        rainbowWallet,
        okxWallet,
        tahoWallet,
        coinbaseWallet,
        argentWallet,
        trustWallet,
        imTokenWallet,
        omniWallet,
        bitgetWallet,
        rabbyWallet,
        phantomWallet,
      ],
    },
  ],
  {
    projectId: projectId,
    appName: appName,
  },
);
```

### Expected Behavior

The build process completes successfully without requiring the explicit addition of `@walletconnect/modal package`

Even if i install missing package, build still fails.

**Comment by KosmosKey** [comment]
@nakedfool Thanks for raising this issue.

May i ask you if you're using a VPN or if your dApp runs in a preview environment ? Are you testing this on localhost ?

Would be good to know what framework or library you're using as well since it might be a webpack issue as well 👀

**Comment by GMGNAI** [comment]
I'm facing the same issue. I'm using a Next.js React project with the following package details:
 
```js
 "@rainbow-me/rainbowkit": "2.0.0",
"viem": "^2.7.3",
"wagmi": "^2.5.5"
```

**Comment by KosmosKey** [comment]
@nakedfool I can't reproduce this on my end. This seems more of a webpack build issue where it might ignore one of the dependencies during build time.

Are you able to share your webpack configuration or `next.config.js` ?

**Comment by nakedfool** [comment]
@KosmosKey sure!

**Comment by KosmosKey** [comment]
@nakedfool Can you share a small reproducible example ? Seems like it works for me.

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/351284aa-1816-453f-b4f5-ae5960a35dbc)

**Comment by nakedfool** [comment]
> @nakedfool Can you share a small reproducible example ? Seems like it works for me.
> 
> ![image](https://private-user-images.githubusercontent.com/53529533/307059067-351284aa-1816-453f-b4f5-ae5960a35dbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzI2ODYsIm5iZiI6MTcwODkzMjM4NiwicGF0aCI6Ii81MzUyOTUzMy8zMDcwNTkwNjctMzUxMjg0YWEtMTgxNi00NTNmLWI0ZjUtYWU1OTYwYTM1ZGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA3MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzNlMTlhMzQ0NTA0Y2VkOTU0NDlhMTJjMDYyNjE3YTUwOGJjNDk2Njg1N2NlOTEzMTQ1NDQ2M2FjM2U2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DwBGi8jVyDpliV5Y8PPqM5K7CnmdD1jjN2HiCR6QYYo)

Huh, i'll try to reproduce issue but it feels like it can be a webpack build issue?

**Comment by nakedfool** [comment]
> I'm facing the same issue. I'm using a Next.js React project with the following package details:
> 
> ```js
>  "@rainbow-me/rainbowkit": "2.0.0",
> "viem": "^2.7.3",
> "wagmi": "^2.5.5"
> ```

Let me know if you figured it out!

**Comment by KosmosKey** [comment]
@nakedfool Can you share a small reproducible example ? Can you share a github code or codesandbox link ?

**Comment by nakedfool** [comment]
> @nakedfool Can you share a small reproducible example ? Github code or codesandbox link would be enough

I'm only able to share code here https://github.com/jk-labs-inc/jokerace/tree/chore/upgrade-to-wagmi-v2 as reproducing it won't make sense in current situation :/

**Comment by nakedfool** [comment]
> > it won't make sense in current situation
> 
> why not? it's really hard to help without a minimal repro >.<

Hm i think because of the number of dependencies that are in my project, however, i'll try to reproduce it and install all of them in a single repo and share here!

**Comment by glitch-txs** [comment]
are you bundling this into a package?

**Comment by KosmosKey** [comment]
@nakedfool Are you able to setup a fresh new RainbowKit and Wagmi project and try to write the same code and then share it here ? It'd really helpful if you could do that since i can then help you to see what's going on 🙏

**Comment by KosmosKey** [comment]
@nakedfool Sounds awesome! Thanks 🙏

**Comment by nakedfool** [comment]
@KosmosKey 

could this actually be due to `wagmi/connectors` package itself? 

```
Error: To use QR modal, please install @walletconnect/modal package
    at I.initialize (E:\jokerace\node_modules\@wagmi\connectors\node_modules\@walletconnect\ethereum-provider\dist\index.cjs.js:1:7377)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.init (E:\jokerace\node_modules\@wagmi\connectors\node_modules\@walletconnect\ethereum-provider\dist\index.cjs.js:1:2743)
```

not sure actually on which package this dependency fails, but if i remove custom connectors and try `walletConnect` from `wagmi/connectors` build would still fail.

**Comment by nakedfool** [comment]
Yeah even if i uninstall `wagmi/connectors` error is still the same as one above, this is still me debugging from the main repo. 

I'll create basic repo with these dependencies until end of week :)

**Comment by nakedfool** [comment]
@KosmosKey 

Here is the small repo that i've just bootstraped with create-rainbowkit https://github.com/nakedfool/jokerace-test-dependencies

Run it and you should be able to see exact error above with the config in `wagmi.ts`

**Comment by KosmosKey** [comment]
@nakedfool Can you add `ssr` field to `true` in `createConfig` function like this ?

```
export const config = createConfig({
  connectors: connectors,
  chains: [mainnet, sepolia],
  transports: {
    [mainnet.id]: http(),
    [sepolia.id]: http(),
  },
  ssr: true, // <- add 'true' here
});
```

**Comment by nakedfool** [comment]
> @nakedfool Can you add `ssr` field to `true` in `createConfig` function like this ?
> 
> ```
> export const config = createConfig({
>   connectors: connectors,
>   chains: [mainnet, sepolia],
>   transports: {
>     [mainnet.id]: http(),
>     [sepolia.id]: http(),
>   },
>   ssr: true, // <- add 'true' here
> });
> ```

hell yeah, this is it! thank youuuuuuuu :)

**Comment by nakedfool** [comment]
Hey @magiziz 

While the `ssr: true` resolved the build, some hooks like `useAccount` are returning now `undefined` during page load, which is because of the `ssr` enabled

Any different way that this build error can be solved?

**Comment by magiziz** [comment]
@nakedfool This shouldn't happen. `useAccount` should never return `undefined`, more info [here](https://wagmi.sh/react/api/hooks/useAccount#useaccount). Did you wrap your `<WagmiProvider>`, `<RainbowKitProvider>` and `<QueryClientProvider>` in the right order ? Can you please share your code ?

**Comment by glitch-txs** [comment]
Use cookies as storage

https://wagmi.sh/react/guides/ssr

**Comment by glitch-txs** [comment]
Yeah you need the wagmi provider which hydrates the store if you're using the SSR flag

**Comment by nakedfool** [comment]
> Yeah you need the wagmi provider which hydrates the store if you're using the SSR flag

Oh i see, much thanks for research & help here! 

It looks like they only have an example for the nextjs app router, they still do not have an example for the pages router, i'll see if i can find a solution!
