### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'l.sendTransaction')

### ISSUE THREAD

**Issue by IbrahimSam96** [rainbow-me/rainbowkit#1795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.0

### wagmi Version

1.4.7

### Current Behavior

Get a error when signing transaction. 

### Expected Behavior

Re-direct to metamask to sign transactions. 

### Anything else?

I'm sure the tx is correct and  works fine on desktop. 

<img width="999" alt="Screenshot 2024-02-22 at 10 52 36 AM" src="https://github.com/rainbow-me/rainbowkit/assets/72482204/3937b3a1-6f1c-4115-9fcd-cf28f7d21442">

**Comment by IbrahimSam96** [comment]
UPDATE: I updated my metamask app to the latest version, and disconnected my wallet. Connected again and tried sending transaction but this is what I get. Is it only wallet connect that's supported ? 

<img width="1000" alt="Screenshot 2024-02-22 at 10 57 21 AM" src="https://github.com/rainbow-me/rainbowkit/assets/72482204/12e1351c-07d4-4e77-92ec-7f901e425943">

**Comment by IbrahimSam96** [comment]
Latest version is  ``@rainbow-me/rainbowkit": "^1.3.6"`` ?

> @IbrahimSam96 Can you share a small reproducible example ? Also is it possible for you to upgrade to RainbowKit v2 ?

Updated to V2: 
```
    "@rainbow-me/rainbowkit": "^2.0.0",
     "viem": "^2.7.12",
    "wagmi": "^2.5.7"
```
Still get same error. I just want to be able to sign any transaction from my phone.

**Comment by KosmosKey** [comment]
@IbrahimSam96 Can you share a small reproducible example ? 

I can't reproduce this on my end. Please send the RainbowKit and wagmi configuration setup + the code where you're signing the transaction.

**Comment by IbrahimSam96** [comment]
### Signing Transaction
``` 
const transactionHash = 'W3siZGF0YSI6IjB4MDk1ZWE3YjMwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA2Zjc3NjA1MWNlMmQzMDFiODA1YjkzZWFkMjc4YTk5NmE5Njc0Y2JlMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDE0N2QzNTcwMCIsInRvIjoiMHhDQjJCMjc3ZjQ1ZjA3NUYwOGNCNDRGOTFCYTMwM0ZCQjEwNjU2RTk1In0seyJkYXRhIjoiMHgyMDc3YzU0YmM0NzYwMzkyMzIxZGEyNzI4MjhmMDgwMzRlOWNiODJiZGIwMWY2MzQ3NGUzMzlkNmNhY2ZkMTJiYzNlOWMwZjIyMTkzMThmMTY3NTk1ZGRkYzliYmU4ZWNiMWNkMGNmMTVjYjNmODJmMDYxMDUxZDAxZGM0OTRkZTA2MzAwNTY0Mjc3MTE3MmJkMDdkNzI0ZjFjZTI5MWIzMzRkNjBlYTQxOTk4MjA1MjYyYmJlNGQwOWIwNTFjMDUwMzk4NmZhOTA1Y2M1OTU3MjBiYzdmZGRlNGQwMjU3YTdlYWE1YTY3NGJhOWJiYTk1MGRmMDM1YjM4MTJlZGRiYTdmNjE4MTcxMDQ3YjczMmE0YzEwNTlmMGZjNjZhYmEwOTI0OWRlMjA1MTJjOTI2MGMxNGU0YmIwZmIyZmU5ZjQwNzU0MWY4MmYwYzdjZTJmNDFjMmM2NjA4N2MxNzkzYzg3NjZmYzhlMjkyMjY2N2MwMzFlZTBkOWI1MGJhMDZiNzk2YjA3ODE2N2U0NDMwOGRjMzVjNTI3YTQ5ZjVlNWE1MmVkOTgxZjI1OGY4Yzg3NGM5MDllYzNjM2RiMjU1MDQ3ZWU0ZWEyZDAxYjg2YmYxNDc2MzRmNTVkMDIzOGViNWI4YTIxNjM1YjIyNjcyZjljNjE4ZjEwOWI1MTU0ZTBjOTQ3NjI0MGY0ZDJmYjg1NTFiZjIwMzMwZmVmM2QyNjBlOTA4YjgyNDYxYzUwNWUyN2Q4M2U3MWFkZDc4YjYxY2NlODMxNTI5NzE5Njg5NGE1MTU3YmVhMWM0NjYxMzgwNTZhZjg1ZWM0OTM3M2QzN2JlNjEwMzA1ZjE1NDQyMTJiNzAwYmEwMjc3YWI4NjFkYzYyNjJkM2RlYWQ2MDI2OTJhZWU2ZDg0NTk5ZWZmMzIxYzYxZGM5YWQ3NDlkMmJiYTQ3NGZhIiwidG8iOiIweDZmNzc2MDUxQ2UyZDMwMWI4MDViOTNlYUQyNzhBOTk2QTk2NzRjYkUiLCJ2YWx1ZSI6IjAiLCJnYXNMaW1pdCI6IjUwMDAwMCJ9XQ='     
const decodedTx = Buffer.from(transactionHash, "base64").toString("utf-8");
const serializedTransaction = JSON.parse(decodedTx);

                    await walletClient.sendTransaction({
                        ...serializedTransaction[1],
                        account: wallet.address!,
                        chain: avalancheFuji,
                    }).then((tx) => {

})
```
### Rainbowkit and wagmi configuration setup 
```
import * as React from 'react';
import {
    darkTheme,
    RainbowKitProvider,
} from '@rainbow-me/rainbowkit';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { WagmiProvider, http } from 'wagmi'
import { getDefaultConfig } from '@rainbow-me/rainbowkit'
import {
    avalancheFuji
} from 'wagmi/chains';

const config = getDefaultConfig({
    appName: 'MegaWeapon - Ludex',
    projectId: '52a2dd0d9df4662c8ebee5de93f9770c',
    chains: [avalancheFuji],
    transports: {
        [avalancheFuji.id]: http(),
    },
})
const queryClient = new QueryClient()

export function Provider({ children }: { children: React.ReactNode }) {

    const [mounted, setMounted] = React.useState(false);
    React.useEffect(() => setMounted(true), []);

    return (
        <WagmiProvider config={config} >
            <QueryClientProvider client={queryClient}>
                <RainbowKitProvider theme={darkTheme({
                    accentColor: '#7b3fe4',
                    accentColorForeground: 'white',
                    borderRadius: 'small',
                    fontStack: 'system',
                    overlayBlur: 'small',
                })} >
                    {mounted && children}
                </RainbowKitProvider>
            </QueryClientProvider>

        </WagmiProvider>
    );
}

```

**Comment by DanielSinclair** [comment]
@IbrahimSam96 It looks like you're crossing a few wires with Viem actions and Wagmi hooks. With Wagmi, you'll typically want to rely on Wagmi's React hooks (which use a Viem `walletClient` under the hood). This is the dev UX the `WagmiProvider` is designed around.

Try setting up your signing routine like this, and reference the docs [here](https://wagmi.sh/react/api/hooks/useSendTransaction):
```tsx
import { useSendTransaction } from 'wagmi'
import { parseEther } from 'viem'

function App() {
  const { sendTransaction } = useSendTransaction()

  return (
    <button
      onClick={() =>
        sendTransaction({
          to: '0xd2135CfB216b74109775236E36d4b433F1DF507B',
          value: parseEther('0.01'),
        })
      }
    >
      Send transaction
    </button>
  )
}
```
If you're still seeing an issue, this is likely a problem with Wagmi and outside of the scope of RainbowKit, so try to open an issue with them [here](https://github.com/wevm/wagmi/issues)

**Comment by IbrahimSam96** [comment]
> Try setting up your signing routine like this, and reference the docs [here](https://wagmi.sh/react/api/hooks/useSendTransaction):

  Thanks for referring me to the docs.

 This signing routine is for sending value to a wallet.  In my case, I'm tryna send an unsigned populated transaction.

**Comment by IbrahimSam96** [comment]
> @IbrahimSam96 It looks like you're crossing a few wires with Viem actions and Wagmi hooks. With Wagmi, you'll typically want to rely on Wagmi's React hooks (which use a Viem `walletClient` under the hood). This is the dev UX the `WagmiProvider` is designed around.
> 
WOW this worked fine for me. Replacing ``walletClient.sendTransaction`` from viem with ``sendTransaction`` from wagmi.
