### ISSUE TITLE
[bug] Make the'WalletConnect Cloud 'feature non-blocking to rainbowkit connection logic

### ISSUE THREAD

**Issue by jiangmaniu** [rainbow-me/rainbowkit#1812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0

### wagmi Version

2.5.7

### Current Behavior

As reported by https://github.com/orgs/WalletConnect/discussions/3719, I also encountered this problem when using `"@rainbow-me/rainbowkit": "^2.0.0"`, When users encounter the `Error: No internet connection detected. Please restart your network and try again.` problem, they will be prevented from using MetaMask (chrome plug-in) to log in to the system. This is a p0 problem for our production. Is there anything good about it solution?

![img_v3_028h_dfef4315-5022-4188-8d78-ca65581504hu](https://github.com/rainbow-me/rainbowkit/assets/50100681/1973d675-cf4a-4272-a7a5-694372b5e106)

**Comment by KosmosKey** [comment]
@jiangmaniu Thanks for raising this issue. Give me some time to investigate this 🙏

**Comment by KosmosKey** [comment]
@jiangmaniu Are you still seeing the issue ?

**Comment by KosmosKey** [comment]
Seems to be backup now. This seems to be something out of our control since we use WalletConnect to get QR code and initialise a session. Hopefully works now, let me know if you face with any other problem.
