### ISSUE TITLE
[bug] <can't show the connect button in the iphone7>

### ISSUE THREAD

**Issue by samaritanz** [rainbow-me/rainbowkit#1816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^2.0.1

### wagmi Version

^2.5.5

### Current Behavior

i can see the connect button in my computer,but i can't see the button in my iphone7 , i dont know why,please help me
![IMG_9113](https://github.com/rainbow-me/rainbowkit/assets/62387737/0ab4fa78-a4e8-4f2e-9142-c1ca8da9b0e9)
![IMG_9113](https://github.com/rainbow-me/rainbowkit/assets/62387737/f158b50f-5aee-427b-ba31-0faf563c708c)

### Expected Behavior

the page can show the connect button in my iphone7 mobile

### Steps To Reproduce

see this page in ihpone7 https://rainbow-wagmi.pages.dev/

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://rainbow-wagmi.pages.dev/

### Anything else?

i use tokenpocket and my iphone7 ios version 13.4.1 and the tokenpocket version 1.5.4

**Comment by samaritanz** [comment]
![IMG_5458](https://github.com/rainbow-me/rainbowkit/assets/62387737/11162d9c-7b73-4062-b305-c96a8192e27b)
i can see the button in my iphone15 or my computer

**Comment by KosmosKey** [comment]
@samaritanz I can't reproduce this on my end.

Screenshot:

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/88ba6c0e-19d4-4716-aa2c-9c594af9cc47)


What browser are you using ?

**Comment by samaritanz** [comment]
iPhone7 iOS 13.4.1 ，your version is 15.0.what the software is you use

**Comment by KosmosKey** [comment]
@samaritanz I use xcode with simulator. What browser are you using ? Is it safari ?

**Comment by KosmosKey** [comment]
@samaritanz Just found out that iPhone 7 especially the iOS 13.4.1 version is outdated and has a lot of issues on a lot of dApps. This is something that's out of our control and the best thing i would suggest is using either better device or switching to desktop devices like laptop or a pc.

**Comment by samaritanz** [comment]
Yes,it’s safari.i can see the button in my iPhone 15 iOS 17.2,because I can connect in some Dapp and the rainbow kit version is low,if I  upgrade the version to latest,then I can’t connect in many Dapp .I don’t know why
