### ISSUE TITLE
[bug] RK 2.x doesn't work with Next.js 13 or below

### ISSUE THREAD

**Issue by morleyzhi** [rainbow-me/rainbowkit#1818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

On Next.js 13, I got this error after migrating to RK 2.x, despite following the instructions:

> No QueryClient set, use QueryClientProvider to set one

The reason this happens is because Next.js loads the cjs version of QueryClientProvider, but the Rainbowkit module loads the new ESM version.

I was able to fix the issue by upgrading to Next.js 14. I'm guessing it improves support for ESM modules.

I don't think this needs to be fixed, but it might be worth pointing out in the Migration Guide that Next.js must be upgraded to 14.

**Comment by KosmosKey** [comment]
@morleyzhi I'm not able to reproduce this issue. Are you able to share your `next.config.js` configuration ? If you can share a small reproducible example that'd be great otherwise i wouldn't be able to see what the real issue is without a reproducible example
