### ISSUE TITLE
[bug] Unable to get default wallets in V2

### ISSUE THREAD

**Issue by misterjame** [rainbow-me/rainbowkit#1827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.0.0

### Current Behavior

I want to include Talisman but also include the default wallets that would be listed under the "Popular" section. There is no way in the documentation to get the default list of wallets. If I want to add a wallet I have to manually configure all wallets and the order they appear in. This is listed as a "feature" in the Migration Guide.

### Expected Behavior

Should be able to get Rainbow Kit's default "Popular" section of wallets and add another section, etc

There should be a functionality like this:
`const wagmiConfig = getDefaultConfig({
  appName: "",
  projectId: "",
  chains: [mainnet],
  wallets: [{groupName: "Partners", wallets: [talismanWallet]}, {groupName: "Popular", wallets: getDefaultWallets()}],
})`

### Steps To Reproduce

`const wagmiConfig = getDefaultConfig({
  appName: "",
  projectId: "",
  chains: [mainnet],
  wallets: [{groupName: "Partners", wallets: [talismanWallet]}],
})`
will only get talisman and installed wallets :(

**Comment by KosmosKey** [comment]
Closing this issue. Please feel free to raise another issue if you're still facing with another problem 🙏
