### ISSUE TITLE
[bug] Multiple wallet connection sessions

### ISSUE THREAD

**Issue by agsola** [rainbow-me/rainbowkit#1833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

After watching this tweet: https://twitter.com/rainbowdotme/status/1757886864823066669
I was quite excited about the new feature of "Multiple wallet connection sessions" and the "Sign-In with Ethereum (SIWE) support with multiple wallet connections".

However, after upgrading to the latest version some users are complaining about this when using SIWE.

After connecting and signing with SIWE one account (account X) from wallet A (let's say Metamask), if I switch to account Y from wallet A the auth session is gone. The useAccount() hook returns both addresses, but only the first one (latest used) is the one used for SIWE. Therefore, everytime I switch accounts for anything (like checking balance), I get kick out from the dApp.

But not only that, if I use wallet B (e.g. Rabby), despite being connected to Metamask (wallet A), doing something on Rabby like changing the current connected wallet break everything again. Now, useAccount() returns just the connected Rabby wallet and none from Metamask, and it disconnect the current session.

I don't find a way to "Sign-In with Ethereum (SIWE) support with multiple wallet connections". Just the latest one, which breaks easily.

But there is more. It disconnect, and the "Connect Wallet" button is shown again.

When clicking on the button, it just ask to sign. But I can't choose the wallet. Then, if I was first connected to Metamask, and then used Rabby, I can't go back to Metamask. I have to click on "Connect Wallet" and Cancel the "Sign message" TWICE, and the third time it finally allows me to choose the wallet again.

### Expected Behavior

It would be ideal to keep the session even if a change in the current wallet is done, and swaping back to that wallet would keep the session open, as was done on previous versions.

Also, interacting with a different wallet should still let the user keep using the connected wallet.

**Comment by KosmosKey** [comment]
@agsola Thanks for raising this issue. 

Everything you were experiencing is exactly what is needed to have the correct authentication system. We didn't only implement account on change event to log you out and disconnect, but also for wallets e.g when switching from Rabby to MetaMask. Of course it has some pros and cons, but this is what comes from wagmi. Wagmi supports multiple wallet connections and you unfortunately you have to disconnect the one or the other to get the correct wallet and sign in again.

If we didn't add that support then the user could switch to another wallet and get wrong data with next-auth or iron session, so we tried to make sure everything works as expected which means you ahve to get logged out first then connect with a wallet again. This just adds another layer protection for the RainbowKit authentication provider.

We always recommend using our authentication provider to have the correct auth mechanism, but if you want to deprecate our provider to your own logic then you could do that too, but ofc takes time to create custom modal, components, verifications and etc...

**Comment by KosmosKey** [comment]
@agsola Also one quick follow up. You can get the current connected wallet address by using `address` value in `useAccount` hook in wagmi [here](https://wagmi.sh/react/api/hooks/useAccount#address)

**Comment by KosmosKey** [comment]
@agsola I see what you mean, but RainbowKit authentication provider only looks for one address and one connector at a time. 

We don't want to keep the session if addresses or connectors changes. Let's say you're connected to address A and we're making a fetch call to get info about adddress A and then emmediately switch to address B. 

In this case we need to log you out otherwise if we keep session on while we have a "changed" behaviour in many use cases users would have to check if the previous address or previous wallet is not the same as the current one and then log them out immedately, this would be not a great user experience.

It's the same as saying keep the session previous session if you're logged via another email.

**Comment by magiziz** [comment]
@agsola Yeah i was thinking more of how other socials work like facebook, instagram and etc. Gmail has their own security logic to switch account and get current sessions from those accounts. I think for now the current approach we did works fine for now and ofc you can always create your own custom authentication with siwe if you have your own approach.

Going to close this issue for now, but feel free to raise another issue if you're facing with other bugs 🙏
