### ISSUE TITLE
[bug] wallet is disconnected when Wagmi config changes

### ISSUE THREAD

**Issue by AlexBHarley** [rainbow-me/rainbowkit#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

When the config provided to `WagmiProvider` changes, my connected wallet is disconnected.

### Expected Behavior

The wallet should remain connected.

### Steps To Reproduce

Take a look at the CodeSandbox and you'll see the issue, when the chain is green you can consider that the "active" chain.

1. If I connect my wallet, the wallet disconnects when I change the "active" chain
2. When I choose Optimism (or Base) as the "active" chain, when I click "Connect" I expect MetaMask to connect and prompt a switch to Optimism (or Base)

This used to work with Rainbowkit V1.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

[CodeSandbox](https://codesandbox.io/p/devbox/inspiring-breeze-xgf285?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltjn8ukv00063b6w55w879lq%2522%252C%2522sizes%2522%253A%255B65.65868263473054%252C34.34131736526946%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltjn8ukv00023b6w1sgywjo9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltjn8ukv00033b6wuvgnl4j3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltjn8ukv00053b6wswm52ody%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltjn8ukv00023b6w1sgywjo9%2522%253A%257B%2522id%2522%253A%2522cltjn8ukv00023b6w1sgywjo9%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltjn8ukv00053b6wswm52ody%2522%253A%257B%2522id%2522%253A%2522cltjn8ukv00053b6wswm52ody%2522%252C%2522activeTabId%2522%253A%2522cltjn9to200cj3b6w8444prhv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cltjn9to200cj3b6w8444prhv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltjn8ukv00033b6wuvgnl4j3%2522%253A%257B%2522id%2522%253A%2522cltjn8ukv00033b6wuvgnl4j3%2522%252C%2522activeTabId%2522%253A%2522cltjn9a4a004i3b6wmuxez7xr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltjn9a4a004i3b6wmuxez7xr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltjn9ac4000ndfemga4ick29%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltjn9qrf009x3b6wtwwt3p4o%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Anything else?

For context, the actual app in question here is [Rollbridge](https://app.rollbridge.app).

You can see that we have a list of rollup bridges, and when a user navigates to a chain then connects their wallet (ie Rollux), we want them to be prompted to switch to the base chain for that rollup (ie Syscoin not Ethereum). 

If we could instead in the ConnectButton component specify which chain we want to switch to, this could also be a nice workaround.

**Comment by magiziz** [comment]
@AlexBHarley This is happening because everytime the active state changes the config reference becomes a fresh new one during re-render. When there is a new config reference wagmi has to reset all states again with the new config.

What i would suggest doing is not sorting or creating a new reference on each re-render with getDefaultConfig, but rather having it outside of the component with all chains included and then doing your own sorting logic in the component.

Here is an example:

```
import "./styles.css";

import {
  ConnectButton,
  getDefaultConfig,
  RainbowKitProvider,
} from "@rainbow-me/rainbowkit";
import "@rainbow-me/rainbowkit/styles.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { WagmiProvider } from "wagmi";
import { base, mainnet, optimism } from "wagmi/chains";

const queryClient = new QueryClient();

const CHAINS = [mainnet, optimism, base];

const config = getDefaultConfig({
  appName: "My RainbowKit App",
  projectId: "YOUR_PROJECT_ID",
  chains: CHAINS,
});

const App = () => {
  const [active, setActive] = useState(mainnet.id);

  const config = useMemo(() => {
    const chains = [...CHAINS].sort((a) => (active === a.id ? -1 : 1));
    return getDefaultConfig({
      appName: "My RainbowKit App",
      projectId: "YOUR_PROJECT_ID",
      chains,
      ssr: true, // If your dApp uses server side rendering (SSR)
    });
  }, [active]);

  return (
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <RainbowKitProvider>
          <div className="App">
            <h1>Hello CodeSandbox</h1>
            <h2>Start editing to see some magic happen!</h2>

            // Do your sorting here
            {CHAINS.map((chain) => (
              <button
                onClick={() => setActive(chain.id)}
                style={{
                  background: chain.id === active ? "green" : undefined,
                }}
              >
                {chain.name}
              </button>
            ))}

            <ConnectButton />
          </div>
        </RainbowKitProvider>
      </QueryClientProvider>
    </WagmiProvider>
  );
};

export default App;
```

**Comment by AlexBHarley** [comment]
@magiziz appreciate the reply, how can we then accomplish point 2 then?

We only sort them because we want the “active” chain to be switched to when a user connects their wallet.

**Comment by magiziz** [comment]
@AlexBHarley Yeah you can pass `initialChain` prop to `<RainbowKitProvider />`. Here is an example in the docs: https://www.rainbowkit.com/docs/chains#customizing-the-initial-chain

Here is an example code:
```
<RainbowKitProvider initialChain={1}>

or

<RainbowKitProvider initialChain={mainnet}>
```

This should let you connect to a wallet and prompt to switch to the desired network 🙏

**Comment by AlexBHarley** [comment]
@magiziz ah, OK yes `initialChain` prop is exactly what we're looking for. I've got one more question you can maybe help with, related to this changing config object. 

In our app the `chains` are actually loaded dynamically from the backend. A few examples of this in action,

- superbridge.app - only Superchain mainnets
- testnets.superbridge.app-  only Superchain testnets
- app.rollbridge.app - _all_ supported mainnets 
 
Now because on the initial render we have no chains yet, that means whenever someone refreshes the page their wallet is disconnected. Any ideas? 

[Relevant code](https://github.com/superbridgeapp/superbridge-app/blob/main/apps/bridge/components/Providers.tsx#L37)

**Comment by magiziz** [comment]
@AlexBHarley I see. Yeah that's kind of a tricky scenario. How about whenever your chains loads from the backend you have a loading screen and then once it's ready you display all supported chains with Wagmi, but loading always needs to be true on the inital render then you call the backend. Does that make sense ?

**Comment by AlexBHarley** [comment]
Ah, ok yes I think that could work, thanks @magiziz.

Will noodle around with that approach
