### ISSUE TITLE
[bug] Multiple Injected Providers for same wallet

### ISSUE THREAD

**Issue by sbauch** [rainbow-me/rainbowkit#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

I'm working on doing some performance refactors in my NextJS app, moving from pages router to app router and rendering a lot more on the server.

When I click between routes in my app without my wallet connected, each navigation adds another duplicate row for injected wallet.

<img width="726" alt="Screenshot 2024-03-09 at 11 50 51 AM" src="https://github.com/rainbow-me/rainbowkit/assets/923033/13cb47a2-01c2-4b7c-addc-05d4473b491c">

Entirely possible this is on my end, I'm not very familiar with Next SSR. But it also happens with Rainbow extension (different chrome profile)

<img width="728" alt="Screenshot 2024-03-09 at 1 46 21 PM" src="https://github.com/rainbow-me/rainbowkit/assets/923033/2ed356f2-a326-46b7-beaa-97b0f113941e">

### Expected Behavior

The discovered wallets should be deduped. Although maybe it's an indication I'm doing something odd?

### Steps To Reproduce

My `getDefaultConfig` uses `ssr: true`

I'm happy to try put together an reproducible example but if there's a simpler explanation here that would be ideal! lmk, i can fork the rainbowkit example and switch it over to app router and see what's what

**Comment by magiziz** [comment]
@sbauch Thanks for raising this issue. This is a bug that comes from the `wagmi` package when rendering in server-side. I've raised a PR in their repo here: https://github.com/wevm/wagmi/pull/3683.

For now can you try to not render a lot on the server and try to use RainbowKit and Wagmi only in client side ?

Check out some of our examples using next-js (SSR) and RainbowKit: 
- https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-app-i18n
- https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-app
- https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next

I know this is a bit crucial, but please bear with us 🙏

**Comment by sbauch** [comment]
thanks for the quick reply!! i love `Set()` lol often forget about it. but awesome ok, glad I didn't do the whole repro.

I _do_ think I'm only rendering wagmi and RainbowKit on the client? I've got an `EthereumProviders` component that's got the `"use client";` directive, but admittedly am still wrapping my head around it all. Feels very similar to the second example above. I don't have a `wallets` key in my config seems like the only difference.

```tsx
"use client";

export const config = getDefaultConfig({
appName: "Speedtracer",
  projectId: "my id",
  chains: [base],
  ssr: true,
  transports: { 
   // ...
  
  },
});

// ...

export const EthereumProviders = ({ children }: Props) => (
  <WagmiProvider config={config}>
    <QueryClientProvider client={queryClient}>
      <RainbowKitProvider>{children}</RainbowKitProvider>
    </QueryClientProvider>
  </WagmiProvider>
);
```

but no worries, i still have a few more things to switch over before i can deploy this anyhow. ill keep an eye on the wagmi PR if you wanna close this

**Comment by magiziz** [comment]
@sbauch Gotcha. Where do you wrap your <EthereumProviders /> ?

**Comment by sbauch** [comment]
Not sure what you mean by wrap, but I import and render the component in what is essentially the root of my client components. so it should be at the top of the suspense boundary?

**Comment by magiziz** [comment]
@sbauch Yeah i meant more like [this](https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-app/app/layout.tsx#L9), but can you share a small portion of your code here so i can see what other approach you can take ?

**Comment by sbauch** [comment]
I push it a little further down. im under the impression that this would cause the page.tsx component to render client side, as it's parent `Providers` component include the `"use client"` directive?

so im still moving some things around with this all to try to address some hydration errors, but something like this:

```tsx
// layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("font-Bebas antialiased", bebasNeue.variable)}>
        {children}
      </body>
    </html>
  );
}

```

```tsx
// page.tsx
const PlayPage = async ({ params: { s } }: { params: { s: string } }) => {
 
  // a bunch of server-side contract calls with viem and redis caching

  return (
    <div
      className="w-[100vw] h=[100vh]"
      style={{ backgroundColor: theme.background }}
    >
      <PageComponent
        seed={BigInt(s)}
        updatedAtBlock={BigInt(updatedAtBlock)}
        currentId={BigInt(today)}
        d={d}
        theme={theme}
        ads={ads}
        leaders={leaders}
      />
    </div>
  );
};
```

```tsx
// PageComponent.tsx
"use client";

// ...

const PlayPage = (props: Props) => {
  return (
    <Providers>
      <div className="max-h-[100dvh] flex flex-col items-center overflow-hidden">
      // ...
      </div>
    </Providers>
    );
}
```

**Comment by magiziz** [comment]
@sbauch Gotcha. The best thing for now is to move your `<Providers>` in `layout.tsx` since that's where your provider will exist on top of your app instead of providing it in `page.tsx` + other pages. Are you able to do that ?

**Comment by sbauch** [comment]
I dont think thats right tbh. imo placing the providers component in the loop would make the page render client side. and i only have one page in this route tree, which i want to render server side, so my providers component is only added on this page

**Comment by magiziz** [comment]
> I dont think thats right tbh. imo placing the providers component in the layout would make the page render client side. and i only have one page in this route tree, which i want to render server side, so my providers component is only added on this page

Sounds good. Yeah if you don't want to wrap it to your whole app that's fine. We'll keep this issue open and ping you once it's resolved on `wagmi`'s side 🙏

**Comment by magiziz** [comment]
@sbauch Sorry for the delay here. Can you upgrade your `wagmi` version to the latest one and see if the issue still persists ?

**Comment by magiziz** [comment]
@sbauch Any updates ?

**Comment by magiziz** [comment]
Closing this issue since it's wagmi has fixed this issue 👍
