### ISSUE TITLE
Clicking on any of the wallets does nothing on mobile.

### ISSUE THREAD

**Issue by atachka** [rainbow-me/rainbowkit#1860]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

2.0.2

### wagmi Version

2.5.7

### Current Behavior

https://github.com/rainbow-me/rainbowkit/assets/56038697/e584029c-7770-4fd4-b071-1c08710f4297

When I click on any of the wallets it does nothing on my mobile, I checked on other devices as well and different browsers too, works fine on desktop

### Anything else?

When I open the rainbow modal clicking on any of the wallets does nothing on my mobile, I checked on other devices as well and different browsers too.

**Comment by magiziz** [comment]
@atachka Thanks for raising this issue.

May i ask you a few questions in order for me to reproduce this issue ? 
- What iPhone and iOS version do you have ?
- Do you have those wallets installed on your device ?

Can you also share a small reproducible example ? That'd be awesome 🙏

**Comment by magiziz** [comment]
@atachka I can't reproduce this on my end.

I've deployed a small RainbowKit example here with create-react-app: https://rainbowkit-create-react-app.vercel.app/

Here is the repository: https://github.com/magiziz/rainbowkit-create-react-app

Can you please share your code and i can take a look what's going wrong ?

**Comment by magiziz** [comment]
What version of `@rainbow-me/rainbowkit`, `wagmi` and `@tanstack/react-query` are you using ?

**Comment by atachka** [comment]
> @atachka What version of `@rainbow-me/rainbowkit`, `wagmi` and `@tanstack/react-query` are you using ?

    wagmi: ^2.5.7,  @rainbow-me/rainbowkit: ^2.0.2, @tanstack/react-query: ^5.27.5,

**Comment by atachka** [comment]
I also deployed this repo https://github.com/magiziz/rainbowkit-create-react-app  on vercel and everything works fine, but it still won't work on localhost

**Comment by atachka** [comment]
Could you confirm, if your repo is working as intended when you run it locally?

**Comment by magiziz** [comment]
@atachka It should work locally and in vercel. If you're on desktop and try to open the mobile version of the connect modal then try to click on one of the wallets you won't get redirected because it'll only work on mobile.

The code you've given me is not correctly setup. I can't see you use `<RainbowKitProvider>`, `<QueryClientProvider>` and `<WagmiProvider>`. Please can you follow our installation guide [here](https://www.rainbowkit.com/docs/installation) ?

**Comment by atachka** [comment]
> @atachka It should work locally and in vercel. If you're on desktop and try to open the mobile version of the connect modal then try to click on one of the wallets you won't get redirected because it'll only work on mobile.
> 
> The code you've given me is not correctly setup. I can't see you use `<RainbowKitProvider>`, `<QueryClientProvider>` and `<WagmiProvider>`. Please can you follow our installation guide [here](https://www.rainbowkit.com/docs/installation) ?

Sorry, the code didn't copy right  

const RainbowProvider: FC<{ children: ReactNode }> = ({ children }) => {
  const config = getDefaultConfig({
    appName: "My RainbowKit App",
    projectId: "YOUR_PROJECT_ID",
    chains: [mainnet, polygon, optimism, arbitrum, base, zora],
  });

  return (
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <RainbowKitProvider>{children}</RainbowKitProvider>
      </QueryClientProvider>
    </WagmiProvider>
  );
};
const App = () => {
  return (
    <UserActionProvider>
      <ThemeProvider theme={theme}>
        <SnackbarProvider
          style={{
            backgroundColor: "#0000",
            boxShadow: "none",
            padding: 0,
          }}
          anchorOrigin={{
            vertical: "top",
            horizontal: "right",
          }}
          maxSnack={3}
        >
          <RainbowProvider>
            <WalletProvider>
              <TransactionProvider>
                <DefaultTransactionUIWrapper>
                  <SupportedTokensProvider>
                    <SwapTabProvider>
                      <SwapDataProvider>
                        <HistoryProvider>
                          <BrowserRouter>
                            <LegalPopup />
                            <Navbar pages={pages} />
                            <ErrorBoundary FallbackComponent={ErrorFallback}>
                              <Routes>
                                <Route path="/" element={<LandingPage />} />
                                <Route
                                  path="/bridge"
                                  element={<SwapPage bridgeUI={true} />}
                                />
                                <Route
                                  path="/swap"
                                  element={<SwapPage bridgeUI={false} />}
                                />
                                <Route
                                  path="/leaderboard"
                                  element={<LeaderboardPage />}
                                />{" "}
                                <Route
                                  path="/points"
                                  element={<PointsPage />}
                                />
                                {/* <Route
                                      path="/staking"
                                      element={<StakingPage />}
                                    /> */}
                                {/* <Route
                                      path="/airdrop"
                                      element={
                                        <VestingPage
                                          contractName="Airdrop"
                                          vestingTitle="Airdrop"
                                          startDate="2024.02.17"
                                          endDate="2024.02.19"
                                        />
                                      }
                                    />
                                    <Route
                                      path="/private"
                                      element={
                                        <VestingPage
                                          contractName="PrivateVesting"
                                          vestingTitle="Private Vesting"
                                          startDate="2024.02.16"
                                          endDate="2024.02.17"
                                        />
                                      }
                                    /> */}
                              </Routes>
                            </ErrorBoundary>
                            <Footer />
                          </BrowserRouter>
                        </HistoryProvider>
                      </SwapDataProvider>
                    </SwapTabProvider>
                  </SupportedTokensProvider>
                </DefaultTransactionUIWrapper>
              </TransactionProvider>
            </WalletProvider>
          </RainbowProvider>
        </SnackbarProvider>
      </ThemeProvider>
    </UserActionProvider>
  );
};
This is how I have it.

**Comment by atachka** [comment]
![Screenshot 2024-03-19 at 17 54 18](https://github.com/rainbow-me/rainbowkit/assets/56038697/8159501e-e803-4a18-9a1b-789cff042692)
![Screenshot 2024-03-19 at 17 55 04](https://github.com/rainbow-me/rainbowkit/assets/56038697/2cad749a-2089-45d7-8882-eb164bb8e06f)
this is my code, but as i told you even your repo this one https://github.com/magiziz/rainbowkit-create-react-app doesn't work locally for me, on my phone or other phones clicking on wallets does nothing

**Comment by magiziz** [comment]
@atachka It doesn't work when you're testing through your phone on localhost ? Can you explain again what part doesn't work ?

**Comment by atachka** [comment]
> @atachka It doesn't work when you're testing through your phone on localhost ? Can you explain again what part doesn't work ?

Yes,
I run the app on localhost,
go on localhost with my phone,
click the connect wallet button,
click metamask and nothing happens.

**Comment by magiziz** [comment]
@atachka Are you running on localhost through your actual phone or through browser mobile tool ?

**Comment by atachka** [comment]
> @atachka Are you running on localhost through your actual phone or through browser mobile tool ?

My actual phone.

**Comment by magiziz** [comment]
@atachka I can't reproduce this on my end.

https://github.com/rainbow-me/rainbowkit/assets/53529533/12ba7ef9-3c51-4b95-877f-c2c763e9972d

Can you please try to remove all your providers and only use RainbowKit provider with wagmi and TanStack query and see if it works ?

**Comment by atachka** [comment]
> @atachka What iOS version and iPhone are you using ?

17.4, Iphone 13 Pro. I also checked the boilerplate project that is created with npm init @rainbow-me/rainbowkit@latest and that doesn't work as well.

**Comment by atachka** [comment]
I found out that the metamask app has browser inside it and my app works fine there, maybe it's something with safari and google chrome. 

https://github.com/rainbow-me/rainbowkit/assets/56038697/843c4946-a84d-458e-9b1a-e817b4aef729

**Comment by magiziz** [comment]
@atachka Just checked on my actual phone as well and works perfectly fine. Can you install a simluator and watch for any console error logs and see what's going on there ?

Do you think you might have any apps or settings that disables you from being redirected from localhost to the app ? We use deep link approach so can you have a look deeper and see what's really going on ?

**Comment by magiziz** [comment]
Also clearing your browser cache might help too

**Comment by atachka** [comment]
![Screenshot 2024-03-20 at 12 03 44](https://github.com/rainbow-me/rainbowkit/assets/56038697/bb93bbed-9ad2-48c5-aad2-d89ac0568990)
I get these errors.

**Comment by magiziz** [comment]
@atachka Ok this seems to be a WalletConnect issue then. Do you have your own project id which you can test with ?

**Comment by atachka** [comment]
> @atachka Ok this seems to be a WalletConnect issue then. Do you have your own project id which you can test with ?

It worked, thanks !
