### ISSUE TITLE
[bug] invalid ENS name crashes application

### ISSUE THREAD

**Issue by TateB** [rainbow-me/rainbowkit#1865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

connecting to an app with an invalid ENS name will crash an entire app

### Expected Behavior

connecting should just not display the invalid name

### Steps To Reproduce

1. visit any rk app (e.g. rainbowkit.com)
2. connect via an account with an invalid name (`0x2031734704dcc0c56f5588dc737851154b44651b` has one)
3. app will crash entirely

**Comment by magiziz** [comment]
@TateB Thanks for raising this issue. I can reproduce this on my end. 

It seems like it has to do with how we're calling `normalize` in wagmi when fetching an ens avatar: https://wagmi.sh/react/api/hooks/useEnsAvatar#usage. They don't allow to have disallowed characters in an ens name which isn't mentioned anywhere in the docs, but we'll fix this on our end no worries 🙏
