### ISSUE TITLE
[bug] The injected body style affects our site's layout.

### ISSUE THREAD

**Issue by emily-nway** [rainbow-me/rainbowkit#1868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.2

### wagmi Version

2.5.7

### Current Behavior

When the connect modal pops up, the positions of some elements in our website are shifted because of the injected position style on the body element. (`position: relative !important;`)
<img width="409" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/93630497/766783aa-bcd1-4e68-bff5-c310bbd5c653">
Also, it would be great if the className property is added to the modal component.

### Expected Behavior

Should not modify the body element's styles as much as possible

### Steps To Reproduce

When the connect modal is opened, you can inspect the body element's style on the dev tool.
<img width="1309" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/93630497/e0d0c6e5-63bd-4a57-8a72-06988bc16d59">

**Comment by magiziz** [comment]
@emily-nway Duplicated issue https://github.com/rainbow-me/rainbowkit/issues/609. We use [react-remove-scroll](https://www.npmjs.com/package/react-remove-scroll) to avoid scrolling when modal is opened.
