### ISSUE TITLE
Error connecting wallet on Telegram Web App.

### ISSUE THREAD

**Issue by DmyKov** [rainbow-me/rainbowkit#1881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0

### wagmi Version

2.5

### Current Behavior

Telegram Mobile App - Android
Telegram Mobile App - iOS
Metamask Mobile App
Telegram Bot 

When i try to connect Metamask via Telegram bot on Android Telegram App i get error page ( see screenshot) net::ERR_UNKNOWN_URL_SCHEME
![Screenshot_2024-03-22-23-50-19-486_ir ilmili telegraph](https://github.com/rainbow-me/rainbowkit/assets/117279331/74345990-ac61-4e35-9bba-dc4e0de2070c)
Video - https://github.com/rainbow-me/rainbowkit/assets/117279331/86eb76cf-b153-4aee-8030-b08b2129e604

On iOS after click on Metamask icon on RainbowKit modal just do not happening nothing. I done get error page but Wallet do not open. Just nothing hapens.

I found closed issue with the same problem
https://github.com/rainbow-me/rainbowkit/issues/1531 
And here https://github.com/nichitagutu/web3modal/commit/a05574f6ee4207d82e018f17e59004122dd7b288 some idea how to fix it. It seems that the problem is in the URL that WalletConnect useing to iniciate interaction with Metamask (or other wallet)
![Screenshot_2024-03-23-00-02-23-380-edit_ir ilmili telegraph](https://github.com/rainbow-me/rainbowkit/assets/117279331/ec82bd40-93c9-4a4b-a6fb-65978744b80a)

Also i tried to open your home page just clicking on the URL in any Telegram chat. URL opens  with the browser implemented in Telegram and it work good. The problem is only in TWA Apps (Telegram Web Apps)

### Expected Behavior
Success wallet connection

### Steps To Reproduce

1. Open Telegram bot with Telegram mobile App
https://t.me/dk_test_bot_bot
2. Click on "Start" button to activate the bot
3. Click on "Test" button (bottom left) to run Telegram web app
4. Try to connect Metamask on RainbowKit home page

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://t.me/dk_test_bot_bot

**Comment by DmyKov** [comment]
Hello
any update? Did you reproduce the error?

**Comment by LeMinhTuAnh** [comment]
i use telegram bot can not open (metamask, trust wallet, coinbase wallet) always failure in telegram bot for android and ios. Can you help me?

**Comment by magiziz** [comment]
@DmyKov This seems to be an error with how deep linking works in telegram web app. Usually you would want to do this within a browser on your phone like safari, chrome or firefox and then get redirected to the app right after, but this is not the case with telegram web app.

Telegram uses embedded iframe which tries to redirect you to the app itself, but crashes and this is something that's out of our control. We've got a pretty similar issue here as well: https://github.com/rainbow-me/rainbowkit/issues/1531

What i would suggest doing is creating a web app where you can redirect users to and try to do your internal logic there instead of using telegram web app. Please feel free to raise another issue if you're facing with any other bugs 🙏

**Comment by meri-maki** [comment]
any news?

**Comment by zkgggggame** [comment]
Any news?...

**Comment by magiziz** [comment]
@meri-maki @zkgggggame Currently RainbowKit doesn't work with Telegram Web App. Please refer to the comment here https://github.com/rainbow-me/rainbowkit/issues/1881#issuecomment-2018198355

**Comment by skhetcho** [comment]
I submitted a PR for a similar issue on ConnectKit, @magiziz could this possibly be adopted into RainbowKit as well?
All it does is that if it is on android, open in _blank target which forces the TWA to open it outside the iframe

**Comment by skhetcho** [comment]
@meri-maki @magiziz 
I updated my connectkit fork, now it work seamlessly with metamask on all devices for Telegram Mini apps ([the fork release](https://github.com/skhetcho/connectkit-fork/releases/tag/v1.0.0))

As long as I have the deeplink uris (such as metamask://) there's a isAndroid conditional in my code that would automatically handle the wc uri with the deep link of the target wallet

**Comment by pouriya73** [comment]
@magiziz  How does the Tonkeeper wallet work?
The main wrapper infrastructure is placed on the mini app program for Telegram, but it seems this feature has been disabled on the Wagmi and Rainbow Kit infrastructures. 
Could you please explain why these two similar mechanisms wouldn't work?

**Comment by tx-tomcat** [comment]
> @meri-maki @magiziz I updated my connectkit fork, now it work seamlessly with metamask on all devices for Telegram Mini apps ([the fork release](https://github.com/skhetcho/connectkit-fork/releases/tag/v1.0.0))
> 
> As long as I have the deeplink uris (such as metamask://) there's a isAndroid conditional in my code that would automatically handle the wc uri with the deep link of the target wallet

It working on iOS. on Android, metamask stuck at connecting state

**Comment by pouriya73** [comment]
You can also use this piece of code to open an external link from within Telegram, which opens the phone browser 
@skhetcho @LeMinhTuAnh @tx-tomcat @magiziz 
```html
<a href="intent://YOUR-LINK#Intent;scheme=https;action=android.intent.action.VIEW;end;');">Open link in external browser</a>
```

**Comment by harissatti** [comment]
does any one find soution ?mine also not working

**Comment by pouriya73** [comment]
> does any one find soution ?mine also not working

@harissatti , Telegram has released the 2nd version of the mini-app and this problem has been solved. I suggest you read its documents and migrate to the new version 

https://docs.telegram-mini-apps.com/packages/telegram-apps-mate

https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/2-x/utils/privacy

**Comment by emilJS777** [comment]
I have the same problem, it seems you need to use those wallets that are coordinated with telegram
