### ISSUE TITLE
[bug] Custom Wallet List not working as per documentation

### ISSUE THREAD

**Issue by davedavinci** [rainbow-me/rainbowkit#1885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.3

### wagmi Version

1.4.13

### Current Behavior

Following this guide: https://www.rainbowkit.com/docs/custom-wallet-list

The function connectorsForWallets() won't accept second param object (appName and ProjectId)

![2024-03-25 094917](https://github.com/rainbow-me/rainbowkit/assets/163287064/10be19ce-07b9-4694-b36d-bc6a6488a4b1)

_______

![2024-03-25 094947](https://github.com/rainbow-me/rainbowkit/assets/163287064/7fb99d35-4550-4371-9e9e-ee89d4a91a85)

_______

![Immagine 2024-03-25 095014](https://github.com/rainbow-me/rainbowkit/assets/163287064/4f364dcb-90f4-4296-8a33-e71f33873f1a)

### Expected Behavior

I'd like to add a custom wallet list

**Comment by davedavinci** [comment]
Hi @magiziz.
I'm not sure I want to do that after having built the whole dApp on a different set of dependencies.
Any workaround to customize wallet list on RK 1 ?

Thanks

**Comment by magiziz** [comment]
@davedavinci Got it. If you don't want to use version 2, then please refer to this documentation here: https://v1.rainbowkit.com/docs/custom-wallets

That's specifically designed for users who use Wagmi and RainbowKit version 1

**Comment by davedavinci** [comment]
> @davedavinci Got it. If you don't want to use version 2, then please refer to this documentation here: https://v1.rainbowkit.com/docs/introduction
> 
> That's specifically designed for users who use Wagmi and RainbowKit version 1

Thanks buddy, worked like a charm!
