### ISSUE TITLE
[bug] [Android and IOS] When I create a Telegram bot to open a webview, which opens a website (using Rainbowkit and Wagmi) to connect to a blockchain wallet, I encounter an issue.

### ISSUE THREAD

**Issue by LeMinhTuAnh** [rainbow-me/rainbowkit#1889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.2

### wagmi Version

2.5.7

### Current Behavior

- link open telegram bot:   https://t.me/halving_btc_1_bot/app
 
https://github.com/rainbow-me/rainbowkit/assets/39867010/759b8240-43c4-4a5e-94a3-e4349736ac8d

- Because we need to use a Telegram bot to develop a game in telegram (instead of redirecting to a browser)

### Expected Behavior

- I Hope you can view and fix this

**Comment by magiziz** [comment]
Duplicated [issue](https://github.com/rainbow-me/rainbowkit/issues/1889)
