### ISSUE TITLE
[bug] connect modal not showing custom wallet button

### ISSUE THREAD

**Issue by technophile-04** [rainbow-me/rainbowkit#1903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^2.0.4

### wagmi Version

^2.5.11

### Current Behavior

The custom wallet button is not rendered inside connect modal when having custom connector + custom wallet.

### Expected Behavior

Similar to rainbowkit v1 it should render custom wallet button in connect modal. 

### Steps To Reproduce

For easy debuggin and MRR, I have just forked this rainbowkit repo and added our custom connector to `packages/examples` dir. It has very minimal changes, checkout the file changes here => https://github.com/technophile-04/rainbowkit/pull/1/files  

#### Steps to setup : 
1. Clone the repo + switch to branch : 

```
git clone -b burner-mrr https://github.com/technophile-04/rainbowkit.git
```

2. Cd in dir and pnpm install : 

```
cd rainbowkit && pnpm install
```

3. Run the dev server : 

```
pnpm run dev
```

4. Visit https://lochost:3000

#### Steps to reproduce : 

1. Make sure you disconnect from metamask / any other wallet 
2. Refresh the page and should be automatically connected to randomly generate account (burner account) 
3. Disconnect and notice that burner wallet button is not rendered in connect modal 

<details>
<summary> 
Example Video : 
</summary> 

https://github.com/rainbow-me/rainbowkit/assets/80153681/51578685-7994-47cf-9aca-ad20c8dd32a5

</details>

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/technophile-04/rainbowkit/pull/1/files

### Context : 

We have been trying to migrate from wagmi v1 => v2 in https://github.com/scaffold-eth/scaffold-eth-2/pull/700, everything works fine with burner wallet being connected and making transactions also no TS errors. 

But when you disconnect and try to connect, the burner wallet button does not show up in connect modal 

| [Wagmi, Rainbow V1](https://github.com/scaffold-eth/scaffold-eth-2) |  [Wagmi, Rainbow V2](https://github.com/scaffold-eth/scaffold-eth-2/tree/wagmi-v2) | 
| -------------------- | -------------------- | 
| ![Screenshot 2024-04-01 at 2 57 55 PM](https://github.com/rainbow-me/rainbowkit/assets/80153681/48036b6c-09ba-44de-83a2-0b41963b2628) | ![Screenshot 2024-04-01 at 3 14 08 PM](https://github.com/rainbow-me/rainbowkit/assets/80153681/55d224b8-abe3-4390-95a7-ee7edc8d1524) |

**Comment by magiziz** [comment]
@technophile-04 Creating wallets in v2 is kind of complicated, but if you look at this `coinbaseWallet` example we have [here](https://github.com/technophile-04/rainbowkit/blob/main/packages/rainbowkit/src/wallets/walletConnectors/coinbaseWallet/coinbaseWallet.ts#L101-L109). You can see that we have a parameters `walletDetails` which is spread operated later in the wallet itself. Can you try doing that approach and see if it works ?

We're looking to simplify wallet creation process, but for now can you go for that approach ?

**Comment by technophile-04** [comment]
> You can see that we have a parameter walletDetails which is spread operated later in the wallet itself. Can you try doing that approach and see if it works ?

Thanks @magiziz !! Just tried it out and works like a charm ! 

<details>
<summary> 
Demo image : 
</summary>  

![Screenshot 2024-04-01 at 11 48 19 PM](https://github.com/rainbow-me/rainbowkit/assets/80153681/06c3b34c-2a45-4c5f-9188-5c6a4a384cee)

</details>

> We're looking to simplify wallet creation process

Nice, Thanks !! 

Some small suggestions: 

- It would have been nice if we have somehow mentioned about spreading walletDetails in docs [here](https://www.rainbowkit.com/docs/custom-wallets#examples) 
- Maybe utilizing typescript to make sure that the developer's passed-in function returns required walletDetails properties 

^ lol not sure if the above things makes sense, since I don't have over context so please feel free to ignore it 

--- 

If anyone in future stumbled upon this or needs help with custom wallet you can find a naive example here : https://github.com/technophile-04/rainbowkit/pull/1/files

--- 

Thanks @magiziz again ! Please feel free to close this issue 🙌

**Comment by magiziz** [comment]
@technophile-04 Glad it worked out. Yeah we also have a PR opened [here](https://github.com/rainbow-me/rainbowkit/pull/1869) and we'll make sure to make it simpler for users to create wallets 🙏

**Comment by magiziz** [comment]
Closing this issue since for now since we're going to deprecate EIP-1193.
