### ISSUE TITLE
[bug] <title>when.  using okxWallet, i get this error

### ISSUE THREAD

**Issue by GalaxySciTech** [rainbow-me/rainbowkit#1905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.8

### wagmi Version

1.3.9

### Current Behavior

createConnector2 is not a function

**Comment by magiziz** [comment]
@GalaxySciTech Can you share a small reproducible example ?

**Comment by magiziz** [comment]
@GalaxySciTech Any updates ?
