### ISSUE TITLE
useChainId returns default chainId even if the current chain is not default.

### ISSUE THREAD

**Issue by berkaycirak** [rainbow-me/rainbowkit#1917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.1

### wagmi Version

2.5.7

### Current Behavior

I am using `useChainId`, and my config is 
```js
export const config = getDefaultConfig({
  appName: 'Heroes NFT',
  projectId: projectId,
  chains: [avalanche, herotestnet],
  ssr: true,
});
```
on the client, when I refresh the page on the herotestnet chain, it returns me two chainIds ( one for avalanche and the other is herotestnet) 

```js
const chainId = useChainId()
console.log(chainId) // I see two different value when I refresh the page on the herotestnet
```

### Expected Behavior

I expected to get only one chainId even if the current chain is different from default chain

**Comment by magiziz** [comment]
@berkaycirak Can you use chain id from `useAccount` hook ?

**Comment by DanielSinclair** [comment]
@berkaycirak This looks to be a Wagmi issue directly. Can you also open an issue on their repo?

**Comment by berkaycirak** [comment]
I did @DanielSinclair

**Comment by DanielSinclair** [comment]
Got it, I see it here: #3799 

Please add additional details to that Issue about: your browser, the wallet you're using, if you have multiple wallets installed and active in your browser, and your project configuration.

The state of these hooks are at a lower level than RainbowKit, so we'll need to investigate further over there.
