### ISSUE TITLE
[bug] fail to detect an installed wallet

### ISSUE THREAD

**Issue by KarmanMax** [rainbow-me/rainbowkit#1919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.18

### wagmi Version

0.12.19

### Current Behavior

the rainbow connector sometimes cannot detect an installed wallet.
an installed wallet(especially for rabby wallet extension) cannot be detected, when its adapter don't complete loading before the initialization of rainbow connector.

### Expected Behavior

the rainbow connector can responsively detect an wallet installed or not.

**Comment by magiziz** [comment]
@KarmanMax The "Installed" wallet feature is only available in the `2.x` versions. You're using `0.12.18` atm ?

**Comment by KarmanMax** [comment]
> @KarmanMax The "Installed" wallet feature is only available in the `2.x` versions. You're using `0.12.18` atm ?

yes. and will not migrate to 1.x/2.x in the short term.

**Comment by magiziz** [comment]
@KarmanMax The auto wallet detection feature is only available in 2.x version and not 1.x

**Comment by magiziz** [comment]
@KarmanMax Were you able to resolve your issue ?

**Comment by KarmanMax** [comment]
@magiziz no. it's too troublesome for our project to migrate to 2.x. it there any posibility to implement the feature in 0.x?

**Comment by magiziz** [comment]
@KarmanMax This won't be possible in 0.x and in 1.x. This is because this feature is only available in wagmi v2 which comes with RainbowKit version 2.x

Please feel free to raise another issue if you find any other bugs. Otherwise i would suggest migrating over to wagmi v2 with RainbowKit 2.x since it has a lot of cool new features 🙏
