### ISSUE TITLE
[bug] Rainbow wallet does not sign a message in Android and iOS.

### ISSUE THREAD

**Issue by bilgin-kocak** [rainbow-me/rainbowkit#1942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.5

### wagmi Version

2.5.19

### Current Behavior

When I sign message with Rainbow Wallet in desktop, it works. But when I try to sign message with android and iOS devices, it does not give any signature and does not return the app.

### Expected Behavior

Message can be signed as in mobile phone like in desktop rainbow wallet.

### Steps To Reproduce

You can open below link in your mobile phone. You can click all blue button in onboarding screens. At the end you will connect with rainbow wallet and you will sign a message. (This works in desktop but not in mobile phone)

https://digitaliga-development.web.app/

**Comment by magiziz** [comment]
@bilgin-kocak Can you share a minimal reproducible example ?
