### ISSUE TITLE
[bug] <Installed wallets are showing wallets that are not in the connectors array>

### ISSUE THREAD

**Issue by FranRom** [rainbow-me/rainbowkit#1952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.5

### wagmi Version

2.5.20

### Current Behavior

I'm passing an array of wallets I want to use in my app and the Connect button is showing installed wallets that are not in the array. (Desktop only)
I need to remove RainbowWallet because it's not working well with zkSync chain, but even if you don't add it you still get it as installed in the modal. 

<img width="368" alt="Screenshot 2024-04-29 at 12 20 10" src="https://github.com/rainbow-me/rainbowkit/assets/32134460/cff8a139-0c99-4d49-90e7-6bc98c0a990a">

This is my implementation: 
```const connectors = connectorsForWallets(
  [
    {
      groupName: 'Default',
      wallets: [
        metaMaskWallet,
        walletConnectWallet,
        trustWallet,
        okxWallet,
        zerionWallet,
      ]
    }
  ],
  {
    projectId: PROJECT_ID,
    appName: APP.name
  }
)
const config = createConfig({
  chains: [APP.network],
  transports: { [APP.network.id]: http() },
  connectors
})
```

### Expected Behavior

I don't want to pop up any wallet in the modal that is not in the connector array

### Steps To Reproduce

1. Pass a default array of wallets to the config except RainbowWallet
2. Get RainbowWallet installed in your browser
3. Open the connect modal and see if the wallet appears as installed although you didn't add it.

**Comment by magiziz** [comment]
You can disable it by setting `multiInjectedProviderDiscovery` to false in `createConfig`. [Here](https://wagmi.sh/core/api/createConfig#multiinjectedproviderdiscovery) is an example.

**Comment by FranRom** [comment]
Thanks! this worked like a charm
