### ISSUE TITLE
[bug] Connect wallet modal MM connect not doing anything

### ISSUE THREAD

**Issue by sergical** [rainbow-me/rainbowkit#1963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.7

### wagmi Version

^1.3.10

### Current Behavior

Clicking the MM button does not do anything

<img width="1681" alt="Screenshot 2024-05-07 at 2 23 12 PM" src="https://github.com/rainbow-me/rainbowkit/assets/3760543/16a7c80c-72e2-48bc-9e30-400d5dd6979f">

### Expected Behavior

Opens up MM extension connect dialog

### Steps To Reproduce

Rainbowkit settings
```
import { connectorsForWallets } from '@rainbow-me/rainbowkit';
import { injectedWallet, metaMaskWallet } from '@rainbow-me/rainbowkit/wallets';
import { configureChains, createConfig } from 'wagmi';
import {
  arbitrum,
  base,
  mainnet,
  optimism,
  polygon,
  sepolia,
} from 'wagmi/chains';
import { SafeConnector } from 'wagmi/connectors/safe';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';

import { env } from '@/env.mjs';

export const { chains, publicClient } = configureChains(
  [mainnet, arbitrum, optimism, polygon, sepolia, base],
  [
    alchemyProvider({ apiKey: env.NEXT_PUBLIC_ALCHEMY_ID || '' }),
    publicProvider(),
  ]
);

// const { connectors } = getDefaultWallets({
//   appName: 'Acctual',
//   projectId: env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID || '',
//   chains,
// });
const connectors = connectorsForWallets([
  {
    groupName: 'Recommended',
    wallets: [
      injectedWallet({ chains }),
      metaMaskWallet({
        projectId: env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID || '',
        chains,
      }),
    ],
  },
]);

export const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: [
    ...connectors(),
    new SafeConnector({
      chains,
      options: { allowedDomains: [/app.safe.global$/], debug: false },
    }),
  ],
  publicClient,
});

```

**Comment by sergical** [comment]
So my browser had a coinbase wallet extension + MM extension installed, removing the CB one seemed to have fixed it - but why would that matter if i am only configuring MM

**Comment by magiziz** [comment]
@sergical Thanks for raising this issue. This is a known issue with coinbase wallet + metamask. The reason this is happening is becaue coinbase wallet is overriding metamask and this is unfortunately something that's out our control since those wallets are responsible for these kind of behaviours.

Although we have a good news for you as well! If you upgrade your RainbowKit to version 2 you should see that this issue will no longer persist due to EIP-6963 support.

Let me know if this helps you 👍
