### ISSUE TITLE
[Fraud, False Adveriting] <Rainbow's Fraud and False Advertising>

### ISSUE THREAD

**Issue by DayOfShah** [rainbow-me/rainbowkit#1968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

current

### wagmi Version

current

### Current Behavior

Rainbow App Listed Tsuru on Base as a free mint with gas cost of 0.02 cents. However, this turned out to be false, as Rainbow actually charged 0.0012 ETH  without any permission or consent. Upon seeing the ad, you could click 'mint' and transaction would be initiated without any further verification. It was not until later that I realized Rainbow has actually charged 0.0012 ETH, a fee that was separate from gas, and obviously no 'free' as Rainbow advertised. 

It was a challenge to find a representative to communicate with at Rainbow, as Rainbow does not make this information clear on any public facing medium. When I notified about Rainbow here, I received a message informing me to contact the Ethereum Foundation. It seems highly unlikely that any Rainbow representative could actually be incompetent enought to believe that the Ethereum Foundation was responsible for Rainbow's fraud and false advertising. 

When I followed up on this matter, I was asked not to discuss here on github and communicate via email. However, via email no communication was provided, except for generic excuses such "we're looking into the matter". Rainbow then quietly closed the github discussion. 

It seems clear that Rainbow is deliberately deceiving and defrauding the public, through unauthorized charges that are small enough to go unnoticed by most victims, and then complicating communications for those victims who are able to identify Rainbow's fraud to the point of exhaustion. 

Our community is already full of scammers and illegitimate projects, who sully the reputation of the industry as a whole. It is important to expose Rainbow's deceptive advertising, and utterly illegitimate business practices. 

It is important that all fraudulent operations crumble. 

Furthermore, given the number of individuals likely to have been unknowingly deceived by Rainbow, its deceptive practices are likely grounds for a class action law suit. If you have utilized the Rainbow platform for any financial transaction, please review these transactions to determine if you have also been victimized. 

### Expected Behavior

Expected Behavior is not to deceive or defraud the public 

### Steps To Reproduce

Stop deceiving and defrauding the public.

**Comment by DayOfShah** [comment]
Rainbow App Listed Tsuru on Base as a free mint with gas cost of 0.02 cents. However, this turned out to be false, as Rainbow actually charged 0.0012 ETH  without any permission or consent. Upon seeing the ad, you could click 'mint' and transaction would be initiated without any further verification. It was not until later that I realized Rainbow has actually charged 0.0012 ETH, a fee that was separate from gas, and obviously no 'free' as Rainbow advertised. 

It was a challenge to find a representative to communicate with at Rainbow, as Rainbow does not make this information clear on any public facing medium. When I notified about Rainbow here, I received a message informing me to contact the Ethereum Foundation. It seems highly unlikely that any Rainbow representative could actually be incompetent enought to believe that the Ethereum Foundation was responsible for Rainbow's fraud and false advertising. 

When I followed up on this matter, I was asked not to discuss here on github and communicate via email. However, via email no communication was provided, except for generic excuses such "we're looking into the matter". Rainbow then quietly closed the github discussion. 

It seems clear that Rainbow is deliberately deceiving and defrauding the public, through unauthorized charges that are small enough to go unnoticed by most victims, and then complicating communications for those victims who are able to identify Rainbow's fraud to the point of exhaustion. 

Our community is already full of scammers and illegitimate projects, who sully the reputation of the industry as a whole. It is important to expose Rainbow's deceptive advertising, and utterly illegitimate business practices. 

It is important that all fraudulent operations crumble. 

Furthermore, given the number of individuals likely to have been unknowingly deceived by Rainbow, its deceptive practices are likely grounds for a class action law suit. If you have utilized the Rainbow platform for any financial transaction, please review these transactions to determine if you have also been victimized.

**Comment by magiziz** [comment]
@DayOfShah I know this is super frustrating, but please let's keep the conversation in this discussion https://github.com/rainbow-me/rainbowkit/discussions/1960. Like i said the team is looking at this issue and we'll contact you back as soon as possible. The issue is unknown at the moment and our team is investigating this. Thanks for your patience 🙏

**Comment by DayOfShah** [comment]
What is the reason Rainbow is attempting to conceal its response to to this
matter?

I’ve been more than patient with Rainbow. Rainbow has done absolutely
nothing for nearly three weeks, except ask that I not discuss this matter
publicly.  There is no reason for this matter to take this long to resolve.
Rainbow’s lack of ethics and honesty have already been demonstrated by
Rainbow’s ill advised attempt to inexplicably instruct me to contact the
Ethereum Foundation to recoup the funds owed to me by Rainbow. There is no
reason to believe that “the team is looking at this issue and we'll contact
you back as soon as possible”.

The longer Rainbow takes to resolve this matter, the more necessary it
becomes to bring this matter to the attention of the broader crypto
community, to identify if others have been similarly defrauded.

If the funds aren’t returned within 24 hours, Rainbow will be responsible
for providing redress for the time it has cost me to resolve this matter.
If Rainbow does not return my funds within 24 hours, and subsequently fails
to provide the owed funds along with the appropriate redress, then Rainbow
will be reported to the Consumer Financial Protection Bureau and the United
States Securities and Exchange Commission.

**Comment by DayOfShah** [comment]
Nothing has been completed. Why would you close this?

**Comment by magiziz** [comment]
@DayOfShah I know this is fustrating especially when you've already signed a transaction, but please bear with us since we're investigating the issue on our end.
