### ISSUE TITLE
[bug] Cannot connect to WalletConnect in Chrome with enabled device toolbar

### ISSUE THREAD

**Issue by pablohpsilva-forjnetwork** [rainbow-me/rainbowkit#1977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.1

### wagmi Version

1.4.12

### Current Behavior

Whenever trying to open WalletConnect on mobile, I get the following error on devtools, dev mode only:

```
Failed to launch 'wc:8951bdf7dbe7a843d437b918ebfd2645bf854907e9f59a3a4450d363f74453f5@2?relay-protocol=irn&symKey=9235d394357ff9a20283d5a016444be47543e0bb13c525eb6f12e31182af35d0' because the scheme does not have a registered handler.
```

I've already registered my app via https://cloud.walletconnect.com/ but I'm still getting this error.

### Expected Behavior

It should simply work, by prompting the walletconnect app installed in the user's phone or, at least, a QRCode.

### Steps To Reproduce

No response

### Anything else?

No response

**Comment by magiziz** [comment]
@pablohpsilva-forjnetwork Can you share a small reproducible example with us ? If you can give use github or codesandbox link that would be the best.

**Comment by magiziz** [comment]
Closing this issue. Please re-open this issue if you're still stuck.
