### ISSUE TITLE
[bug] Bybit wallet integration not working

### ISSUE THREAD

**Issue by hernan-clich** [rainbow-me/rainbowkit#1982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.6

### wagmi Version

2.8.1

### Current Behavior

Bybit wallet appears as one of the installed wallets but when attempting to connect it, and endless loading state appears that says the following:

> Opening Bybit Wallet...
> Confirm connection in the extension

However, the wallet never prompts user interaction.

### Expected Behavior

The wallet should prompt user confirmation to connect to the requesting dapp.

### Steps To Reproduce

I was able to reproduce in the live production site, `https://www.rainbowkit.com/`.

- Download Bybit Google Chrome extension (currently v2.4.25): https://chromewebstore.google.com/detail/bybit-wallet/pdliaogehgdbhbnmkklieghmmjkpigpa
- Click on Connect wallet
- Bybit will appear in the "Installed" section
- Click on Bybit
- The loading state starts and nothing else happens

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com

### Anything else?

I was able to reproduce in the live production site, `https://www.rainbowkit.com/`.

<img width="1512" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/62221379/d91bc055-38b4-4cef-941e-c1e5c3066e14">

**Comment by magiziz** [comment]
This seems to be an issue with Bybit extension not working properly. Those wallets are responsible for these kind of behaviors since we don't have control over what actions they do. In this case it's a bug and i would suggest reporting this to their support team.
