### ISSUE TITLE
[bug] Touchpad zoom and pan do not work on modals

### ISSUE THREAD

**Issue by hexcowboy** [rainbow-me/rainbowkit#1990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.0

### wagmi Version

N/A

### Current Behavior

Modals in RainbowKit do not allow zooming or panning when a modal is open.

### Expected Behavior

Modals should allow for zooming or panning using a touchscreen on touch devices or a touch trackpad.

### Steps To Reproduce

1. Open a modal on a touchscreen device or a device with a touchpad
2. Try zooming by pinching your fingers

**Comment by DanielSinclair** [comment]
@hexcowboy This was actually a design choice that felt appropriate on mobile. Is there a particular issue your seeing that requires pan and zoom, or a usability problem with this behavior?

**Comment by hexcowboy** [comment]
ah, i see. i think the main issue here is accessibility, and you can [read a bit more about what the WCAG says about this specific issue](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html)

i quite frequently zoom using my touchpad on my macbook to be able to read things on my screen

**Comment by magiziz** [comment]
@hexcowboy We're going to close this issue since this was a part of our design choice. Feel free to raise another issue if you find any other bugs. Otherwise thanks for raising the PR 👍
