### ISSUE TITLE
[bug] process.env breaks Vite-based projects in Dev

### ISSUE THREAD

**Issue by mirshko** [rainbow-me/rainbowkit#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.0

### wagmi Version

2.9.2

### Current Behavior

Importing RainbowKit in Vite after 2.1.0 causes the app to crash when running in local dev.

https://github.com/rainbow-me/rainbowkit/blob/2d4c86d87c3acf01d9f2a8d5e79cbe14d32a8ca7/packages/rainbowkit/src/core/network/enhancedProvider.ts#L7

This crashes Vite in local

### Expected Behavior

env variable call is performed rather with import.meta.env or process.env based on the corresponding environment.

### Steps To Reproduce

React + Vite site import rainbowkit and run in development.

**Comment by magiziz** [comment]
@mirshko Thanks for raising this issue. We're going to push a fix here in a bit 👍
