### ISSUE TITLE
Rainbow wallet and metamask QR codes don't display when pressing their tabs [bug]

### ISSUE THREAD

**Issue by stuckinaboot** [rainbow-me/rainbowkit#2009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.2

### wagmi Version

2.5.16

### Current Behavior

Try pressing "connect wallet" here and then selecting rainbow wallet. It doesn't display a QR code https://www.netprotocol.app/app/inscribed-drops/mint/base/0

I also tried on latest rainbow version and ran into the same issues https://github.com/stuckinaboot/Net/pull/39

### Expected Behavior

I expected RainbowKit to allow me to select Rainbow wallet so that I can connect my rainbow wallet to my dapp

**Comment by stuckinaboot** [comment]
<img width="728" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/1824753/85a4466a-1919-4623-a1cf-39b90c90d365">
Example: I select Rainbow and QR code doesn't display

Here is my providers file (all my code here is open-source): https://github.com/stuckinaboot/Net/blob/main/website/src/app/providers.tsx

**Comment by magiziz** [comment]
It seems like there is something wrong with your WalletConnect project id. Does this work in localhost ? Can you re-generate a new project id and try with that ?

I'm also pretty sure there is something in your settings in WalletConnect cloud you'd have to configure to make this work in a production environment.

<img width="1508" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/53529533/9184c7c6-bd65-40bb-a51a-e42f7d0734c5">

**Comment by magiziz** [comment]
Can you try setting https://www.netprotocol.app as an allowed domain ?

<img width="816" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/53529533/209d93fd-8454-42f9-aa06-dac82cc8429e">

**Comment by stuckinaboot** [comment]
Thank you, sorry for false alarm -- that fixed 
<img width="826" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/1824753/12e3224d-1a5a-4d6d-a049-3424df4742ba">

I'll let others who have this issue know as well
