### ISSUE TITLE
[bug] Invalid balance formatting shows balance in exponential format

### ISSUE THREAD

**Issue by brijeshagal** [rainbow-me/rainbowkit#2015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^2.0.0

### wagmi Version

^2.5.7

### Current Behavior

When the balance is quite small, the wallet shows balance in exponential format as seen in screenshot below:
<img width="858" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/87767138/372031de-43ae-4b7d-8963-21d792ec01b6">

### Expected Behavior

Balance should be shown in numeric form and not in scientific notation.

### Steps To Reproduce

Very low balance on Base chain caused this. If balance is around 0.0000009 (simply 7 decimals), scientific notation is seen. 

User Address: `0x1c512FaA65B2C9660bBe7c01f83Bc7bF175B700B`

**Comment by magiziz** [comment]
@brijeshagal The formatted balance comes from `useBalance` hook from wagmi. You can raise a PR to their repo if you consider this an issue.

Wagmi github repo link: https://github.com/wevm/wagmi
