### ISSUE TITLE
[bug] sending transaction not working for OKX wallet

### ISSUE THREAD

**Issue by melvinmcrn** [rainbow-me/rainbowkit#2016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.5, 2.1.1

### wagmi Version

2

### Current Behavior

When connecting to OKX wallet on a desktop (using chrome, brave), connecting the wallet works fine but when the user tries to send a transaction, it does not trigger OKX to sign a transaction.

It works fine for other wallets or other dApps that use other libraries though.

**Comment by magiziz** [comment]
@melvinmcrn I'm able to send a transaction with OKX wallet 

<img width="1218" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/53529533/b86b0c36-b032-41b7-b1dc-cba2f96e82fb">

We're using this test dApp to test https://rainbowkit-example.vercel.app

Can you share a small reproducible example with us ?

**Comment by magiziz** [comment]
@melvinmcrn You can find it here https://github.com/rainbow-me/rainbowkit/tree/main/packages/example. Let me know if this works 👍

**Comment by melvinmcrn** [comment]
@magiziz We haven't changed anything to our code but seems like it's working now. Maybe there was some problem with the OKX wallet itself.

Sorry for your time and thank you for your support! :)
