### ISSUE TITLE
openConnectModal opening unstyled modal ui

### ISSUE THREAD

**Issue by berkaycirak** [rainbow-me/rainbowkit#2027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.7

### wagmi Version

2.8.5

### Current Behavior

I am trying to making a custom button by using hooks providen via rainbow kit. However, when I use `useConnectModal` hook, modal ui behavior is different than default `ConnectButton` behavior. I don't know the reason. Does anyone have that issue before?
- Below image is useConnectModal hook result
![image](https://github.com/rainbow-me/rainbowkit/assets/81809211/e5946a7d-3cd9-4686-9e8b-8e193c9f2904)

### Expected Behavior

I was expecting a behavior like default ConnectButton moda 
![image](https://github.com/rainbow-me/rainbowkit/assets/81809211/07f593c8-6d58-453c-af32-0b9ac39ead90)

**Comment by magiziz** [comment]
@berkaycirak Did you add `import '@rainbow-me/rainbowkit/styles.css'` to your app ? Also can you share a small reproducible example ?

**Comment by berkaycirak** [comment]
Huh :) I assume it was already imported in rainbowProvider but I am wrong. Thanks for that, it works now
