### ISSUE TITLE
[bug] <title>The installed browser wallet plug-in cannot be detected

### ISSUE THREAD

**Issue by zhengyi-chang** [rainbow-me/rainbowkit#2046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.2

### wagmi Version

2.8.5

### Current Behavior

The installed browser wallet plug-in: halo wallet cannot be detected
I installed halo's wallet plugin in my Google browser and we rainbowkit didn't recognize the wallet I installed

### Expected Behavior

Hope to fix the halo wallet detection or official support halo wallet would be appreciated

**Comment by magiziz** [comment]
@zhengyi-chang It seems like Halo is not supporting EIP-6963. You should reach out to their team and ask if they can support EIP-6963 then it'll work in RainbowKit.
