### ISSUE TITLE
[bug] not working as expected when setting preference to "smartWalletOnly"

### ISSUE THREAD

**Issue by KarmanMax** [rainbow-me/rainbowkit#2053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.2

### wagmi Version

2.9.10

### Current Behavior

Case: the CoinbaseWallet extension enabled, and the coinbaseWallet's preference set to "smartWalletOnly", select Coinbase in the connect modal.

Behavior: it's not connecting to the Coinbase smart wallet as expected, it's connecting to the CoinbaseWallet extension instead.

### Expected Behavior

always connect to the Coinbase smart wallet when the coinbaseWallet's preference set to "smartWalletOnly", whatever CoinbaseWallet extension(or mobile app) is available.

**Comment by magiziz** [comment]
@KarmanMax Can you provide a small reproducible example ?

**Comment by KarmanMax** [comment]
> @KarmanMax Can you provide a small reproducible example ?
sure. here is a simple example:
https://github.com/KarmanMax/rainbow-test

**Comment by magiziz** [comment]
@KarmanMax I'm able to get the coinbase smart wallet window popup. Can you try in incognito mode ?

<img width="896" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/53529533/f8dd9c53-3c6f-4008-9b07-cc0e57751c8c">

If we detect that you have coinbase wallet browser extension we would rather use that than the smart wallet option.

**Comment by magiziz** [comment]
@KarmanMax Any luck ?

**Comment by KarmanMax** [comment]
> If we detect that you have coinbase wallet browser extension we would rather use that than the smart wallet option.

that's the issue here I want to talk about. As the preference named "smartWalletOnly", I thought it expects to always use the smart wallet whatever there is a coinbase wallet extension.

Actually what I want is something like what [stargate](https://stargate.finance/bridge) does, which provides coinbase extension and smart wallet separately and the smart wallet option always popup the smart wallet connect modal whatever there is a coinbase wallet extension.
And I want to implement this in rainbowkit, I tried adding a custom coinbaseWallet with preference set to "smartWalletOnly" but it doesn't behavior in that way. it will use coinbase wallet extension when the extension is available.

**Comment by magiziz** [comment]
@KarmanMax I see. You could create your own [coinbaseWallet](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/wallets/walletConnectors/coinbaseWallet/coinbaseWallet.ts), but remove the `rdns` field and set `preference` to "smartWalletOnly". Can you try doing that and let me know if it works ?

**Comment by KarmanMax** [comment]
it works! thanks a lot @magiziz

**Comment by Forsect** [comment]
Hey guys, I have a problem but on other direction - i want to set the `eoaOnly` preference to coinbaseWallet. It works great on mobile and incognito desktop browser - what I mean by that it does not suggest the smart wallet option and asks me to get app/extension instead. Great! But as soon as I have extension, on top of its popup there is a string with action:
`Using browser extension. Switch to smart wallet`

Same as the OP, I was hoping there won't be a way to use the smart wallet, but looks like there is. In my app flow it breaks, and I don't want that. Unfortunately, from what I see it's not like the extension has always "prio" and I am hoping user won't click it - sometimes the "smart wallet" has a prio and now it definitely will break. Can I do anything about that? Like block this option from showing up and make it truly "eoaOnly"?

**Comment by DanielSinclair** [comment]
@Forsect I wasn't able to reproduce that issue. It seems to work as expected for me, prioritizing the extension. Maybe try updating Wagmi/Viem to pull in the latest Coinbase peer dependency, and clearing cookies/cache for the Coinbase domains <img width="765" alt="Screenshot 2024-12-04 at 3 56 54 AM" src="https://github.com/user-attachments/assets/81a81e4f-1ff1-4180-95d0-099a3a679a9c">
