### ISSUE TITLE
[bug] Peer dependency issue: react-i18next@13.5.0 ... Found i18next@22.5.1

### ISSUE THREAD

**Issue by Spencer-Sch** [rainbow-me/rainbowkit#2054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.2

### wagmi Version

2.10.2

### Current Behavior

After executing `npm install @rainbow-me/rainbowkit wagmi viem@2.x @tanstack/react-query` to add RaindbowKit to existing Next.js project I get the following error:

![overriding-peer-deps](https://github.com/rainbow-me/rainbowkit/assets/78219375/f39c320c-51eb-41d5-9eb9-2193dc42c46c)

When running `npm run dev` I get the following error:

![module-not-found](https://github.com/rainbow-me/rainbowkit/assets/78219375/e537752c-24e9-451a-bc27-583da038058f)

The project builds and displays on localhost:3000. The RainbowKit ConnectWallet component renders and functions as expected.

### Expected Behavior

I expected for Next.js to build and run locally without any dependency issues.

### Steps To Reproduce

1. init project with `npx create-next-app@latest`
2. test local environtment by running `npm run dev`
3. navigate to `localhost:3000` in browser (I'm using Chrome)
4. stop local environment with `ctr+c` then `y` then `enter`
5. add RainbowKit with `npm install @rainbow-me/rainbowkit wagmi viem@2.x @tanstack/react-query`
6. Add Wagmi, QueryClient, and RainbowKit providers (with Wallet Connect project id) and rainbowKit `ConnectWallet` component to project as directed by the RainbowKit documentation. (https://www.rainbowkit.com/docs/installation#import)
7. run local environment with `npm run dev`
8. navigate to `localhost:3000` in browser (I'm using Chrome)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/Spencer-Sch/next-rainbowkit-issue-recreation

### Anything else?

Next.js with RainbowKit libs was all working properly last week. It was all working properly earlier today as well until I tried to add DaisyUI to the project. That's when I started seeing this peer dep conflict about i18. However, the issue has persisted even in brand new project installs without the addition of DaisyUI.

Package.json
![package-json](https://github.com/rainbow-me/rainbowkit/assets/78219375/60127b38-735e-4761-8c03-2a09506406d1)

**Comment by magiziz** [comment]
@Spencer-Sch These are just peer dependencies warnings that are coming from `@metamask/sdk` dependency which is used by `wagmi`. Those warnings shouldn't cause any errors in your app.

Regarding your `Can't resolve 'pino-pretty'...` error, this comes from the WalletConnect SDK which is also used by `wagmi`. You would need to configure your `next.config.js` like this https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-app/next.config.js

Let me know if this helps 👍

**Comment by Spencer-Sch** [comment]
Thank you for your reply, @magiziz!

I wish I had known the warnings could be safely ignored before I spent multiple hours trying to solve it 🤦‍♂️.

That's ok though, because your suggestion about `next.config.js` has made all the "Import trace" and "Module not found" messages disappear!

Thank you again!
