### ISSUE TITLE
[bug] Don't add too much extra content to HTML tags

### ISSUE THREAD

**Issue by Pszz** [rainbow-me/rainbowkit#2056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

"@rainbow-me/rainbowkit": "^2.1.2",

### wagmi Version

 "wagmi": "^2.9.8"

### Current Behavior

![image](https://github.com/rainbow-me/rainbowkit/assets/12093551/69988720-3df4-4fd5-88b8-6351e5219173)

This is not very beautiful.
You can use other methods, such as className
`:root { }`
`html {}`

### Expected Behavior

Ensure that the user's original code is not changed.

### Steps To Reproduce

RT

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

No

### Anything else?

No

**Comment by magiziz** [comment]
@Pszz These extra contents are coming from the WalletConnect modal. Feel free to raise an issue on their repo here https://github.com/walletconnect/walletconnect-monorepo.

**Comment by glitch-txs** [comment]
Hi @magiziz, this can be removed by using `showQrModal: false` in the WalletConnect configuration or lazy loading the initiation of the instance where you need this config as `true`.

**Comment by magiziz** [comment]
@glitch-txs Is it possible to lazy load `walletConnect` connector with Wagmi's [createConfig](https://wagmi.sh/core/api/connectors/walletConnect#walletconnect) ?

**Comment by glitch-txs** [comment]
I don't think it's possible, but I believe you only require the modal for a specific option right (image)?
![image](https://github.com/rainbow-me/rainbowkit/assets/66949816/c264ee7c-7572-49f8-87e8-d4329406995e)

In this case I think you can pass down the connector to the connect function directly? You could maybe lazy load it there?
https://wagmi.sh/react/api/hooks/useConnect#mutate

**Comment by magiziz** [comment]
@Pszz The best way to do this for now is to not include the `walletConnectWallet`. There isn't a way to lazy load connectors in wagmi so going to close this issue for now. Feel free to re open this issue if you see anything that's causing unexpected behaviours.
