### ISSUE TITLE
[bug] Conflict between phantom Wallet and core wallet

### ISSUE THREAD

**Issue by tronghoangvmo** [rainbow-me/rainbowkit#2071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.2

### wagmi Version

2.9.5

### Current Behavior

when install phantom wallet extension and core wallet extension, rainbow-kit can't detect phantom wallet

### Expected Behavior

 rainbow-kit can detect phantom wallet

### Steps To Reproduce

- install phantom wallet extension
- install core wallet extension

**Comment by tronghoangvmo** [comment]
![Screenshot 2024-07-01 at 3 07 51 PM](https://github.com/rainbow-me/rainbowkit/assets/172233806/67ecdf44-8906-4254-bce5-cbf9efaad4dc)
![Screenshot 2024-07-01 at 3 05 53 PM](https://github.com/rainbow-me/rainbowkit/assets/172233806/675e7be0-df91-4565-9ad9-6eda45dda3ca)

**Comment by magiziz** [comment]
@tronghoangvmo We're working on a fix. Apparently they didn't follow the right approach with EIP-6963 icon property.

**Comment by tronghoangvmo** [comment]
@magiziz pls build new version with this bug, we need golive our project with bold phantom wallet and core wallet
