### ISSUE TITLE
[bug] ChainNotConfiguredError: Chain not configured.

### ISSUE THREAD

**Issue by mits87** [rainbow-me/rainbowkit#2075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.3

### wagmi Version

2.10.9

### Current Behavior

Currently when I'm creating the RainbowKit configuration like this:

```tsx
"use client";

import { GetSiweMessageOptions, RainbowKitSiweNextAuthProvider } from "@rainbow-me/rainbowkit-siwe-next-auth";
import {
  RainbowKitProvider as BaseRainbowKitProvider,
  getDefaultWallets,
  getDefaultConfig,
} from "@rainbow-me/rainbowkit";
import { mainnet } from "wagmi/chains";
import { WagmiProvider } from "wagmi";

const { wallets } = getDefaultWallets();

const getSiweMessageOptions: GetSiweMessageOptions = () => ({
  statement: process.env.NEXT_PUBLIC_WALLET_SIGN_MESSAGE,
});

export default function RainbowKitProvider({ children }: React.PropsWithChildren): React.ReactElement {
  const config = getDefaultConfig({
    ssr: true,
    appName: 'App Name',
    projectId: 'WALLET_CONNECT_PROJECT_ID',
    chains: [
      mainnet,
    ],
    wallets,
  });

  return (
    <WagmiProvider config={config}>
      <RainbowKitSiweNextAuthProvider getSiweMessageOptions={getSiweMessageOptions}>
        <BaseRainbowKitProvider modalSize="compact">
          {children}
        </BaseRainbowKitProvider>
      </RainbowKitSiweNextAuthProvider>
    </WagmiProvider>
  );
}
```

I'm getting an error: `ChainNotConfiguredError: Chain not configured.`

<img width="1064" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/605186/bf8e3a13-afdf-4629-ad7a-ec017a954c61">

When I change my `chains` for example if I replace `mainnet` to `arbitrum` then everything works as expected. 

### Expected Behavior

Application should NOT crash.

### Steps To Reproduce

Just pass only `mainnet` to the `chains` or an empty array.

### Anything else?

Also would be great if you can allow to provide empty array in chains - in that case we should see `Switch Networks` window with message like "No available networks" etc. 

Currently we can't provide empty array because application crash:
<img width="1061" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/605186/c490d7c7-d8f2-47b0-96e0-1943decd6656">

This could help to have better user experience and manage `chains` dynamically

**Comment by magiziz** [comment]
@mits87 Mhmm seems like you're using `getDefaultConfig` within the component itself and not defining it outside of the component.

Can you try this code ?

```tsx
"use client";

import { GetSiweMessageOptions, RainbowKitSiweNextAuthProvider } from "@rainbow-me/rainbowkit-siwe-next-auth";
import {
  RainbowKitProvider as BaseRainbowKitProvider,
  getDefaultWallets,
  getDefaultConfig,
} from "@rainbow-me/rainbowkit";
import { mainnet } from "wagmi/chains";
import { WagmiProvider } from "wagmi";

const { wallets } = getDefaultWallets();

const getSiweMessageOptions: GetSiweMessageOptions = () => ({
  statement: process.env.NEXT_PUBLIC_WALLET_SIGN_MESSAGE,
});

const config = getDefaultConfig({
  ssr: true,
  appName: 'App Name',
  projectId: 'WALLET_CONNECT_PROJECT_ID',
  chains: [mainnet],
  wallets,
});

export default function RainbowKitProvider({ children }: React.PropsWithChildren): React.ReactElement {
  return (
    <WagmiProvider config={config}>
      <RainbowKitSiweNextAuthProvider getSiweMessageOptions={getSiweMessageOptions}>
        <BaseRainbowKitProvider modalSize="compact">
          {children}
        </BaseRainbowKitProvider>
      </RainbowKitSiweNextAuthProvider>
    </WagmiProvider>
  );
}
```

You can also check out our example dApp here if it helps https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next/src/pages/_app.tsx

**Comment by magiziz** [comment]
@mits87 Here is an example with app router as well https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-app/src/app/providers.tsx

**Comment by mits87** [comment]
I've tried like this:
```tsx
<WagmiProvider
      config={{
        ...config,
        chains: config.chains.filter(({ id }) =>
          [{ chainId: "42161" }].map(({ chainId }) => String(chainId)).includes(String(id)),
        ) as unknown as readonly [Chain, ...Chain[]],
      }}
    >
```

but this does not work:

<img width="568" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/605186/e9640f4d-7b52-4e2a-ab86-b9b6c885ef4a">

**Comment by magiziz** [comment]
@mits87 Any updates ?

**Comment by magiziz** [comment]
Closing this issue for now. Feel free to re-open this if you're still stuck.
