### ISSUE TITLE
Unable to use the wallet plugin that you developed

### ISSUE THREAD

**Issue by lianshao123** [rainbow-me/rainbowkit#2080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0-beta.3

### wagmi Version

^2.5.4

### Current Behavior

I used my own wallet plugin, and then clicked on wallet to jump to metamask, I don't know why this is happening, my wallet already supports EIP6963.Through EIP6963 test everything is normal, the making of address is the https://github.com/MetaMask/vite-react-ts-eip-6963.git.At present, I am testing locally and have not sent it online, and the online version does not support EIP6963.
![b23b9cfbe9b390318c820283444f42a1](https://github.com/rainbow-me/rainbowkit/assets/48192529/5aa3810c-deb3-491d-baed-035e407ebe59)
![898d507fafd3bced5299d57a05f5a2c7](https://github.com/rainbow-me/rainbowkit/assets/48192529/c4f71af3-e62f-494e-a0b5-b8b6dfa07106)

### Expected Behavior

Clicking on My Echooo wallet plugin will take you to my echooo wallet normally

**Comment by magiziz** [comment]
@lianshao123 Can you update your RainbowKit dependency to the latest version (`2.1.3`) ? Also i don't know why your extension doesn't work with EIP-6963 since i can't view the code. All the EIP-6963 wallets are working fine for RainbowKit.

Can you try using [mipd](https://github.com/wevm/mipd) library to announce your provider as EIP-6963 ?

**Comment by lianshao123** [comment]
@magiziz Yes, I use mipd, which is part of my code.  It worked fine when I removed all the other plugins and left only the Echooo plugin.  Do you have a plugin whitelist or something like that?
![c65d32d3bc6f737efaeccacff848fee0](https://github.com/rainbow-me/rainbowkit/assets/48192529/285bc4b6-9113-4c11-89af-d7c5f09e655e)

**Comment by magiziz** [comment]
@lianshao123 Can you do similar to what we do here ? https://github.com/rainbow-me/browser-extension/blob/master/src/entries/inpage/index.ts#L65-L80

**Comment by magiziz** [comment]
Closing this issue for now, if you're still stuck please re-open this issue.

**Comment by lianshao123** [comment]
https://github.com/user-attachments/assets/7d03fdd8-4c64-4501-b677-5781f3e85e49


https://github.com/user-attachments/assets/3b97b64d-1746-4fa3-b6e3-8e862d2f7a28

What are the conditions for the rainbow call to be satisfied? What are the compliance criteria for the Rainbow certification plugin?

**Comment by lianshao123** [comment]
The video above showcases two different dApps. The first one does not use Rainbow, while the second one utilizes the testing methods provided by Rainbow.

**Comment by lianshao123** [comment]
![image](https://github.com/user-attachments/assets/124971f2-2357-4286-b865-4f76b9e73816)
This is the code from the Echooo wallet plugin. When there are other plugins in Google Chrome, it modifies the ev, changing it to MetaMask, which causes the issue of clicking the Echooo plugin redirecting to the MetaMask plugin. How does RainbowKit send messages? Doesn't it send messages in a way other than postMessage?
