### ISSUE TITLE
[bug] Cannot read properties of null (reading 'getItem')

### ISSUE THREAD

**Issue by aetche** [rainbow-me/rainbowkit#2086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.2

### wagmi Version

2.10.2

### Current Behavior

We found that Sentry reports some Android users cannot load the page due to the error: `Cannot read properties of null (reading 'getItem')`. It looks like `getRecentWalletIds` is trying to access `getItem` from `localStorage` when it's null

> TypeError
Cannot read properties of null (reading 'getItem')

browser: **Chrome Mobile WebView 126.0.6478**
os: **Android**

![Screenshot 2024-07-05 at 2 23 44 PM](https://github.com/rainbow-me/rainbowkit/assets/24905167/a7e2de9d-5dd5-4d1f-a07c-786797ea8868)

### Expected Behavior

Application should NOT crash.

### Steps To Reproduce

I wasn't able to reproduce it.

### Anything else?

Found that the same [issue](https://github.com/pmndrs/zustand/discussions/1799) occurred with Zustand

**Comment by magiziz** [comment]
@aetche Pretty unusual. All browsers should support [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage#browser_compatibility). I'm also not able to reproduce this on Android for some reason. If `localStorage.getItem` doesn't exist then it'll not only impact RainbowKit, but other peer dependencies we have like Wagmi and Coinbase.

If you could try to give a small reproducible example that'd be awesome. This way we can find out why the issue appears in first place.
