### ISSUE TITLE
[bug] Wagmi Coinbase wallet  TypeError on mobile browsers 

### ISSUE THREAD

**Issue by HagiaSofiya** [rainbow-me/rainbowkit#2096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.2

### wagmi Version

2.9.11

### Current Behavior

The stack is Next 14 with app and typescript. When clicking on the Coinbase Wallet option on mobile,  nothing happens. Console throws this error

`Unhandled Promise Rejection: TypeError: Module is not a constructor (evaluating 'new(await a(Promise.all([n.e(50),n.e(8434),n.e(460),n.e(6140)]).then(n.t.bind(n,50460,19))))({...e,appChainIds:t.chains.map(e=>e.id)})')`

### Expected Behavior

It should link out to https://keys.coinbase.com/onboarding. 

### Steps To Reproduce

On mobile, navigate to https://bazaar.alkimiya.io/ and click Coinbase Wallet

### Anything else?

wagmi config

```
import { connectorsForWallets } from '@rainbow-me/rainbowkit'
import {
  coinbaseWallet,
  metaMaskWallet,
  walletConnectWallet,
} from '@rainbow-me/rainbowkit/wallets'
import { createConfig } from 'wagmi'
import { cookieStorage, createStorage, http } from 'wagmi'
import { foundry, mainnet, sepolia } from 'wagmi/chains'

const connectors = connectorsForWallets(
  [
    {
      groupName: 'Recommended',
      wallets: [metaMaskWallet, walletConnectWallet, coinbaseWallet],
    },
  ],
  {
    appName: 'Production',
    projectId: `${process.env.NEXT_PUBLIC_WC_PROJECT_ID}`,
  },
)

export const config = createConfig({
  connectors,
  chains: process.env.NODE_ENV === 'development' ? [mainnet, foundry, sepolia] : [mainnet, sepolia],,
  ssr: true,

  storage: createStorage({
    storage: cookieStorage,
  }),
  transports: {
    [sepolia.id]: http(),
    [foundry.id]: http(process.env.NEXT_PUBLIC_STAGING_RPC_URL),
    [mainnet.id]: http(), // Add this line to fix the error
  },
})

```

**Comment by magiziz** [comment]
@HagiaSofiya Can't seem to reproduce this. Do you think this might be an issue with the webpack bundler ?

https://github.com/user-attachments/assets/70f2687c-dee5-4735-b124-1147a5633331

**Comment by HagiaSofiya** [comment]
> @HagiaSofiya Can't seem to reproduce this. Do you think this might be an issue with the webpack bundler ?
> 
>  cb-repro.mov

I am using a [turbo repo ](https://turbo.build/)with the default webpack config. It only throws this error on mobile. You can checkout out the live build [here](https://bazaar.alkimiya.io/).

**Comment by magiziz** [comment]
@HagiaSofiya Code looks ok and works for me. Can you provide a minimal reproducible example by sharing a github repo or codesandbox link ? 

Here is our example dApp if it's helpful too https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next-app

**Comment by magiziz** [comment]
@HagiaSofiya Any luck ?

**Comment by HagiaSofiya** [comment]
@magiziz Thank you for your patience! I made a repo where i reproduced our config with the exact same package versions. 

[https://github.com/HagiaSofiya/rainbow-coinbase](https://github.com/HagiaSofiya/rainbow-coinbase)

I was trying to figure out why it works in the repo I made vs on our live site.  

On local host it throws this error 
<img width="948" alt="Screenshot 2024-07-18 at 8 16 05 PM" src="https://github.com/user-attachments/assets/c7b46d1c-f394-4da2-a5a5-5127036bf989">
