### ISSUE TITLE
[bug] Module not found: Can't resolve 'lit-html'

### ISSUE THREAD

**Issue by linghuccc** [rainbow-me/rainbowkit#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.3

### wagmi Version

2.9.2

### Current Behavior

Use command "yarn create @rainbow-me/rainbowkit" to init project, and then run "yarn dev" to start the project, below error will be reported:
Module not found: Can't resolve 'lit-html'

### Expected Behavior

No error.

### Steps To Reproduce

yarn create @rainbow-me/rainbowkit

yarn dev

**Comment by magiziz** [comment]
Seems like an polyfill issue. Let's keep the discussion here https://github.com/rainbow-me/rainbowkit/issues/2098
