### ISSUE TITLE
[bug] Can't resolve 'events'; Can't resolve 'buffer'; Can't resolve 'lit-html'

### ISSUE THREAD

**Issue by linghuccc** [rainbow-me/rainbowkit#2098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.3

### wagmi Version

2.10.10

### Current Behavior

I use below command to create a new react app:
`yarn create react-app my-app`

and then installed rainbowkit using below command:
`yarn add @rainbow-me/rainbowkit wagmi viem@2.x @tanstack/react-query`

Update src/index.js file to below:
```
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import '@rainbow-me/rainbowkit/styles.css';
import {
  getDefaultConfig,
  RainbowKitProvider,
} from '@rainbow-me/rainbowkit';
import { WagmiProvider } from 'wagmi';
import {
  mainnet,
  polygon,
  optimism,
  arbitrum,
  base,
} from 'wagmi/chains';
import {
  QueryClientProvider,
  QueryClient,
} from "@tanstack/react-query";

const config = getDefaultConfig({
  appName: 'My RainbowKit App',
  projectId: 'YOUR_PROJECT_ID',
  chains: [mainnet, polygon, optimism, arbitrum, base],
  ssr: true, // If your dApp uses server side rendering (SSR)
});

const queryClient = new QueryClient();

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <RainbowKitProvider>
          <App />
        </RainbowKitProvider>
      </QueryClientProvider>
    </WagmiProvider>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

Then try to run the project using below command:
`yarn start`

Below errors will appear.
![error](https://github.com/user-attachments/assets/e39915a7-f2ad-453d-a681-09467530cb4c)

### Expected Behavior

No error.

### Steps To Reproduce

yarn create react-app my-app

cd my-app

yarn add @rainbow-me/rainbowkit wagmi viem@2.x @tanstack/react-query

        Update src/index.js file;
        
yarn start

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/github/linghuccc/rainbowkit-error/main

**Comment by DanielSinclair** [comment]
It looks like you're missing some polyfills for your project. Reference the `src/polyfills.ts` file in this Create React App example and accompanying `buffer` dependency in the `package.json`: https://github.com/rainbow-me/rainbowkit/tree/b25db9a1f1f5acc96e28a12e38c2156e4fdbf51d/examples/with-create-react-app

**Comment by linghuccc** [comment]
> It looks like you're missing some polyfills for your project. Reference the `src/polyfills.ts` file in this Create React App example and accompanying `buffer` dependency in the `package.json`: https://github.com/rainbow-me/rainbowkit/tree/b25db9a1f1f5acc96e28a12e38c2156e4fdbf51d/examples/with-create-react-app

Thanks, after I created polyfills.js file, installed buffer, events and lit-html modules, most of the errors disappeared, only the below error persists:
![r0](https://github.com/user-attachments/assets/11ba4676-f5e7-4bd7-86da-082138ee5de9)

**Comment by DanielSinclair** [comment]
Ensure that you've followed the Wagmi installation guide and installed the Tanstack peer dependency https://wagmi.sh/react/getting-started#manual-installation

**Comment by linghuccc** [comment]
> Ensure that you've followed the Wagmi installation guide and installed the Tanstack peer dependency https://wagmi.sh/react/getting-started#manual-installation

I suspect the error comes from yarn, but I am not sure how to fix it.
![yarn1](https://github.com/user-attachments/assets/9d72a0ac-3db2-4948-9be3-094f93d2d4e6)
![yarn2](https://github.com/user-attachments/assets/26f8f8de-7a13-4dd5-836c-7852ab046a19)

**Comment by DanielSinclair** [comment]
You might have conflicting peer dependencies installed. Clean your package.json, reference the peer versions here, and give that a try: https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next/package.json

**Comment by linghuccc** [comment]
> You might have conflicting peer dependencies installed. Clean your package.json, reference the peer versions here, and give that a try: https://github.com/rainbow-me/rainbowkit/blob/main/examples/with-next/package.json

I have tried to use the package json file from the example, but was not successful. Later I changed yarn from v4.3.1 to v1.22.19 and there is no above errors.

Frankly speaking, your reply speed is very fast, but the product has a lot of bugs. Simply following the installation commands also fails. I really do not think rainbowkit is a product ready for use.

**Comment by magiziz** [comment]
@linghuccc Can you delete `node_modules` and `yarn.lock`, then do `yarn install` again ?

**Comment by linghuccc** [comment]
> @linghuccc Can you delete `node_modules` and `yarn.lock`, then do `yarn install` again ?

Done, still the same. I think the error originated from yarn peer dependency issue.

**Comment by magiziz** [comment]
@linghuccc Yes that's right. It's a peer dependency issue, but i don't see why this would cause your app to crash. If you run your app is it working again ?

**Comment by linghuccc** [comment]
> @linghuccc Yes that's right. It's a peer dependency issue, but i don't see why this would cause your app to crash. If you run your app is it working again ?

When you say "run your app", I suppose you mean "open the web page" because I am trying to build a react project. The index page will never show up and the error in below reply will always come up:
https://github.com/rainbow-me/rainbowkit/issues/2098#issuecomment-2229995195

**Comment by magiziz** [comment]
@linghuccc Gotcha. Can you re-upload your code to codesandbox or github repo and i'll have a look ?

**Comment by linghuccc** [comment]
> @linghuccc Gotcha. Can you re-upload your code to codesandbox or github repo and i'll have a look ?

Sure, the codes is in below URL:
https://github.com/linghuccc/rainbowkit-error

**Comment by magiziz** [comment]
> > @linghuccc Gotcha. Can you re-upload your code to codesandbox or github repo and i'll have a look ?
> 
> Sure, the codes are in below URL: https://github.com/linghuccc/rainbowkit-error

Thanks! Will take a look and get back.

**Comment by magiziz** [comment]
@linghuccc Apologies for the delay. I just checked out your code and doesn't seem like i'm getting any errors. I can see some warnings, but you can modify your start command like so.

```
"start": "GENERATE_SOURCEMAP=false react-scripts start"
```

The reason why this is happening is because the project uses create-react-app which isn't stable anymore and you should definetely look into using another library such as vite.

![image](https://github.com/user-attachments/assets/46cf7c54-700c-4a14-846d-6a6e805e787a)

**Comment by linghuccc** [comment]
> @linghuccc Apologies for the delay. I just checked out your code and doesn't seem like i'm getting any errors. I can see some warnings, but you can modify your start command like so.
> 
> ```
> "start": "GENERATE_SOURCEMAP=false react-scripts start"
> ```
> 
> The reason why this is happening is because the project uses create-react-app which isn't stable anymore and you should definetely look into using another library such as vite.
> 
> ![image](https://private-user-images.githubusercontent.com/53529533/353836747-46cf7c54-700c-4a14-846d-6a6e805e787a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MTczMjksIm5iZiI6MTcyMjgxNzAyOSwicGF0aCI6Ii81MzUyOTUzMy8zNTM4MzY3NDctNDZjZjdjNTQtNzAwYy00YTE0LTg0NmQtNmE2ZTgwNWU3ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAwMTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzAxNDA0YzUyOGZiM2FiMDM2ZDEwNGZkYzI0MTM0ZjVmNTUzYTVjN2JiY2NkOTcxNDNiMDU0NDQ1ZDQ0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jJ_D8ggQvTE4BAek7OXw6FInOZoBQOt5ZvScpDPFFnY)

Thank you for your reply. I have updated start script as you suggested and below is the error I encountered:
![1](https://github.com/user-attachments/assets/d7f8a4d2-1e1a-4a38-a4fa-b02a86913cec)

I also need to point out, this error does not only appear when using "create-react-app". In fact, in my other post, I have reported similar errors when using "yarn create @rainbow-me/rainbowkit": https://github.com/rainbow-me/rainbowkit/issues/2097

**Comment by magiziz** [comment]
@linghuccc I was not able to reproduce this for some reason. Did you do npm install and npm start ?

**Comment by linghuccc** [comment]
> @linghuccc I was not able to reproduce this for some reason. Did you do npm install and npm start ?

As I described in the steps, I used "yarn" command, and did not use "npm" command.

**Comment by linghuccc** [comment]
> @linghuccc Yes i did `yarn install` and `yarn start`. Everything worked fine for me.
> 
> <img alt="image" width="398" src="https://private-user-images.githubusercontent.com/53529533/355167710-06f7b05a-ce4e-4768-8438-8639960e817c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDYyOTQsIm5iZiI6MTcyMjkwNTk5NCwicGF0aCI6Ii81MzUyOTUzMy8zNTUxNjc3MTAtMDZmN2IwNWEtY2U0ZS00NzY4LTg0MzgtODYzOTk2MGU4MTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAwNTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYWNkZDcwMWE5NGMyY2RlYmMyNTNkZGM0YTFkNzkxNGMxMjQxYjBkMDY3NDc2NGY3ZmI3OWUyYWYyNjc3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10lXCOy450-YGVmOSK3Pg1ALUs68lzmiRzy8UjeLXk0"> <img alt="image" width="1728" src="https://private-user-images.githubusercontent.com/53529533/355167786-02aaf4dc-9515-43ac-855e-1b2c2d1c7521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDYyOTQsIm5iZiI6MTcyMjkwNTk5NCwicGF0aCI6Ii81MzUyOTUzMy8zNTUxNjc3ODYtMDJhYWY0ZGMtOTUxNS00M2FjLTg1NWUtMWIyYzJkMWM3NTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAwNTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NWRjOTk5ODQ5MWRmMTdlYWJiNjlkZDg4NWE1NjdlMDIzNjZkMDY0NmI0MGQwNTJhMjExZmMxNDk3ZWVlY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ErOcfCNDD9l0RwC0FySfpxh7rYw3-8787-aAlz-s79w">

What is your yarn version?

**Comment by magiziz** [comment]
@linghuccc `1.22.22`

**Comment by linghuccc** [comment]
> @linghuccc `1.22.22`

I have tried one more time with yarn@1.22.22, but the error remains.
![error](https://github.com/user-attachments/assets/f04707c7-d0aa-45e7-a28b-25d197463ebb)

**Comment by magiziz** [comment]
@linghuccc Can you confirm that this is the right repo ? https://github.com/linghuccc/rainbowkit-error

**Comment by linghuccc** [comment]
> @linghuccc Can you confirm that this is the right repo ? https://github.com/linghuccc/rainbowkit-error

Please refer to below repo for the latest error (yarn version 1.22.22)
https://github.com/linghuccc/rainbowkit-yarn.1.22.22

Thank you.

**Comment by magiziz** [comment]
@linghuccc In your `App.js` you need to add `client` to `<QueryClientProvider>` like this.

```tsx
const config = getDefaultConfig({
  appName: 'Uniswap Example',
  projectId: process.env.REACT_APP_PROJECT_ID,
  chains: [mainnet, sepolia],
  ssr: true, // If your dApp uses server side rendering (SSR)
  transports: {
    [sepolia.id]: http('https://sepolia.infura.io/v3/' + process.env.REACT_APP_INFURA_KEY),
  }
});

const queryClient = new QueryClient(); // <- here

const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(
  <React.StrictMode>
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <RainbowKitProvider>
          <App />
        </RainbowKitProvider>
      </QueryClientProvider>
    </WagmiProvider>
  </React.StrictMode>
);
```

**Comment by linghuccc** [comment]
> @linghuccc In your `App.js` you need to add `client` to `<QueryClientProvider>` like this.
> 
> ```tsx
> const config = getDefaultConfig({
>   appName: 'Uniswap Example',
>   projectId: process.env.REACT_APP_PROJECT_ID,
>   chains: [mainnet, sepolia],
>   ssr: true, // If your dApp uses server side rendering (SSR)
>   transports: {
>     [sepolia.id]: http('https://sepolia.infura.io/v3/' + process.env.REACT_APP_INFURA_KEY),
>   }
> });
> 
> const queryClient = new QueryClient(); // <- here
> 
> const root = ReactDOM.createRoot(document.getElementById("root"));
> 
> root.render(
>   <React.StrictMode>
>     <WagmiProvider config={config}>
>       <QueryClientProvider client={queryClient}>
>         <RainbowKitProvider>
>           <App />
>         </RainbowKitProvider>
>       </QueryClientProvider>
>     </WagmiProvider>
>   </React.StrictMode>
> );
> ```

You are right! I must have missed it during copy and paste!

I immediately went to check projects initialized using "yarn create @rainbow-me/rainbowkit" and "yarn create vite". Luckily I did not make the same mistake for those two projects. Even luckier I found out that those two projects no longer has similar error as before. Well, all at a sudden, I am all good.

Thank you for pointing this out.

**Comment by linghuccc** [comment]
Thank you so much, magiziz!
