### ISSUE TITLE
Clicking on the Echooo wallet redirects to MetaMask

### ISSUE THREAD

**Issue by lianshao123** [rainbow-me/rainbowkit#2115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.3

### wagmi Version

2.1.3

### Current Behavior

this issues:    https://github.com/rainbow-me/rainbowkit/issues/2080

**Comment by magiziz** [comment]
@lianshao123 Echooo wallet doesn't seem to be supported in RainbowKit. Can you provide a minimal reproducible example ?

**Comment by lianshao123** [comment]
> @lianshao123RainbowKit 似乎不支持 Echooo 钱包。您能提供一个最小的可重现示例吗？

I can, but I need a little time

**Comment by lianshao123** [comment]
https://github.com/lianshao123/simplified-echooo.git
This is the code for the echooo plugin after I deleted some parts of it. The EIP6963 code has been added to the inpage file. To run the project, please execute npm i --force and then run npm run dev. Add the build folder to the Google Chrome extension. @magiziz

**Comment by lianshao123** [comment]
https://github.com/user-attachments/assets/c89e6850-fcd5-4b32-9c6a-5c4f2e741c3b

The execution effect is similar to this: the Echooo plugin will pop up, although it is a blank plugin.

**Comment by lianshao123** [comment]
There's another question: how to run RainbowKit to test and troubleshoot bugs?

**Comment by magiziz** [comment]
Seems like an Echoo wallet problem if it's not working as expected since almost every wallet that supports EIP-6963 works fine.

**Comment by lianshao123** [comment]
> 如果它不能按预期工作，似乎是 Echoo 钱包的问题，​​因为几乎每个支持 EIP-6963 的钱包都能正常工作。



> Seems like an Echoo wallet problem if it's not working as expected since almost every wallet that supports EIP-6963 works fine.

It can run normally. The example given above is just a simplified version after I removed most of the code, which is why it shows a blank white screen. The Echooo wallet in the Google Play Store displays correctly.
https://github.com/lianshao123/simplified-echooo.git  This is the link after I removed most of the code.

**Comment by lianshao123** [comment]
![image](https://github.com/user-attachments/assets/0a5bc824-f6de-4a95-942a-0c19fb6fbcef)
Do you have a wallet address whitelist?

**Comment by DanielSinclair** [comment]
@lianshao123 We do not. These are the wallet connectors we support by default that wallets can include. EIP-6963 wallets have replaced the need for these for injected extensions (as they are always included in RainbowKit). You can always open a PR for a wallet on the RainbowKit repo to add full wallet support.

**Comment by lianshao123** [comment]
![image](https://github.com/user-attachments/assets/2bf03456-911e-4a2d-93a6-7f88318e7ea5)

This is the code from the Echooo wallet plugin. When there are other plugins in Google Chrome, it modifies the ev, changing it to MetaMask, which causes the issue of clicking the Echooo plugin redirecting to the MetaMask plugin. How does RainbowKit send messages? Doesn't it send messages in a way other than postMessage?
