### ISSUE TITLE
[bug] "Get" wallet button shows empty screen

### ISSUE THREAD

**Issue by magiziz** [rainbow-me/rainbowkit#2121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.3

### wagmi Version

2.12.1

### Current Behavior

When clicking on "Get a Wallet" and then choosing an EIP-6963 wallet it'll show an empty screen.

https://github.com/user-attachments/assets/3ab127c0-97f1-4e20-b0ab-5f0a06e17a1f

### Expected Behavior

Shouldn't display an empty screen and instead it should show the wallet download details.

### Steps To Reproduce

- Have MetaMask installed
- Go to https://www.rainbowkit.com
- Click "Connect Wallet" -> "Get a Wallet" -> "Get" (MetaMask)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com

**Comment by annemarieshev** [comment]
Hello @magiziz 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat
