### ISSUE TITLE
[bug] issue connecting with Compass Wallet

### ISSUE THREAD

**Issue by thelostone-mc** [rainbow-me/rainbowkit#2130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.4

### wagmi Version

2.12.0

### Current Behavior

When I connect using compass wallet on Gitcoin. The connection fails cause it's unable to do getAccounts.
I then tried using the compass wallet on https://www.rainbowkit.com/ and the connection fails there as well
![Deploy](https://github.com/user-attachments/assets/41d2f872-b583-4657-bb26-c44d5e8a3da1)

### Expected Behavior

Compass Wallet Should connect like Metamask

### Steps To Reproduce

Head over to https://www.rainbowkit.com/  and try connecting to the compass wallet 

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/

### Anything else?

This original issue was reported on gitcoin https://github.com/gitcoinco/grants-stack/issues/3581 and i wasn't able to debug the issue

**Comment by magiziz** [comment]
@thelostone-mc This is a compass wallet issue rather than RainbowKit issue. Their extension is not able to connect and i think the best thing to do for now is to reach out to their support team and report this bug.
