### ISSUE TITLE
[bug] The title of Binance Wallet should be 'Binance Web3 Wallet' in page '/site/data/zh-CN/docs /custom-wallet-list.mdx', line 149

### ISSUE THREAD

**Issue by pengandpeng** [rainbow-me/rainbowkit#2134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.0.0

### wagmi Version

2.12.0

**Comment by DanielSinclair** [comment]
Resolved this. Thanks for reporting!
