### ISSUE TITLE
[bug] [doc] documentation adds a lot of duplication 

### ISSUE THREAD

**Issue by HydenLiu** [rainbow-me/rainbowkit#2141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.4

### wagmi Version

2.1.4

### Current Behavior

Hi,  The documentation adds a lot of duplication?
about pr link: https://github.com/rainbow-me/rainbowkit/pull/2073/files#diff-621b82fff20457996cddcf7da5cd91184cdac48d06f14be0ff662ec20e7c95be

### Expected Behavior

These are all duplicates.
<img width="1708" alt="image" src="https://github.com/user-attachments/assets/2f41b58c-4c2b-4d02-9622-f08a6631c913">

### Steps To Reproduce

see website 
https://www.rainbowkit.com/zh-CN/docs/theming

**Comment by DanielSinclair** [comment]
Resolved this. Thanks for reporting!
