### ISSUE TITLE
[bug] missing RAINBOW_PROVIDER_API_KEY env variable

### ISSUE THREAD

**Issue by eyooooo** [rainbow-me/rainbowkit#2142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

latest

### wagmi Version

latest

### Current Behavior

performing `pnpm install` on a freshly cloned repo throws the error `throw new Error('missing RAINBOW_PROVIDER_API_KEY env variable');`

### Expected Behavior

no error

### Steps To Reproduce

clone repo and do pnpm i

**Comment by magiziz** [comment]
In `packages/rainbowkit` create `.env.local` file and pass in an random string to `RAINBOW_PROVIDER_API_KEY` variable.

```
RAINBOW_PROVIDER_API_KEY=random_string
```

**Comment by eyooooo** [comment]
> In `packages/rainbowkit` create `.env.local` file and pass in an random string to `RAINBOW_PROVIDER_API_KEY` variable.
> 
> ```
> RAINBOW_PROVIDER_API_KEY=random_string
> ```

thanks for the quick reply. my quick fix was to just do `export RAINBOW_PROVIDER_API_KEY=rainbow` but my issue is assuming this is a bug since it was unexpected behavior on a fresh install. unless creating .env.local is something everyone but me does, in which case i will respectfully bow out :)
