### ISSUE TITLE
[bug] Some downloaded wallets are unable to connect using the WalletButton component

### ISSUE THREAD

**Issue by qhcy** [rainbow-me/rainbowkit#2144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.4

### wagmi Version

2.9.2

### Current Behavior

I found when using the WalletButton component, clicking the Rainbow wallet button and the Trust wallet button will pop up a QR code window, but I have already downloaded the browser extensions for these two wallets, including the one from the Rainbow official website.
![image](https://github.com/user-attachments/assets/5e42c585-e129-4bb1-a254-5286583a8547)

Actually, I found that when using the getDefaultWallets() function, the data output in the console shows Rainbow as "not installed".
![image](https://github.com/user-attachments/assets/e09c7f68-332e-4118-84d0-d9c0d64e5232)

By the way, I'm curious to know how I can retrieve the wallet list in the same way as the modal displays it. If you could provide some guidance on that, I would greatly appreciate it.

### Expected Behavior

When I click on the downloaded wallet button, it should call the wallet connection.

### Steps To Reproduce

You can open the Rainbow official documentation and use the WalletButton component to reproduce the issue.

**Comment by magiziz** [comment]
@qhcy Seems like it's an EIP-1193 issue. What if you disable all extensions apart from Rainbow wallet ? I've seen this before and it's because different wallets try to override each other.

**Comment by qhcy** [comment]
@magizizYes, you are right!Thank you.

**Comment by magiziz** [comment]
> @magiziz Yes, you are right!Thank you.I have too many wallet extensions.🥲

What happens when you disable all wallet extensions apart from Rainbow wallet ?

**Comment by qhcy** [comment]
@magiziz The wallet can be connected normally, and` getDefaultWallets()` can get the correct value
