### ISSUE TITLE
[bug] Unable to add custom wallet to wallet list

### ISSUE THREAD

**Issue by Adebesin-Cell** [rainbow-me/rainbowkit#2151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^2.1.4

### wagmi Version

^2.12.4

### Current Behavior

The custom wallet "Magic" does not show up in the wallet list when using version 2.x. Definition of magic connector can be found [here](https://github.com/magiclabs/wagmi-magic-connector/blob/main/src/lib/connectors/dedicatedWalletConnector.ts)

## Code Samples
```ts 
import { dedicatedWalletConnector } from '@magiclabs/wagmi-connector
```

```ts
export const rainbowMagicConnector = ({ chain }: { chain: Chain }): Wallet => ({
  id: 'magic',
  name: 'Magic',
  iconUrl: 'https://svgshare.com/i/pXA.svg',
  iconBackground: 'white',
  installed: true,
  rdns: 'io.magic',

  createConnector: () =>
    dedicatedWalletConnector({
      chains: [chain],
      options: {
        customLogo: 'https://iq.social/images/iq-logo.svg',
        apiKey: env.NEXT_PUBLIC_MAGIC_API_KEY,
        accentColor: '#ea3b87',
        oauthOptions: {
          providers: ['google', 'facebook', 'twitter', 'discord'],
        },
        isDarkMode: false,
        magicSdkConfiguration: {
          network: {
            chainId: chain.id,
            rpcUrl: chain.rpcUrls.default.http[0],
          },
        },
      },
    }),
})
```

```ts

const connectors = connectorsForWallets(
  [
    {
      groupName: 'Suggestions',
      wallets: [() => rainbowMagicConnector({ chain: polygon })]
    },
    ...getDefaultWallets({
      appName: 'My App',
      projectId: env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
    }).wallets
  ],
  {
    appName: 'My App',
    projectId: env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
  }
);

const config = createConfig({
  chains: [chain] as any,
  connectors,
  transports: {
    [chain.id]: http()
  },
  multiInjectedProviderDiscovery: false
});
```

### Expected Behavior

The custom wallet "Magic" should appear in the wallet list.

### Steps To Reproduce

1. Import the `dedicatedWalletConnector`:

    ```typescript
    import { dedicatedWalletConnector } from '@magiclabs/wagmi-connector';
    ```

2. Define the custom wallet connector:

    ```typescript
    export const rainbowMagicConnector = ({ chain }: { chain: Chain }): Wallet => ({
      id: 'magic',
      name: 'Magic',
      iconUrl: 'https://svgshare.com/i/pXA.svg',
      iconBackground: 'white',
      installed: true,
      rdns: 'io.magic',

      createConnector: () =>
        dedicatedWalletConnector({
          chains: [chain],
          options: {
            customLogo: 'https://iq.social/images/iq-logo.svg',
            apiKey: env.NEXT_PUBLIC_MAGIC_API_KEY,
            accentColor: '#ea3b87',
            oauthOptions: {
              providers: ['google', 'facebook', 'twitter', 'discord'],
            },
            isDarkMode: false,
            magicSdkConfiguration: {
              network: {
                chainId: chain.id,
                rpcUrl: chain.rpcUrls.default.http[0],
              },
            },
          },
        }),
    });
    ```

3. Attempt to use the custom wallet in your RainbowKit setup:

    ```typescript
    const connectors = connectorsForWallets(
      [
        {
          groupName: 'Suggestions',
          wallets: [() => rainbowMagicConnector({ chain: polygon })],
        },
        ...getDefaultWallets({
          appName: 'My App',
          projectId: env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
        }).wallets,
      ],
      {
        appName: 'My App',
        projectId: env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
      }
    );

    const config = createConfig({
      chains: [chain] as any,
      connectors,
      transports: {
        [chain.id]: http(),
      },
      multiInjectedProviderDiscovery: false,
    });
    ```

4. Observe that the "Magic" wallet does not appear in the wallet list.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://stackblitz.com/edit/stackblitz-starters-swcim7?file=app%2Fconfig.ts

## Media

<img width="748" alt="Screenshot 2024-08-20 at 5 09 55 PM" src="https://github.com/user-attachments/assets/bbbe4e3a-dd96-4834-9f39-f9caea77b748">

<img width="744" alt="Screenshot 2024-08-20 at 5 12 58 PM" src="https://github.com/user-attachments/assets/2932840c-1d7e-443a-b3ea-678e2d44116b">

**Comment by Adebesin-Cell** [comment]
@DanielSinclair I created the issue as requested, kindly help look at it, thanks 👏

**Comment by Adebesin-Cell** [comment]
Hey @DanielSinclair, I've been debugging the issue and discovered that while the connectors are being passed to `createConfig` through `getDefaultConfig` from RainbowKit, it seems that Wagmi isn't properly parsing them. This might be related to the information in the [Wagmi documentation on creating connectors](https://wagmi.sh/dev/creating-connectors).

Additionally, I noticed that the Safe wallet doesn't render in RainbowKit, even though it is listed on Wagmi's page [here](https://wagmi.sh/core/api/connectors/safe).

At this point, I'm not sure what the best course of action is. If you have any suggestions or leads, I would greatly appreciate your input.

Thanks in advance!

**Comment by Adebesin-Cell** [comment]
Hey @DanielSinclair, thanks! I'll be closing this, I figured it out

**Comment by Adebesin-Cell** [comment]
@magiziz @DanielSinclair Hi, I would like to make contributions to rainbowkit, can my GitHub account be added to the repo?

**Comment by cedrichan** [comment]
@Adebesin-Cell Do you recall how you were able to address this?

**Comment by Adebesin-Cell** [comment]
Hey **@cedrichan**, yeah, I think I do! I ended up following the `coinbaseWallet` approach. Here's how they set up the connector:

```ts
createConnector: (walletDetails: WalletDetailsParams) => {
  const connector: CreateConnectorFn = coinbaseConnector({
    appName,
    appLogoUrl: appIcon,
    preference: coinbaseWallet.preference,
  });

  return createConnector((config) => ({
    ...connector(config),
    ...walletDetails,
  }));
}
```

This was the approach I was trying to configure back then, although I struggled to get the connector working 😅. Below is the more detailed code I used, which involves `magicWallet` and the `dedicatedWalletConnector` from `@magiclabs/wagmi-connector`:

```ts
import { env } from '@/env';
import { dedicatedWalletConnector } from '@magiclabs/wagmi-connector';
import type { Wallet } from '@rainbow-me/rainbowkit';
import type { Chain } from 'viem';
import { polygon } from 'viem/chains';
import { createConnector } from 'wagmi';

export const createMagicConnector = ({ chain }: { chain: Chain }): Wallet => ({
  id: 'magic',
  name: 'Magic',
  iconUrl: 'https://svgshare.com/i/pXA.svg',
  iconBackground: '#fff',
  installed: true,
  iconAccent: '#b4acfc',

  createConnector: (walletDetails) => {
    const magicConnector = dedicatedWalletConnector({
      chains: [chain],
      options: {
        customLogo: 'https://iq.social/images/iq-logo.svg',
        apiKey: env.NEXT_PUBLIC_MAGIC_API_KEY,
        accentColor: '#ea3b87',
        oauthOptions: {
          providers: ['google', 'facebook', 'twitter', 'discord'],
        },
        isDarkMode: false,
        magicSdkConfiguration: {
          network: {
            chainId: chain.id,
            rpcUrl: chain.rpcUrls.default.http[0],
          },
        },
      },
    });

    return createConnector((config) => ({
      ...magicConnector(config),
      ...walletDetails,
    }));
  },
});

export const magicWallet = () => createMagicConnector({ chain: polygon });
```

You can also refer to [this pull request](https://github.com/magiclabs/wagmi-magic-connector/pull/23) for more context. This setup worked for me, though it took a bit of trial and error to get everything configured properly. Hope this helps!
