### ISSUE TITLE
[bug] Custom ConnectButton not working

### ISSUE THREAD

**Issue by 0xhiler** [rainbow-me/rainbowkit#2171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.4

### wagmi Version

2.12.5

### Current Behavior

I have followed this guide:
https://www.rainbowkit.com/docs/custom-connect-button

But it shows this error:
`Error: Functions are not valid as a child of Client Components. This may happen if you return children instead of <children /> from render. Or maybe you meant to call this function rather than return it.
  <... children={function children}>`

![image](https://github.com/user-attachments/assets/973b8ada-eacb-4a23-841f-d9ab282cea1b)

Whenever I use the raw `<ConnectButton />`, then whole code working.
I am using the Next(v14.2.4), typescript(v5) and react(v18)

Let me know if you need more info to check this issue

### Expected Behavior

I expected that code working and showing the customized `WalletConnect` button, but failed

**Comment by DanielSinclair** [comment]
@0xhiler Can you share a CodeSandbox etc. reproducible example for us to have a look at your setup?

**Comment by Adebesin-Cell** [comment]
> Can confirm, bug exists, simply copied code snippet from https://www.rainbowkit.com/docs/custom-connect-button to my Next14 project. Immediately got this error.

Add “use client” perhaps to the button?
