### ISSUE TITLE
[bug] Custom chain name is overriden by default chain config

### ISSUE THREAD

**Issue by ilzheev** [rainbow-me/rainbowkit#2172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.0

### wagmi Version

2.9.0

### Current Behavior

Init BNB Chain with custom chain config
```json
  {
    id: 56,
    name: 'BNB Chain',
    iconBackground: '#fff',
    nativeCurrency: {
      decimals: 18,
      name: 'BNB Chain',
      symbol: 'BNB',
    },
    rpcUrls: {
      public: { http: ['https://rpc.ankr.com/bsc'] },
      default: { http: ['https://rpc.ankr.com/bsc'] },
    },
    blockExplorers: {
      default: { name: 'BscScan', url: 'https://bscscan.com' },
    }
  }
```

Chain with this config is displayed in Rainbowkit, but the name is overriden to `BSC`:
<img width="361" alt="image" src="https://github.com/user-attachments/assets/cde96130-49fb-4d77-a7ff-8b40b6658e7d">

### Expected Behavior

Chain name should be as set in custom config – `BNB Chain`

### Steps To Reproduce

- Init custom chain with following config:
```json
  {
    id: 56,
    name: 'BNB Chain',
    iconBackground: '#fff',
    nativeCurrency: {
      decimals: 18,
      name: 'BNB Chain',
      symbol: 'BNB',
    },
    rpcUrls: {
      public: { http: ['https://rpc.ankr.com/bsc'] },
      default: { http: ['https://rpc.ankr.com/bsc'] },
    },
    blockExplorers: {
      default: { name: 'BscScan', url: 'https://bscscan.com' },
    }
  }
```
- do NOT include standard BSC chain config in Rainbowkit init

**Comment by DanielSinclair** [comment]
@ilzheev This is currently expected. We use colloquial names (i.e. `Arbitrum` vs `Arbitrum One`) for a handful of chains. Do you think `BNB` is incorrect in this context?

**Comment by ilzheev** [comment]
@DanielSinclair When we initially deployed, BNB Chain team asked us to rename `BSC / Binance Smart Chain` to `BNB Chain` in our UI – I assume they don't want to be associated with Binance anymore and try to stick to `BNB Chain` name.

If the requirement is to use colloquial names only, I am not sure if `BNB` is better than `BSC`.

Ideal solution, in my opinion, allow developers to override name parameter using custom chains – especially considering that `iconBackground` & `iconUrl` are allowed to be overridden using custom chain config. Not sure what name override does not work in the same config struct.

**Comment by jTerraBit** [comment]
@DanielSinclair @ilzheev We are also experiencing this issue and need to set the name to `BNB Chain`

**Comment by jill6666** [comment]
Hi @DanielSinclair @ilzheev 👋

Thanks for the great work on RainbowKit! I'm following up on this issue bc we’re running into the same problem and wanted to share a bit about our scenario:

We’re building a product where clarity for end users is crucial, and we’ve noticed that many users are confused by seeing “BSC” as the chain name — they perceive it as outdated. The term “BNB” or “BNB Chain” is more widely recognized and accepted now, especially among newer Web3 users.

It would be really helpful if we could customize the chain display name to improve user experience and avoid this confusion. Is there a chance this could be reopened or considered for support again?

Happy to provide more context if helpful — and really appreciate your time!
