### ISSUE TITLE
[bug] Uncaught error when opening WalletConnect modal.

### ISSUE THREAD

**Issue by einaralex** [rainbow-me/rainbowkit#2187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.6

### wagmi Version

2.12.9

### Current Behavior

Uncaught error in console when you choose WalletConnect in modal

error: [object Object]" is not valid JSON, coming from walletconnect-core (I think)

### Steps To Reproduce

This can be done on https://www.rainbowkit.com/.

1. Make sure to clear site data.
2. Observe dev tools when connecting with WalletConnect.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/

### Anything else?

I've been having issues where it fails silently the first time I try to sign through WalletConnect with a fresh state.

Also, I noticed that even if you only set walletConnectWallet as the only wallet.
When you check for the connectors `const connectors = useConnectors(),` you'll see 2 walletConnect connectors; that can't be right?

**Comment by aman2000verma** [comment]
Facing the same issue locally with other wallets too (e.g. Trust Wallet)
Sometimes it work, but sometimes throws this error randomly

**Comment by DanielSinclair** [comment]
This should now be resolved with Wagmi `v2.12.17` which includes upgraded WalletConnect libraries
