### ISSUE TITLE
[bug] Request Connect Wallet

### ISSUE THREAD

**Issue by hoangman1108** [rainbow-me/rainbowkit#2200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.4

### wagmi Version

2.5.16

### Current Behavior

I use IOS devices,
bowser Brave on mobile

Step 1: Open Brave
Step 2: open my website with using rainbowKit
Step 3: Connect Wallet and select metamask
Step 4: it request Brave wallet not open metamask

### Expected Behavior

I use IOS devices,
bowser Brave on mobile

Step 1: Open Brave
Step 2: open my website with using rainbowKit
Step 3: Connect Wallet and select metamask
Step 4: Open request connect Metamask

### Steps To Reproduce

It just code base, 
still happen when connect on your website
https://www.rainbowkit.com/

**Comment by DanielSinclair** [comment]
This is unfortunately a Brave Browser design choice. You'll need to go to Settings > Web3 > Ethereum and disable the "Sites can request access to your Ethereum wallet" toggle and change Default Ethereum Wallet to None. 
![IMG_4384](https://github.com/user-attachments/assets/7fa9f1a8-8950-4777-b7a0-230bcf47b635)
