### ISSUE TITLE
[bug] Connect Wallet Modal shows two MetaMask options

### ISSUE THREAD

**Issue by doyourbest96** [rainbow-me/rainbowkit#2208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.7

### wagmi Version

2.12.9

### Current Behavior

![2024-10-08_3-58-01](https://github.com/user-attachments/assets/6b5b3e31-e0ea-4cda-9909-2a52321b3d8b)

Please help me to fix this problem.

**Comment by Julietnacy** [comment]
@doyourbest96 It might be worth checking if one of them is for a different network or version. Have you tried selecting both to see if one works better than the other?

**Comment by DanielSinclair** [comment]
@doyourbest96 Do you have multiple Chrome extensions installed, like MetaMask and MetaMask Flask?

**Comment by doyourbest96** [comment]
I have only installed MetaMask extension and they works one.
You can see in this picture what happened.
![2024-10-08_14-56-00](https://github.com/user-attachments/assets/5c0a4aa6-0b83-4875-bedc-2d50eaf204ed)

**Comment by Julietnacy** [comment]
@doyourbest96 okay but it just shows two

**Comment by doyourbest96** [comment]
Yeah and this bug disappears after once it connected.

**Comment by Julietnacy** [comment]
@doyourbest96  It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID MET07638
Please see the link below to our dedicated support line:
[metamask Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by doyourbest96** [comment]
I think this problem is not on MetaMask.
As you can see above picture, all wallets are dupullicated in wallet list.

**Comment by Julietnacy** [comment]
@doyourbest96 It sounds like there might be a glitch with how the wallets are being displayed.

**Comment by doyourbest96** [comment]
@Julietnacy How can I solve this problem?

**Comment by Julietnacy** [comment]
@doyourbest96 I’ve already directed you to contact wallet support. They might be able to help resolve the issue.

**Comment by doyourbest96** [comment]
@Julietnacy Okay, I'll check. thank you.

**Comment by Julietnacy** [comment]
@doyourbest96 Reach out to them now so they can assist you in resolving it.

**Comment by DanielSinclair** [comment]
@doyourbest96 Did you resolve the issue? The previous user you were interacting with in this thread was a phishing bot
