### ISSUE TITLE
[bug] <OKX Metamask link confusion> 

### ISSUE THREAD

**Issue by LukeAntarctic** [rainbow-me/rainbowkit#2211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

lastest

### wagmi Version

lastest

### Current Behavior

In the scenario where OKX is installed but Metamask is not installed, click on the link Metamask and let me link OKX. What I expect is to link Metamask, which can be implemented using this technique https://eips.ethereum.org/EIPS/eip-6963#abstract

**Comment by LukeAntarctic** [comment]
in https://www.rainbowkit.com/zh-CN/docs/introduction Can reproduce

**Comment by DanielSinclair** [comment]
This is currently expected behavior. We rely on the MetaMask button as a fallback for all `window.ethereum` providers because this has historically been a common UI pattern.
