### ISSUE TITLE
[bug] Vercel Deployment fails even though project ID defined.

### ISSUE THREAD

**Issue by Patrick-Ehimen** [rainbow-me/rainbowkit#2260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.1.5

### wagmi Version

2.12.8

### Current Behavior

I have a Nextjs14 project, and my WalletConnectId variable is populated within an .env variable but only works with localhost. When trying to build with vercel, the error shows up.

'Error: No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect v2'

### Expected Behavior

Build should not fail.

### Steps To Reproduce

To Reproduce

1. Create NextJS 14 project
2. Create .env in root directory
3. Declare project ID variable with process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
4. Use wagmi or Rainbow kit to create providers
5. Deploy project to github amd when Vercel tries to build project the build fails with the error

  "Error: No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect 
    v2"

**Comment by DanielSinclair** [comment]
It sounds like you just need to add `NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID` to your Vercel deployment env variables via their dashboard or CLI. https://vercel.com/guides/how-to-add-vercel-environment-variables
