### ISSUE TITLE
[bug] Elements with role="dialog" or role="alertdialog" do not have accessible names.

### ISSUE THREAD

**Issue by mlenser** [rainbow-me/rainbowkit#2270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

"@rainbow-me/rainbowkit": "^2.2.1",

### wagmi Version

2.14.0

### Current Behavior

`wcm-modal` does not have an accessible name according to Lighthouse.

`wcm-modal` likely comes from wallet connect and may need to be an issue on a dependent package

### Expected Behavior

Lighthouse accessibility passes

### Steps To Reproduce

Run lighthouse on an app with rainbowkit on web. https://www.rainbowkit.com for example will fail:
![image](https://github.com/user-attachments/assets/bbb4d1f7-cf57-4916-976b-b9e263292ff2)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com

**Comment by DanielSinclair** [comment]
That is upstream in WalletConnect correct. Have relayed to their team!
