### ISSUE TITLE
[bug] Custom Fonts cause Hydration issues with NextJS

### ISSUE THREAD

**Issue by exception** [rainbow-me/rainbowkit#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.3

### Current Behavior

For some reason, changing the font on the theme causes a React Hydration issue. Below are a couple of images detailing the issue:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/5695356/167017893-40648157-7518-4770-8ee6-05cbff1a0e7b.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/5695356/167017946-62cdb327-77b4-4b48-b899-cdab619b0ae5.png">

Code used to generate the issue:
```
const rainbowTheme = merge(
    lightTheme({
        borderRadius: 'none',
        accentColor: 'black',
    }),
    {
        colors: {
            modalBorder: 'black',
        },
        fonts: {
            body: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        },
    } as Theme,
);
```

**Comment by exception** [comment]
Now that I've had more time to test this, it seems like adding RainbowKit itself starts causing hydration issues all over the app. Not sure what causes this as the errors aren't very specific, but from what I've seen it could be accessing window properties before load, and causing render mismatches.

**Comment by markdalgleish** [comment]
Are you able to share a minimal repro of the other hydration issues you're seeing?

**Comment by markdalgleish** [comment]
Regarding the font issue, I believe it's caused by the use of quote characters. As a short term workaround, can you avoid using these?

**Comment by exception** [comment]
Was able to track down the issue, it was caused by a mismatch using a `useMemo` with the wagmi `useAccount` hook, swapped to a `useEffect` to force it running on the client and seemed to do the fix, seems like an issue with wagmi in the end. 

Regarding fonts, @markdalgleish your suggestion did seem to do the trick. 
Thanks!
