### ISSUE TITLE
[bug] Chain logo not loading 

### ISSUE THREAD

**Issue by YannikSood** [rainbow-me/rainbowkit#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.0.2

### wagmi Version

0.2.17

### Current Behavior

I was displaying the chain selector, and found that the ethereum logo shows up in dev but not in prod.

**Comment by YannikSood** [comment]
Dev environment is Next + React, Deployed using vercel

**Comment by markdalgleish** [comment]
We migrated our icons to use base64 data URLs in v0.1.0. Can you upgrade and see if that fixes your issue?

**Comment by YannikSood** [comment]
That worked! Thanks Mark
