### ISSUE TITLE
[Styles] Tailwind CSS, Create React App

### ISSUE THREAD

**Issue by derekbrown** [rainbow-me/rainbowkit#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.3

### Current Behavior

I currently have a create-react-app application using Tailwind CSS. The RainbowKit styles aren't generated, leading to a "module not found" error. 

### Expected Behavior

Styles to properly load.

### Steps To Reproduce

Generate app from create-react-app 6.2.0. install Tailwind npm:@tailwindcss/postcss7-compat@^2.2.4 with postcss ^7.0.36 and postcss-import ^14.1.0. Install RainbowKit, following instructions.

### Anything else?

While I'm almost certain that this is a build tooling issue (there is a known issue between postcss 8, css loading, and create-react-app), I'm wondering if there is a static-generated CSS file that can be used for cases like this?

**Comment by nickbytes** [comment]
@derekbrown can you please link to a minimal reproducible example?

**Comment by nickbytes** [comment]
Hey @derekbrown, I'm going to close this issue. If you could provide a minimal reproducible example, we're happy to reopen and take a look at it!
