### ISSUE TITLE
[bug] non-MetaMask wallet connectivity issues with Vite JS

### ISSUE THREAD

**Issue by zubinkhavarian** [rainbow-me/rainbowkit#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.4

### Current Behavior

When using rainbowkit with a TypeScript based React app built with ViteJS and standard configuration to setup wallet provider connections any of the non-MetaMask wallet providers fail to work and the console shows a `ReferenceError: global is not defined` error message.

This happens when running Vite JS dev server by running `yarn dev`.
On the production build of the Vite JS app (`yarn build`, `yarn preview`), there's no error messages displayed but the non-MetaMask wallets fail to work as expected and no QR code is displayed.

### Expected Behavior

non-MetaMask wallet providers should function normally and QR code must be displayed.

### Steps To Reproduce

1) Setup a standard Vite JS React app: https://vitejs.dev/guide/#scaffolding-your-first-vite-project
2) Configure a standard wallet setup based on rainbowkit docs: https://www.rainbowkit.com/docs/installation
3) Try connecting to non-MetaMask wallets and observe Chrome console for errors.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/intelligent-surf-n8b7dy

### Anything else?

![ScreenShot 2022-05-06 23 40 47@2x](https://user-images.githubusercontent.com/210675/167236767-50e4deee-533b-4c94-9cff-bb9fc509c958.png)

**Comment by nickbytes** [comment]
@zubinkhavarian thanks for the issue w/ example! Can you take a look at [this issue](https://github.com/vitejs/vite/issues/7257) and see if something here solves your problem?

**Comment by zubinkhavarian** [comment]
> @zubinkhavarian thanks for the issue w/ example! Can you take a look at [this issue](https://github.com/vitejs/vite/issues/7257) and see if something here solves your problem?

@nickbytes, the errors I'm running into are exactly from the issue you shared. The solutions provided there are not conclusive and work to a certain degree and I'm able to get past the initial hurdle but there are more related errors that pop up after that.

From what it looks like, this isn't an issue with rainbowkit and it is safe to close this here. But it would be worth keeping an eye on what the fix for this problem would be and include it in the documentation at some later point since I'd imagine many people will run into the same while using rainbowkit with the vitejs bundler for example.

**Comment by nickbytes** [comment]
Thanks @zubinkhavarian – that's great feedback. We'll be releasing a tool to help scaffold out new projects and will be sure to include a vite example there.
