### ISSUE TITLE
[bug] Brave browser does not detect Metamask

### ISSUE THREAD

**Issue by aeither** [rainbow-me/rainbowkit#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.3

### Current Behavior

With connect a wallet Modal is opened with ConnectButton. Select Metamask as provider in the options, it shows that the brave browser doesn't have Metamask install.
![image](https://user-images.githubusercontent.com/36173828/167245647-d3f4d476-8512-4aaf-a9cc-5e95cc6cc39e.png)

### Expected Behavior

Metamask should pop up to connect with the website.

### Steps To Reproduce

Install Metamask extension in Brave Browser. Click on ConnectButton, select Metamask as provider.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/

### Anything else?

Brave has a shield service enabled by default that block ads. The only way I found to be able to connect to the website with Metamask is by disabling the shield so rainbowkit can detect I have metamask installed. 
![image](https://user-images.githubusercontent.com/36173828/167245814-3487454b-4843-4e64-8081-db08465cf6a2.png)

**Comment by nerderlyne** [comment]
I think this error may be related to the same issue. I get this in brave with `autoConnect` true
<img width="965" alt="autoConnect brave error" src="https://user-images.githubusercontent.com/13903299/167310407-b388c45a-35b0-405d-8fd3-4989217613b4.png">

**Comment by nickbytes** [comment]
@aeither thanks, yea this behavior is happening for me as well.

I believe this is a wagmi issue, as I can reproduce on their [example site](https://wagmi.sh/examples/connect-wallet). I've opened an issue there: https://github.com/tmm/wagmi/issues/434

**Comment by tmm** [comment]
Fixed on the wagmi end https://github.com/tmm/wagmi/issues/434

**Comment by nickbytes** [comment]
This will be fixed in the next release @aeither @nerderlyne
