### ISSUE TITLE
[bug] <ReferenceError: Buffer is not defined>

### ISSUE THREAD

**Issue by jbreite** [rainbow-me/rainbowkit#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.4

### Current Behavior

Can't connect to Rainbow or Wallet Connect and get this in the console: "Uncaught (in promise) ReferenceError: Buffer is not defined". My wallet connects to MetaMask, but when I try to connect to my Rainbow wallet via mobile, the error on my phone was “Error initializing WalletConnect”.

### Expected Behavior

Connect to Rainbow or WalletConnect wallet via mobile. 

### Steps To Reproduce

1. Go to this [link](https://articlepersonalization.web.app) 
2. Try to connect to Rainbow or Wallet Connect

**Comment by jcheese1** [comment]
you'd need to install buffer as walletConnect modal depends on it, and append it to window

**Comment by jbreite** [comment]
Was able to figure it out! Thanks so much for the response!

**Comment by preet-jain** [comment]
> Was able to figure it out! Thanks so much for the response!

How did you solve it ?

**Comment by vacekj** [comment]
> > Was able to figure it out! Thanks so much for the response!
> 
> How did you solve it ?

You need to polyfill `buffer`. create a new file, e.g. `patches.tsx`, import it in your `index.ts` before importing rainbowkit, and add this to the file:

```
import { Buffer } from "buffer";
window.Buffer = Buffer;
```

Fixed the issue for me!
