### ISSUE TITLE
How do you set React state while using rainbowkit?

### ISSUE THREAD

**Issue by d2vin** [rainbow-me/rainbowkit#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1

### wagmi Version

1

### Current Behavior

Currently sending my browser for a loop when I try to set react state in next js. My calling setState before the UI is being returned.

### Expected Behavior

Expected to set state

### Steps To Reproduce

 <ConnectButton.Custom accountStatus="address">
          {({
            account,
            chain,
            openAccountModal,
            openChainModal,
            openConnectModal,
            mounted,
          }) => {
            setAccount(account.address); // set the address state [address, setAddress]
            return (
              <div
                {...(!mounted && {
                  "aria-hidden": true,
                  style: {
                    opacity: 0,
                    pointerEvents: "none",
                    userSelect: "none",
                  },
                })}
              >
                {(() => {
                  if (!mounted || !account || !chain) {
                    return (
                      <button onClick={openConnectModal} type="button">
                        Connect Wallet
                      </button>
                    );
                  }

                  if (chain.unsupported) {
                    return (
                      <button onClick={openChainModal} type="button">
                        Wrong network
                      </button>
                    );
                  }

                  return (
                    <div style={{ display: "flex", gap: 12 }}>
                      <button
                        onClick={openChainModal}
                        style={{ display: "flex", alignItems: "center" }}
                        type="button"
                      >
                        {chain.hasIcon && (
                          <div
                            style={{
                              background: chain.iconBackground,
                              width: 12,
                              height: 12,
                              borderRadius: 999,
                              overflow: "hidden",
                              marginRight: 4,
                            }}
                          >
                            {chain.iconUrl && (
                              <Image
                                alt={chain.name ?? "Chain icon"}
                                src={chain.iconUrl}
                                width="12"
                                height="12"
                              />
                            )}
                          </div>
                        )}
                        {chain.name}
                      </button>

                      <button onClick={openAccountModal} type="button">
                        {account.displayName}
                        {account.displayBalance
                          ? ` (${account.displayBalance})`
                          : ""}
                      </button>
                    </div>
                  );
                })()}
              </div>
            );
          }}
        </ConnectButton.Custom>

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/docs/custom-connect-button

**Comment by wong2** [comment]
What is `setAccount`? 

Btw, please fix your code formatting.

**Comment by pmarais** [comment]
That is really nice, that you can use the `import { useAccount } from 'wagmi'` & `const { data } = useAccount()`

It would be useful to add that to the documentation

**Comment by nickbytes** [comment]
@d2vin I'm closing this issue since it sounds like an application issue, rather than a bug within RainbowKit. Please feel free to jump over to the [Discussions Q&A](https://github.com/rainbow-me/rainbowkit/discussions/categories/q-a) if you are looking for some help from the community.
