### ISSUE TITLE
[bug] When disconnecting from Coinbase Wallet, the account does not update to reflect this.

### ISSUE THREAD

**Issue by GV14982** [rainbow-me/rainbowkit#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.4

### Current Behavior

When I am using the CoinBase wallet and I disconnect from within the CoinBase Wallet app, it does not disconnect in my application state and retains the previously selected Account address.

### Expected Behavior

When I disconnect from the app, have it clear the account within the application state.

### Steps To Reproduce

Connect a  wallet using CoinBase Wallet app, then disconnect inside of the CoinBase app, the account will not become null.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/heuristic-shadow-1i79b6

### Anything else?

I am not sure if this is an issue with Wagmi, or possibly the CoinBase Wallet SDK, but I thought I would post here first.

**Comment by markdalgleish** [comment]
I had a quick look into this and found that this is also reproducible when using wagmi directly — you can try it here: https://wagmi.sh/examples/connect-wallet — so it's at least a wagmi issue, if not an issue with the Coinbase Wallet SDK.

I noticed that when disconnecting from within the Coinbase Wallet app while on the wagmi site, the page refreshes and the connector name within the demo disappears, replaced with a placeholder element. This might help debug things there (cc @tmm)

Before disconnecting in app:

<img width="339" alt="Screen Shot 2022-05-11 at 1 35 09 pm" src="https://user-images.githubusercontent.com/696693/167764243-fa28d17f-e8f7-401b-8c32-0f5a6fa90817.png">

After disconnecting in app:

<img width="301" alt="Screen Shot 2022-05-11 at 1 34 51 pm" src="https://user-images.githubusercontent.com/696693/167764304-9e501a7b-20a3-47fd-bf82-ac5990f68ae0.png">

**Comment by GV14982** [comment]
Cool, thanks for looking into this, I wasn't totally sure where to post, so I figured I'd start at the highest level of abstraction.

Btw, thanks for building this, it makes my life waaaaay easier.
