### ISSUE TITLE
Please add Gnosis integration in the wallet list!

### ISSUE THREAD

**Issue by jcheese1** [rainbow-me/rainbowkit#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.3

### Current Behavior

Would be great if you can add gnosis as a built in

### Expected Behavior

Have gnosis built-in

**Comment by RusseII** [comment]
Would love this!

**Comment by Geczy** [comment]
> Closing this since it's not a bug. We plan on supporting gnosis in the future though!

Any plans @nickbytes ?

**Comment by kasparkallas** [comment]
The Gnosis Safe wagmi connector PR also got merged and package published: https://github.com/safe-global/safe-apps-sdk/pull/324 & https://www.npmjs.com/package/@gnosis.pm/safe-apps-wagmi

**Comment by Geczy** [comment]
> The Gnosis Safe wagmi connector PR also got merged and package published: [safe-global/safe-apps-sdk#324](https://github.com/safe-global/safe-apps-sdk/pull/324) & [npmjs.com/package/@gnosis.pm/safe-apps-wagmi](https://www.npmjs.com/package/@gnosis.pm/safe-apps-wagmi)

this is huge, @nickbytes ?

**Comment by platschi** [comment]
Would love to see this implemented, this is currently the only blocker for us to implement rainbowkit :)

**Comment by platschi** [comment]
Any update on this? @nickbytes

**Comment by jacobedawson** [comment]
this is the one thing holding us back from integrating Rainbow
