### ISSUE TITLE
[bug] Connection Failed on Mobile Safari

### ISSUE THREAD

**Issue by alaaan** [rainbow-me/rainbowkit#350]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.4

### Current Behavior

When connecting to local Next.JS project and clicking rainbow from safari, spins for a while and then displays Connection Failed.  This is on Rinkbey network.  Scanning QR rainbow code connects wallet with no problem.

![IMG_5771](https://user-images.githubusercontent.com/8431313/167478419-e93086af-78c0-443d-8966-d4403c8676b5.PNG)
 

### Expected Behavior

Expect modal in rainbow to show option to connect.

**Comment by nickbytes** [comment]
@alaaan can you please link to a minimal reproducible example?

**Comment by nickbytes** [comment]
@alaaan I'm going to close this issue. If it still seems like a problem and you could provide a minimal reproducible example, we're happy to take a look at it!
