### ISSUE TITLE
Is there a Rainbow Connector to use with wagmi?

### ISSUE THREAD

**Issue by hhff** [rainbow-me/rainbowkit#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.0.0

### wagmi Version

0.0.3

### Current Behavior

I'd like to provide a Rainbow connector to my users, but I am not using Rainbow Kit. I don't believe this library makes it possible for me to import just the wagmi connector.

### Expected Behavior

I'd love to be able to do:

```
import { createClient } from 'wagmi';
import { RainbowWalletConnector } from '@rainbow/rainbowkit';

const client = createClient({
  connectors({ chainId }) {
    return [
      new RainbowWalletConnector({ ... }),
    ]
  }
})

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider client={client}>
      <Component {...pageProps} />
    </Provider>
  );
};
```

### Anything else?

Rainbowkit is awesome! I just wanna build my own UI.

**Comment by nicoglennon** [comment]
heyo @hhff 🤠 currently there is no `RainbowConnector` in wagmi or Rainbowkit. To render the QR codes for Rainbow (and all other WalletConnect wallets) we use wagmi's `WalletConnectConnector` with [the `qrcode` option as `false`](https://github.com/rainbow-me/rainbowkit/blob/209aa43f6adaef8935d23b0e27d9fb661064a160/packages/rainbowkit/src/wallets/walletConnectors/rainbow/rainbow.ts#L27) to grab the uri. We then construct a [custom QR code](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/QRCode/QRCode.tsx) with that uri.

The idea of a `RainbowConnector` is interesting though -- curious what you envision for it exactly?
