### ISSUE TITLE
[bug] Ledger Live wallet connect fails on "Retry"

### ISSUE THREAD

**Issue by olivierlesnicki** [rainbow-me/rainbowkit#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

Latest

### wagmi Version

Latest

### Current Behavior

- Go on https://www.rainbowkit.com/
- Attempt to connect with Ledger Live
- Reject the wallet connect in Ledger Live
- Go back to RainbowKit popup and click retry
- An error message appears:
"Invalid or missing handshakeTopic parameter value"

### Expected Behavior

I should just be provided with the wallet connect confirmation popup in Ledger Live

**Comment by nickbytes** [comment]
@olivierlesnicki this is on desktop, correct?

**Comment by jxom** [comment]
Hi! Are you still able to reproduce this? I tried to reproducing, but no luck! Could have been fixed as a side-effect of a new wagmi/RainbowKit version perhaps?
