### ISSUE TITLE
[bug] Labels not working

### ISSUE THREAD

**Issue by ashwwwin** [rainbow-me/rainbowkit#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.5

### Current Behavior

Can't seem to get labels to work easily, think it's a bug - can anyone confirm whether there's a fix for this? My usage is roughly like this:

```
import { ConnectButton } from '@rainbow-me/rainbowkit'

import '@rainbow-me/rainbowkit/styles.css'

return (<ConnectButton showBalance={false} chainStatus="none" label="Create an account"/>)
```

I ended up going to `static/chunks/pages/_app.js` and changed it manually for now. This isn't an urgent issue but it is annoying and would be nice if it were easier.

**Comment by enesozturk** [comment]
Same here, probably will be fixed with the [last PR](https://github.com/rainbow-me/rainbowkit/pull/379). Waiting for the new release 🤞🏽

**Comment by nickbytes** [comment]
@ashwwwin @enesozturk – it hasn't be released yet. The PR mentioned by @enesozturk only merges it on github. We use [changesets](https://github.com/changesets/changesets) to help manage our versions and publishing. This feature will be available once [this PR](https://github.com/rainbow-me/rainbowkit/pull/309) gets merged + the new version is published to NPM.
