### ISSUE TITLE
[bug] styles.css not found

### ISSUE THREAD

**Issue by maxmandia** [rainbow-me/rainbowkit#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.5

### Current Behavior

Importing rainbow's styles.css file but says the file isn't found. 

### Expected Behavior

Excpected to see the file. 

### Steps To Reproduce

followed the installation, but used yarn instead of npm.

**Comment by nickbytes** [comment]
@maxmandia could you please include a minimal reproducible example?

**Comment by maxmandia** [comment]
I just followed the instructions on the docs in a react application. 

This is the error: ./src/App.tsx
Module not found: Can't resolve '@rainbow-me/rainbowkit/styles.css' in '/Users/maxmandia/repos/gethashchat/src'

**Comment by maxmandia** [comment]
Unfortunately I am not able to share source code as of yet. Not sure if there's a way around this.

**Comment by maxmandia** [comment]
negative. I just re-opened the issue (closed previously because I thought I was being dumb on my end (maybe still am?)). hopefully we can get some insight into the error.

**Comment by nickbytes** [comment]
> I just followed the instructions on the docs in a react application.

@maxmandia there's a lot of different build tooling available to be used by React applications. Without seeing some code, it'll be tough for us to debug what's going on here.

**Comment by maxmandia** [comment]
totally fair! will take a look. thanks for being responsive :)

**Comment by nickbytes** [comment]
Going to close this. If you've got a minimal reproducible example, feel free to reopen.

**Comment by stuckinaboot** [comment]
Same error, I don't even see a styles.css in the latest npm package. I'm using this (successfully) as a workaround `import "@rainbow-me/rainbowkit/dist/index.css"`
