### ISSUE TITLE
[bug] can't make this work with vite

### ISSUE THREAD

**Issue by Dhaiwat10** [rainbow-me/rainbowkit#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.5

### Current Behavior

I setup Rainbowkit following your installation guide and tried rendering the connect button. Nothing is showing up. All I see is a blank page. 

### Expected Behavior

I should be seeing the connect wallet button from rainbowkit. I should also be seeing that piece of text I have added above the connect button in `App.tsx` (codesandbox link below). I am guessing that the page is not being rendered at all / is crashing.

### Steps To Reproduce

1. Go to https://codesandbox.io/s/rainbowkit-vite-demo-l81x9g
2. Wait for the dependencies to get installed
3. You will notice a blank white page in the preview tab

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/rainbowkit-vite-demo-l81x9g

**Comment by zubinkhavarian** [comment]
@Dhaiwat10, in your environment you are not specifying the `ALCHEMY_ID` which is why the provider is failing to initialize. Either provide a key for `ALCHEMY_ID` or remove it from the array and rely on the fallback.

What you currently have in `main.tsx`:
```tsx
const { chains, provider } = configureChains(
  [chain.mainnet, chain.polygon, chain.optimism, chain.arbitrum],
  [apiProvider.alchemy(process.env.ALCHEMY_ID), apiProvider.fallback()]
);
```

Replace with:
```tsx
const { chains, provider } = configureChains(
  [chain.mainnet, chain.polygon, chain.optimism, chain.arbitrum],
  [apiProvider.fallback()]
);
```

Or you can look at this example here:
https://github.com/zubinkhavarian/rainbowkit-vitejs-bug/blob/main/src/main.tsx

**Comment by Dhaiwat10** [comment]
@zubinkhavarian oh ffs... thanks dude! For some reason it works with Next.js when you don't specify an Alchemy ID. TIL
