### ISSUE TITLE
[bug] Wrong Network in Light Theme color has no contrast 

### ISSUE THREAD

**Issue by magiclars-off** [rainbow-me/rainbowkit#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.5

### Current Behavior

`connectButtonTextError` in the Light Theme is white which is not visible with white backgrounds. Is it possible to make it another color?

issue:
![image](https://user-images.githubusercontent.com/62888804/169357132-7e1820e6-92cf-4299-ba83-09f868a3f639.png)

text is there:
![image](https://user-images.githubusercontent.com/62888804/169357366-b1dd1ff1-0c21-48dd-8c09-31a5a4750178.png)

### Expected Behavior

Have a contrasting color such as black

### Steps To Reproduce

use default theme and switch to an unsupported network

**Comment by peduarte** [comment]
Can you specify the exact steps to reproduce this? 

This is what I see in light mode, when i'm on Rinkeby: 
![CleanShot 2022-05-20 at 14 44 13@2x](https://user-images.githubusercontent.com/372831/169530656-98cd01c6-0bfe-4d1c-bd77-e4f31ba4985f.png)

Screen shot taken from our example site: https://rainbowkit-example.vercel.app/

**Comment by paulmars** [comment]
currently looking at this

<img width="376" alt="image" src="https://user-images.githubusercontent.com/8290/169624722-d6fee6ae-4fcd-4cec-a73c-831bab920789.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/8290/169624730-f589d132-3bd7-4ce3-9fe0-37b9f67743d4.png">

**Comment by magiclars-off** [comment]
I closed the PR as it was my own mistake.

I moved the RainbowKitProvider to my Layout.tsx instead of App.tsx such that I can switch rainbowKit theme upon toggling light / dark mode. However I forget to move the style.css to my Layout file thus not adding the styles correctly, resulting in this issue

**Comment by peduarte** [comment]
@magiclars-off ah gotcha, that makes sense 👍 thanks for the clarification!
