### ISSUE TITLE
[bug] `<WagmiProvider />` is deprecated

### ISSUE THREAD

**Issue by ernestognw** [rainbow-me/rainbowkit#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.1

### wagmi Version

0.4.0

### Current Behavior

Many sections across the docs recommend using the `WagmiProvider` within Rainbow Kit usage.
Currently, it behaves correctly, but it was just deprecated and suggested to use `WagmiConfig` instead.

[This is the deprecation notice](https://github.com/tmm/wagmi/commit/1928685bad22e00e9440739a3f65d8a9901716a4#diff-a462dffcb2bf1aa3ce0a57b49b45ef734e52fb3cb2d19b7233341dbd97701905L118)

### Expected Behavior

The deprecation warning should not appear

### Steps To Reproduce

Follow installation steps [here](https://www.rainbowkit.com/docs/installation), and you'll get the deprecation notice if you're using Typescript

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/tmm/wagmi/commit/1928685bad22e00e9440739a3f65d8a9901716a4#diff-1cee8646d2cfba37d6ce6a6e9a8d16f8caba0b99fc3a1ad0cb997ed8c7384d2eR4

**Comment by jxom** [comment]
Will be resolved in #412.
