### ISSUE TITLE
[bug] Connecting a wallet in React example fails on iOS

### ISSUE THREAD

**Issue by cgrayson-ch** [rainbow-me/rainbowkit#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.5

### Current Behavior

When I use the `react` example from the [official repo](https://github.com/rainbow-me/rainbowkit-examples/tree/main/with-create-react-app), connecting to my wallet _in a browser on a laptop_ works as expected but _on iOS_ fails.

Clicking on the "connect" button will open the corresponding wallet app but will not prompt for a pairing request once the app is open. When testing with Metamask it just fails silently. When testing with Rainbow Wallet a text box pops up stating "Error initializing with WalletConnect."

Curiously, both of the `next.js` examples found in the official repo work as expected (on both laptop browser _and_ mobile thick clients).

### Expected Behavior

I expect the "connect" button to successfully open a wallet and initiate the pairing sequence on Android and iOS.

### Steps To Reproduce

1. Clone the official examples repo at https://github.com/rainbow-me/rainbowkit-examples
2. Change directory to the `with-create-react-app` subdirectory
3. Install dependencies (`npm install`)
4. Run the server (`npm start`)
5. On a mobile phone, point your browser to the server spun up in the previous step
6. Click on the "connect" button
7a. Choose Metamask and observe that the Metamask app is opened but no prompt to pair the wallet is received
7b. Choose Rainbow Wallet and observe the error stating that there was a Wallet Connect misconfiguration

**Comment by nickbytes** [comment]
@cgrayson-ch I'm going to close this now. Feel free to re-open and/or reach out if you're still having issues!
