### ISSUE TITLE
[bug] the webpage in the mobile chrome browser and wechat, the wallet pop-up window displays an adaptation error

### ISSUE THREAD

**Issue by 0x3Anthony** [rainbow-me/rainbowkit#450]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

0.2.1

### wagmi Version

0.4.5

### Current Behavior

When opening the webpage in the mobile chrome browser and wechat, the wallet pop-up window displays an adaptation error. The pop-up window should be at the bottom, and now it is centered, and the layout is abnormal.
![image](https://user-images.githubusercontent.com/100060836/171214316-eab661b1-d67c-4586-aa60-b50a833eb94c.png)

### Expected Behavior

This is a screenshot of the mobile terminal of the Safari browser, this UI display is normal.
![image](https://user-images.githubusercontent.com/100060836/171214557-5e4b2239-de65-4885-baf0-d3b045fb952d.png)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/rainbow-me/rainbowkit-examples/tree/main/with-next

**Comment by nickbytes** [comment]
@0x3Anthony thanks for the bug report! Looks like your device isn't being recognized as a mobile device for some reason. Which device are you using? I've got an iPhone and a Samsung A12 – both seem to be showing the intended mobile layout in Chrome's mobile browser.

I don't have wechat, but can download now to see what it looks like there.

**Comment by 0x3Anthony** [comment]
> 
My two iPhones are iPhone11pro max and iPhone6s respectively, and the ios versions are 15.5 and 15.4.1, both of which are the latest versions of ios. The UI layout is abnormal in both the chrome mobile browser and wechat, and the demo code is https://github.com/rainbow-me/rainbowkit-examples/tree/main/with-next, no changes, just preview the demo

**Comment by AkshatGiri** [comment]
This commit fixes the issue on ios chrome - https://github.com/rainbow-me/rainbowkit/commit/2eced212a32e0cb2ceff0ccd0e360f954ec68b08

**Comment by nickbytes** [comment]
Thanks @AkshatGiri – going to close this. Anyone should feel free to re-open if they see this issue again!

**Comment by 0x3Anthony** [comment]
> This commit fixes the issue on ios chrome - [2eced21](https://github.com/rainbow-me/rainbowkit/commit/2eced212a32e0cb2ceff0ccd0e360f954ec68b08)
> 
> I had to update the package to the latest version manually in the `package.json`

wow it's great 🤗
