### ISSUE TITLE
[bug] The mobile terminal (chrome, safari browser) has already installed metamask, and cannot evoke the login in the metamask dapp. At present, it is a problem of jumping to the application market

### ISSUE THREAD

**Issue by 0x3Anthony** [rainbow-me/rainbowkit#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.2.3

### wagmi Version

0.4.5

### Current Behavior

The mobile terminal (chrome, safari browser) has already installed metamask, and cannot evoke the login in the metamask dapp. Currently, it is jumping to the application market such as the AppStore, which is an incorrect interaction
![7DBB30B5-FF18-4DC3-9013-A97D1FA73631_1_201_a](https://user-images.githubusercontent.com/100060836/171840909-e8c0ff6e-f8ee-407a-8848-4a6605b98673.jpeg)
ps.My two iPhones are iPhone11pro max and iPhone6s respectively, and the ios versions are 15.5 and 15.4.1, both of which are the latest versions of ios. 

### Expected Behavior

If metamask has been installed on the mobile terminal, it can directly invoke metamask and complete the login and use in metamask. This kind of experience and interaction is currently common in the industry.
![IMG_3181](https://user-images.githubusercontent.com/100060836/171844353-3872409c-b001-4516-b2c4-45d9fd7ca652.jpg)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/rainbow-me/rainbowkit-examples/tree/main/with-next

**Comment by sashadev-sky** [comment]
Linking a discussion i opened about this too: https://github.com/rainbow-me/rainbowkit/discussions/452

**Comment by nickbytes** [comment]
Going to close this issue as we have some related ones and the team is very focused right now on getting to the bottom of deeplinking issues.
