### ISSUE TITLE
[bug] Disconnecting Coinbase Wallet hydrating error

### ISSUE THREAD

**Issue by LALauw** [rainbow-me/rainbowkit#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.2.3

### wagmi Version

0.4.7

### Current Behavior

Logging into the application using Coinbase wallet works fine. But when disconnecting from the application Nextjs is throwing several errors and switches to client-side rendering instead (see images below for context). 

![image](https://user-images.githubusercontent.com/96945030/171997975-35b78c46-e97b-4787-9158-69b8ab4c8162.png)
![image](https://user-images.githubusercontent.com/96945030/171997985-36cf3115-84fc-45e9-baaa-f55dd485b09c.png)

### Expected Behavior

It shouldn't throw these errors. 

### Steps To Reproduce

- Create a fresh nextjs with typescript project.
- Install dependencies i.e. rainbow-kit, wagmi ^& ethers
- Create a component like shown below: 

````typescript
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import LoggedInComponent from "../components/LoggedInComponent";
import LoginComponent from "../components/LoginComponent";
import Menu from "../components/Menu";

const Home: NextPage = () => {
  const { data: account } = useAccount();
  return (
    <div className="p-5 flex flex-col items-center justify-center bg-neutral-900 w-full h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className="h-[100vh] w-full flex items-center justify-center">
        <div className="w-[95%] h-[95%] bg-neutral-800 rounded-lg border-[2px] border-white/20 p-5">
          {!account && <LoginComponent />}
          {account && <LoggedInComponent />}
        </div>
      </main>
    </div>
  );
};

export default Home;
```` 

- Launch the application > Login using Coinbase Wallet (mobile app) > Then disconnect from the application using the connectbutton or from the app itself. 

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

Couldn't get it working in sandbox with nextjs.
Here is a link anyways: https://codesandbox.io/s/elegant-merkle-ey3s98?file=/pages/index.js

**Comment by nickbytes** [comment]
Hey @LALauw – thanks for checking out RainbowKit! 

This looks like Next.js hydration error, rather than a RainbowKit-specific error. Is there any reason you think this has to do w/ RainbowKit? 

If you're having trouble getting setup, you should try `npm init @rainbow-me/rainbowkit`(or [if you use yarn or pnpm](https://github.com/rainbow-me/rainbowkit/tree/main/packages/create-rainbowkit)). This will scaffold out a RainbowKit + wagmi + Next.js site for you with a working configuration.
