### ISSUE TITLE
Cannot wake up metamask when sending a transaction

### ISSUE THREAD

**Issue by chunsenye** [rainbow-me/rainbowkit#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

"@rainbow-me/rainbowkit": "^0.2.2",

### wagmi Version

    "wagmi": "^0.4.5",

### Current Behavior

After sending the transaction, I have to manually open metamask

### Expected Behavior

After sending a transaction, Metamask opens automatically

### Steps To Reproduce

https://rainbowkit-example-qjw5zn6d2-rainbowdotme.vercel.app/

safari mobilde open the website
connect with Metamsk
send transaction action
After sending the transaction, I have to manually open metamask

### Anything else?

https://rainbowkit-example-qjw5zn6d2-rainbowdotme.vercel.app/

**Comment by chunsenye** [comment]
https://github.com/tmm/wagmi/issues/558
[tmm](https://github.com/tmm) : If you use WalletConnectConnector with qrcode: true, deeplinking works as expected.
<img width="978" alt="image" src="https://user-images.githubusercontent.com/30768615/172397933-2bb970fe-2f0e-44c3-82d5-2c9eaee5e465.png">
it works？

**Comment by chunsenye** [comment]
> [tmm/wagmi#558](https://github.com/tmm/wagmi/issues/558) [tmm](https://github.com/tmm) : If you use WalletConnectConnector with qrcode: true, deeplinking works as expected. <img alt="image" width="978" src="https://user-images.githubusercontent.com/30768615/172397933-2bb970fe-2f0e-44c3-82d5-2c9eaee5e465.png"> it works？

https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/wallets/walletConnectors/metaMask/metaMask.ts

**Comment by markdalgleish** [comment]
This should be fixed in RainbowKit >= [0.2.4](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.2.4).
