### ISSUE TITLE
[bug] Switch network does not allow a change in metamask mobile browser

### ISSUE THREAD

**Issue by tobowers** [rainbow-me/rainbowkit#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.2.1

### wagmi Version

0.4.5

### Current Behavior

You can see this in action at https://boa.larvamaiorum.com. Connect wallet shows "Wrong network" (correctly) and then when you click to switch to the "Crypto Rome Network" it says "confirm in wallet" but there is no confirmation screen or add network, etc.

### Expected Behavior

Expect a wallet dialog to pop up to swtich network. Failing that, more information for the users on what they should do (maybe connection info they have to manually add?)

### Steps To Reproduce

Repro steps are in the "current behavior" section.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://boa.larvamaiorum.com

**Comment by sashadev-sky** [comment]
For me also Rainbow Wallet throws a SwitchNetworkError on mobile (and via walletConnect). The reason it says is because the "network is unsupported". This happens when I try to switch from mainnet to rinkeby (have not tried other testnets). But if I select rinkeby initially it works and if I switch networks from rinkeby to mainnet its ok

**Comment by tobowers** [comment]
bumping this as rainbow wallet just doesn't even *prompt* me to switch when connected. And then the UI gets stuck in the wrong network because there's no option to disconnect in rainbowkit (clicking "Wrong Network" only pulls up the 'confirm in wallet' but there is no place to confirm)

**Comment by nickbytes** [comment]
Thanks for digging into this @sashadev-sky @tobowers.

@sashadev-sky 
> This happens when I try to switch from mainnet to rinkeby

Do you have testnets enabled in the Rainbow app? You can enable these in your settings.

@tobowers I cannot speak to how the Metamask mobile browser works. Could this have something to do w/ the "Crypto Rome Network" not being added as a chain in the app?

**Comment by tobowers** [comment]
> @tobowers I cannot speak to how the Metamask mobile browser works. Could this have something to do w/ the "Crypto Rome Network" not being added as a chain in the app?

Thanks @nickbytes but I would hope that rainbow kit intends on supporting metamask mobile? The chain is added to *our* dapp and the switch network and add to metamask works on desktop, but not on mobile.

However, the following site: https://mainnet.skalenodes.com/ *works* to add networks in metamask mobile.

**Comment by tobowers** [comment]
> Do you have testnets enabled in the Rainbow app? You can enable these in your settings.

I pointed out that it happens with alternative networks not just testnets too.

**Comment by markdalgleish** [comment]
This should be fixed in [wagmi v0.5.1](https://github.com/tmm/wagmi/releases/tag/wagmi%400.5.1) (thanks @tmm 🙏)

RainbowKit doesn't support wagmi v0.5 yet, but we have a [PR in progress](https://github.com/rainbow-me/rainbowkit/pull/542) (thanks @jxom 🙏) so it's not far off.

**Comment by markdalgleish** [comment]
[RainbowKit v0.4.0](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.4.0) is out now with support for wagmi v0.5.

Closing this issue since this should now be fixed, but please feel free to re-open if you're still having trouble.
