### ISSUE TITLE
[bug] Coinbase Wallet not connecting on mobile

### ISSUE THREAD

**Issue by tmwBuidls** [rainbow-me/rainbowkit#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.2.4

### wagmi Version

0.4.12

### Current Behavior

Clicking the Coinbase Wallet icon on mobile does nothing

### Expected Behavior

It opens the coinbase app and connects

### Steps To Reproduce

Install Rainbow Kit with the Coinbase Wallet connector and click the Connect Button, followed by Coinbase.

### Anything else?

A similar thing happens on the rainbowkit website itself, although it manages to open the app it doesn't connect. Unfortunately it's hard to give any helpful errors or context as I can't find any.

**Comment by markdalgleish** [comment]
This seems to be an issue across both mobile and desktop when the app/extension is older than the Coinbase Wallet SDK version. This has been patched in Coinbase Wallet SDK v3.3.0, so you can fix it by ensuring you're on the latest version.

I've opened a PR fixing this on our docs site: #516. In our case I ran `pnpm update @coinbase/wallet-sdk`.

**Comment by markdalgleish** [comment]
I've also submitted a PR to wagmi so that it depends on the patched version of Coinbase Wallet SDK: https://github.com/tmm/wagmi/pull/598.
