### ISSUE TITLE
[bug] Trust Wallet and WalletConenct not connecting

### ISSUE THREAD

**Issue by miekassu** [rainbow-me/rainbowkit#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.3.0

### wagmi Version

0.4.12

### Current Behavior

Scanning Trust Wallet or WalletConnect QR code opens Trust Wallet application, but no connection is made. No any errors is shown.

Navigating to dApp with Trust Wallet in-app browser opens Trust Wallet, but no connection is made. No any errors is shown.

### Expected Behavior

Scanning QR code or opening dApp  in Trust Wallet app would promt request to connect wallet to dApp.

### Steps To Reproduce

Basic example, add Trust and WalletConnect connectors, and try connecting.

**Comment by cattingcat** [comment]
I have the same issue. But it throws exception immediately after scanning QR
`browser.ts:44 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'importKey')
    at browser.ts:44:11
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at n (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at Jt (163.356e3128.chunk.js:1:51456)`

**Comment by cattingcat** [comment]
Also It seem that it is broken only im prod build. When I start locally everything is ok

**Comment by markdalgleish** [comment]
I haven't been able to reproduce this on desktop (via QR code), in mobile Safari via WalletConnect, and in Trust's in-app browser. Are you still experiencing this issue? If so, are you able to share a minimal repro?

**Comment by miekassu** [comment]
> Also It seem that it is broken only im prod build. When I start locally everything is ok

I can also confirm this. @markdalgleish did you try build version?

**Comment by cattingcat** [comment]
Well, I tried to connect via WalletConnect (1inch wallet) to https://www.rainbowkit.com/ and it is broken sometimes.
On my app with "@rainbow-me/rainbowkit": "latest", it is still broken on prod build with the same error in logs:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'importKey')
    at browser.ts:44:11
    at f (main.76f83b50.js:sourcemap:2:1762807)
    at Generator._invoke (main.76f83b50.js:sourcemap:2:1762560)
    at Generator.next (main.76f83b50.js:sourcemap:2:1763170)
    at n (main.76f83b50.js:sourcemap:2:1758076)
    at s (main.76f83b50.js:sourcemap:2:1758279)
    at main.76f83b50.js:sourcemap:2:1758338
    at new Promise (<anonymous>)
    at main.76f83b50.js:sourcemap:2:1758219
    at Ft (browser.ts:40:8)
```

**Comment by markdalgleish** [comment]
@cattingcat You said WalletConnect on https://rainbowkit.com is broken sometimes — is the same error message you've shared here, or unrelated?

**Comment by markdalgleish** [comment]
@miekassu I can connect scanning the Trust Wallet QR code on https://rainbowkit.com and https://rainbowkit-example.vercel.app which are both prod builds.

**Comment by cattingcat** [comment]
> @cattingcat You said WalletConnect on https://rainbowkit.com is broken sometimes — is it the same error message you've shared here, or unrelated?

I think it is unrelated, because it just didn't work few times, but without errors in console

**Comment by nickbytes** [comment]
I also cannot reproduce this. If you can provide more details or provide steps to reliably reproduce this issue, feel free to drop a comment and we can reopen!
