### ISSUE TITLE
[bug] Latest update breaks 'sign message' flows on iOS

### ISSUE THREAD

**Issue by JamieLottering** [rainbow-me/rainbowkit#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.3.1

### wagmi Version

0.4.12

### Current Behavior

When calling `signMessageAsync` from `wagmi` while being connected to Rainbow Wallet user is redirected to the interstitial page and replaces the previous url. This cancels the promise that was awaiting the response from `signMessageAsync` on the previous page, making it impossible to complete user actions that require authentication through signing messages.

Video:

https://user-images.githubusercontent.com/134010/174201761-54bef23d-b783-4564-afcb-c523c40b9ed4.mov

### Expected Behavior

User is not navigated to interstitial page. 

### Steps To Reproduce

https://user-images.githubusercontent.com/134010/174201801-f549820d-dc3d-4173-9288-7736e6094619.mov

### Anything else?

Happens on Chrome, Firefox, and Safari for iOS,

**Comment by enesozturk** [comment]
Is this fixed on new releases? I see [v0.3.3 notes](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.3.3) but it doesn't look related to this.
