### ISSUE TITLE
[bug] Connect Modal Not Dismissed After Connecting to Rainbow When App Is Within WebView (React Native)

### ISSUE THREAD

**Issue by nickcherry** [rainbow-me/rainbowkit#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.3.4

### wagmi Version

0.4.12

### Current Behavior

When trying to connect to Rainbow via a web app embedded in a React Native [webview](https://github.com/react-native-webview/react-native-webview), the Rainbow app will launch with the expected connect prompt, then return to the native app after the user connects, but the connect modal will still be present. Even when we force the container component to rerender when the window regains focus, `useAccount` will not return a connected account.

https://user-images.githubusercontent.com/229477/175085019-eb6adbfa-8ad5-4021-9fa2-dd420cec7ec8.mov

### Expected Behavior

We would expect the modal to be dismissed when the user returns to the native/web app and for `useAccount` to return a valid account.

### Steps To Reproduce

1. In a [React Native app](https://github.com/nickcherry/rainbowkit-test-mobile-2), launch a webview that points to https://funny-bombolone-7101cc.netlify.app/ (the source of which can be found [here](https://github.com/nickcherry/rainbowkit-test-2)).
2. Press "Connect Wallet"
3. Choose Rainbow
4. From Rainbow, connect to the web app
5. After being redirected to the native app, observe that the modal has not been dismissed.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/nickcherry/rainbowkit-test-mobile-2

**Comment by nickbytes** [comment]
Thanks for the issue here @nickcherry – I really appreciate how much detail and time you put into this. 

We'll take a look at this this week. We haven't spent much time working w/ RainbowKit in React Native, but this is super exciting.

**Comment by nickcherry** [comment]
Update: I _think_ the issue has to do with [redirects vs opening new windows](https://github.com/rainbow-me/rainbowkit/pull/479/files#r907599654). https://github.com/nickcherry/rainbowkit-test-mobile-2/pull/1

**Comment by markdalgleish** [comment]
In [v0.3.6](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.3.6) we shipped a fix related to webviews leaving blank tabs behind that may be related to this. Have you updated since then and, if so, are you still experiencing this issue?

**Comment by nickcherry** [comment]
Yep, working great now, thanks @markdalgleish! Good to close.

**Comment by smolleyes** [comment]
hi ! no way to share your webview code 😅? 

thanks!
