### ISSUE TITLE
[bug] Cannot Connect to Coinbase Wallet on Mobile

### ISSUE THREAD

**Issue by nickcherry** [rainbow-me/rainbowkit#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.3.4

### wagmi Version

0.4.12

### Current Behavior

When a user tries to connect to Coinbase Wallet from mobile Safari, the Coinbase Wallet app will launch and take the user to the web app via Coinbase Wallet's dapp browser. Then, if the user tries to connect to Coinbase Wallet from within the dapp browser, nothing will happen.

https://user-images.githubusercontent.com/229477/175171435-e33557eb-5884-4930-82f5-0f348b74d7db.mov

### Expected Behavior

Ideally, when trying to connect to Coinbase Wallet from mobile Safari, Coinbase wallet would prompt the user to connect without needing them to redundantly select Coinbase Wallet again from Wallet's dapp browser. But at the very least, it should be possible to connect to Coinbase Wallet from within Coinbase Wallet's dapp browser.

### Steps To Reproduce

1. Navigate to https://funny-bombolone-7101cc.netlify.app/
2. Try to connect to Coinbase Wallet
3. Once Coinbase Wallet launches the web app in its dapp browser, try again to connect to Coinbase Wallet

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/nickcherry/rainbowkit-test

**Comment by markdalgleish** [comment]
Looks like you're running into this issue: https://github.com/rainbow-me/rainbowkit/issues/507

Your lock file says you're running v3.2.0 of `@coinbase/wallet-sdk`. Updating to v3.3.0 should fix it.

If updating fails to fix it, please feel free to re-open this issue.

**Comment by nickcherry** [comment]
Ah, you are right! Forcing `@coinbase/wallet-sdk` to resolve to `3.3.0` did the trick. Thank you!
