### ISSUE TITLE
In Coinbase in-app browser, it doesn't trigger login confirmation when visiting showtime.xyz

### ISSUE THREAD

**Issue by nickbytes** [rainbow-me/rainbowkit#531]
From @enesoturk

```
Hi @markdalgleish, thanks for the response, I will continue to follow the issues you opened. 

Additionally, Coinbase has a weird behavior when trying to log in. It opens the Coinbase Wallet app but there is an in-app browser, opening the `showtime.xyz` on it, and triggers nothing. When I try to log in with Coinbase again in that in-app browser, it doesn't trigger login confirmation.

Steps to reproduce: 
- Go [showtime.xyz](https://showtime.xyz/) on mobile web
- Connect Wallet
- Coinbase, it will open Coinbase in-app browser
- Again, login -> Connect Wallet > Coinbase
- Does nothing.

_Originally posted by @enesozturk in https://github.com/rainbow-me/rainbowkit/issues/521#issuecomment-1162890857_
```

**Comment by markdalgleish** [comment]
@enesozturk Sounds like you're hitting this issue with Coinbase Wallet SDK: https://github.com/rainbow-me/rainbowkit/issues/507.

Looking at [showtime-frontend/yarn.lock](https://github.com/showtime-xyz/showtime-frontend/blob/staging/yarn.lock) I can see you're on v3.2.0 of `@coinbase/wallet-sdk`. If you update to v3.3.0 it should fix the problem. If not, please feel free to re-open the issue.

**Comment by enesozturk** [comment]
re: https://github.com/rainbow-me/rainbowkit/issues/521#issuecomment-1163839469

Thanks for the reply guys. I tried [https://rainbowkit-example.vercel.app/](https://rainbowkit-example.vercel.app/ ) but it seems the same on it. Here is a video recording. Also checked Coinbase Wallet app updates but looks up to date already.

https://user-images.githubusercontent.com/19428358/175231919-baaf701a-c00e-4c6e-91bf-931b0021e0f1.MP4

**Comment by markdalgleish** [comment]
I might be missing something, but isn't this expected behaviour? It's taking you to Coinbase Wallet's in-app browser and then connecting via its injected connector. What behaviour were you expecting instead?

**Comment by enesozturk** [comment]
Shouldn't it redirect me to the actual app just like Rainbow or MetaMa*k does? Think like I'm a user of Rainbow-Example app, I wanted to log in to the app by using Coinbase Wallet. It opened the Rainbow-Example in the in-app browser of Coinbase mobile app. So after that? Will I continue to RE on it?

**Comment by markdalgleish** [comment]
>Shouldn't it redirect me to the actual app just like Rainbow or MetaMa*k does? Think like I'm a user of Rainbow-Example app, I wanted to log in to the app by using Coinbase Wallet. It opened the Rainbow-Example in the in-app browser of Coinbase mobile app. So after that? Will I continue to use RE on it?

Yep, that's right. As far as I understand they don't let you connect on mobile within your regular browser.
