### ISSUE TITLE
[bug] Connector is reqiored

### ISSUE THREAD

**Issue by AnishDe12020** [rainbow-me/rainbowkit#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.3.5

### wagmi Version

0.5.0

### Current Behavior

Not able to connect wallet, "connect is required" error in console
![image](https://user-images.githubusercontent.com/63192115/175929305-ed684dd1-0e1f-4e37-b758-4a3bd3cea4f9.png)

### Expected Behavior

Should be able to connect the wallet without any error

### Steps To Reproduce

Make a new nextjs typescript app, follow the [official installation guide](https://www.rainbowkit.com/docs/installation) (manual setup)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://gist.github.com/AnishDe12020/c25d9e870277b1be376443b974f703c3

### Anything else?

Works fine with older version (rainbowkit v0.1.0, wagmi v0.3.5)

Gist has `_app.tsx` of nextjs project (main rainbowkit logic). Rest is just the connect button component

**Comment by jxom** [comment]
RainbowKit [does not support `wagmi@0.5.x`](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/package.json#L45) just yet – will be soon though! For now, you will need to use `wagmi@0.4.x`.

**Comment by maximedegreve** [comment]
I'm having the same issue and I'm dependant on that release for the onConnect callback fixes.

**Comment by peduarte** [comment]
@maximedegreve in the works https://github.com/rainbow-me/rainbowkit/pull/542 🔧
