### ISSUE TITLE
Can't get passed modal. "Connector is required."

### ISSUE THREAD

**Issue by salieflewis** [rainbow-me/rainbowkit#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.3.6

### wagmi Version

0.5.2

### Current Behavior

Can't get RainbowKit to work with a 'yarn create react-app' template

<img width="719" alt="Screen Shot 2022-06-27 at 8 32 55 PM" src="https://user-images.githubusercontent.com/37086973/176061967-be702e70-68aa-4b03-8733-ccd434f1b8cd.png">

After the modal appears, I click on the different wallet clients and the error shown above appears.

**Comment by jxom** [comment]
RainbowKit [does not support wagmi@0.5.x](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/package.json#L45) just yet – [will be soon though](#542)! For now, you will need to use wagmi@0.4.x.
