### ISSUE TITLE
[bug] "automatically connect to first configured chain" keeps invoking annoying network switch 

### ISSUE THREAD

**Issue by kasparkallas** [rainbow-me/rainbowkit#563]
### RainbowKit Version

0.4.0

### wagmi Version

0.5.5

### Current Behavior

In the app I have, the network can be chosen before connecting the wallet, i.e. the user can interact with the app and leave the wallet connection for last. When user finally connects then a switch to the first chain is always triggered which can be completely off from what was chosen in the app. When the user doesn't abide to the network switch then **the wallet is not connected**.

In a nutshell, `wagmi` makes it possible to pass in the Chain ID when using `useConnect` _but_ RainbowKit hides this and instead forces a switch to the arbitrary first network.

### Expected Behavior

* Not hide the features that wagmi exposes -- make it possible to pass in Chain ID when connecting with RainbowKit
* Not _force_ a network switch at all when connecting with RainbowKit

### Anything else?

Issue introduced in this PR: https://github.com/rainbow-me/rainbowkit/pull/511

**Comment by 0xbhoori** [comment]
+1. It should be possible to connect to any chain passed in the `chains` array. At least, it should be given as an option.
