### ISSUE TITLE
[bug] Encountered two children with the same key

### ISSUE THREAD

**Issue by LALauw** [rainbow-me/rainbowkit#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.1

### wagmi Version

0.5.6

### Current Behavior

Opening connect wallet modal gives the following error & not able to connet wallet: 

Warning: Encountered two children with the same key, `walletConnect`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
![image](https://user-images.githubusercontent.com/32265116/177355448-6f14d596-9fef-4d30-9851-ff278279f8c4.png)

How I implemented the code: 
````typescript
const Home: NextPage = () => {
const { chains, provider } = configureChains(
    [chain.polygon, chain.polygonMumbai],
    [publicProvider()]
  );

  const { connectors } = getDefaultWallets({
    appName: "name",
    chains,
  });

  const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
  });

   return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider
        chains={chains}
        theme={darkTheme()}
        showRecentTransactions={true}
      >
<div></div>
        </RainbowKitProvider>
    </WagmiConfig>
);
};

//Connect button
 <ConnectButton
              chainStatus="icon"
              accountStatus={{
                smallScreen: "address",
                largeScreen: "full",
              }}
              showBalance
            />
```` 

### Expected Behavior

Being able to connect my wallet using Rainbowkit. 

### Steps To Reproduce

Follow my code example and run it with nextjs - Typescript. 
I ran it with nextjs 12.2.0 and tailwindcss in a fresh project, same error.

One more thing I noticed: 
When I run `npm run build` into `npm run start` I do not get the error. Only when running `npm run dev`.

**Comment by tmm** [comment]
You need to either:
- call `configureChains`, `getDefaultWallets`, and `createClient` outside of your component body and in the global scope 
- or make sure it is stable across renders

**Comment by LALauw** [comment]
> You need to either:
> 
> * call `configureChains`, `getDefaultWallets`, and `createClient` outside of your component body and in the global scope
> * or make sure it is stable across renders (e.g. `React.useMemo`)

Hmm I moved it to my _app.tsx which is at the root. But same result. 
`````typescript
    import "../styles/globals.scss";
import type { AppProps } from "next/app";
import "@rainbow-me/rainbowkit/styles.css";
import {
  darkTheme,
  getDefaultWallets,
  RainbowKitProvider,
} from "@rainbow-me/rainbowkit";
import { chain, configureChains, createClient, WagmiConfig } from "wagmi";
import { publicProvider } from "wagmi/providers/public";

function MyApp({ Component, pageProps }: AppProps) {
  const { chains, provider } = configureChains(
    [chain.polygon, chain.polygonMumbai],
    [publicProvider()]
  );

  const { connectors } = getDefaultWallets({
    appName: "name",
    chains,
  });

  const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
  });

  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains} showRecentTransactions={true}>
        <Component {...pageProps} />
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

export default MyApp;
````

**Comment by tmm** [comment]
Move these calls outside of `MyApp` and it will work.

**Comment by LALauw** [comment]
> Move these calls outside of `MyApp` and it will work.

Painful mistake on my end there, yes it worked! Took me too long to see that mistake 😪
