### ISSUE TITLE
[bug] react example on compile giving warnings

### ISSUE THREAD

**Issue by AmanRaj1608** [rainbow-me/rainbowkit#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.1

### wagmi Version

0.5.3

### Current Behavior

Downloaded the react examples code and complied.
Getting lots of warnings on compiling `yarn start`

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/42104907/177540256-4b7d9d98-fe3f-4611-8cf0-214778bd4dea.png">

### Steps To Reproduce

node version - v16.14.2
node version - 8.5.0

```
git download - https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app
yarn
yarn start
```

**Comment by markdalgleish** [comment]
These warnings are a known issue for create-react-app users, not something that we can control: https://github.com/facebook/create-react-app/discussions/11767.

The build is still completing successfully though so it seems you can safely ignore them.
