### ISSUE TITLE
[aria-*] attributes do not match their roles

### ISSUE THREAD

**Issue by williamlmao** [rainbow-me/rainbowkit#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.2

### wagmi Version

0.5.9

### Current Behavior

Lighthouse report is flagging the ETH icon in Rainbowkit for an accessibility issue: 

[aria-*] attributes do not match their roles
Each ARIA `role` supports a specific subset of `aria-*` attributes. Mismatching these invalidates the `aria-*` attributes. [Learn more](https://web.dev/aria-allowed-attr/?utm_source=lighthouse&utm_medium=devtools).

![Screen Shot 2022-07-16 at 1 44 24 PM](https://user-images.githubusercontent.com/55903529/179371439-c0a7c78d-30a1-41d4-98dd-64f597f58f37.png)

### Steps To Reproduce

Run chrome devtools lighthouse report on a site with Rainbow kit installed, after wallet connection

**Comment by robgleason** [comment]
This is interesting. I am trying to reproduce your results. I created the Rainbowkit React App and deployed it to Netlify. I also ran a Lighthouse report. I got it passed audit, and I'll attach the results. Would you be able to share a website that you had this issue?
![rainbowwalletbug](https://user-images.githubusercontent.com/46877134/180633032-8f610d17-e3cf-4fe8-998b-2cc7ff65e5b0.PNG)

**Comment by williamlmao** [comment]
Hey @robgleason, sorry for the late response here. Here's my site - [Repo](https://github.com/williamlmao/nextjs-dapp-starterkit  ) | [Deployment](https://nextjs-dapp-starterkit.vercel.app/) 

Hm.. this IS interesting. I'm struggling to think of a reason why our reports differ. You can see in my repo that I'm not doing anything special with Rainbow Kit. Just doing the basic install steps. No custom theme or anything. You'll find `<ConnectWallet/>` in /components/Header. 

All that being said, this isn't a big problem and if it's not an issue on your end there's no need to concern yourself with it unless we see more reports of similar issues. For now I can also just use a custom theme and display "ETH" instead.
