### ISSUE TITLE
[bug] Can't remove mainnet from supported chains when configured via `configureChains`

### ISSUE THREAD

**Issue by wottpal** [rainbow-me/rainbowkit#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.5

### wagmi Version

0.6.0

### Current Behavior

Situation: We do not support mainnet in our dApp, but we need to include an RPC-provider in `configureChains` to have ens-name & avatar lookups working properly. So we do something like this:

```ts
export const supportedChains: Chain[] = allChains.filter((chain) =>
  env.supportedChains.includes(chain.id)
)
export const { chains, provider } = configureChains(
  Array.from(new Set([chain.mainnet, ...supportedChains])),
  // ...
```

Now we don't want rainbowkit to offer the mainnet-option in its chain-switcher menu (which it would obviously do if we just use the exported `chains` object). This is why we do filter the `chains` object (again) after running through `configureChains` via:

```ts
export const supportedWagmiChains: Chain[] = chains.filter((chain) => {
  return env.supportedChains.includes(chain.id)
})
```

And using it like:

```tsx
<RainbowKitProvider chains={supportedWagmiChains}>…</RainbowKitProvider>
```

But that doesn't solve the problem. "Ethereum" is still shown as an option in the chain-switch menu (without icon though):

<img width="400" alt="Screen Shot 2022-08-02 at 11 58 28" src="https://user-images.githubusercontent.com/3930150/182347919-af446f21-28f5-4c22-be83-f575f9093ef4.png">

### Expected Behavior

1. If a chain is not passed to `RainbowKitProvider`, fully ignore it.
2. But more importantly, offer an easy way to provide a mainnet RPC for ens-lookup without requiring mainnet to be supported.

### Anything else?

Thanks in advance as always ❤️

**Comment by wottpal** [comment]
Any ideas @markdalgleish @jxom @nicoglennon? Or can I provide any more information?

**Comment by markdalgleish** [comment]
@wottpal Just opened a PR to support this!

**Comment by wottpal** [comment]
Awesome, thanks! 

The `useMainnet` function looks good to me, but of course, you should wait for more sophisticated reviewers 🤓

**Comment by markdalgleish** [comment]
You can now filter chains before passing them to RainbowKit in [v0.4.8](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.4.8).
