### ISSUE TITLE
[bug] signing in mobile wallet connect (metamask) pops the app store

### ISSUE THREAD

**Issue by tobowers** [rainbow-me/rainbowkit#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.1

### wagmi Version

0.5.3

### Current Behavior

see: https://github.com/cowprotocol/cowswap/issues/510 - there are some work arounds, but it gets complicated because rainbow is a wrapper around wagmi which is a wrapper around wallet connect.

Requesting the signer to do things, will open metamask, but then open the appstore.

### Expected Behavior

Expected to pop the wallet, then return to the app

### Steps To Reproduce

sign anything on mobile transactions or text. see: https://github.com/MetaMask/metamask-mobile/pull/4167 https://github.com/cowprotocol/cowswap/issues/510

**Comment by tobowers** [comment]
So as the instructions say there if you do any http requests at all (including to rpc servers, etc) then you will get the app store, but if the very first request is to do the browser thing then this will work.

**Comment by markdalgleish** [comment]
As you mentioned, this is an unavoidable issue with app linking via WalletConnect on iOS. I recently added some documentation to the WalletConnect site that goes into more detail about this issue and explains how to manage it: https://docs.walletconnect.com/mobile-linking#ios-app-link-constraints
