### ISSUE TITLE
[bug] 404 on Learn More link

### ISSUE THREAD

**Issue by niratodev** [rainbow-me/rainbowkit#637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.5

### wagmi Version

0.6.0

### Current Behavior

"Learn More" links directs users to a page that doesn't exist

### Expected Behavior

Correct link

### Steps To Reproduce

Click on the Learn More link

**Comment by niratodev** [comment]
![image](https://user-images.githubusercontent.com/73018676/183221553-2a5e4de8-1a6f-4088-ab4d-894261591778.png)

**Comment by markdalgleish** [comment]
I wasn't able to reproduce this. Are you still experiencing the issue, or was it a temporary outage?

**Comment by niratodev** [comment]
@markdalgleish Yeah, looks like it was temporary. Thanks.
