### ISSUE TITLE
[bug] <title>

### ISSUE THREAD

**Issue by Mr-Beast-bpsr** [rainbow-me/rainbowkit#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.5

### wagmi Version

0.6.1

### Current Behavior

Some time's after connectiing the wallet i get connector not found issue. Which is in development as well as in production.

### Expected Behavior

Transaction to happen without the connector issue.

### Steps To Reproduce

Create a next js app , connect wallet and make a transaction with contract.

**Comment by markdalgleish** [comment]
Are you able to share a minimal repro of this issue?

**Comment by jxom** [comment]
This issue has been temporarily closed due to the lack of a minimal reproducible example. Please upload a minimal reproducible example (you can use [this template](https://codesandbox.io/s/rainbowkit-nextjs-gz890p)) and then we will reopen this issue. :)
