### ISSUE TITLE
[bug] CodeSandbox link not working

### ISSUE THREAD

**Issue by wong2** [rainbow-me/rainbowkit#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.2

### wagmi Version

0.5.9

### Current Behavior

The CodeSandbox examples in README can't connect wallet successfully

### Expected Behavior

Connect successfully

### Steps To Reproduce

* Open the Sandbox links in README: https://codesandbox.io/s/rainbowkit-create-react-app-1vwx1r
* Click connect.
* Get `Error connecting, please retry!`
* Console logs `Error: No wagmi client found. Ensure you have set up a client: https://wagmi.sh/docs/client`

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/rainbowkit-create-react-app-1vwx1r

**Comment by jxom** [comment]
Hey there!

I am going to open up an issue on wagmi for this as this is not specific to RainbowKit 🙏 

We are aware of this issue with wagmi though, and we hope to have a fix very soon!
