### ISSUE TITLE
[bug]: Error: No wagmi client found.

### ISSUE THREAD

**Issue by Geczy** [rainbow-me/rainbowkit#647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.6

### wagmi Version

0.6.2

### Current Behavior

Error: No wagmi client found. Ensure you have set up a client: [wagmi.sh/docs/client](https://wagmi.sh/docs/client)
at getClient (getProvider-e3d84eba.esm.js?dc91:1000:1)
at MetaMaskConnector.connect (wagmi-core-connectors-metaMask.esm.js?6ab8:102:147)
at async connect (wagmi-core.esm.js?2d30:257:1)
window.console.error @ next-dev.js?4cd6:20

### Expected Behavior

No error	

### Steps To Reproduce

just try login with metamask

<img width="765" alt="image" src="https://user-images.githubusercontent.com/1036968/184370110-9052cd0f-56dc-41b2-b25b-3e243e170ce1.png">

### Anything else?

it switches my network but if im on the right network this error will show

**Comment by markdalgleish** [comment]
Could you please share a minimal repro?

**Comment by jxom** [comment]
This issue has been temporarily closed due to the lack of a minimal reproducible example. Please upload a minimal reproducible example (you can use [this template](https://codesandbox.io/s/rainbowkit-nextjs-gz890p)) and then we will reopen this issue. :)
