### ISSUE TITLE
[bug] example/with-next-mint-nft freezes when selecting coinbase wallet

### ISSUE THREAD

**Issue by missphyrgames** [rainbow-me/rainbowkit#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.8

### wagmi Version

0.6.0

### Current Behavior

In the `example/with-next-mint-nft` project, I run `pnpm dev` in my terminal and head to localhost:3000. I click the 'Connect Wallet' button and choose the Coinbase wallet option. This makes the page freeze. 

I also tried this in the `example/with-next` project which works fine and I can connect with the Coinbase Wallet.

### Expected Behavior

The page should not freeze and I should be able to click the mint button to mint an nft.

### Steps To Reproduce

Click 'Connect Wallet' button and choose Coinbase Wallet.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/hungry-phoebe-f4sddj?file=/package.json

### Anything else?

I was able to reproduce this error both on my local machine and on codesandbox.

**Comment by shrugs** [comment]
I've also noticed coinbase's wallet royally fucking up my website's performance, and it's really hard to track down

**Comment by jxom** [comment]
Hey! This one can be fixed by upgrading to the latest version of `wagmi`. Let me know if there are any other issues. :)
