### ISSUE TITLE
[bug] Can't connect with an injected wallet

### ISSUE THREAD

**Issue by grachyov** [rainbow-me/rainbowkit#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

unknown

### wagmi Version

unknown

### Current Behavior

I have an enabled injected wallet Tokenary, which is added to wagmi.

However, there is no "injected wallet" option on [Flash3](https://flash3.io/#/unclaimed) and [Lyra](https://app.lyra.finance/trade/eth).

Hence, I can't connect to these dapps.

### Expected Behavior

Suggest the "injected wallet" option when there is one.

### Steps To Reproduce

Enable [Tokenary extension for Safari](https://tokenary.io/get), try connecting to [Flash3](https://flash3.io/#/unclaimed) or [Lyra](https://app.lyra.finance/trade/eth).

**Comment by jxom** [comment]
We have an "Injected Wallet" option by default in RainbowKit in our `getDefaultWallets` util. However, I'd say that it is pretty likely that Flash3 & Lyra have configured RainbowKit with custom wallets, and have not included an injected option. 
Let me reach out and get an answer for you! 🙏

**Comment by grachyov** [comment]
Hey @jxom thanks for the response!
Wish it was impossible to disable an injected option.
This way dapps won't be able to accidentally exclude users who have an injected wallet installed.
What do you think?

**Comment by jxom** [comment]
It's a very good point. I can bring it up with the team! 😊
