### ISSUE TITLE
[bug] Unable to connect to hardhat wallet

### ISSUE THREAD

**Issue by akcgjc007** [rainbow-me/rainbowkit#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.0

### wagmi Version

0.6.4

### Current Behavior

Throwing error while trying to connect with hardhat:

![Screenshot from 2022-08-24 10-14-48](https://user-images.githubusercontent.com/56300182/186331100-2f65b547-9626-419f-83f2-732ba89b5bdd.png)

### Expected Behavior

It should connect with hardhat local node.

### Steps To Reproduce

```
"@rainbow-me/rainbowkit": "^0.5.0",
"wagmi": "^0.6.4",
```
Adding `chain.hardhat` in configured chains, this error is thrown.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/rainbowkit-nextjs-forked-f49oib

**Comment by jxom** [comment]
Hey! You can fix this by adding your Hardhat network into MetaMask. :)

https://support.chainstack.com/hc/en-us/articles/4408642503449-Using-MetaMask-with-a-Hardhat-node

Let me know if you have any issues setting this up!
