### ISSUE TITLE
[bug] Rainbow kit modal does not close after connecting wallet.

### ISSUE THREAD

**Issue by kunalalite** [rainbow-me/rainbowkit#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.4.5

### wagmi Version

^0.6.0

### Current Behavior

I am using rainbowkit to onboard users using to my dapp using metamask wallet. When I select metamask in the connect wallet modal, The account is connected, as I can see the address in the connect wallet button. Although, the connect modal does not close and keeps prompting "Waiting for connection".

### Expected Behavior

The connect modal should close once metamask or any other wallet is connected.

### Steps To Reproduce

Connect wallet using metamask.

**Comment by jlevers** [comment]
I'm also running into this issue. In my case, if I close the modal while it's hanging on `Waiting for connection`, the `ConnectButton` correctly shows my wallet/balance...but as soon as I refresh the page, I have to try to connect again, and the situation repeats itself.

**Comment by liushaozhen** [comment]
Same question, waiting for reply

**Comment by jxom** [comment]
Hi. Can you please upload a minimal reproducible example? [Here is a template CodeSandbox.](https://codesandbox.io/s/rainbowkit-nextjs-gz890p)
