### ISSUE TITLE
[bug] <I can't able to connect walletconnect on desktop with my mobile>

### ISSUE THREAD

**Issue by Aun-Shahbaz-Awan** [rainbow-me/rainbowkit#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.4.1

### wagmi Version

^0.5.6

### Current Behavior

It shows the QR code of walletconnect wallet but can't connect after scanning from mobile.

### Anything else?

Minimal Reproducible In Private I can't able to share. so please cooperate.

**Comment by Aun-Shahbaz-Awan** [comment]
Also, it through 81 warnings at the start of different packages like:

Failed to parse source map from '~/node_modules/json-rpc-engine/src/mergeMiddleware.ts' file: Error: ENOENT: no such file or directory, open '~/node_modules/json-rpc-engine/src/mergeMiddleware.ts'

Failed to parse source map from '~/node_modules/@walletconnect/jsonrpc-utils/src/index.ts' file: Error: ENOENT: no such file or directory, open '~/node_modules/@walletconnect/jsonrpc-utils/src/index.ts

My Project is in React.Js.

**Comment by jxom** [comment]
This issue has been temporarily closed due to the lack of a minimal reproducible example. Please upload a minimal reproducible example (you can use [this template](https://codesandbox.io/s/rainbowkit-nextjs-gz890p)) and then we will reopen this issue. :)
