### ISSUE TITLE
[bug] Can't resolve styles.css

### ISSUE THREAD

**Issue by JClutch** [rainbow-me/rainbowkit#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

"^0.5.0"

### wagmi Version

"^0.6.4"

### Current Behavior

<img width="468" alt="Screen Shot 2022-08-25 at 5 29 15 PM" src="https://user-images.githubusercontent.com/25985512/186772830-f6071aed-282f-4ee7-9e6f-8e70d81026ec.png">

### Expected Behavior

Trying to install the rainbowkit for desktop/web app

Everything goes well except for the error I get when trying to import the styles. If I don't import the styles functionally it works but w/o the appropriate styling it's unusable

Double checked my webpack w/ other css modules and those imports work fine

```
  module: {
    rules: [{
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.(png|woff|woff2|eot|ttf|svg)$/,
        loader: 'url-loader?limit=100000'
      },
      {
        test: /\.scss$/,
          use: [{
            loader: "style-loader"
          }, {
            loader: "css-loader" 
          }, {
            loader: "sass-loader"
          }]
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      }
    ]
  },
```

### Steps To Reproduce

Just followed the instructions listed here https://www.rainbowkit.com/docs/installation

Here's the boilerplate codebase I'm using https://github.com/JClutch/simple-react-full-stack

### Anything else?

<img width="1428" alt="Screen Shot 2022-08-25 at 5 34 21 PM" src="https://user-images.githubusercontent.com/25985512/186773561-5524f813-dba0-4509-bc1d-e429780f44a0.png">

Here's a screenshot of it working w/o the styling showing that the imports from said location are working. Interesting thing is though the import path is 

import '@rainbow-me/rainbowkit/styles.css';

But there's only a folder there w/ no index.css located there

**Comment by nickbytes** [comment]
@JClutch Checkout this answer here and let me know if this works! 

https://github.com/rainbow-me/rainbowkit/discussions/375#discussioncomment-3152151
