### ISSUE TITLE
[bug] createMessage from createAuthenticationAdapter can't be async

### ISSUE THREAD

**Issue by Y0moo** [rainbow-me/rainbowkit#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.0

### wagmi Version

0.6.4

### Current Behavior

I'm creating a custom rainbow kit AuthProvider from [docs](https://www.rainbowkit.com/docs/custom-authentication#creating-a-custom-adapter).  Here is an example from the docs:
```
createMessage: ({ nonce, address, chainId }) => {
    return new SiweMessage({
      domain: window.location.host,
      address,
      statement: 'Sign in with Ethereum to the app.',
      uri: window.location.origin,
      version: '1',
      chainId,
      nonce,
    });
  },
```

### Expected Behavior

The problem is you can not generate the message asynchronously. I'd like to make an API request to let's say backend and from its response generate a Message:
```
createMessage: async ({ address, chainId }) => {
      const message = await apiPost('/auth/request-message', { address, chainId, network: 'evm' });
      return message;
},
```
But this will fail even if you add `await` and `async` to `createMessage` and `getMessageBody` because in the code [permalink](https://github.com/rainbow-me/rainbowkit/blob/337478b7a6b904fad652c8e1bd21854c00e9903e/packages/rainbowkit/src/components/SignIn/SignIn.tsx#L75) you have:
```
const message = authAdapter.createMessage({ address, chainId, nonce });
```
So adding there `await` should solve this problem

**Comment by joakim-roos** [comment]
Any idea how to solve this? Got exactly the same problem on my side :(

**Comment by markdalgleish** [comment]
Out of interest, do you have a concrete example of what you need access to asynchronously?

**Comment by mikefortney** [comment]
Couldn't you use `.then().catch()` instead of async/await in this case?

**Comment by brianyates** [comment]
I have a related qualm - the `createMessage` function shouldn't need to be asynchronous, but `getNonce` needs to be able to accept parameters (like the `address` and `chainId`)...otherwise how would your nonce have any significance? Shouldn't your nonce be tied to an address on the backend?

**Comment by Y0moo** [comment]
@nickbytes please re-open this issue. It's not resolved

**Comment by HappySean2845** [comment]
> I have a related qualm - the `createMessage` function shouldn't need to be asynchronous, but `getNonce` needs to be able to accept parameters (like the `address` and `chainId`)...otherwise how would your nonce have any significance? Shouldn't your nonce be tied to an address on the backend?

Excactly, getNonce always get address undefined but it's needed in my auth process
