### ISSUE TITLE
[bug] TransactionStoreProvider missing div breaking css

### ISSUE THREAD

**Issue by dereknelson** [rainbow-me/rainbowkit#689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.3.4

### wagmi Version

0.4.12

### Current Behavior

Getting this error:
```
Warning: Expected server HTML to contain a matching <div> in <div>.
    in div (created by RainbowKitProvider)
    in TransactionStoreProvider (created by RainbowKitProvider)
    in RainbowKitProvider (created by RootComponent)
    in QueryClientProvider (created by WagmiConfig)
    in WagmiConfig (created by RootComponent)
    in RootComponent (created by HotExportedRootComponent)
    in AppContainer (created by HotExportedRootComponent)
    in HotExportedRootComponent
```
which is making a bunch of our CSS act weirdly

### Expected Behavior

not to get this warning & have our CSS broken

### Anything else?

normal 
![image](https://user-images.githubusercontent.com/6868432/186990538-862aefb7-6717-498a-a6ae-1f282ea70496.png)
with rainbowkit ![image](https://user-images.githubusercontent.com/6868432/186990588-23693105-85bf-41f8-a4fc-07d882a84e1c.png)

**Comment by shrugs** [comment]
that error means there's a div under `<RainbowKitProvider/>` that is not the same when hydrating on the client (and any hydration error will probably break your page). i would remove that provider from your tree and see if the hydration mismatch still occurs

**Comment by dereknelson** [comment]
@shrugs i narrowed it down to this error:
```
Warning: Expected server HTML to contain a matching <style> in <div>.
    in style (created by RainbowKitProvider)
    in div (created by RainbowKitProvider)
```
which occurs [here](https://github.com/rainbow-me/rainbowkit/blob/1a4f2f700b850582df1a0ccb1b37b2caa5e5a44e/packages/rainbowkit/src/components/RainbowKitProvider/RainbowKitProvider.tsx#L114)

**Comment by dereknelson** [comment]
i'm new to SSR, i'm guessing my best path forward is to not render rainbowkit serverside & wait to render it until it's clientside?

**Comment by shrugs** [comment]
you can render rainbowkit serverside, it supports it. is that style rendered within RainbowKitProvider or within your own components?

**Comment by dereknelson** [comment]
@shrugs turns out that wasn't what was breaking the css. still receiving the error about matching divs but doesn't seem to be harmful ¯\\_(ツ)_/¯

**Comment by shrugs** [comment]
something in this codeblock is rendering differently on your server than it is on the client

https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/RainbowKitProvider/RainbowKitProvider.tsx#L114

**Comment by dereknelson** [comment]
hey so still getting that warning in development (which looks fine) but once we deploy it to production, it's broken (without any errors or warnings)

![image](https://user-images.githubusercontent.com/6868432/190453658-3df28727-3746-40c8-a93a-c7ccc7f42199.png)
![image](https://user-images.githubusercontent.com/6868432/190453688-4aab35f1-67ac-4f81-9bc1-08c02bc4557f.png)

**Comment by markdalgleish** [comment]
@dereknelson Would you be able to share a repro link?

**Comment by dereknelson** [comment]
it's an issue with our webpack config not including the css.

**Comment by shrugs** [comment]
hilariously _i'm_ running into this again, integrating `@rainbow-me/rainbowkit 1.0.12` into a next13 app. setting theme to null fixes the issue, as does this hack

```
function ThemedRainbowKitProvider(props: ComponentProps<typeof RainbowKitProvider>) {
  const { resolvedTheme } = useTheme();
  const hydrated = useIsHydrated();
  return (
    <RainbowKitProvider //
      theme={!hydrated ? null : (resolvedTheme ?? "light") === "light" ? lightTheme() : darkTheme()}
      {...props}
    />
  );
}
```

**Comment by dereknelson** [comment]
hilariously i work at rainbow now so i can follow up on upstreaming a hack like that!

**Comment by shrugs** [comment]
that's incredible. i ended up with something like this:

```tsx
function ThemedRainbowKitProvider(props: ComponentProps<typeof RainbowKitProvider>) {
  const hydrated = useIsHydrated();
  const { session, isLoading } = useSession();

  return (
    <RainbowKitAuthenticationProvider
      adapter={adapter}
      status={isLoading ? "loading" : !!session?.address ? "authenticated" : "unauthenticated"}
    >
      <RainbowKitProvider //
        theme={
          !hydrated
            ? null
            : {
                lightMode: lightTheme(THEME_OPTIONS),
                darkMode: darkTheme(THEME_OPTIONS),
              }
        }
        {...props}
      />
    </RainbowKitAuthenticationProvider>
  );
}
```
