### ISSUE TITLE
[bug] <Can't sign in production while using RainbowKitSiweNextAuthProvider>

### ISSUE THREAD

**Issue by Merrick17** [rainbow-me/rainbowkit#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.0

### wagmi Version

0.6.4

### Current Behavior

the code works fine , however in production doesn't allow to connect and verify , in the console shows this 
https://canggu-property-next-vu-app-bbd.vercel.app/api/auth/callback/credentials? 401

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://canggu-property-next-vu-app-bbd.vercel.app/

**Comment by jxom** [comment]
I can seem to sign the message and authenticate correctly. Did you manage to fix this?

**Comment by peduarte** [comment]
Also able to sign and authenticate properly using the link provided.

@Merrick17 is this issue stale?

<img width="1318" alt="CleanShot 2022-09-14 at 15 48 09@2x" src="https://user-images.githubusercontent.com/372831/190171951-e2a83eae-7a5e-4ad7-8ab0-527364ab21c7.png">

**Comment by Merrick17** [comment]
hello yes it was an issue with the middleware function i fixed it and deployed and forgot to close this issue. 
my bad

**Comment by peduarte** [comment]
@Merrick17 cool, thanks for letting us know

**Comment by 0xAskar** [comment]
could you explain the error? I'm having a similar problem with the `callback/credentials` and it can't verify the signature. I included both the nextauth url and secret in the env variables on heroku but still am getting credentials problems

**Comment by ickas** [comment]
@Merrick17 I'm facing exactly this problem when deploying on Vercel. Do you have any tips for this one? 😅

**Comment by Merrick17** [comment]
`import NextAuth from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
import { getCsrfToken } from "next-auth/react";
import { SiweMessage } from "siwe";
import { NextApiRequest, NextApiResponse } from "next";

export default async function auth(req: NextApiRequest, res: NextApiResponse) {
  const providers = [
    CredentialsProvider({
      name: "Ethereum",
      credentials: {
        message: {
          label: "Message",
          type: "text",
          placeholder: "0x0",
        },
        signature: {
          label: "Signature",
          type: "text",
          placeholder: "0x0",
        },
      },
      async authorize(credentials) {
        try {
          console.log("credentials?.message", credentials?.message);
          const siwe = new SiweMessage(
            JSON.parse(credentials?.message || "{}")
          );

          const nextAuthUrl =
            process.env.NEXTAUTH_URL ||
            (process.env.VERCEL_URL
              ? `https://${process.env.VERCEL_URL}`
              : null);
          if (!nextAuthUrl) {
            return null;
          }

          const nextAuthHost = new URL(nextAuthUrl).host;
          if (siwe.domain !== nextAuthHost) {
            return null;
          }

          if (siwe.nonce !== (await getCsrfToken({ req }))) {
            return null;
          }

          await siwe.validate(credentials?.signature || "");
          return {
            id: siwe.address,
          };
        } catch (e) {
          return null;
        }
      },
    }),
  ];

  // @ts-ignore
  const isDefaultSigninPage =
    req.method === "GET" &&
    req.query.nextauth &&
    req.query.nextauth.includes("signin");

  // Hide Sign-In with Ethereum from default sign page
  if (isDefaultSigninPage) {
    providers.pop();
  }

  return await NextAuth(req, res, {
    // https://next-auth.js.org/configuration/providers/oauth
    providers,
    session: {
      strategy: "jwt",
    },
    secret: process.env.NEXTAUTH_SECRET,
    callbacks: {
      async session({ session, token }) {
        // @ts-ignore
        session.address = token.sub;
        // @ts-ignore
        session.user.name = token.sub;
        return session;
      },
    },
  });
}
`
next auth url , the trick is with the  const nextAuthUrl =
            process.env.NEXTAUTH_URL ||
            (process.env.VERCEL_URL
              ? `https://${process.env.VERCEL_URL}`
              : null);
