### ISSUE TITLE
[bug] in my app , when i open in mobile chrome browser , the rainbowkit can open metamask but has no connect pop-up

### ISSUE THREAD

**Issue by zhaishengzhang** [rainbow-me/rainbowkit#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.3.4

### wagmi Version

^0.4.12

### Current Behavior

![image](https://user-images.githubusercontent.com/11833064/187594964-195142c2-d3e7-41b5-8bd1-00d0798d99db.png)

it's work in pc chrome , but mobile chrome , it's can open mm, but has no connect pop-up like the up image. and the account info can't be back to my app
the code just like this,  my app creat by react app not nextjs

`<WagmiConfig  client={wagmiClient}>`
      `   <RainbowKitProvider chains={chains}>`
      `    <ConnectButton />`
      ` </RainbowKitProvider>`
    ` </WagmiConfig>`

### Expected Behavior

like rainbowkit website , can open mm and has a connect pop-up, when connect the data of account back to my app

**Comment by LeoClairet05** [comment]
Hello @zhaishengzhang! Did you find a solution? I'm facing the same problem, thanks!
