### ISSUE TITLE
[bug] Can't connect to Mobile Metamask 

### ISSUE THREAD

**Issue by LeifuChen** [rainbow-me/rainbowkit#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.1

### wagmi Version

0.6.2

### Current Behavior

User couldn't connect the dapp with the mobile metamask. After clicking the `connect wallet` and selecting the metamask, the user will redirect to the following page.

![image](https://user-images.githubusercontent.com/4819006/189302102-cf8bfdf8-a6ef-439a-a3e4-01fd669ac0bf.png)

### Expected Behavior

Connected to dapp normally.

### Steps To Reproduce

1. Open https://www.rainbowkit.com/ in mobile metamask
2. Click `Connect Wallet`
3. Choose `MetaMask`
4. See the Error page

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/

**Comment by Davis1233798** [comment]
same issue on mobile, can connect to wallet perfectly with rainbowkit.com but can't connect with my personal site

**Comment by jxom** [comment]
Thank you for finding this! We should be using the injected provider here instead of Wallet Connect. Will get onto this soon! :)

**Comment by markdalgleish** [comment]
This is now fixed in [RainbowKit v0.5.3](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.5.3).
