### ISSUE TITLE
[bug] coinbase wallet switches to Ethereum Mainnet and then to custom chain when connecting  

### ISSUE THREAD

**Issue by billyjitsu** [rainbow-me/rainbowkit#748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.2

### wagmi Version

0.6.5

### Current Behavior

With a custom chain activated when using coinbase wallet, it wants to switch to Ethereum (which is not listed in chain options) and then prompts to switch to custom chain.   It will work after but then randomly switches back to ethereum and will have to switch back on the website to correct it.

current _app.js setup:

import "../styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { getDefaultWallets, RainbowKitProvider, darkTheme, lightTheme, midnightTheme } from "@rainbow-me/rainbowkit";
import { chain, configureChains, defaultChains, createClient, WagmiConfig } from "wagmi";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { jsonRpcProvider } from 'wagmi/providers/jsonRpc';
import { publicProvider } from "wagmi/providers/public";

/* adding gnosis network */
const GnosisChain = {
  id: 100,
  name: 'Gnosis Chain',
  network: 'Gnosis',
  nativeCurrency: {
    decimals: 18,
    name: 'xDai',
    symbol: 'xDai',
  },
  rpcUrls: {
    default: 'https://rpc.ankr.com/gnosis',
  },
  blockExplorers: {
    default: { name: 'Gnosis Scan', url: 'https://gnosisscan.io/' },
  },
  iconUrls: ["https://images.prismic.io/koinly-marketing/16d1deb7-e71f-48a5-9ee7-83eb0f7038e4_Gnosis+Chain+Logo.png"],
  testnet: false,
}

const { chains, provider } = configureChains(
  [GnosisChain],
  [// alchemyProvider({ alchemyId: process.env.NEXT_PUBLIC_ALCHEMY_ID }),
   jsonRpcProvider({ rpc: () => ({ http: 'https://rpc.ankr.com/gnosis' }) }), // Move this top top
   publicProvider()
  ]
);
const { connectors } = getDefaultWallets({
  appName: "The NFBeez",
  chains,
});
const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});

function MyApp({ Component, pageProps }) {
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider coolMode chains={chains} theme={lightTheme({
      accentColor: '#ffdd0f',  //color of wallet  try #703844
      accentColorForeground: 'black',
      borderRadius: 'large',
      fontStack: 'system',
    })}>
        <Component {...pageProps} />
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

export default MyApp;

### Expected Behavior

Just connect to custom chain

### Steps To Reproduce

Just connect to correct chain

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://nfbeezgenesis.vercel.app/

**Comment by markdalgleish** [comment]
I wasn't able to reproduce the first part of your issue, but I could reproduce being switched back to mainnet when I refreshed the page: https://github.com/wagmi-dev/wagmi/issues/966. Does this describe part of your issue?
