### ISSUE TITLE
[bug] Hydration error in examples/with-next-mint-nft

### ISSUE THREAD

**Issue by Drblessing** [rainbow-me/rainbowkit#761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.6.0

### wagmi Version

^0.6.0

### Current Behavior

After logging in with my wallet on `http://localhost:3000/`, then refreshing, I get:
`Unhandled Runtime Error. Error: Hydration failed because the initial UI does not match what was rendered on the server.`

### Expected Behavior

The error should not pop up. 

### Steps To Reproduce

1. Fork Repo
2. Run `pnpm install` in repo root
3. Run `cd examples/with-next-mint-nft`in repo root
4. Run `pnpm run dev`
5. Log in with wallet
6. Refresh page

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-mint-nft

### Anything else?

![image](https://user-images.githubusercontent.com/52829488/190833592-c188e643-0525-4d8c-9c50-45fe9c846c51.png)

**Comment by agonist** [comment]
gm @Drblessing , I'm running into the same kind of issue.
I found this issue https://github.com/wagmi-dev/wagmi/issues/542
It basically seem that wagmi doesn't work properly with NextJs currently.

I'm just going to skip those libraries for now as a simple fix.

**Comment by jxom** [comment]
There are workarounds for this: https://github.com/wagmi-dev/wagmi/issues/542#issuecomment-1144178142
