### ISSUE TITLE
[bug] Facing "failed to parse source map from @walletConnect" warnings

### ISSUE THREAD

**Issue by Vedantp8** [rainbow-me/rainbowkit#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.1

### wagmi Version

0.5.12

### Current Behavior

Getting the following warning in the terminal while running the react app.

Failed to parse source map from 'D:\git\my_app\Frontend\node_modules\@walletconnect\crypto\src\helpers\env.ts' file: Error: ENOENT: no such file or directory, open 

and many more of same type for the different files in @walletconnect\crypto\src\helpers folder

### Expected Behavior

Warnings should be cleared from the terminal.

### Anything else?

<img width="682" alt="Screenshot 2022-09-22 163411" src="https://user-images.githubusercontent.com/66231644/191730831-c9c7e226-f85d-4bd8-8a78-893599f51a74.png">

**Comment by jxom** [comment]
Hi. Can you please provide a minimal reproducible example via a CodeSandbox or minimal repository?
I will re-open this issue when one is provided.

**Comment by Vedantp8** [comment]
https://github.com/Vedantp8/Rainbow-Wallet-demo

**Comment by Vedantp8** [comment]
https://github.com/Vedantp8/Rainbow-Wallet-demo

This is the file for minimal reproducible example.

**Comment by nichosystem** [comment]
Also experiencing this issue
