### ISSUE TITLE
[bug] Changing account/address on Metamask doesn't logout (SIWE)

### ISSUE THREAD

**Issue by soccerarenadev** [rainbow-me/rainbowkit#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.6.1

### wagmi Version

0.6.7

### Current Behavior

When changing the current account/address on Metamask, which did the login, the AuthJS doesn't realize.  It keeps logged with the former address but connected with a new address.

### Expected Behavior

Logout.

### Steps To Reproduce

Change address while logged. 

### Anything else?

-

**Comment by adbario** [comment]
This is likely not considered a bug in RainbowKit, which doesn't directly listen to the Wagmi Connector events. You could use the Wagmi hooks and local state to find out when the address has been changed, or you can likely listen to the [Wagmi ConnectorEvents](https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/connectors/base.ts#L12) which are based on the underlying provider events.

**Comment by 0xAskar** [comment]
@adbario Do you mind explaining a bit more in detail?
