### ISSUE TITLE
[bug] Button shows up unstyled, potential Tailwind conflict

### ISSUE THREAD

**Issue by zkSoju** [rainbow-me/rainbowkit#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.1

### wagmi Version

0.6.0

### Current Behavior

I have tailwind installed and I am experiencing a similar issue to the one mentioned here in #329 regarding tailwind css specificity potentially. The ConnectButton shows up completely unstyled.

### Expected Behavior

Normal CSS styling is expected

**Comment by HappySean2845** [comment]
Hi, how do you solve the  issue, I found the same problem

**Comment by zkSoju** [comment]
> Hi, how do you solve the issue, I found the same problem

Just make sure to import the rainbowkit styles after your other styles like so.

import "../styles/globals.css";
import "../styles/tailwind.css";
import "@rainbow-me/rainbowkit/styles.css";
