### ISSUE TITLE
[bug] Styling issue on mobile (iPhone)

### ISSUE THREAD

**Issue by Solicity-dev** [rainbow-me/rainbowkit#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.0

### wagmi Version

0.6.0

### Current Behavior

Hi! 

We are currently building a PWA and are using your package for the Web 3 connection which is pretty cool, usefull and works perfectly, thanks for your hard work. 

But we are facing an issue with the css styling as you can see on the following screenshot with the Network modal, it's not centered in landscape mode. Same issue with the wallet selector modal that doesn't feat well with the screen size.

Would it be possible to patch it? 

Thank you 💪

![Screenshoot](https://user-images.githubusercontent.com/91335945/193357378-c56b9f92-1040-45d4-9996-2354986262c0.jpeg)

![IMG_5412](https://user-images.githubusercontent.com/91335945/193358000-e4e75cce-c02c-4fc8-868e-9ca79d5003db.PNG)

**Comment by nickbytes** [comment]
Thanks, i'm able to reproduce this but landscape mode on the phone is a pretty low priority right now. I'll leave this up, if you feel like submitting a PR, I'd be happy to look at it.
