### ISSUE TITLE
[bug] Minting seems to not work on other chains like Optimism

### ISSUE THREAD

**Issue by le-kag** [rainbow-me/rainbowkit#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.701

### wagmi Version

0.6.8

### Current Behavior

I updated everything to make it able to mint an nft on optimism but the button isn't sending the tx message to Metamask wallet. I'm not sure if it's a problem with the rpc I put in. Please look into this.

P.s: Otherwise, Great work!

### Expected Behavior

It's supposed to send the tx to the wallet and mint the NFT.

### Steps To Reproduce

- Configure the chain to optimism
- Put in the abi of a deployed contract
- Add all the necessary wallets (i.e: MetaMask)
- Add an rpc
- Check if you can mint

**Comment by DanielSinclair** [comment]
Hi @le-kag! Do you have example code? Have been unable to replicate but would like to squash this if there is an outstanding issue on our end.

**Comment by DanielSinclair** [comment]
Closing this issue for now, but check back if you're still experiencing this problem or have some reproducible example code, and we'll reopen
