### ISSUE TITLE
[bug] Unhandled Runtime Error when trying to connect from iOS 16

### ISSUE THREAD

**Issue by apecollector** [rainbow-me/rainbowkit#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.7.0

### wagmi Version

^0.6.0

### Current Behavior

When I try to connect from mobile safari on iOS 16 I get the following error after choosing any provider (metamask, rainbow, etc...)

```
 1 of 1 unhandled error

Unhandled Runtime Error
TypeError: undefined is not an object (evaluating '_walletconnect_environment__WEBPACK_IMPORTED_MODULE_0__.getSubtleCrypto().importKey')
Call Stack
asyncFunctionResume

[native code]
asyncFunctionResume

[native code]
asyncFunctionResume

[native code]
<unknown>

[native code]
promiseReactionJobWithoutPromise

[native code]
promiseReactionJob

[native code]
```

### Expected Behavior

Connect as normally

**Comment by moribayashi0406** [comment]
+1

**Comment by h0tw4t3r** [comment]
any updates on this?

**Comment by DanielSinclair** [comment]
Am unable to replicate this, @h0tw4t3r. Do you have a recommended test path or example code?
