### ISSUE TITLE
Wagmi hook returning undefined.

### ISSUE THREAD

**Issue by itz-jherie** [rainbow-me/rainbowkit#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.2

### wagmi Version

0.6.0

### Current Behavior

 useContractRead Hook returning undefined.
I bootstrapped the whole file by using the rainbowkit quickstart command so that I'll have minimal configuration. I've already tried to manually configure rainbowkit in an existing project but I was getting the same issue. The connectwallet button and display of accounts works quite alright but I can't interact with smart contracts.
I'll attach Images to show my config, dependencies and versions, my implementation and errors.
Typescript shows an error too but I don't understand because I don't know how to use typescript yet.

### Expected Behavior

I'm supposed to get data in the return of the useContractRead.

### Anything else?

![Screenshot (22)](https://user-images.githubusercontent.com/64599754/196973303-9a08d77c-bf9c-42b2-8d9e-5c119b6bd4ee.png)
![Screenshot (23)](https://user-images.githubusercontent.com/64599754/196973312-e13258b7-a1ec-4aa4-b4c2-8a579bc6b415.png)
![Screenshot (24)](https://user-images.githubusercontent.com/64599754/196973322-62ba13c8-0c24-4ac1-b6e9-3daa7ce943a7.png)
![Screenshot (26)](https://user-images.githubusercontent.com/64599754/196973327-71d3bdf2-8fc5-43cd-8f57-c38dce86d0ad.png)
![Screenshot (27)](https://user-images.githubusercontent.com/64599754/196973333-78d16004-8583-448d-99e6-4b9d161b557c.png)

**Comment by adbario** [comment]
@itz-jherie On Wagmi 0.6.0 that `address` key in `useContractRead` should be `addressOrName`. See more here https://github.com/wagmi-dev/wagmi/blob/wagmi%400.6.0/packages/react/src/hooks/contracts/useContractRead.ts

You might want to upgrade Wagmi to the latest version.

**Comment by jxom** [comment]
Yep, need to upgrade wagmi!

Closing as this is not directly related to RainbowKit.

**Comment by itz-jherie** [comment]
Why doesn't it install the latest package? It installs version 0.6.8 but running "npm view" it clearly shows the latest is 0.7.5
