### ISSUE TITLE
[bug] http POST 429 on console log

### ISSUE THREAD

**Issue by fonzarely** [rainbow-me/rainbowkit#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.3

### wagmi Version

0.7.5

### Current Behavior

The console log is filled with HTTP error 429 on Alchemy.
My Metamask is not connected to Alchemy.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/707217/197417498-bddc56ff-d15f-4cc3-b3a9-6d9890c707f8.png">

### Expected Behavior

As I'm not using Alchemy, it should not happen.
It's happening on RainbowKit web site too.

### Steps To Reproduce

Add Rainbowkit to a NextJs projet.

### Anything else?

Rainbow Kit is great ! :)

**Comment by adbario** [comment]
@fonzarely This comes from `ethers` Alchemy Provider, which uses a [default Alchemy API key](https://github.com/ethers-io/ethers.js/blob/c80fcddf50a9023486e9f9acb1848aba4c19f7b6/packages/providers/src.ts/alchemy-provider.ts#L21) unless you provide a custom key. The default key is widely used and leads to rate limited response (429).

**Comment by fonzarely** [comment]
Thanks a lot @adbario !

**Comment by fonzarely** [comment]
But it feels strange as I'm not using AlchemyWebSocketProvider.

**Comment by lucian55** [comment]
how do i stop requesting this interface?

**Comment by fonzarely** [comment]
Add alchemyProvider to your config. 

```javascript
const getChain = () =>
  process.env.ETH_NETWORK === 'mainnet' ? chain.mainnet : chain.goerli

const { chains, provider } = configureChains(
  [getChain()],
  [
    alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_ID }),
    publicProvider(),
  ]
)
```

**Comment by brossetti1** [comment]
@fonzarely this does not fix the error for me -- the `defaultAlchemyApiKey` of `_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC` is still be represented even if i add my own `apiKey`

**Comment by daniiba** [comment]
I was using `alchemyProvider({ alchemyId: ` instead of `apiKey`. Changing it to `apiKey` fixed the issue for me

**Comment by xrkuzd** [comment]
> Add alchemyProvider to your config.
> 
> ```js
> const getChain = () =>
>   process.env.NEXT_PUBLIC_ETH_NETWORK === 'mainnet' ? chain.mainnet : chain.goerli
> 
> const { chains, provider } = configureChains(
>   [getChain()],
>   [
>     alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_ID }),
>     publicProvider(),
>   ]
> )
> ```

What if you aren't using Alchemy as a provider?  What to put in it's place?

**Comment by 2manslkh** [comment]
I think RainbowKit just consumes too much RPC Calls due to the usage of wagmi hooks by default.

Is it possible to only refresh the values on ProfileDetails when needed?

Relevant Code:

https://github.com/rainbow-me/rainbowkit/tree/4a1500ac46cf98828959bdb4174a96163323a81e/packages/rainbowkit/src/components/ProfileDetails

**Comment by junhuang-ho** [comment]
I have the same issue, getting this error:

> POST https://polygon-mumbai.g.alchemy.com/v2/_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC 429

Here is my setup, I am using my own API key and changing `pollingInterval` did **not** help.

```
const { chains, provider } = configureChains(
  [chain.polygonMumbai],
  [alchemyProvider({ apiKey: process.env.ALCHEMY_API_KEY }), publicProvider()],
  { pollingInterval: 10_000 }
);
```

**Comment by TheDojoSamurai** [comment]
> The issue could be fixed by appending `NEXT_PUBLIC_` to the env variable, but isn't this bad as it exposes the private API key?

Setting `REACT_APP_ALCHEMY_API_KEY` did not help in my case. Still have the same issue.

**Comment by graphicstone** [comment]
I am still getting this error on my React App, with my apiKey stored in .env file. 

And I was trying to debug the code and saw that while calling the getUrl function the apiKey that it got was my apiKey from .env file but then it again called the same function and this time the apiKey was the default apiKey (_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC). Some thing of a fallback but I am not sure. 

Did someone else also got in to this?

**Comment by adbario** [comment]
> I am still getting this error on my React App, with my apiKey stored in .env file.
> 
> And I was trying to debug the code and saw that while calling the getUrl function the apiKey that it got was my apiKey from .env file but then it again called the same function and this time the apiKey was the default apiKey (_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC). Some thing of a fallback but I am not sure.
> 
> Did someone else also got in to this?

I would suggest posting all relevant pieces of your code here; that would significantly increase the chances of getting help. You should also always include the package version you're using.

**Comment by harishiv-singh** [comment]
`  const { chains, provider } = configureChains(
    [chain.mainnet],
    [alchemyProvider({ apiKey: process.env.ALCHEMY_ID }), publicProvider()],
  );`

This is the code where I am using the apiKey for alchemyProvider. I tried hard coding it just to check for the issue but it's still giving me the same error.

The version that I am using is
`"@rainbow-me/rainbowkit": "^0.7.4"`
`"wagmi": "^0.7.5"`
`"ethers": "^5.7.1"`

**Comment by graphicstone** [comment]
`const { chains, provider } = configureChains( [chain.mainnet], [alchemyProvider({ apiKey: process.env.ALCHEMY_ID }), publicProvider()], );`

This is the code where I am using the apiKey for alchemyProvider. I tried hard coding it just to check for the issue but it's still giving me the same error.

The version that I am using is
```
"@rainbow-me/rainbowkit": "^0.7.4"
"wagmi": "^0.7.5"
"ethers": "^5.7.1"
```

**Comment by adbario** [comment]
> `const { chains, provider } = configureChains( [chain.mainnet], [alchemyProvider({ apiKey: process.env.ALCHEMY_ID }), publicProvider()], );`
> 
> This is the code where I am using the apiKey for alchemyProvider. I tried hard coding it just to check for the issue but it's still giving me the same error.
> 
> The version that I am using is
> 
> ```
> "@rainbow-me/rainbowkit": "^0.7.4"
> "wagmi": "^0.7.5"
> "ethers": "^5.7.1"
> ```

@graphicstone You didn't mention whether this is a next.js app or something else, but with next.js the env variable name needs to be prefixed with `NEXT_PUBLIC_`, for example, `NEXT_PUBLIC_ALCHEMY_API_KEY ` For Create React App please read this https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by graphicstone** [comment]
@adbario I have mentioned earlier that it's a React.js project, and it's not an issue with the env variable, because I tried hard coding my API key as well instead of getting it from the env variables. Still it was giving the same error of HTTP error 429 on Alchemy.

**Comment by tcheee** [comment]
This issue might help: https://github.com/family/connectkit/issues/36

**Comment by rtman** [comment]
also seeing this, its using the public alchemy key even when I specify my own.

**Comment by rafinskipg** [comment]
I'm having the same problem, even using the alchemy provider (on next, with next_public)

**Comment by adbario** [comment]
> I'm having the same problem, even using the alchemy provider (on next, with next_public)

Here's a simple example app where the Alchemy API key is set up correctly:
https://github.com/adbario/rainbowkit-nextjs-example

**Comment by rafinskipg** [comment]
> > I'm having the same problem, even using the alchemy provider (on next, with next_public)
> 
> Here's a simple example app where the Alchemy API key is set up correctly: https://github.com/adbario/rainbowkit-nextjs-example

My code setup is correct but i'm still getting the same error after a bit of usage

**Comment by rafinskipg** [comment]
Does anyone found a solution to this?

**Comment by imthatcarlos** [comment]
anyone looking into this? would love to have a clean console again 🥲

**Comment by brossetti1** [comment]
so I was experiencing this issue, If i look at the latest version of wagmi, i no longer see the api key hardcoded for alchemy, I would suggest upgrading wagmi and seeing if that helps..

i have not checked this myself, and dont have time at the moment, all i can say is that earlier when i commented here, I saw the alchemy key hardcoded somewhere referencing the default alchemy key of `_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC` and so no local environment variables would take. I cannot find that anymore- might have something to do with this commit from 5 days ago https://github.com/wagmi-dev/wagmi/pull/1202

**Comment by adbario** [comment]
> so I was experiencing this issue, If i look at the latest version of wagmi, i no longer see the api key hardcoded for alchemy, I would suggest upgrading wagmi and seeing if that helps..
> 
> i have not checked this myself, and dont have time at the moment, all i can say is that earlier when i commented here, I saw the alchemy key hardcoded somewhere referencing the default alchemy key of `_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC` and so no local environment variables would take. I cannot find that anymore- might have something to do with this commit from 5 days ago
> 
> [wagmi-dev/wagmi#1202](https://github.com/wagmi-dev/wagmi/pull/1202)

The default Alchemy API key is coming from [ethers.js](https://github.com/ethers-io/ethers.js/blob/74e3d98d1df2bd97be258202a63517d4aa1ba8fd/packages/providers/src.ts/alchemy-provider.ts#L21) instead of `wagmi`

**Comment by imthatcarlos** [comment]
thanks for the suggestion @brossetti1 - but I upgraded wagmi and still get the error.  I think it is coming out of ethers as @adbario is suggesting. 

one thing I find interesting is that wagmi [requires the api key](https://wagmi.sh/docs/migration-guide#alchemyprovider) for the alchemy provider. I just tried switching to the json rpc provider... same issue.

**Comment by jxom** [comment]
RainbowKit `0.8.0` adds `wagmi@0.8.x` as a peer dependency to help solve this issue. 

To prevent being rate-limited, `wagmi@0.8.x` has made **`apiKey` required** for the `alchemyProvider`, and has added better RPC defaults for `publicProvider`. Please ensure you have provided your own API Key to the Alchemy Provider!

**Comment by imthatcarlos** [comment]
@jxom - I don't think the issue has been resolved. just updated package versions and still getting the error. Is it possible that the `apiKey` prop is not properly being passed down to wagmi/ethers ?

```
"@rainbow-me/rainbowkit": "^0.8.0",
"wagmi": "^0.8.5",
```

<img width="1080" alt="Screen Shot 2022-11-17 at 9 56 31 AM" src="https://user-images.githubusercontent.com/20136572/202480361-07c26fa5-066b-443f-b1ca-505d9ffb2313.png">

**Comment by chillx2land** [comment]
I'm getting same error.

```package.json
    "@rainbow-me/rainbowkit": "^0.6.1",
    "ethers": "^5.7.1",
    "react": "18.2.0",
    "wagmi": "^0.6.7"
```


![スクリーンショット 2022-11-21 15 03 08](https://user-images.githubusercontent.com/27806180/202976797-e4adef13-bc69-48e7-95d7-dda0f660d2f5.png)

**Comment by lsbyerley** [comment]
I am still seeing this issue with the following versions. Any idea on how to prevent it?

```
"@rainbow-me/rainbowkit": "0.8.1",
"wagmi": "0.9.6"
"next": "13.1.4",
"ethers": "5.5.1",
```

**Comment by AlvaroLuken** [comment]
Having this issue as well, no fix seems to be available yet...
