### ISSUE TITLE
[bug] Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)

### ISSUE THREAD

**Issue by soccerarenadev** [rainbow-me/rainbowkit#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.3

### wagmi Version

0.7.5

### Current Behavior

I'm getting this error from a few days back when using Alchemy:
When Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)

Even just using the example from scratch, I'm getting it:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/99416733/197504522-696e0c8a-1ae5-4b4c-9d4b-a20c2c8f7207.png">

Seems to be something to do with Alchemy.

### Expected Behavior

Not fail.

### Steps To Reproduce

npm init @rainbow-me/rainbowkit@latest
cd my-rainbowkit-app 
npm run dev

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/zen-browser-c5mh21?file=/pages/_app.tsx

**Comment by szanuje** [comment]
Same for me.

**Comment by lucian55** [comment]
Same for me.

**Comment by brossetti1** [comment]
this comes from the websocket provider right now, removed it and stopped getting this error but thats not the best solution

**Comment by szanuje** [comment]
@soccerarenadev @brossetti1 Alchemy changed connection url, and Ethers library cannon handle it properly, so e.g `AlchemyRpcProvider()` won't work if you are using it. You would need to use `JsonRpcProvider()` or `WebSocketProvider` and pass full connection string. It would then work just fine ;)
Examples:
```
    return new providers.WebSocketProvider(
      `wss://eth-mainnet.g.alchemy.com/v2/${alchemyId}`,
      ETHEREUM_MAINNET_CHAIN_ID,
    );
```
```
    return new providers.JsonRpcProvider(
      `https://eth-mainnet.g.alchemy.com/v2/${alchemyId}`,
      ETHEREUM_MAINNET_CHAIN_ID,
    );
```

**Comment by soccerarenadev** [comment]
> @soccerarenadev @brossetti1 Alchemy changed connection url, and Ethers library cannon handle it properly, so e.g `AlchemyRpcProvider()` won't work if you are using it. You would need to use `JsonRpcProvider()` or `WebSocketProvider` and pass full connection string. It would then work just fine ;) Examples:
> 
> ```
>     return new providers.WebSocketProvider(
>       `wss://eth-mainnet.g.alchemy.com/v2/${alchemyId}`,
>       ETHEREUM_MAINNET_CHAIN_ID,
>     );
> ```
> 
> ```
>     return new providers.JsonRpcProvider(
>       `https://eth-mainnet.g.alchemy.com/v2/${alchemyId}`,
>       ETHEREUM_MAINNET_CHAIN_ID,
>     );
> ```

Still, it shouldn't behave like this. It should catch the error and fallback to the next provider is given.

**Comment by stackaccount1** [comment]
I am also running into this issue on a fresh build `npm init @rainbow-me/rainbowkit@latest`

**Comment by stackaccount1** [comment]
> @soccerarenadev @brossetti1 Alchemy changed connection url, and Ethers library cannon handle it properly, so e.g `AlchemyRpcProvider()` won't work if you are using it. You would need to use `JsonRpcProvider()` or `WebSocketProvider` and pass full connection string. It would then work just fine ;) Examples:
> 
> ```
>     return new providers.WebSocketProvider(
>       `wss://eth-mainnet.g.alchemy.com/v2/${alchemyId}`,
>       ETHEREUM_MAINNET_CHAIN_ID,
>     );
> ```
> 
> ```
>     return new providers.JsonRpcProvider(
>       `https://eth-mainnet.g.alchemy.com/v2/${alchemyId}`,
>       ETHEREUM_MAINNET_CHAIN_ID,
>     );
> ```

How is this configured in practice in rainbowkit
_app.js

**Comment by pbies** [comment]
ETHEREUM_MAINNET_CHAIN_ID is really = 1
