### ISSUE TITLE
[bug] ConnectButton styling completely broken in Next13

### ISSUE THREAD

**Issue by 0xAsynchronous** [rainbow-me/rainbowkit#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.7.4

### wagmi Version

^0.7.10

### Current Behavior

All styling is broken
<img width="221" alt="Screenshot 2022-11-04 at 00 18 17" src="https://user-images.githubusercontent.com/105571815/199858849-5434d8bd-6291-4e76-985e-1fb9e51a8aa6.png">

### Expected Behavior

Normal ConnectButton styling
<img width="337" alt="Screenshot 2022-11-04 at 00 19 02" src="https://user-images.githubusercontent.com/105571815/199858902-8163274f-7ee4-4145-a62a-902be01ab39c.png">

### Steps To Reproduce

1. npx create-next-app@latest --experimental-app
2. install rainbowkit dependencies and setup as described in the [docs](https://www.rainbowkit.com/docs/installation).
3. Use `<ConnectButton />` in the tsx/jsx file

I have shared a codesandbox which demonstrates this behavior

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/p/github/0xAsynchronous/next13-rainbowkit/draft/optimistic-allen?file=%2Fapp%2Flayout.tsx&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A16%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cla1qsahn000gl2fvdqvgd2n4%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fapp%252Flayout.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cla1qtt4y00bh2e6dzefzz9v6%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cla1qtrcq007k2e6dcg9kmuzc%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

**Comment by mykcryptodev** [comment]
How was this resolved?
