### ISSUE TITLE
Rainbow can't detect network

### ISSUE THREAD

**Issue by neulad** [rainbow-me/rainbowkit#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.4

### wagmi Version

^0.7.5

### Current Behavior

Every time I run Next.js project I get `could not detect network`. I tried to run `npm init @rainbow-me/rainbowkit@latest` and ran generated project to check if my setup was misconfigured, but it crashes too. I tried to connect to different networks using metamask but it didn't help me. I use Next.js v12.3.2.

### Expected Behavior

It should execute without throwing this error.

### Steps To Reproduce

```sh
npm init @rainbow-me/rainbowkit@latest
npm run dev
```

### Anything else?

![Screenshot from 2022-11-05 16-11-37](https://user-images.githubusercontent.com/116178300/200126684-66717bb6-5900-460a-89c7-c16d1da30295.png)

I checked it on different under firefox and chromium.

**Comment by neulad** [comment]
After removing my privacy-based extensions (e.g. privacy bedger/possum etc.) everything worked. It didn't depend on browser.

**Comment by neulad** [comment]
Wow I just found out that Dark Reader caused all Hydration issues.

**Comment by ptaberg** [comment]
Get the same issue after `npm init @rainbow-me/rainbowkit@latest`, but I have no any privacy-based extensions

**Comment by jordanlesich** [comment]
Yeah, same as @ptaberg
