### ISSUE TITLE
[bug] wallet.brave() does not seem to work?

### ISSUE THREAD

**Issue by DillonLin** [rainbow-me/rainbowkit#859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.6.2

### wagmi Version

0.6.4

### Current Behavior

Calling wallet.brave() does not work but calling other wallets such as wallet.argent() seems to work.

<img width="1725" alt="Screen Shot 2022-11-07 at 3 58 28 PM" src="https://user-images.githubusercontent.com/30581721/200232086-fd66110f-9508-4c78-99d5-8c2138c8da0e.png">
<img width="1145" alt="Screen Shot 2022-11-07 at 4 04 58 PM" src="https://user-images.githubusercontent.com/30581721/200232096-c14db089-fd6f-4a0e-a1bf-fec47f3678d8.png">

### Expected Behavior

Brave wallet appears as a wallet option.

**Comment by karangorania** [comment]
Still not showing. I am having the same problem.
