### ISSUE TITLE
[bug] dependency fail: peer wagmi@"0.5.x || 0.6.x || 0.7.x" from @rainbow-me/rainbowkit@0.7.4

### ISSUE THREAD

**Issue by actuallymentor** [rainbow-me/rainbowkit#864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.4

### wagmi Version

0.8.1

### Current Behavior

npm i fails

### Expected Behavior

npm i succeeds

### Steps To Reproduce

Install wagmi 0.8.1, run npm i.

**Comment by adbario** [comment]
@actuallymentor Until the dependency in updated on RainbowKit, you can temporarily pass this by installing < 8 version of `wagmi`:
```shell
npm install wagmi@0.7.15
```
