### ISSUE TITLE
[bug] wagmi version > 8 seems to be causing rainbowkit to be buggy

### ISSUE THREAD

**Issue by junhuang-ho** [rainbow-me/rainbowkit#869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.4

### wagmi Version

0.8.3

### Current Behavior

The bugs I have experienced so far:
When I disconnect from wallet using the `<ConnectButton />`'s account modal, after disconnecting,

1. connect modal pops up, selecting MetaMask browser in chrome triggers the account modal. 
2. close button does not work in connect modal.
3. does not disconnect properly (when I manually go to another url of my app using the browser search bar, wallet seems to remain connected)

### Expected Behavior

Fix buggy behaviour to being compatible with the latest wagmi version :)

**Comment by technophile-04** [comment]
Hey, @junhuang-ho thanks for creating this issue, facing the same problems.
Adding to the bugs you mentioned above, there is also some problem with the balance not showing up when connected even though `showBalance` prop is passed to the `ConnectButton` component. 

For a minimal reproducible example, I just created a repo similar to [rainbow-next-mintNFT](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-mint-nft) example and upgraded the version of wagmi to 0.8.3 

repo for minimal reproducible example with current bugs: https://github.com/technophile-04/minimal-rainbow-next-mintNFT
example with current bugs :  [sandbox link ](https://codesandbox.io/p/github/technophile-04/minimal-rainbow-next-mintNFT/draft/kind-dan?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clafl8lxs0007l1jq7rjx9yd3%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522clafl8oq3000r3b6n0sz5hahf%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clafl9e3j00903b6n6g64h5wd%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clafl9d0b006x3b6nnbv4jzqm%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by sgao056** [comment]
Encountered same problem, hope they can give solution asap.

**Comment by jxom** [comment]
PR for wagmi 0.8 support is here: #871!

**Comment by junhuang-ho** [comment]
buggy behavior described here still persists after upgrading to rainbowkit 0.8.0 @jxom

**Comment by junhuang-ho** [comment]
Here is a minimal reproducible code: https://github.com/junhuang-ho/test-rainbowkit

Connect to metamask wallet then disconnect. The problems stated should arise.

**Comment by Fabien-Morrow** [comment]
Annoyed by this too.

**Comment by danielgangl** [comment]
Having the exact same issues. Additionally: When connecting, the connect modal stayes open in a loading state even after I confirmed the connection in MetaMask.
This are extremely annoying issues - please fix these asap! Already cost me many hours trying to debug some weird behaviour....

**Comment by henryf10h** [comment]
When I  click on 'copy address' I get: "Cannot read properties of undefined (reading 'writeText')", I neither can't close the modal. Not mentioning the hydration errors. My rainbowkit's version is the 8.6.0.

**Comment by JoeyKhd** [comment]
+1

**Comment by bmraubo** [comment]
Reverting Wagmi to 0.6.8 seems to have resolved most of our problems, but a lot of the hook parameter names have been changed between 0.6.8 and 0.8.10, so it's a bit of work.

**Comment by ardasevinc** [comment]
Such a letdown. Is there no single sdk/web3 button UI project that just works? I want good UX for my users but then I have extremely bad DX....

**Comment by bettiolo** [comment]
@ardasevinc I have a similar problem. If you find something, let me know

**Comment by ardasevinc** [comment]
> @ardasevinc I have a similar problem. If you find something, let me know

I'm taking a look at web3-onboard. It seems marginally better than what I've tried so far...

It's not painless but at least it works

**Comment by junhuang-ho** [comment]
I am using 

```
"next": "^12.3.4"
"ethers": "^5.7.1"
"wagmi": "^0.8.8"
"@rainbow-me/rainbowkit": "^0.8.0"
"@tanstack/react-query": "^4.16.1"
```

and everything seems to be working fine.

**Comment by m4r0z** [comment]
Hey guys, still getting this issue, any fix for this?
