### ISSUE TITLE
[bug] Cannot connect to WalletConnect in Chrome with enabled device toolbar

### ISSUE THREAD

**Issue by smyzin** [rainbow-me/rainbowkit#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.0

### wagmi Version

0.8.6

### Current Behavior

Get an error when trying to connect a WalletConnect/Rainbow/Coinbase. There is no issue with MetaMask because I have its extension

```
Failed to launch 'wc:ee52bd81-b3ee-412e-a6c0-4d69f6c9ad3e@1?bridge=https%3A%2F%2Fy.bridge.walletconnect.org&key=6df29dee4ee75b216eb851179944c0db5d7db49cb830fb8975fe96ea283d4a3f' because the scheme does not have a registered handler.
```
<img width="1512" alt="Снимок экрана 2022-11-25 в 00 12 54" src="https://user-images.githubusercontent.com/5114069/203863721-05d66fcc-0716-428f-bfe3-78f55a49af17.png">

### Expected Behavior

If it's a desktop system, it should show a QR or open extension if you have one. If it's a mobile device, it should work as it is now

<img width="374" alt="Снимок экрана 2022-11-25 в 00 06 47" src="https://user-images.githubusercontent.com/5114069/203863092-7a0df438-0f02-4bf5-8214-4bb6724aa524.png">

### Steps To Reproduce

You can check it right on the leading site of [RainbowKit](https://www.rainbowkit.com/). It would be best if you visited it, opened developer tools (console), enabled the device toolbar, and tried to connect a wallet via WalletConnect, for instance. You will see an error above.

**Comment by DanielSinclair** [comment]
Device Mode actually only simulates mobile devices, if I understand correctly. The mobile behavior is what you're seeing here.

**Comment by pablohpsilva-forjnetwork** [comment]
I have the same issue today. Any news on how to solve this? 
Only mobile is affected.
