### ISSUE TITLE
[bug] Connecting a wallet does not consistently deeplink to Play Store on Android when no WC wallets available

### ISSUE THREAD

**Issue by jckw** [rainbow-me/rainbowkit#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.4

### wagmi Version

0.6.8

### Current Behavior

When connecting a wallet on Android devices, most of the options do not deep link to the Play Store in the way that the iOS apps deep link to the App Store. The behaviour is actually inconsistent, since Coinbase wallet _does_ link to the Play Store, and the others (including Rainbow!) don't.

### Expected Behavior

All wallet options (or, at least the default options) deeplink to the Play Store when the wallet isn't installed.

### Steps To Reproduce

Example: Visit https://www.rainbowkit.com/ on an Android device, without Rainbow Wallet or any WalletConnect-enabled wallet installed. Try to connect your wallet via the button, and see how now wallets are connected.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com

### Anything else?

There is some strange code that switches config based on whether a user is on iOS or Android. This is present for some wallets, but no others. 

I couldn't work out why this switch was added in the first place.

Patching the package to remove it resulted in the correct behaviour on Android and left iOS behaviour unaffected:

```diff
diff --git a/node_modules/@rainbow-me/rainbowkit/dist/index.js b/node_modules/@rainbow-me/rainbowkit/dist/index.js
index 72c680d..63b9634 100644
--- a/node_modules/@rainbow-me/rainbowkit/dist/index.js
+++ b/node_modules/@rainbow-me/rainbowkit/dist/index.js
@@ -320,7 +320,7 @@ var metaMaskWallet = ({
       });
       const getUri = async () => {
         const { uri } = (await connector.getProvider()).connector;
-        return isAndroid() ? uri : `https://metamask.app.link/wc?uri=${encodeURIComponent(uri)}`;
+        return `https://metamask.app.link/wc?uri=${encodeURIComponent(uri)}`;
       };
       return {
         connector,
@@ -409,7 +409,7 @@ var rainbowWallet = ({
       });
       const getUri = async () => {
         const { uri } = (await connector.getProvider()).connector;
-        return isAndroid() ? uri : `https://rnbwapp.com/wc?uri=${encodeURIComponent(uri)}`;
+        return `https://rnbwapp.com/wc?uri=${encodeURIComponent(uri)}`;
       };
       return {
         connector,
@@ -459,7 +459,7 @@ var walletConnectWallet = ({
     const getUri = async () => (await connector.getProvider()).connector.uri;
     return {
       connector,
-      ...ios ? {} : {
+      ...ios || isAndroid() ? {} : {
         mobile: { getUri },
         qrCode: { getUri }
       }
diff --git a/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-CEBYRAIG.js b/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-CEBYRAIG.js
index a7cc353..48e732a 100644
--- a/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-CEBYRAIG.js
+++ b/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-CEBYRAIG.js
@@ -37,7 +37,7 @@ var rainbowWallet = ({
       });
       const getUri = async () => {
         const { uri } = (await connector.getProvider()).connector;
-        return isAndroid() ? uri : `https://rnbwapp.com/wc?uri=${encodeURIComponent(uri)}`;
+        return `https://rnbwapp.com/wc?uri=${encodeURIComponent(uri)}`;
       };
       return {
         connector,
diff --git a/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-DSGPFCE6.js b/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-DSGPFCE6.js
index 8cc9d89..e3e3eb3 100644
--- a/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-DSGPFCE6.js
+++ b/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-DSGPFCE6.js
@@ -49,7 +49,7 @@ var metaMaskWallet = ({
       });
       const getUri = async () => {
         const { uri } = (await connector.getProvider()).connector;
-        return isAndroid() ? uri : `https://metamask.app.link/wc?uri=${encodeURIComponent(uri)}`;
+        return `https://metamask.app.link/wc?uri=${encodeURIComponent(uri)}`;
       };
       return {
         connector,
diff --git a/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-OORSNVWZ.js b/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-OORSNVWZ.js
index 0cafcc6..67b6bc0 100644
--- a/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-OORSNVWZ.js
+++ b/node_modules/@rainbow-me/rainbowkit/dist/wallets/walletConnectors/chunk-OORSNVWZ.js
@@ -1,4 +1,5 @@
 import {
+  isAndroid,
   isIOS
 } from "./chunk-KHDDZZDB.js";
 import {
@@ -22,7 +23,7 @@ var walletConnectWallet = ({
     const getUri = async () => (await connector.getProvider()).connector.uri;
     return {
       connector,
-      ...ios ? {} : {
+      ...ios || isAndroid() ? {} : {
         mobile: { getUri },
         qrCode: { getUri }
       }
```

**Comment by Geektrovert** [comment]
@jckw I'm facing the same issue, have you found a solution for this?

**Comment by Geektrovert** [comment]
I'm facing the issue on iOS too though!

**Comment by DanielSinclair** [comment]
Hi @jckw. This is actually expected behavior currently. On Android, RainbowKit favors deep links, whereas on iOS, RainbowKit favors Universal Links. When a Universal Link fails, the user ends up on one of those fallback download pages. This is the unhappy path that we hope users rarely see. This switch is implemented within the wallet connector so that each wallet can codify their own logic; it can get complicated quickly across different wallets. It appears that Coinbase's connector logic actually changed on us to always show the intermediary Connect page (to choose either Coinbase product) instead of attempting a Deep Link. We'll have to re-evaluate how to better support that particular wallet.

I'll close this for now, but we'll look into potentially bringing the same fallback download logic into core RainbowKit for Android. Check back soon!

**Comment by Ashoat** [comment]
Note that while this patch "fixes" the deeplinking to Play Store, it breaks more important functionality (Android fails to redirect to app for login) – recommend not trying it!
