### ISSUE TITLE
[bug] Update wagmi to 0.9.x

### ISSUE THREAD

**Issue by tuler** [rainbow-me/rainbowkit#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.0

### wagmi Version

0.9.1

### Current Behavior

../../node_modules/@rainbow-me/rainbowkit/dist/chunk-GH36UIKI.js
Attempted import error: 'chain' is not exported from 'wagmi' (imported as 'wagmiChains').

Import trace for requested module:
../../node_modules/@rainbow-me/rainbowkit/dist/chunk-GH36UIKI.js
../../node_modules/@rainbow-me/rainbowkit/dist/index.js

### Expected Behavior

Breaking change in wagmi.
Need to update rainbowkit

### Steps To Reproduce

Create a rainbow project, and update wagmi to latest version.

**Comment by sasicodes** [comment]
+1

**Comment by nfts2me** [comment]
+1 
having the same issue

**Comment by AndyOooh** [comment]
+1

**Comment by 0xTimepunk** [comment]
Please, someone do this :)!

**Comment by bettiolo** [comment]
I think wagmi and siwe are both held back by the dependencies of the sdk

**Comment by iv7dev** [comment]
1+ downgrade or wait

**Comment by z0r0z** [comment]
blz 🙏

**Comment by HZHAIX** [comment]
This should be include in the new version: `"@rainbow-me/rainbowkit": "^0.8.1",`

**Comment by DanielSinclair** [comment]
#903 is merged in, and [@rainbow-me/rainbowkit@0.8.1](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.8.1) is now available
