### ISSUE TITLE
[bug] Disconnection feature not working properly

### ISSUE THREAD

**Issue by gilles-hemmerle** [rainbow-me/rainbowkit#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.4

### wagmi Version

0.6.8

### Current Behavior

When connecting a metamask wallet through the chrome extension, the rainbow kit propose a Disconnect modal when clicking on the Connect button. Disconnection work as expected.

The issue is that if we refresh the browser, the previous wallet is connected again.

### Expected Behavior

Two options:
- Tell the user that disconnection feature is not available for metamask browser extension and it should be handled directly through the metamask extension
- Find a way to simulate the disconnected state when "disconnect" feature is used in rainbowkit. so the user does not see his previous wallet connected when refreshing the browser

### Steps To Reproduce

* Initialize the rainbowkit extension
* Create a Connection button

```tsx
<ConnectButton.Custom>
  {({
    account,
    chain,
    openAccountModal,
    openChainModal,
    openConnectModal,
    mounted,
  }) => {
    return (
      <div
        className="wallet-button-wallet"
        {...(!mounted && {
          'aria-hidden': true,
          style: {
            opacity: 0,
            pointerEvents: 'none',
            userSelect: 'none',
          },
        })}
      >
        {(() => {
          if (!mounted || !account || !chain) {
            return (
              <Button
                variant="outline-primary"
                onClick={openConnectModal}
                type="button"
              >
                Connect Wallet
              </Button>
            );
          }

          if (chain.unsupported) {
            return (
              <Button variant="danger" onClick={openChainModal} type="button">
                Wrong network
              </Button>
            );
          }

          return (
            <div style={{ display: 'flex', gap: 12 }}>
              <Button variant="primary" onClick={openAccountModal} type="button">
                <img src={avatar} className="me-1" alt="Avatar" />
                {account.displayName}
              </Button>
            </div>
          );
        })()}
      </div>
    );
  }}
</ConnectButton.Custom>
```

* Connect a metamask wallet through browser extension
* Use the disconnect button

![image](https://user-images.githubusercontent.com/2291800/207076967-38b112a0-7808-433c-8b7b-2b88475961a4.png)

* The wallet is disconnected
* Refresh the browser one or two times: The wallet is automatically reconnected

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://d2cdkz.csb.app/

**Comment by h0tw4t3r** [comment]
https://github.com/rainbow-me/rainbowkit/issues/807

**Comment by DanielSinclair** [comment]
Closing in favor of the discussion in #807
