### ISSUE TITLE
[bug] when disconnect，ConnectModal reopened

### ISSUE THREAD

**Issue by teeway2021** [rainbow-me/rainbowkit#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

^0.9.0

### Current Behavior

[bug] when disconnect，ConnectModal reopened

### Expected Behavior

do not reopen

**Comment by intergalacticspacehighway** [comment]
@teeway2021 can you try it after disabling strict mode in react? This looks related to https://github.com/rainbow-me/rainbowkit/issues/836#issuecomment-1303571558

**Comment by Nightvision53** [comment]
@intergalacticspacehighway It worked for me. I had the same issue but when I disabled strict mode it was solved.

**Comment by DanielSinclair** [comment]
Closing in favor of #836
