### ISSUE TITLE
Metamask download link for Firefox is incorrect

### ISSUE THREAD

**Issue by jmrossy** [rainbow-me/rainbowkit#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.5

### Current Behavior

Links to Chrome web store

![Screenshot 2022-12-23 at 16 54 19](https://user-images.githubusercontent.com/710751/209409289-18e37372-c86a-46d4-bbf1-d48ec053852e.png)

### Expected Behavior

Should link to Firefox extension store

**Comment by adbario** [comment]
@jmrossy Just tested this, and [detecting the Firefox](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/utils/browsers.ts#L32) seems to work as expected, but as you said, I also get the wrong download link. This seems to be coming from the [MetaMaskWalletConnector](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/wallets/walletConnectors/metaMaskWallet/metaMaskWallet.ts#L58), which only has a download link to Chrome Extension Store.

For the browser extensions, there should ideally be links to each store, or use the usual MetaMask link, which will always point you in the right direction: https://metamask.io/download/.

As the browser detections already exist, I don't see any reason to redirect the users to the correct extension store.

**Comment by DanielSinclair** [comment]
Good find. We'll introduce multiple download links into the wallet connector schema to properly route the installation. You'll see a PR in the coming days!
