### ISSUE TITLE
[bug] Excessive CPU usage from invisible spinning svg

### ISSUE THREAD

**Issue by 0xTARC** [rainbow-me/rainbowkit#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.0

### Current Behavior

Invisible spinning SVG causing ridiculous amount of CPU usage

I think caused by this PR: https://github.com/rainbow-me/rainbowkit/commit/d2a2a6aead377fcab420903377e65eb9f1e00e9f

![Recording 2022-12-28 at 20 54 18](https://user-images.githubusercontent.com/97852365/209901315-cd95c474-06e7-4abd-ad68-ffd89678cfdb.gif)

I would have fixed it myself but couldn't get the repo to build 

see it live here: https://jpoold-ui.vercel.app/
code: https://github.com/0xTARC/jpoold-ui

### Expected Behavior

That spinning SVG shouldn't be there

### Steps To Reproduce

Install rainbow kit

Connect wallet

Observe spinning svg or super high CPU usage in chrome task manager

**Comment by 0xTARC** [comment]
we faced this issue in fiat dao frontend as well and fixed it with a simple css override
https://github.com/fiatdao/fiat-ui-i/commit/ab965a637211a8b6ca6b46f789d0020ec4603799

**Comment by DanielSinclair** [comment]
A weird one! Don't quite understand why the `SpinnerIcon` styling would be leaking in this way 🤔

**Comment by KosmosKey** [comment]
Hey @0xTARC. I have created a pull request for this bug: https://github.com/rainbow-me/rainbowkit/pull/1609. It will be merged on one of the next releases.
