### ISSUE TITLE
[bug] Ledger nano X - transfer requests failing

### ISSUE THREAD

**Issue by RonanKMcGovern** [rainbow-me/rainbowkit#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.5.0

### wagmi Version

^0.6.4

### Current Behavior

A Ledger Nano X device is connecting correctly via Ledger Live, but transfer requests are failing.

There is no issue when using Ledger Nano X via Metamask browser extension.

### Expected Behavior

When there is a transfer request, there should be a prompt shown to approve in Ledger Live. Instead, nothing happens.

### Steps To Reproduce

Connect via Ledger Live with a Nano X (I have not tested Ledger S).

### Anything else?

No

**Comment by DanielSinclair** [comment]
I was unable to replicate this issue with the Nano S. But we are working with the Ledger team to adopt the new Ledger Connect standard that should stitch together the Ledger ecosystem a bit better and add stability.  Will close this in favor of #938
