### ISSUE TITLE
[bug] Remix example fails to run

### ISSUE THREAD

**Issue by wengzilla** [rainbow-me/rainbowkit#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.6

### Current Behavior

The current Rainbow kit example for Remix fails to boot. This is a common error for ESM packages in Remix, but the usual fix of adding things to `serverDependenciesToBundle` does not seem to be working here... Any thoughts on how I might be able to fix?

```
wagmi is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
@wagmi/core is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
@wagmi/connectors is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
@wagmi/chains is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
Remix App Server started at http://localhost:8000 (http://192.168.86.52:8000)
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/X/Code/rainbowkit/examples/with-remix/node_modules/@wagmi/connectors/dist/index.js from /X/edweng/Code/rainbowkit/examples/with-remix/build/index.js not supported.
Instead change the require of /Users/X/Code/rainbowkit/examples/with-remix/node_modules/@wagmi/connectors/dist/index.js in /Users/edweng/Code/rainbowkit/examples/with-remix/build/index.js to a dynamic import() which is available in all CommonJS modules.
```

Here is my remix.config.js file:
```
/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: ['**/.*'],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    '@rainbow-me/rainbowkit',
    '@rainbow-me/rainbowkit/wallets',
    'wagmi',
    '@wagmi/core',
  ],
};
```

### Expected Behavior

When running `npm run dev`, I would have expected the Remix server to start and to be able to immediately run through the Rainbowkit wallet connect demo.

### Steps To Reproduce

```
cd '<PATH>/rainbowkit/examples/with-remix'
npm install
npm run dev
```

**Comment by wengzilla** [comment]
Ok, so I partially figured it out... If I pull in https://github.com/rainbow-me/rainbowkit/pull/922, then I can run `npm run dev` and the server actually boots.

When I try this setup in my Remix Blues app, it fails to run (same error related to ESM) using `cross-env NODE_ENV=development node --inspect --require ./node_modules/dotenv/config --require ./mocks ./build/server.js`. However, if I install the `@remix-run/serve` package, it stops complaining.

Should I switch to using @remix-run/serve? Why is it failing when I run `npm run dev` with my Remix Blues app?

**Comment by DanielSinclair** [comment]
This should now be resolved with `serverDependenciesToBundle` changes referenced in #973.
