### ISSUE TITLE
Got unknown error occurred in the trust wallet

### ISSUE THREAD

**Issue by phatmecury** [rainbow-me/rainbowkit#945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.2

### Current Behavior

We're using TrustWallet to scan Qrcode WalletConnect. 
And usePrepareSendTransaction, sendTransaction function to do transfer.
It's working on metamask as well. both desktop and mobile
![IMG_3335](https://user-images.githubusercontent.com/71438346/211538071-58d6f43a-c091-4ca0-8058-f80bfd0ead44.png)

### Expected Behavior

Should open transfer section in the trust wallet

### Steps To Reproduce
"dependencies": {
"@rainbow-me/rainbowkit": "^0.8.1",
"ethers": "^5.0.0",
"next": "^12.1.6",
"react": "^18.1.0",
"react-dom": "^18.1.0",
"wagmi": "^0.9.0"
},
"devDependencies": {
"@types/node": "^17.0.35",
"@types/react": "^18.0.9",
"eslint": "^8.15.0",
"eslint-config-next": "^12.1.6",
"typescript": "^4.7.2"
}
const { config } = usePrepareSendTransaction({
    request: {
      to: '',
      value: debouncedAmount ? utils.parseEther(debouncedAmount) : undefined,
    }
  });
  const sendTrans = useSendTransaction(config);
  const waitTrans = useWaitForTransaction({
    hash: sendTrans.data?.hash,
  })

  const onSubmit = () => {
    sendTrans.sendTransaction?.();
  }

**Comment by DanielSinclair** [comment]
Hi @phatmecury! This seems to be an issue somewhere on the Wagmi side or Trust Wallet. If it works on MetaMask, it is more likely a Trust Wallet issue. Otherwise, try to open an issue for [Wagmi](https://github.com/wagmi-dev/wagmi).

**Comment by shadowfaz16** [comment]
hello, having this problem as well. were you able to fix it?
