### ISSUE TITLE
[bug] Regenerating Wagmi client causes rainbowkit buttons not to work

### ISSUE THREAD

**Issue by rafinskipg** [rainbow-me/rainbowkit#953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.8.x

### Current Behavior

Given that we regenerate the wagmi client to change network configuration at certain point, the buttons of rainbowkit become unresponsive after that.

If we switch to dark or light theme, the buttons work again, i guess because it re-renders them.

```
 <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains} theme={mode === 'light' ? lightTheme() : darkTheme()}>
        <RouterProvider router={router} />
      </RainbowKitProvider>
    </WagmiConfig>
```

### Expected Behavior

Buttons still work after changing the wagmi client

### Steps To Reproduce

Alter the wagmiclient object at some point

**Comment by DanielSinclair** [comment]
Hi @rafinskipg! Could you provide example source code? I'm unable to replicate the issue.

**Comment by rafinskipg** [comment]
@DanielSinclair , i will try.

1 - Assuming a normal wagmi provider / rainbow kit stuff.
```
<WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains} theme={colorMode === 'light' ? lightTheme() : darkTheme()}>
        <RouterProvider router={router} />
      </RainbowKitProvider>
    </WagmiConfig>
```

2 - We regenerate the wagmiClient based on changes from the user RPCs (user can configure custom RPCs from the UI)

```
// Chains should be regenerated each time the config.rpcs change
  const { wagmiClient, chains } = useMemo(() => {
    return getWagmiClientAndChains(rpcs, siteConfig.name);
  }, [rpcs]);
```

3 - We have a function that calls the generate client with the new RPCs

```
import { getDefaultWallets } from '@rainbow-me/rainbowkit';
import { Chain, configureChains, createClient } from 'wagmi';
import { mainnet, optimism, goerli, arbitrum, hardhat } from 'wagmi/chains';

import { publicProvider } from 'wagmi/providers/public';
import { jsonRpcProvider } from 'wagmi/providers/jsonRpc';
import { RPC } from '../config/types/rpc';

export const getChainsAndProvider = (rpcs: RPC[]) => {
  return configureChains(
    [mainnet, goerli, optimism, arbitrum, hardhat],
    [
      jsonRpcProvider({
        priority: 0,
        weight: 2,
        static: false,
        rpc: chain => {
          const rpc = rpcs.find(i => i.chainId === chain.id);
          return rpc && rpc.url
            ? {
                http: rpc.url
              }
            : null;
        }
      }),
      publicProvider({
        priority: 10,
        weight: 3
      })
    ]
  );
};

type CreateClientReturnType = ReturnType<typeof createClient>;

export const getWagmiClientAndChains = (
  rpcs: RPC[],
  appName: string
): {
  wagmiClient: CreateClientReturnType;
  chains: Chain[];
} => {
  const { chains, provider, webSocketProvider } = getChainsAndProvider(rpcs);
  const { connectors } = getDefaultWallets({
    appName,
    chains
  });

  const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
    webSocketProvider
  });

  return { wagmiClient: wagmiClient as any, chains };
};

```

4 - The RPCs object is similar to : 
```
[ 
{chainId: 5, url: 'https://eth-goerli.g.alchemy.com/v2/XXXXX'}]
```

Please, note: I upgraded Wagmi to 'v0.10.11' and the error with rainbowkit does not happen anymore. 

Will you update the version rainbowkit depends on soon?

**Comment by rjborba** [comment]
I'm facing a simular issue. In my case, when I simply call createClient again, even if I do not replace the original client, it makes the modal stuck on the state:
Opening MetaMask...
Confirm connection in the extension

**Comment by ketys-from-meiro** [comment]
Same here with the latest version...

**Comment by pedromcunha** [comment]
Running into the same issue

**Comment by DanielSinclair** [comment]
Bumped RainbowKit to be in parity with Wagmi v0.10.x, so this should be resolved now. Please update to these new mins and let me know if you're still experiencing the issue.
