### ISSUE TITLE
[bug] Adding new networks with API key

### ISSUE THREAD

**Issue by nfts2me** [rainbow-me/rainbowkit#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.10.x

### Current Behavior

When adding a new network RainbowKit doesn't always take the network from the public RPC, exposing the Alchemy/Infura API keys and keeping that for the new network for the user, which makes no sense.

### Expected Behavior

Use public RPCs to add the networks instead of API-based RPCs.

**Comment by DanielSinclair** [comment]
Hi @nfts2me! Can you provide additional detail? Am unable to pinpoint the unexpected behavior you're referring to.

**Comment by nfts2me** [comment]
There you have:
https://github.com/wagmi-dev/wagmi/pull/1665

It seems to be a wagmi bug.
