### ISSUE TITLE
[issue] <error Couldn't find the binary git>

### ISSUE THREAD

**Issue by evilkongsNFTs** [rainbow-me/rainbowkit#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

Latest

### wagmi Version

Latest

### Current Behavior

I have tried to install the dependencies in different ways and I always get an error that I have managed to solve so far. At the moment of installing the dependencies with "yarn" I get an error that I have not been able to solve. "error Couldn't find the binary git"
![error](https://user-images.githubusercontent.com/118764825/213913977-82013b04-4dc1-414a-96c5-cf3e375cea01.PNG)

**Comment by adbario** [comment]
@evilkongsNFTs This is not related to RainbowKit; you need to have git installed on the machine where you're installing the dependencies.

**Comment by evilkongsNFTs** [comment]
> @evilkongsNFTs This is not related to RainbowKit; you need to have git installed on the machine where you're installing the dependencies.

I have solved it, git is installed, apparently it was an error with yarn, I deleted the application cache and proceeded to delete the yarn files, then I opened my powershell as administrator and inserted "npm install --global yarn" and then I put the files in with a "--force"
