### ISSUE TITLE
Multiple account connect feature available on rainbowkit ? 

### ISSUE THREAD

**Issue by deveshsr124** [rainbow-me/rainbowkit#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.7.1

### wagmi Version

^0.6.8

### Current Behavior

When using Rainbow Kit's popup to connect multiple MetaMask wallets all at once and using the useAccount() hook from wagmi then I am not being able to get all of those account's wallet address . I am only getting one account address at a time 

### Expected Behavior

When using Rainbow Kit's popup to connect multiple MetaMask wallets and using the useAccount() hook from wagmi, all connected wallets should be accessible. in short , I want my rainbowkit popup to connect to multiple metamask wallets at once and provide me with an array of connected accounts.

### Steps To Reproduce

1. Connect multiple MetaMask wallets using Rainbow Kit's popup . 
2. Use the useAccount() hook from wagmi to access connected wallets . 
3. Observe that only one wallet is accessible .
![Screenshot_20230123_171203](https://user-images.githubusercontent.com/68158386/214031290-de55d3bc-dde2-44b1-b9ea-74d1b991b13f.png)

4 . I want to connect all of these accounts using rainbowkit openConnectModal() and get all of these account address , not only one .

**Comment by adbario** [comment]
@deveshsr124 To achieve this, [wagmi](https://github.com/wagmi-dev/wagmi) should implement the feature first. As it's a pretty uncommon use case, I don't think they'll be up for the task. See the conversation here 👉  https://github.com/wagmi-dev/wagmi/discussions/504

**Comment by Isotopist** [comment]
It's a feature metamask allows with its web3.js framework but that hasn't been imported into rainbow. Implementing it would most likely allow further use cases for building dapps using rainbow (like monitoring dashboards accross accounts). For this rainbow should probably differentiate "connected" from "selected" wallets so users can connect multiple metamask wallets at once while still performing actions from the "selected" wallet. A wallet could then be recognized as "connected" even if not "selected" so to avoid any such conflict.

**Comment by DanielSinclair** [comment]
This is something we hope to work towards, but will require improvements upon the Ethereum Provider standard and wallets. If Wagmi makes progress here, we'll certainly work to make RainbowKit compatible.

**Comment by dani69654** [comment]
Hello there, is there an update?
