### ISSUE TITLE
[issue] Property 'toNumber' does not exist on type '{}'

### ISSUE THREAD

**Issue by evilkongsNFTs** [rainbow-me/rainbowkit#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

Latest

### wagmi Version

Latest

### Current Behavior

I am trying to build my react and I get an error "Property 'toNumber' does not exist on type '{}'". I do not understand why this, I have seen the youtube video made by rainbow and it is as it is, what should I do?

![image](https://user-images.githubusercontent.com/118764825/214138618-8c5ca7ca-89fc-412c-8973-6014ea294e6b.png)

**Comment by DanielSinclair** [comment]
Hi @evilkongsNFTs! Can you share some source code? Or is this occurring in [with-next-mint-nft](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-mint-nft)?

**Comment by evilkongsNFTs** [comment]
> Hi @evilkongsNFTs! Can you share some source code? Or is this occurring in [with-next-mint-nft](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-next-mint-nft)?

I just change it to:

useEffect(() => {
      if (totalSupplyData) {
        setTotalMinted(Number(totalSupplyData));
      }
  }, [totalSupplyData]);
