### ISSUE TITLE
[bug] Can't connect using Valora wallet (WalletConnect)

### ISSUE THREAD

**Issue by yieniggu** [rainbow-me/rainbowkit#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.6

### Current Behavior

Currently when I try to connect using [valora wallet](https://valoraapp.com/es/new-home-redesign) on Celo maoninnet, I get a timeout. This happens in a strange way since sometimes I get to grant access to the app and then get timeouted on the connection. I tried connecting on rainbow home page, and it went through the connection once, then got timeout again.

### Expected Behavior

I want to connect to my valora wallet from mobile without getting timeout.

### Steps To Reproduce

```
import "@rainbow-me/rainbowkit/styles.css";
import {
  ConnectButton,
  getDefaultWallets,
  RainbowKitProvider,
} from "@rainbow-me/rainbowkit";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { publicProvider } from "@wagmi/core/providers/public";
import { jsonRpcProvider } from "@wagmi/core/providers/jsonRpc";

const Celo = {
  id: 42220,
  name: "Celo Mainnet",
  network: "Celo Mainnet",
  iconUrl: "https://rainbowkit-with-celo.vercel.app/icons/celo.svg",
  iconBackground: "#fff",
  nativeCurrency: {
    decimals: 18,
    name: "CELO",
    symbol: "CELO",
  },
  rpcUrls: {
    default: { http: ["https://forno.celo.org"] },
  },
  blockExplorers: {
    default: {
      name: "Celo Explorer",
      url: "https://explorer.celo.org/mainnet",
    },
    etherscan: { name: "CeloScan", url: "https://celoscan.io" },
  },
  contracts: {
    multicall3: {
      address: "0xcA11bde05977b3631167028862bE2a173976CA11",
      blockCreated: 13112599,
    },
  },
  testnet: false,
};

export const { chains, provider } = configureChains(
  [Celo],
  [
    jsonRpcProvider({ rpc: () => ({ http: "https://forno.celo.org" }) }),
    publicProvider(),
  ]
);
const { connectors } = getDefaultWallets({
  appName: "Kolor dAPP",
  chains,
});

export const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});

export const App = () => {
  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains}>
        <YourApp />
      </RainbowKitProvider>
    </WagmiConfig>
  );
};

const YourApp = () => {
  return <ConnectButton />;
};

```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/elastic-scott-w5hhvx?file=/src/index.js

**Comment by DanielSinclair** [comment]
The [Demo](https://rainbowkit-with-celo.vercel.app/) for `rainbowkit-celo` from the CELO team appears to work for me. That library is actively maintained and is probably the best path to implement. Reference their implementation and report back here if you're still seeing the issue!

https://github.com/celo-org/rainbowkit-celo
https://docs.celo.org/developer/rainbowkit-celo

**Comment by yieniggu** [comment]
I tried reproducing the code but having some errors on it, could you help me solve it please. Already opened (an issue)[https://github.com/celo-org/rainbowkit-celo/issues/26] on their github repo but I think this is a webpack issue.

**Comment by aaronmgdr** [comment]
Ive seen this on Valora before. specifically Valora will say its timed out but it actually connected. The Valora team thought it was a UI issue on their end

**Comment by DanielSinclair** [comment]
Going to close this for now, but definitely chime back if you're inclined to think this is on the RainbowKit side
