### ISSUE TITLE
[bug] Can't select suitable provider when browser has Metamask and coinbase wallet extensions

### ISSUE THREAD

**Issue by EhsanParsania** [rainbow-me/rainbowkit#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.10.10

### Current Behavior

When browser has both Metamask wallet extension and Coin wallet extension, there are two providers in the window.etherum, so application can't choose between them and after connect you can't call your contract function, except you've chosen one of them when you want to provide a provider ( to web3.js or ethers ) 

NORMALLY WITH METAMASK :  
window.etherum = metamask

WHEN BOTH WALLETS ARE INSTALLED :
window.ethereum.providers = { metamask, coinbasewallet }

### Expected Behavior

There should be a fallback in rainbow-kit  that returns what wallet extension the user has chosen, then in the app, you can provide the suitable provider

**Comment by DanielSinclair** [comment]
The [Wagmi](https://github.com/wagmi-dev/wagmi) project would have better guidance here; RainbowKit connectors are a wrapper around Wagmi's `InjectedConnector`.
