### ISSUE TITLE
[Issue] Error: cannot estimate gas

### ISSUE THREAD

**Issue by evilkongsNFTs** [rainbow-me/rainbowkit#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

Latest

### wagmi Version

Latest

### Current Behavior

I am making a mint button with rainbow kit, I had previously made it with some problems but in the end it was achieved. Now making another one with the same method I get this error, I want to point out that the previous one I made was a free mint and this one has a cost, reading in metamask suggests that I should indicate a gas limit in my code, how should I do it?
![Error on mint button](https://user-images.githubusercontent.com/118764825/215289274-e5df3697-2094-4bf3-8535-b4cfc07db3e1.PNG)

### Steps To Reproduce

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import contractInterface from "../contract-abi.json";
import FlipCard, { BackCard, FrontCard } from '../components/FlipCard';
import {
  useAccount,
  useContractRead,
  usePrepareContractWrite,
  useContractWrite,
  useWaitForTransaction,
} from "wagmi";

const Home: NextPage = () => {

  const { isConnected } = useAccount();

  const { config } = usePrepareContractWrite({
    address: '0xe947C7e8f8ccd4505BF0c96d47cd3c14C6C2A2f5',
    abi: contractInterface,
    functionName: 'mint',
  });

  const { write: mint,
    isSuccess: isMintStarted,
    isLoading: isMintLoading,
    data: mintData,
    error: mintError,
  } = useContractWrite(config)

  const {
    data: txData,
    isSuccess: txSuccess,
    error: txError,
  } = useWaitForTransaction({
    hash: mintData?.hash,
  });

  const { data: totalSupplyData } = useContractRead({
    ...config,
    functionName: 'totalSupply',
    watch: true,
  });

  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  const [totalMinted, setTotalMinted] = useState(0);

  useEffect(() => {
      if (totalSupplyData) {
        setTotalMinted(Number(totalSupplyData));
      }
  }, [totalSupplyData]);

  const isMinted = txSuccess;

  return (
    <>
    <div className="page">
      <div className="container container2">
        <div style={{ flex: '1 1 auto' }}>
          <div style={{ padding: '24px 24px 24px 0' }}>
            <h1 style={{ marginBottom: '12', color: 'white' }}>Mint for 0.025 ETH ⬇️ </h1>
            <p style={{ margin: '12px 0 24px', color: 'white' }}>
              {totalMinted} EK Minted!🔥
            </p>
            
            <ConnectButton />

            {mintError && (
              <p style={{ marginTop: 24, color: 'red' }}>
                ❌ Error: {mintError.message}
              </p>
            )}
            {txError && (
              <p style={{ marginTop: 24, color: 'red' }}>
                ❌ Error: {txError.message}
              </p>
            )}

            {mounted && isConnected && !isMinted && (
              <button
                style={{ marginTop: 24}}
                disabled={!mint || isMintLoading || isMintStarted}
                className="button"
                data-mint-loading={isMintLoading}
                data-mint-started={isMintStarted}
                onClick={() => mint?.()}
              >
                {isMintLoading && 'Waiting for approval'}
                {isMintStarted && 'Minting...'}
                {!isMintLoading && !isMintStarted && '🎉 Mint'}
              </button>
            )}
          </div>
        </div>

        <div style={{ flex: '0 0 auto' }}>
          <FlipCard>
            <FrontCard isCardFlipped={isMinted}>
              <Image
                layout="responsive"
                src="/nft.gif"
                width="800"
                height="800"
                alt="Evil Kongs NFT"
              />
            </FrontCard>
            <BackCard isCardFlipped={isMinted}>
              <div style={{ padding: 24 }}>
                <Image
                  src="/nft.gif"
                  width="80"
                  height="80"
                  alt="Evil Kongs NFT"
                  style={{ borderRadius: 8, alignItems: "center" }}
                />
                <h2 style={{ marginTop: 24, marginBottom: 6 }}>You're NFT is Minted!🥳. Welcome to Family Kong</h2>
                <p style={{ marginBottom: 24 }}>
                  Your NFT will show up in your wallet in the next few minutes. be a patient.
                </p>
                <p style={{ marginBottom: 6 }}>
                  View on{' '}
                  <a href={`https://etherscan.io/tx/${mintData?.hash}`}>
                    Etherscan
                  </a>
                </p>
              </div>
            </BackCard>
          </FlipCard>
        </div>
      </div>
    </div>
    </>
  );
};

export default Home;

**Comment by DanielSinclair** [comment]
@evilkongsNFTs This issue is occurring a bit lower in the stack than RainbowKit or Wagmi. I'd suggest searching around or opening an issue with the [ethers](https://github.com/ethers-io/ethers.js/) project.
