### ISSUE TITLE
[bug] Couldn't find any versions for "@rainbow-me/rainbowkit" that matches "^0.9.0"

### ISSUE THREAD

**Issue by Dsinghbailey** [rainbow-me/rainbowkit#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

8.1.0

### wagmi Version

9.0.0

### Current Behavior

running the migration guide in the docs:
`npm i @rainbow-me/rainbowkit@^0.9.0 wagmi@^0.9.0`

gives the following error:
Couldn't find any versions for "@rainbow-me/rainbowkit" that matches "^0.9.0"

Looks like rainbow kit's most recent version is 0.8.1

Is this a typo?

### Expected Behavior

I expect 
npm i @rainbow-me/rainbowkit@^0.9.0 wagmi@^0.9.0
to run without issue

### Steps To Reproduce

just run:
npm i @rainbow-me/rainbowkit@^0.9.0 wagmi@^0.9.0

**Comment by DanielSinclair** [comment]
Thanks for highlighting this @Dsinghbailey. We'll update the docs and create a new release tag for 0.9 to remain in-sync with Wagmi
