### ISSUE TITLE
I need to add KaiKas Wallet

### ISSUE THREAD

**Issue by DragonDev1010** [rainbow-me/rainbowkit#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.11.2

**Comment by DanielSinclair** [comment]
Should be easy! The Wallet List can be totally customized, including adding new wallets. You'll just need to create a custom wallet connector for KaiKas. Have a look at these sections of our docs:
- [Custom Wallet List](https://www.rainbowkit.com/docs/custom-wallet-list)
- [Custom Wallets](https://www.rainbowkit.com/docs/custom-wallets)

The wallet creator can also open a PR to export the connector for all devs
