### ISSUE TITLE
[Issue] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by praddoskanna** [rainbow-me/rainbowkit#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.11.3

### Current Behavior

 I Installed rainbowkit by using Yarn add @rainbow-me/rainbowkit wagmi ethers , Installation went Successfull , But after Importing the given statement as per docs i am facing this error .
 
 I have Created a simple react 17 App with simple import

import { WagmiConfig, createClient, configureChains, mainnet } from 'wagmi';

I am getting this error when compiling.

ERROR in ./node_modules/wagmi/dist/index.js 188:33
Module parse failed: Unexpected token (188:33)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

![image](https://user-images.githubusercontent.com/69679608/216311271-e2814219-6970-49b4-bbc2-7df60702777f.png)
 I tried to adjust webpack config file but i am not able to find an exact solution for this.
 
 

### Expected Behavior

Loader should be able to load the Content

### Steps To Reproduce

Its An React App

**Comment by DanielSinclair** [comment]
@praddoskanna Can you provide a sample? This appears to be an issue somewhere between the Webpack setup and Wagmi, rather than on the RainbowKit side.

**Comment by DanielSinclair** [comment]
Closing for now. Will reopen if this issue persists

**Comment by dawn0tria** [comment]
I am getting the same issue when trying to import wagmi in a react app and build it with webpack, to use the component in another react app? 

// webpack.config.js
var path = require("path");

  module.exports = {
    mode: "production",
    entry: "./src/index.js",
    output: {
      path: path.resolve("build"),
      filename: "index.js",
      libraryTarget: "commonjs2"
    },
    module: {
      rules: [
        { test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" },
        {
          test: /\.css$/,
          loader: "style-loader!css-loader"
        }
      ]
    },
    externals: {
      react: "react"
    }
  };
  
  Am i missing something?

**Comment by DanielSinclair** [comment]
@dawn0tria Can you share a reproducible CodeSandbox example? Can have a look at your configuration in greater detail
